/* Generated by tool/gen_core.dart from f3d_physics.h: do not edit.
 *
 * The WebAssembly build's exports for the calls that take or give a
 * 64-bit value, which JavaScript would have as a BigInt: two 32-bit halves
 * in, and out the low half, the high one kept for f3d_wasm_high. */
#include "f3d_physics.h"

static uint32_t g_high;

F3D_API uint32_t f3d_wasm_high(void) { return g_high; }

F3D_API uint32_t f3d_joint_create__w(void * world, int type, uint32_t a_low, uint32_t a_high, uint32_t b_low, uint32_t b_high, f3d_real ax, f3d_real ay, f3d_real az, f3d_real ux, f3d_real uy, f3d_real uz) {
  const uint64_t v = f3d_joint_create((void *)world, type, ((uint64_t)a_high << 32) | a_low, ((uint64_t)b_high << 32) | b_low, ax, ay, az, ux, uy, uz);
  g_high = (uint32_t)(v >> 32);
  return (uint32_t)v;
}

F3D_API uint32_t f3d_joint_create_distance__w(void * world, uint32_t a_low, uint32_t a_high, uint32_t b_low, uint32_t b_high, f3d_real ax, f3d_real ay, f3d_real az, f3d_real bx, f3d_real by, f3d_real bz) {
  const uint64_t v = f3d_joint_create_distance((void *)world, ((uint64_t)a_high << 32) | a_low, ((uint64_t)b_high << 32) | b_low, ax, ay, az, bx, by, bz);
  g_high = (uint32_t)(v >> 32);
  return (uint32_t)v;
}

F3D_API int f3d_joint_destroy__w(void * world, uint32_t joint_low, uint32_t joint_high) {
  return f3d_joint_destroy((void *)world, ((uint64_t)joint_high << 32) | joint_low);
}

F3D_API int f3d_joint_is_valid__w(void * world, uint32_t joint_low, uint32_t joint_high) {
  return f3d_joint_is_valid((void *)world, ((uint64_t)joint_high << 32) | joint_low);
}

F3D_API int f3d_joint_set_limits__w(void * world, uint32_t joint_low, uint32_t joint_high, int enabled, f3d_real lower, f3d_real upper) {
  return f3d_joint_set_limits((void *)world, ((uint64_t)joint_high << 32) | joint_low, enabled, lower, upper);
}

F3D_API int f3d_joint_set_cone__w(void * world, uint32_t joint_low, uint32_t joint_high, int enabled, f3d_real angle) {
  return f3d_joint_set_cone((void *)world, ((uint64_t)joint_high << 32) | joint_low, enabled, angle);
}

F3D_API int f3d_joint_set_friction__w(void * world, uint32_t joint_low, uint32_t joint_high, int enabled, f3d_real torque) {
  return f3d_joint_set_friction((void *)world, ((uint64_t)joint_high << 32) | joint_low, enabled, torque);
}

F3D_API int f3d_joint_set_motor__w(void * world, uint32_t joint_low, uint32_t joint_high, int enabled, f3d_real speed, f3d_real max_force) {
  return f3d_joint_set_motor((void *)world, ((uint64_t)joint_high << 32) | joint_low, enabled, speed, max_force);
}

F3D_API int f3d_joint_set_spring__w(void * world, uint32_t joint_low, uint32_t joint_high, int enabled, f3d_real hertz, f3d_real damping) {
  return f3d_joint_set_spring((void *)world, ((uint64_t)joint_high << 32) | joint_low, enabled, hertz, damping);
}

F3D_API int f3d_joint_set_length__w(void * world, uint32_t joint_low, uint32_t joint_high, f3d_real length, f3d_real least, f3d_real most) {
  return f3d_joint_set_length((void *)world, ((uint64_t)joint_high << 32) | joint_low, length, least, most);
}

F3D_API int f3d_joint_set_collide__w(void * world, uint32_t joint_low, uint32_t joint_high, int collide) {
  return f3d_joint_set_collide((void *)world, ((uint64_t)joint_high << 32) | joint_low, collide);
}

F3D_API int f3d_joint_get_value__w(void * world, uint32_t joint_low, uint32_t joint_high, void * out) {
  return f3d_joint_get_value((void *)world, ((uint64_t)joint_high << 32) | joint_low, (void *)out);
}

F3D_API int f3d_joint_get_swing__w(void * world, uint32_t joint_low, uint32_t joint_high, void * out) {
  return f3d_joint_get_swing((void *)world, ((uint64_t)joint_high << 32) | joint_low, (void *)out);
}

F3D_API int f3d_joint_get_force__w(void * world, uint32_t joint_low, uint32_t joint_high, void * out) {
  return f3d_joint_get_force((void *)world, ((uint64_t)joint_high << 32) | joint_low, (void *)out);
}

F3D_API int f3d_world_ray_cast__w(void * world, f3d_real ox, f3d_real oy, f3d_real oz, f3d_real dx, f3d_real dy, f3d_real dz, f3d_real max_distance, uint32_t mask, uint32_t ignore_low, uint32_t ignore_high, void * body, void * hit) {
  return f3d_world_ray_cast((void *)world, ox, oy, oz, dx, dy, dz, max_distance, mask, ((uint64_t)ignore_high << 32) | ignore_low, (void *)body, (void *)hit);
}

F3D_API uint32_t f3d_world_ray_cast_all__w(void * world, f3d_real ox, f3d_real oy, f3d_real oz, f3d_real dx, f3d_real dy, f3d_real dz, f3d_real max_distance, uint32_t mask, uint32_t ignore_low, uint32_t ignore_high, void * bodies, void * hits, uint32_t capacity) {
  return f3d_world_ray_cast_all((void *)world, ox, oy, oz, dx, dy, dz, max_distance, mask, ((uint64_t)ignore_high << 32) | ignore_low, (void *)bodies, (void *)hits, capacity);
}

F3D_API uint32_t f3d_world_overlap_shape__w(void * world, int kind, f3d_real a, f3d_real b, f3d_real c, f3d_real rounding, f3d_real px, f3d_real py, f3d_real pz, f3d_real qx, f3d_real qy, f3d_real qz, f3d_real qw, uint32_t mask, uint32_t ignore_low, uint32_t ignore_high, void * out, uint32_t capacity) {
  return f3d_world_overlap_shape((void *)world, kind, a, b, c, rounding, px, py, pz, qx, qy, qz, qw, mask, ((uint64_t)ignore_high << 32) | ignore_low, (void *)out, capacity);
}

F3D_API int f3d_world_cast_shape__w(void * world, int kind, f3d_real a, f3d_real b, f3d_real c, f3d_real rounding, f3d_real px, f3d_real py, f3d_real pz, f3d_real qx, f3d_real qy, f3d_real qz, f3d_real qw, f3d_real tx, f3d_real ty, f3d_real tz, uint32_t mask, uint32_t ignore_low, uint32_t ignore_high, void * body, void * hit) {
  return f3d_world_cast_shape((void *)world, kind, a, b, c, rounding, px, py, pz, qx, qy, qz, qw, tx, ty, tz, mask, ((uint64_t)ignore_high << 32) | ignore_low, (void *)body, (void *)hit);
}

F3D_API uint32_t f3d_world_move_character__w(void * world, f3d_real radius, f3d_real half_height, void * position, f3d_real dx, f3d_real dy, f3d_real dz, f3d_real max_slope_cos, f3d_real step_height, uint32_t mask, uint32_t ignore_low, uint32_t ignore_high, void * ground_body, void * ground) {
  return f3d_world_move_character((void *)world, radius, half_height, (void *)position, dx, dy, dz, max_slope_cos, step_height, mask, ((uint64_t)ignore_high << 32) | ignore_low, (void *)ground_body, (void *)ground);
}

F3D_API uint32_t f3d_body_create__w(void * world, int type, f3d_real px, f3d_real py, f3d_real pz, f3d_real mass) {
  const uint64_t v = f3d_body_create((void *)world, type, px, py, pz, mass);
  g_high = (uint32_t)(v >> 32);
  return (uint32_t)v;
}

F3D_API int f3d_body_destroy__w(void * world, uint32_t body_low, uint32_t body_high) {
  return f3d_body_destroy((void *)world, ((uint64_t)body_high << 32) | body_low);
}

F3D_API int f3d_body_is_valid__w(void * world, uint32_t body_low, uint32_t body_high) {
  return f3d_body_is_valid((void *)world, ((uint64_t)body_high << 32) | body_low);
}

F3D_API int f3d_body_set_velocity__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real x, f3d_real y, f3d_real z) {
  return f3d_body_set_velocity((void *)world, ((uint64_t)body_high << 32) | body_low, x, y, z);
}

F3D_API int f3d_body_get_velocity__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_velocity((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_set_position__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real x, f3d_real y, f3d_real z) {
  return f3d_body_set_position((void *)world, ((uint64_t)body_high << 32) | body_low, x, y, z);
}

F3D_API int f3d_body_get_position__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_position((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_get_world_position__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_world_position((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_set_angular_velocity__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real x, f3d_real y, f3d_real z) {
  return f3d_body_set_angular_velocity((void *)world, ((uint64_t)body_high << 32) | body_low, x, y, z);
}

F3D_API int f3d_body_get_angular_velocity__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_angular_velocity((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_set_orientation__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real x, f3d_real y, f3d_real z, f3d_real w) {
  return f3d_body_set_orientation((void *)world, ((uint64_t)body_high << 32) | body_low, x, y, z, w);
}

F3D_API int f3d_body_get_orientation__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_orientation((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_set_shape__w(void * world, uint32_t body_low, uint32_t body_high, int kind, f3d_real a, f3d_real b, f3d_real c) {
  return f3d_body_set_shape((void *)world, ((uint64_t)body_high << 32) | body_low, kind, a, b, c);
}

F3D_API int f3d_body_get_inertia__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_inertia((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_get_inertia_tensor__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_inertia_tensor((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_set_rounding__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real radius) {
  return f3d_body_set_rounding((void *)world, ((uint64_t)body_high << 32) | body_low, radius);
}

F3D_API int f3d_body_set_hull__w(void * world, uint32_t body_low, uint32_t body_high, uint32_t hull) {
  return f3d_body_set_hull((void *)world, ((uint64_t)body_high << 32) | body_low, hull);
}

F3D_API int f3d_body_set_mesh__w(void * world, uint32_t body_low, uint32_t body_high, uint32_t mesh) {
  return f3d_body_set_mesh((void *)world, ((uint64_t)body_high << 32) | body_low, mesh);
}

F3D_API int f3d_body_get_mass__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_mass((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_lock_rotation__w(void * world, uint32_t body_low, uint32_t body_high, int locked) {
  return f3d_body_lock_rotation((void *)world, ((uint64_t)body_high << 32) | body_low, locked);
}

F3D_API int f3d_body_set_damping__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real linear, f3d_real angular) {
  return f3d_body_set_damping((void *)world, ((uint64_t)body_high << 32) | body_low, linear, angular);
}

F3D_API int f3d_body_set_drag__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real coefficient) {
  return f3d_body_set_drag((void *)world, ((uint64_t)body_high << 32) | body_low, coefficient);
}

F3D_API int f3d_body_apply_impulse__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real x, f3d_real y, f3d_real z) {
  return f3d_body_apply_impulse((void *)world, ((uint64_t)body_high << 32) | body_low, x, y, z);
}

F3D_API int f3d_body_apply_impulse_at__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real x, f3d_real y, f3d_real z, f3d_real px, f3d_real py, f3d_real pz) {
  return f3d_body_apply_impulse_at((void *)world, ((uint64_t)body_high << 32) | body_low, x, y, z, px, py, pz);
}

F3D_API int f3d_body_add_force__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real x, f3d_real y, f3d_real z) {
  return f3d_body_add_force((void *)world, ((uint64_t)body_high << 32) | body_low, x, y, z);
}

F3D_API int f3d_body_add_torque__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real x, f3d_real y, f3d_real z) {
  return f3d_body_add_torque((void *)world, ((uint64_t)body_high << 32) | body_low, x, y, z);
}

F3D_API int f3d_body_set_bullet__w(void * world, uint32_t body_low, uint32_t body_high, int bullet) {
  return f3d_body_set_bullet((void *)world, ((uint64_t)body_high << 32) | body_low, bullet);
}

F3D_API int f3d_body_set_friction__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real friction) {
  return f3d_body_set_friction((void *)world, ((uint64_t)body_high << 32) | body_low, friction);
}

F3D_API int f3d_body_set_restitution__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real restitution) {
  return f3d_body_set_restitution((void *)world, ((uint64_t)body_high << 32) | body_low, restitution);
}

F3D_API int f3d_body_set_collision_filter__w(void * world, uint32_t body_low, uint32_t body_high, uint32_t layer, uint32_t mask) {
  return f3d_body_set_collision_filter((void *)world, ((uint64_t)body_high << 32) | body_low, layer, mask);
}

F3D_API int f3d_body_is_asleep__w(void * world, uint32_t body_low, uint32_t body_high) {
  return f3d_body_is_asleep((void *)world, ((uint64_t)body_high << 32) | body_low);
}

F3D_API int f3d_body_wake__w(void * world, uint32_t body_low, uint32_t body_high) {
  return f3d_body_wake((void *)world, ((uint64_t)body_high << 32) | body_low);
}

F3D_API int f3d_body_set_material__w(void * world, uint32_t body_low, uint32_t body_high, void * material) {
  return f3d_body_set_material((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)material);
}

F3D_API int f3d_body_set_temperature__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real kelvin) {
  return f3d_body_set_temperature((void *)world, ((uint64_t)body_high << 32) | body_low, kelvin);
}

F3D_API int f3d_body_get_temperature__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_temperature((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_add_heat__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real joules) {
  return f3d_body_add_heat((void *)world, ((uint64_t)body_high << 32) | body_low, joules);
}

F3D_API int f3d_body_add_water__w(void * world, uint32_t body_low, uint32_t body_high, f3d_real kg) {
  return f3d_body_add_water((void *)world, ((uint64_t)body_high << 32) | body_low, kg);
}

F3D_API int f3d_body_get_water__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_water((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_get_fuel__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_fuel((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_is_burning__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_is_burning((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}

F3D_API int f3d_body_get_heat_release__w(void * world, uint32_t body_low, uint32_t body_high, void * out) {
  return f3d_body_get_heat_release((void *)world, ((uint64_t)body_high << 32) | body_low, (void *)out);
}
