/// What this game ships that somebody else made.
///
/// The class and the screen are `flutter3d_ui`'s — see `Credit` there. What is
/// here is the list, which is this game's alone.
///
/// **This game had no credits screen at all**, and until now it did not need
/// one: every texture and every sound in it is generated by a script in
/// `tool/`, and the only model was the generated key. The monsters are the
/// first thing in it somebody else made.
library;

import 'package:flutter3d_app/flutter3d_app.dart'; // Credit, from flutter3d_ui

/// Everything the game ships that somebody else made.
///
/// The textures come from ambientCG and every sound is synthesised by
/// `tool/make_sounds.py`; the textures are credited in
/// `assets/textures/LICENSES.md` and appear here as one line rather than five,
/// because five rows saying CC0 is a screen nobody reads to the end of.
abstract final class Credits {
  static const List<Credit> models = <Credit>[
    Credit(
      file: 'models/monster_runner.glb',
      work: 'Frog, from the Ultimate Monsters pack',
      author: 'Quaternius',
      source: 'https://quaternius.com/packs/ultimatemonsters.html',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modified: true,
    ),
    Credit(
      file: 'models/monster_shooter.glb',
      work: 'Wizard, from the Ultimate Monsters pack',
      author: 'Quaternius',
      source: 'https://quaternius.com/packs/ultimatemonsters.html',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modified: true,
    ),
    Credit(
      file: 'models/monster_tank.glb',
      work: 'Yeti, from the Ultimate Monsters pack',
      author: 'Quaternius',
      source: 'https://quaternius.com/packs/ultimatemonsters.html',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modified: true,
    ),
    // **The editor's marks.** Generated here by `tool/make_models.py`, out of
    // the same functions that build the shooter template's models — a note, a
    // pickup, a way down and the point the player starts at. They exist because
    // an editor that cannot know what a word means was drawing a coloured cube
    // for every one of them.
    Credit(
      file: 'models/exit.glb',
      work: 'A way down',
      author: 'this repository',
      source: 'tool/make_models.py',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    ),
    Credit(
      file: 'models/note.glb',
      work: 'A page on a wall',
      author: 'this repository',
      source: 'tool/make_models.py',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    ),
    Credit(
      file: 'models/pickup.glb',
      work: 'A crate of supplies',
      author: 'this repository',
      source: 'tool/make_models.py',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    ),
    Credit(
      file: 'models/player_spawn.glb',
      work: 'Where the player starts',
      author: 'this repository',
      source: 'tool/make_models.py',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    ),
    Credit(
      file: 'models/key.glb',
      work: 'A key',
      // Generated here, and the entry is the record of that rather than a debt.
      // The key that used to sit in this slot in both games came from an
      // archive with no licence file and no author, and was the only thing
      // standing between either of them and a release.
      author: 'this repository',
      source: 'apps/flutter3d_demo_platformer/tool/make_key.py',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    ),
  ];

  /// The ones whose licence makes naming the author a condition.
  ///
  /// Empty, because everything here is CC0 — which is why the pack was chosen.
  /// The list stays: the next model dropped into `assets/models` is one
  /// somebody found somewhere.
  static List<Credit> get owed =>
      models.where((Credit c) => c.owesAttribution).toList();

  /// The ones that cannot be credited because nobody knows who made them.
  ///
  /// While this has anything in it the game cannot be released, whatever the
  /// screen says. `credits_test.dart` reads the asset directory rather than
  /// this list, so an untraced file arriving is a red test rather than an entry
  /// somebody forgets to add.
  static List<Credit> get untraced =>
      models.where((Credit c) => !c.traced).toList();
}
