/// What this game ships that somebody else made.
///
/// The ledger, the class and the screen are `flutter3d_game_ui/screens.dart`' — see
/// `CreditLedger` there. What is here is the list, which is this game's alone.
///
/// **This game had no credits screen at all**, and until now it did not need
/// one: every texture and every sound in it is generated by a script in
/// `tool/`, and the only model was the generated key. The monsters are the
/// first thing in it somebody else made.
library;

import 'package:flutter3d_game_ui/screens.dart';

/// Everything the game ships that somebody else made.
///
/// The textures come from ambientCG and every sound is synthesised by
/// `tool/make_sounds.py`; the textures are credited in
/// `assets/textures/LICENSES.md` and appear here as one line rather than five,
/// because five rows saying CC0 is a screen nobody reads to the end of.
const CreditLedger credits = CreditLedger(<Credit>[
  Credit(
    file: 'models/monster_runner.glb',
    work: 'Frog, from the Ultimate Monsters pack',
    author: 'Quaternius',
    source: 'https://quaternius.com/packs/ultimatemonsters.html',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    modified: true,
  ),
  Credit(
    file: 'models/monster_shooter.glb',
    work: 'Wizard, from the Ultimate Monsters pack',
    author: 'Quaternius',
    source: 'https://quaternius.com/packs/ultimatemonsters.html',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    modified: true,
  ),
  Credit(
    file: 'models/monster_tank.glb',
    work: 'Yeti, from the Ultimate Monsters pack',
    author: 'Quaternius',
    source: 'https://quaternius.com/packs/ultimatemonsters.html',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    modified: true,
  ),
  // **The two weapons that have art.** The fists and the rocket launcher are
  // still procedural blocks and so are credited to nobody, which is the
  // honest entry for a shape this repository made up.
  Credit(
    file: 'models/weapon_pistol.glb',
    work: 'Pistol, from the Ultimate Gun pack',
    author: 'Quaternius',
    source: 'https://quaternius.com/packs/ultimategun.html',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    modified: true,
  ),
  Credit(
    file: 'models/weapon_shotgun.glb',
    work: 'Shotgun, from the Ultimate Gun pack',
    author: 'Quaternius',
    source: 'https://quaternius.com/packs/ultimategun.html',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    modified: true,
  ),
  // **The editor's marks, and one of them the game's too.** Generated by
  // `tool/make_models.py`, out of the same functions that build the shooter
  // template's models — a note, a pickup, a way down and the point the player
  // starts at. They exist because an editor that cannot know what a word
  // means was drawing a coloured cube for every one of them.
  //
  // `exit.glb` is no longer only a mark: the game draws it too, because an
  // exit is a trigger with no geometry and the way out of every level was an
  // invisible box in a wall. See `exit_door.dart`.
  Credit(
    file: 'models/exit.glb',
    work: 'A way down',
    author: 'this repository',
    source: 'tool/make_models.py',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
  ),
  Credit(
    file: 'models/note.glb',
    work: 'A page on a wall',
    author: 'this repository',
    source: 'tool/make_models.py',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
  ),
  Credit(
    file: 'models/pickup.glb',
    work: 'A crate of supplies',
    author: 'this repository',
    source: 'tool/make_models.py',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
  ),
  Credit(
    file: 'models/player_spawn.glb',
    work: 'Where the player starts',
    author: 'this repository',
    source: 'tool/make_models.py',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
  ),
  Credit(
    file: 'models/key.glb',
    work: 'A key',
    // Generated here, and the entry is the record of that rather than a debt.
    // The key that used to sit in this slot in both games came from an
    // archive with no licence file and no author, and was the only thing
    // standing between either of them and a release.
    author: 'this repository',
    source: 'apps/flutter3d_demo_platformer/tool/make_key.py',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
  ),
]);
