/// Translates the engine's GLSL into a Dart table of WGSL and reflection.
///
///     dart run tool/generate_shaders.dart
///
/// Generated at build time and committed, for the reason the other two
/// backends' tables are: a translation that fails should fail while somebody is
/// looking, not on a user's first frame. `tool/ci.sh` runs this and diffs the
/// result, because a table nobody diffed once held a sky from before the sky
/// was rewritten, and the browser drew a different sky from Impeller with
/// nothing able to see it.
///
/// **The built-in shaders and a loadable bundle are two pipelines, and only one
/// of them is obvious.** `webgpu_bundle_section.dart` is what a `ShaderBundle`
/// carries; this file is what the engine's own stages are. Building the section
/// alone would give a backend that can read somebody else's bundle and cannot
/// draw a scene — every `LightingModel.shaderName` the renderer asks for would
/// go unanswered — and it would look finished from the outside, because the
/// codec would be tested and green. So both come out of one manifest, in one
/// run, through one preparation.
///
/// The sources come from `flutter3d_shaders`, resolved by package name through
/// `.dart_tool/package_config.json` — the one mapping pub guarantees for path,
/// git and hosted dependencies alike. A relative path would work here and break
/// the day this package is consumed from the cache.
///
/// **Nothing here may reach `package:flutter`.** `tool/ci.sh` calls this with
/// `dart run`, on the plain Dart VM, the same way it calls the WebGL2
/// generator; `flutter3d_hardware` reaches `package:flutter` for the widget
/// `present` returns, so importing `src/webgpu_bundle_section.dart` here would
/// make this a script CI has no way to run. This file prints that file's types
/// rather than constructing them, which is why it does not need them.
library;

import 'dart:io';

// The include resolver, and only the include resolver. A second one would be a
// second answer to "which headers does this shader really pull in", and the two
// backends would drift apart in the one place where drifting apart cannot be
// seen from either side. Called from here rather than from `prepareStage`
// because `flutter3d_webgl` is a dev dependency and a file under `lib/` may
// only import what ships.
//
// ignore: implementation_imports
import 'package:flutter3d_webgl/src/glsl_translate.dart';
import 'package:flutter3d_webgpu/src/glsl_to_wgsl.dart';
import 'package:flutter3d_webgpu/src/source_package.dart';
import 'package:flutter3d_webgpu/src/wgsl_compiler.dart';

void main(List<String> args) {
  final ShaderSet shaders;
  try {
    shaders = loadShaders();
  } on StateError catch (error) {
    _fail(error.message);
  }

  // Resolved once and kept, because both the varying scan and the preparation
  // read the whole tree of headers and neither should read it twice.
  final Map<String, String> resolved;
  try {
    resolved = <String, String>{
      for (final entry in shaders.stages.values)
        entry.file: resolveIncludes(
          shaders.sources[entry.file]!,
          shaders.sources,
          from: entry.file,
        ),
    };
  } on GlslTranslateError catch (error) {
    _fail(error.message);
  }

  // One pass to learn every varying name, then the numbering, then the
  // preparation. Two passes because a varying's location is decided across the
  // manifest and not inside one file — see `assignVaryingLocations`.
  final Map<String, int> varyingLocations;
  try {
    varyingLocations = assignVaryingLocations(<Set<String>>[
      for (final entry in shaders.stages.values)
        scanVaryings(
          resolved[entry.file]!,
          from: entry.file,
          fragment: entry.fragment,
        ),
    ]);
  } on WgslPrepareError catch (error) {
    _fail(error.message);
  }

  final vertex = <String, _Stage>{};
  final fragment = <String, _Stage>{};
  shaders.stages.forEach((name, entry) {
    final PreparedStage prepared;
    final CompiledStage compiled;
    try {
      prepared = prepareStage(
        resolved[entry.file]!,
        from: entry.file,
        fragment: entry.fragment,
        varyingLocations: varyingLocations,
      );
      compiled = compileStage(
        prepared.glsl,
        name: name,
        fragment: entry.fragment,
      );
    } on WgslPrepareError catch (error) {
      _fail('$name: ${error.message}');
    } on WgslCompileError catch (error) {
      _fail('$name: ${error.message}');
    }

    _checkOffsets(name, prepared, compiled.offsets);

    (entry.fragment ? fragment : vertex)[name] = (
      wgsl: compiled.wgsl,
      prepared: prepared,
    );
  });

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_shaders.dart. Do not edit.')
    ..writeln('//')
    ..writeln('// Source: package:flutter3d_shaders, through glslangValidator')
    ..writeln('// and naga. `tool/ci.sh` regenerates this file and fails if')
    ..writeln('// what comes out is not what is committed.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'package:flutter3d_hardware/flutter3d_hardware.dart';")
    ..writeln()
    ..writeln("import 'src/webgpu_bundle_section.dart';")
    ..writeln()
    ..writeln('/// Every shader the engine asks for, in WGSL, beside the')
    ..writeln('/// reflection a `GPUShaderModule` cannot be asked for.')
    ..writeln('final WebGpuSectionStages engineShaders = (')
    ..writeln('  vertex: <String, WebGpuStage>{');
  vertex.forEach((name, stage) => _writeStage(out, name, stage));
  out
    ..writeln('  },')
    ..writeln('  fragment: <String, WebGpuStage>{');
  fragment.forEach((name, stage) => _writeStage(out, name, stage));
  out
    ..writeln('  },')
    ..writeln(');');

  final target = File('lib/engine_shaders.dart');
  target.writeAsStringSync(out.toString());

  // Formatted here rather than left to `dart format` later, because `ci.sh`
  // formats the tree and *then* regenerates and diffs this file. An unformatted
  // generator would make those two steps disagree on a day nothing changed.
  final formatted = Process.runSync('dart', <String>['format', target.path]);
  if (formatted.exitCode != 0) {
    _fail('dart format refused ${target.path}: ${formatted.stderr}');
  }

  stdout.writeln(
    'wrote ${target.path}: ${vertex.length} vertex, ${fragment.length} '
    'fragment, ${vertex.length + fragment.length} of ${shaders.stages.length} '
    'stages through glslang and naga',
  );
}

/// Holds the packer's std140 arithmetic against glslang's own decorations.
///
/// Two independent answers to the same question. The packer computes offsets
/// from the GLSL because the reflection has to exist before there is any WGSL
/// to read it out of; glslang writes them into the SPIR-V because that is what
/// `std140` means. They agree here or the build stops.
///
/// **A block the listing does not mention at all is the sharper failure.** It
/// means the reflection claims a block the compiled shader does not have —
/// which happens the moment a `#ifndef` guard is read wrongly, and which the
/// engine turns into a bind of a slot that is not there. `lib/surface.glsl`
/// records what that costs on the other two backends: a native crash inside
/// Metal, and a draw discarded with nothing logged.
void _checkOffsets(
  String name,
  PreparedStage prepared,
  Map<String, Map<String, int>> offsets,
) {
  for (final block in prepared.blocks) {
    final theirs = offsets[block.name];
    if (theirs == null) {
      _fail(
        '$name: the reflection has the block "${block.name}" and the compiled '
        'shader does not',
      );
    }
    for (final member in block.members) {
      final expected = theirs[member.name];
      if (expected == null) {
        _fail(
          '$name: "${block.name}.${member.name}" is in the reflection and not '
          'in the compiled block',
        );
      }
      if (expected != member.offsetInBytes) {
        _fail(
          '$name: "${block.name}.${member.name}" is at ${member.offsetInBytes} '
          'by std140 and at $expected in the SPIR-V',
        );
      }
    }
  }
}

/// One finished stage: the WGSL the two compilers made, and the reflection the
/// preparation handed out.
typedef _Stage = ({String wgsl, PreparedStage prepared});

void _writeStage(StringBuffer out, String name, _Stage stage) {
  out
    ..writeln("    '$name': WebGpuStage(")
    ..writeln("      wgsl: r'''")
    ..write(stage.wgsl)
    ..writeln("''',")
    ..writeln('      attributes: <WebGpuAttribute>[');
  for (final attribute in stage.prepared.attributes) {
    out.writeln(
      "        WebGpuAttribute(name: '${attribute.name}', "
      'location: ${attribute.location}, '
      'format: VertexFormat.${attribute.format}),',
    );
  }
  out
    ..writeln('      ],')
    ..writeln('      blocks: <WebGpuBlock>[');
  for (final block in stage.prepared.blocks) {
    out
      ..writeln('        WebGpuBlock(')
      ..writeln("          name: '${block.name}',")
      ..writeln('          group: ${block.group},')
      ..writeln('          binding: ${block.binding},')
      ..writeln('          sizeInBytes: ${block.sizeInBytes},')
      ..writeln('          members: <WebGpuBlockMember>[');
    for (final member in block.members) {
      out.writeln(
        "            WebGpuBlockMember(name: '${member.name}', "
        'offsetInBytes: ${member.offsetInBytes}, '
        'sizeInBytes: ${member.sizeInBytes}),',
      );
    }
    out
      ..writeln('          ],')
      ..writeln('        ),');
  }
  out
    ..writeln('      ],')
    ..writeln('      samplers: <WebGpuSampler>[');
  for (final sampler in stage.prepared.samplers) {
    out
      ..writeln('        WebGpuSampler(')
      ..writeln("          name: '${sampler.name}',")
      ..writeln('          group: ${sampler.group},')
      ..writeln('          textureBinding: ${sampler.textureBinding},')
      ..writeln('          samplerBinding: ${sampler.samplerBinding},')
      ..writeln(
        '          dimension: WebGpuTextureDimension.${sampler.dimension},',
      )
      ..writeln('        ),');
  }
  out
    ..writeln('      ],')
    ..writeln('    ),');
}

Never _fail(String message) {
  stderr.writeln('generate_shaders: $message');
  exit(2);
}
