/// Writes `lib/engine_compute_shaders.dart`: the engine's compute stages in
/// WGSL, with their bindings and workgroup size — `H6`.
///
///     dart run tool/generate_compute_shaders.dart
///
/// Beside `generate_shaders.dart` rather than inside it, for the reason the
/// compute stages have a manifest of their own: the render stages go through
/// a packer that numbers every binding and assigns every varying, and a
/// compute stage has neither a vertex half to agree with nor anything to
/// number — its GLSL writes `set` and `binding` out, and those numbers are
/// the reflection. So this reads them back off the source, compiles through
/// the same glslang and naga with the same flags, and writes a second table.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter3d_webgl/src/glsl_translate.dart';
import 'package:flutter3d_webgpu/src/source_package.dart';
import 'package:flutter3d_webgpu/src/wgsl_compiler.dart';

final RegExp _localSize = RegExp(
  r'layout\s*\(\s*local_size_x\s*=\s*(\d+)'
  r'(?:\s*,\s*local_size_y\s*=\s*(\d+))?'
  r'(?:\s*,\s*local_size_z\s*=\s*(\d+))?\s*\)\s*in\s*;',
);
final RegExp _storage = RegExp(
  r'layout\s*\(([^)]*)\)\s*(readonly\s+)?buffer\s+(\w+)',
);
final RegExp _uniform = RegExp(
  r'layout\s*\(([^)]*)\)\s*uniform\s+(\w+)\s*\{([^}]*)\}',
);
final RegExp _member = RegExp(r'(vec4|mat4)\s+(\w+)\s*(?:\[\s*(\d+)\s*\])?\s*;');

int _qualifier(String layout, String name, String stage) {
  final match = RegExp('$name\\s*=\\s*(\\d+)').firstMatch(layout);
  if (match == null) {
    throw StateError(
      '$stage: a binding without `$name = …` in its layout; compute stages '
      'write their numbers out, and the numbers are the reflection',
    );
  }
  return int.parse(match.group(1)!);
}

void main() {
  final root = packageRoot('flutter3d_shaders');
  final shaders = '$root/shaders';
  final manifest =
      jsonDecode(File('$shaders/flutter3d.compute.json').readAsStringSync())
          as Map<String, Object?>;
  final sources = <String, String>{
    for (final file in Directory(shaders)
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('.glsl') || f.path.endsWith('.comp')))
      file.path.substring(shaders.length + 1): file.readAsStringSync(),
  };

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_compute_shaders.dart. Do not edit.')
    ..writeln('//')
    ..writeln('// Source: flutter3d.compute.json in package:flutter3d_shaders,')
    ..writeln('// through glslangValidator and naga.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'src/webgpu_bundle_section.dart';")
    ..writeln("import 'src/webgpu_compute_stage.dart';")
    ..writeln()
    ..writeln("/// The engine's compute stages, in WGSL, with their bindings.")
    ..writeln(
      'const Map<String, WebGpuComputeStage> engineComputeShaders = '
      '<String, WebGpuComputeStage>{',
    );

  for (final MapEntry(key: name, value: raw) in manifest.entries) {
    final file = ((raw! as Map<String, Object?>)['file']! as String)
        .replaceFirst('shaders/', '');
    final glsl = resolveIncludes(sources[file]!, sources, from: file);
    final size = _localSize.firstMatch(glsl);
    if (size == null) throw StateError('$name declares no local_size');
    final compiled = compileStage(
      glsl,
      name: name,
      fragment: false,
      compute: true,
    );
    out
      ..writeln("  '$name': WebGpuComputeStage(")
      ..writeln("    wgsl: r'''")
      ..write(compiled.wgsl)
      ..writeln("''',")
      ..writeln(
        '    workgroupSize: (${size.group(1)}, ${size.group(2) ?? 1}, '
        '${size.group(3) ?? 1}),',
      )
      ..writeln('    storage: <WebGpuStorageBinding>[');
    for (final m in _storage.allMatches(glsl)) {
      out.writeln(
        "      WebGpuStorageBinding(name: '${m.group(3)}', "
        'group: ${_qualifier(m.group(1)!, 'set', name)}, '
        'binding: ${_qualifier(m.group(1)!, 'binding', name)}, '
        'readOnly: ${m.group(2) != null}),',
      );
    }
    out
      ..writeln('    ],')
      ..writeln('    blocks: <WebGpuBlock>[');
    for (final m in _uniform.allMatches(glsl)) {
      // std140 for the engine's own convention — every member a vec4 or a
      // mat4 — is sixteen bytes a row and nothing to pad.
      var offset = 0;
      final members = <String>[];
      for (final member in _member.allMatches(m.group(3)!)) {
        final count = int.parse(member.group(3) ?? '1');
        final bytes = (member.group(1) == 'mat4' ? 64 : 16) * count;
        members.add(
          "        WebGpuBlockMember(name: '${member.group(2)}', "
          'offsetInBytes: $offset, sizeInBytes: $bytes),',
        );
        offset += bytes;
      }
      out
        ..writeln('      WebGpuBlock(')
        ..writeln("        name: '${m.group(2)}',")
        ..writeln('        group: ${_qualifier(m.group(1)!, 'set', name)},')
        ..writeln(
          '        binding: ${_qualifier(m.group(1)!, 'binding', name)},',
        )
        ..writeln('        sizeInBytes: $offset,')
        ..writeln('        members: <WebGpuBlockMember>[')
        ..writeAll(members.map((l) => '$l\n'))
        ..writeln('        ],')
        ..writeln('      ),');
    }
    out
      ..writeln('    ],')
      ..writeln('  ),');
  }
  out.writeln('};');

  final target = File('lib/engine_compute_shaders.dart')
    ..writeAsStringSync(out.toString());
  Process.runSync('dart', <String>['format', target.path]);
  stdout.writeln(
    'wrote ${target.path}: ${manifest.length} compute '
    '${manifest.length == 1 ? 'stage' : 'stages'}',
  );
}
