// GENERATED by tool/embed_migrations.dart. Do not edit.
// Source: lib/src/db/migrations/*.sql
library;

import 'database.dart';

/// Every migration, in the order their numbers put them.
const migrations = <Migration>[
  Migration(1, '001_accounts_and_models.sql', r'''
-- The whole schema the first release needs: who has an account, who is signed
-- in, what was uploaded, and what is being rate limited.
--
-- Written as one migration rather than five because none of it has shipped yet;
-- from the second release on, every change is its own numbered file and this
-- one is never edited again.

create extension if not exists citext;

-- **Case folded, because a mailbox is.** `Ann@example.com` and
-- `ann@example.com` reach the same person, and a service that let them be two
-- accounts would send the reset letter to an account nobody signs into.
create table users (
  id                bigserial primary key,
  email             citext      not null unique,
  handle            text        not null unique,
  display_name      text        not null,
  password_hash     text        not null,
  email_verified_at timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- The session token itself is never stored: the row holds its SHA-256, so a
-- copy of this table is not a set of working cookies.
create table sessions (
  id           bigserial primary key,
  user_id      bigint      not null references users (id) on delete cascade,
  token_sha256 bytea       not null unique,
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at   timestamptz not null,
  user_agent   text,
  ip           inet
);

create index sessions_by_user on sessions (user_id);
create index sessions_by_expiry on sessions (expires_at);

-- One table for both letters. The purpose is a column rather than two tables
-- because everything else about them is identical — issued, expires, used once
-- — and two tables would be two places to fix a mistake about single use.
create table email_tokens (
  id           bigserial primary key,
  user_id      bigint      not null references users (id) on delete cascade,
  purpose      text        not null check (purpose in ('verify', 'reset')),
  token_sha256 bytea       not null unique,
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null,
  used_at      timestamptz
);

create index email_tokens_by_user on email_tokens (user_id, purpose);

create table models (
  id             bigserial primary key,
  owner_id       bigint      not null references users (id) on delete cascade,
  slug           text        not null,
  title          text        not null,
  description    text        not null default '',
  visibility     text        not null default 'private'
                 check (visibility in ('private', 'public')),
  -- Null while the model is private: a licence is chosen at publication, and a
  -- default one would be a licence nobody picked.
  licence        text,
  source_format  text        not null,
  triangle_count integer     not null default 0,
  size_bytes     bigint      not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  -- The slug is not unique, even per owner: a model's address is
  -- `/m/<id>-<slug>`, so the id already tells two chairs apart and the slug is
  -- there for the person reading the link.
  published_at   timestamptz
);

create index models_by_owner on models (owner_id, updated_at desc);

create index models_public_recent on models (published_at desc)
  where visibility = 'public';

-- Content, addressed by its own hash. Two people who upload the same cube have
-- one file on disk and two rows here.
create table model_files (
  id           bigserial primary key,
  model_id     bigint      not null references models (id) on delete cascade,
  kind         text        not null check (kind in ('source', 'preview')),
  blob_sha256  text        not null,
  bytes        bigint      not null,
  content_type text        not null,
  filename     text        not null,
  created_at   timestamptz not null default now(),

  unique (model_id, kind)
);

create index model_files_by_blob on model_files (blob_sha256);

-- Attempts worth counting: sign-in, registration, password reset. Kept in the
-- database rather than in memory so that a restart is not a way to clear the
-- count, and swept by the same job that sweeps expired sessions.
create table rate_events (
  bucket     text        not null,
  at         timestamptz not null default now()
);

create index rate_events_by_bucket on rate_events (bucket, at desc);
'''),
  Migration(2, '002_model_revisions.sql', r'''
-- Revision history for a model's source file, added for the cabinet's "save
-- back" stage. `model_files` still holds the current source — what
-- `/files/<id>/source` serves — so this table is everything a save replaced:
-- `revisionsOf` lists what changed, and `revisionFile` can still serve an
-- older upload by its own id.
--
-- **Append-only.** A row here is inserted once and never updated — the whole
-- reason to keep revisions is that an earlier save stays exactly as it was,
-- not as a copy that could itself drift.

create table model_revisions (
  id             bigserial primary key,
  model_id       bigint      not null references models (id) on delete cascade,
  blob_sha256    text        not null,
  bytes          bigint      not null,
  content_type   text        not null,
  filename       text        not null,
  triangle_count integer     not null default 0,
  created_at     timestamptz not null default now(),
  -- Never null: a save only ever happens through `_editing`, which checks for
  -- a signed-in session before any of this runs, so there is always somebody
  -- to ask about a change. No `on delete cascade` to `users`: deleting a
  -- model already takes every one of its revisions with it through
  -- `model_id`, so by the time a user row itself is deleted — which cascades
  -- through `models.owner_id` first — nothing here still points at them.
  created_by     bigint      not null references users (id)
);

-- Listing a model's history newest-first, the only order `revisionsOf` reads
-- it in.
create index model_revisions_by_model on model_revisions (model_id, created_at desc);

-- The same reason `model_files_by_blob` exists: `isReferenced` runs this
-- lookup for every blob a delete considers freeing, and once revisions exist
-- a blob can be kept alive by one of these rows alone, after a later save has
-- already moved `model_files` on to a different hash.
create index model_revisions_by_blob on model_revisions (blob_sha256);
'''),
  Migration(3, '003_projects_and_categories.sql', r'''
-- Projects, so a model can live inside one or stand alone, and category plus
-- full-text search, so the public showcase can be browsed and searched.

-- A folder an owner keeps their own models in. Nothing about visibility or
-- publication lives here — grouping a model under a project is not a second
-- place `canView`/`canEdit` gets decided; every model still carries its own
-- `owner_id` and its own `visibility`, project or no project.
create table projects (
  id          bigserial primary key,
  owner_id    bigint      not null references users (id) on delete cascade,
  slug        text        not null,
  title       text        not null,
  description text        not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- The same shape `models_by_owner` already has: a cabinet or a project list
-- reads one owner's rows, most recently changed first.
create index projects_by_owner on projects (owner_id, updated_at desc);

-- Nullable, because a model does not have to sit in a project at all, and
-- `set null` rather than `cascade` is what makes "delete a project, its
-- models become personal" a fact of this constraint alone — no application
-- code walks a deleted project's models to detach them, because by the time
-- any of it would run, the constraint has already done it.
alter table models add column project_id bigint references projects (id) on delete set null;

-- Looked up on every move and on a project's own page: which models currently
-- sit in one project, most recently changed first — the same reason
-- `models_by_owner` exists for the owner-wide list. Partial, since most rows
-- (every model with no project) have nothing to answer here.
create index models_by_project on models (project_id, updated_at desc)
  where project_id is not null;

-- A model's own category, chosen at publication the same way its licence is
-- — null while private, because a private model does not need one, and
-- constrained to a short fixed list for the same reason `licence` is a known
-- set of values rather than free text: the showcase's category filter only
-- ever chooses from this list, never matches whatever a client happened to
-- send.
alter table models add column category text
  check (category in (
    'characters', 'props', 'environments', 'vehicles', 'architecture',
    'abstract', 'other'
  ));

-- What the public showcase's own search reads — title weighted above
-- description, `english` config, and `stored` so a search does not
-- recompute this from every row on every query. This exists to serve the
-- showcase's search box alone; nothing else in this service searches a
-- model by its content.
alter table models add column search tsvector
  generated always as (
    setweight(to_tsvector('english', title), 'A') ||
    setweight(to_tsvector('english', description), 'B')
  ) stored;

create index models_search on models using gin (search);
'''),
];
