// GENERATED by flutter3d_testing/tool/quality_table.dart. Do not edit by hand.
//
// ignore_for_file: lines_longer_than_80_chars

/// The rows `QualityTable.of` reads — `N2`.
///
/// Not yet measured on any device class: every class holds the same
/// rows, measured on the software rasteriser at 128×80 over
/// two scenes (a room with occlusion, reflections and contact shadows;
/// a colonnade in volumetric fog with light shafts). The FLIP column
/// is the pictures' own; the cost column is the rasteriser's, which
/// stands in until each class is measured with `measureQualityTable`
/// on its own GPU. `AdaptiveQuality` corrects the rows it visits.
library;

/// Per `DeviceClass`, whether the rows were measured on that class.
const List<bool> qualityMeasured = <bool>[false, false, false];

/// Per `DeviceClass`, each `QualitySetting.grid` row's frame time over full
/// quality's.
const List<List<double>> qualityCost = <List<double>>[
  <double>[1.0000, 0.9300, 0.8600, 0.8200, 0.6900, 0.6200, 0.6100, 0.5400, 0.4700, 0.4500, 0.4100, 0.3900, 0.3600, 0.3200, 0.3000, 0.2800, 0.2300, 0.2200, 0.2100, 0.2000],
  <double>[1.0000, 0.9300, 0.8600, 0.8200, 0.6900, 0.6200, 0.6100, 0.5400, 0.4700, 0.4500, 0.4100, 0.3900, 0.3600, 0.3200, 0.3000, 0.2800, 0.2300, 0.2200, 0.2100, 0.2000],
  <double>[1.0000, 0.9300, 0.8600, 0.8200, 0.6900, 0.6200, 0.6100, 0.5400, 0.4700, 0.4500, 0.4100, 0.3900, 0.3600, 0.3200, 0.3000, 0.2800, 0.2300, 0.2200, 0.2100, 0.2000],
];

/// Per `DeviceClass`, each `QualitySetting.grid` row's mean FLIP against
/// full quality.
const List<List<double>> qualityFlip = <List<double>>[
  <double>[0.0000, 0.0236, 0.0535, 0.0638, 0.0717, 0.0756, 0.0870, 0.0929, 0.0927, 0.0961, 0.1033, 0.1093, 0.0968, 0.1007, 0.1051, 0.1124, 0.1201, 0.1224, 0.1282, 0.1359],
  <double>[0.0000, 0.0236, 0.0535, 0.0638, 0.0717, 0.0756, 0.0870, 0.0929, 0.0927, 0.0961, 0.1033, 0.1093, 0.0968, 0.1007, 0.1051, 0.1124, 0.1201, 0.1224, 0.1282, 0.1359],
  <double>[0.0000, 0.0236, 0.0535, 0.0638, 0.0717, 0.0756, 0.0870, 0.0929, 0.0927, 0.0961, 0.1033, 0.1093, 0.0968, 0.1007, 0.1051, 0.1124, 0.1201, 0.1224, 0.1282, 0.1359],
];
