/// Each level's committed lightmap was baked from the walls that shipped.
///
///     flutter test test/lightmap_freshness_test.dart
///
/// The crypt's five levels are generated by `tool/regenerate_levels.py`, and
/// both sidecars beside a level document are baked from it: the visibility
/// table, which `visibility_test.dart` holds to the brushes, and this one.
/// Only the table was checked. A regeneration that moves a wall therefore
/// failed one test and not the other, and the obvious repair — re-run
/// `bake_visibility` until it goes green — ships five stale lightmaps, which
/// the loader then refuses at runtime with a warning nobody reads and lights
/// the whole crypt with direct light and flat ambient instead.
///
/// The check is the loader's own: `Lightmap.isStaleFor` is exactly what
/// `LevelLoader.build` asks before it accepts a bake. Failing here is the same
/// question asked where somebody can still answer it.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter3d_game/flutter3d_game.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  for (final name in <String>[
    'crypt',
    'vaults',
    'deep',
    'cistern',
    'sanctum',
  ]) {
    test('$name ships a lightmap baked from its own brushes and lights', () {
      // Mutation: move a wall in assets/levels/crypt.json — the level hash
      // changes, `isStaleFor` answers true and this fails, which is what a
      // regenerated level with no re-bake looks like.
      final level = Level.fromJson(
        jsonDecode(File('assets/levels/$name.json').readAsStringSync())
            as Map<String, dynamic>,
      );
      final map = Lightmap.fromBytes(
        File('assets/levels/$name.lightmap.bin').readAsBytesSync(),
      );
      expect(
        map.isStaleFor(level),
        isFalse,
        reason:
            'run dart run flutter3d_sim:bake_lightmap — otherwise the level '
            'loads with no baked light at all, and only says so in a warning',
      );
    });
  }
}
