// GENERATED by flutter3d_impeller/tool/stage_bindings.dart.
// Do not edit; run the tool after any shader edit.

/// What every stage in the engine's bundle keeps once compiled:
/// the uniform blocks and samplers a draw through it must bind
/// and may bind. Read off impellerc's Metal reflection, so a
/// resource the source declares and the compiler dropped is
/// not here. `FakeBackend(stageBindings: stageBindings)` holds
/// a renderer to it on the VM.
library;

const Map<String, ({Set<String> blocks, Set<String> samplers})>
stageBindings = <String, ({Set<String> blocks, Set<String> samplers})>{
  'BlinnPhong': (
    blocks: <String>{
      'FogInfo',
      'FragInfo',
      'IrradianceInfo',
      'LightListInfo',
      'PointShadow',
    },
    samplers: <String>{
      'base_color_texture',
      'emissive_texture',
      'irradiance_texture',
      'light_list_texture',
      'lightmap_texture',
      'metallic_roughness_texture',
      'normal_texture',
      'occlusion_texture',
      'point_shadow_static_texture',
      'point_shadow_texture',
      'shadow_texture',
    },
  ),
  'BloomDownsample': (
    blocks: <String>{'BloomInfo'},
    samplers: <String>{'source_texture'},
  ),
  'BloomThreshold': (
    blocks: <String>{'BloomInfo'},
    samplers: <String>{'source_texture'},
  ),
  'BloomUpsample': (
    blocks: <String>{'BloomInfo'},
    samplers: <String>{'source_texture'},
  ),
  'CameraVelocity': (
    blocks: <String>{'CameraVelocityInfo'},
    samplers: <String>{'surface_texture'},
  ),
  'Composite': (
    blocks: <String>{'CompositeInfo', 'FragCoordInfo'},
    samplers: <String>{
      'ao_texture',
      'bloom_texture',
      'contact_shadow_texture',
      'display_texture',
      'lut_texture',
      'scene_texture',
    },
  ),
  'ContactShadow': (
    blocks: <String>{'ContactShadowInfo', 'FragCoordInfo', 'NoiseInfo'},
    samplers: <String>{'blue_noise_texture', 'surface_texture'},
  ),
  'DebugLine': (blocks: <String>{}, samplers: <String>{}),
  'DebugLineVertex': (blocks: <String>{'LineInfo'}, samplers: <String>{}),
  'DepthOfField': (
    blocks: <String>{'DofInfo', 'FragCoordInfo'},
    samplers: <String>{'scene_texture', 'surface_texture'},
  ),
  'FieldDecay': (
    blocks: <String>{'FieldDecayInfo'},
    samplers: <String>{'field_texture'},
  ),
  'FullscreenVertex': (blocks: <String>{}, samplers: <String>{}),
  'Fxaa': (blocks: <String>{'FxaaInfo'}, samplers: <String>{'source_texture'}),
  'Impostor': (
    blocks: <String>{'FogInfo', 'FragInfo', 'LightListInfo', 'PointShadow'},
    samplers: <String>{
      'base_color_texture',
      'light_list_texture',
      'normal_texture',
      'point_shadow_static_texture',
      'point_shadow_texture',
      'shadow_texture',
    },
  ),
  'ImpostorVertex': (blocks: <String>{'FrameInfo'}, samplers: <String>{}),
  'IrradianceConvolve': (
    blocks: <String>{'ConvolveInfo'},
    samplers: <String>{
      'field_texture',
      'radiance_texture',
      'seed_texture',
      'surface_texture',
    },
  ),
  'Lambert': (
    blocks: <String>{
      'FogInfo',
      'FragInfo',
      'IrradianceInfo',
      'LightListInfo',
      'PointShadow',
    },
    samplers: <String>{
      'base_color_texture',
      'emissive_texture',
      'irradiance_texture',
      'light_list_texture',
      'lightmap_texture',
      'normal_texture',
      'occlusion_texture',
      'point_shadow_static_texture',
      'point_shadow_texture',
      'shadow_texture',
    },
  ),
  'LightShafts': (
    blocks: <String>{'FragCoordInfo', 'NoiseInfo', 'ShaftInfo'},
    samplers: <String>{
      'blue_noise_texture',
      'scene_texture',
      'shadow_texture',
      'surface_texture',
    },
  ),
  'Luminance': (
    blocks: <String>{'LuminanceInfo'},
    samplers: <String>{'scene_texture'},
  ),
  'MeshInstancedVertex': (
    blocks: <String>{'FrameInfo', 'MorphInfo', 'MorphInstanceInfo'},
    samplers: <String>{'morph_instance_weights', 'morph_texture'},
  ),
  'MeshLightmappedVertex': (
    blocks: <String>{'FrameInfo', 'MorphInfo'},
    samplers: <String>{'morph_texture'},
  ),
  'MeshSkinnedVertex': (
    blocks: <String>{'FrameInfo', 'MorphInfo', 'SkinInfo'},
    samplers: <String>{'morph_texture'},
  ),
  'MeshVertex': (
    blocks: <String>{'FrameInfo', 'MorphInfo'},
    samplers: <String>{'morph_texture'},
  ),
  'MrtProbe': (blocks: <String>{}, samplers: <String>{}),
  'Normals': (blocks: <String>{'FogInfo'}, samplers: <String>{}),
  'ObjectId': (
    blocks: <String>{'IdInfo'},
    samplers: <String>{'base_color_texture'},
  ),
  'Particle': (blocks: <String>{'FogInfo'}, samplers: <String>{}),
  'ParticleMesh': (blocks: <String>{'FogInfo'}, samplers: <String>{}),
  'ParticleMeshVertex': (
    blocks: <String>{'ParticleMeshInfo'},
    samplers: <String>{},
  ),
  'ParticleTextured': (
    blocks: <String>{'FogInfo'},
    samplers: <String>{'particle_texture'},
  ),
  'ParticleVertex': (blocks: <String>{'ParticleInfo'}, samplers: <String>{}),
  'Pbr': (
    blocks: <String>{
      'FogInfo',
      'FragInfo',
      'IrradianceInfo',
      'LightListInfo',
      'PointShadow',
    },
    samplers: <String>{
      'base_color_texture',
      'emissive_texture',
      'environment_texture',
      'irradiance_texture',
      'light_list_texture',
      'lightmap_texture',
      'ltc_texture',
      'metallic_roughness_texture',
      'normal_texture',
      'occlusion_texture',
      'point_shadow_static_texture',
      'point_shadow_texture',
      'shadow_texture',
    },
  ),
  'PolylineVertex': (
    blocks: <String>{'FrameInfo', 'MaterialParams'},
    samplers: <String>{},
  ),
  'ProbePrefilter': (
    blocks: <String>{'ProbeInfo'},
    samplers: <String>{'capture_texture'},
  ),
  'Reflections': (
    blocks: <String>{'FragCoordInfo', 'NoiseInfo', 'ReflectionInfo'},
    samplers: <String>{
      'blue_noise_texture',
      'scene_texture',
      'surface_texture',
    },
  ),
  'ShadowCopy': (
    blocks: <String>{'ShadowCopyInfo'},
    samplers: <String>{'static_shadow_texture'},
  ),
  'ShadowDepth': (blocks: <String>{}, samplers: <String>{}),
  'ShadowDepthMasked': (
    blocks: <String>{'MaskInfo'},
    samplers: <String>{'base_color_texture'},
  ),
  'ShadowDistance': (blocks: <String>{'ShadowLight'}, samplers: <String>{}),
  'ShadowDistanceMasked': (
    blocks: <String>{'MaskInfo', 'ShadowLight'},
    samplers: <String>{'base_color_texture'},
  ),
  'ShadowTileReset': (blocks: <String>{}, samplers: <String>{}),
  'ShadowTileResetVertex': (blocks: <String>{}, samplers: <String>{}),
  'Sky': (blocks: <String>{}, samplers: <String>{}),
  'SkyCube': (blocks: <String>{}, samplers: <String>{'sky_texture'}),
  'SkyCubeVertex': (blocks: <String>{}, samplers: <String>{}),
  'SkyVertex': (blocks: <String>{}, samplers: <String>{}),
  'Splat': (blocks: <String>{'FogInfo'}, samplers: <String>{}),
  'Ssao': (
    blocks: <String>{'NoiseInfo', 'SsaoInfo'},
    samplers: <String>{
      'albedo_texture',
      'blue_noise_texture',
      'scene_texture',
      'surface_texture',
    },
  ),
  'SsaoBlur': (
    blocks: <String>{'SsaoBlurInfo'},
    samplers: <String>{'ao_texture', 'surface_texture'},
  ),
  'TemporalAccumulate': (
    blocks: <String>{'AccumulateInfo'},
    samplers: <String>{
      'current_texture',
      'history_texture',
      'velocity_texture',
    },
  ),
  'TemporalResolve': (
    blocks: <String>{'TemporalInfo'},
    samplers: <String>{
      'history_texture',
      'scene_texture',
      'surface_texture',
      'velocity_texture',
    },
  ),
  'Toon': (
    blocks: <String>{
      'FogInfo',
      'FragInfo',
      'IrradianceInfo',
      'LightListInfo',
      'PointShadow',
    },
    samplers: <String>{
      'base_color_texture',
      'emissive_texture',
      'irradiance_texture',
      'light_list_texture',
      'lightmap_texture',
      'metallic_roughness_texture',
      'normal_texture',
      'occlusion_texture',
      'point_shadow_static_texture',
      'point_shadow_texture',
      'shadow_texture',
    },
  ),
  'Unlit': (
    blocks: <String>{'FogInfo', 'FragInfo'},
    samplers: <String>{'base_color_texture'},
  ),
  'Velocity': (
    blocks: <String>{'VelocityInfo'},
    samplers: <String>{'surface_texture'},
  ),
  'VelocityInstancedVertex': (
    blocks: <String>{'FrameInfo', 'MorphInfo', 'PrevFrameInfo'},
    samplers: <String>{'morph_texture'},
  ),
  'VelocitySkinnedVertex': (
    blocks: <String>{'FrameInfo', 'MorphInfo', 'PrevFrameInfo', 'SkinInfo'},
    samplers: <String>{'morph_texture', 'prev_joint_texture'},
  ),
  'VelocityVertex': (
    blocks: <String>{'FrameInfo', 'MorphInfo', 'PrevFrameInfo'},
    samplers: <String>{'morph_texture'},
  ),
  'VertexTextureProbe': (blocks: <String>{}, samplers: <String>{}),
  'VertexTextureProbeVertex': (
    blocks: <String>{'ProbeInfo'},
    samplers: <String>{'probe_texture'},
  ),
  'ViewportShade': (
    blocks: <String>{'ShadeInfo'},
    samplers: <String>{'scene_texture', 'surface_texture'},
  ),
  'Xray': (
    blocks: <String>{'FogInfo', 'FragInfo'},
    samplers: <String>{'base_color_texture'},
  ),
};
