// GENERATED by flutter3d_impeller/tool/stage_bindings.dart.
// Do not edit; run the tool after any shader edit.

/// A class per uniform block the engine's stages declare, one
/// preallocated array per member, laid out as the compiler lays
/// it out. Filled in place and bound with
/// `PassEncoder.bindBlock`.
library;

import 'dart:typed_data';

import 'package:flutter3d_hardware/flutter3d_hardware.dart';

/// `AccumulateInfo`.
final class AccumulateInfoBlock extends UniformBlock {
  AccumulateInfoBlock() : super('AccumulateInfo');

  /// `params`: Vector4, at byte 0.
  final Float32List params = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'params': params,
  };
}

/// `BloomInfo`.
final class BloomInfoBlock extends UniformBlock {
  BloomInfoBlock() : super('BloomInfo');

  /// `params`: Vector4, at byte 0.
  final Float32List params = Float32List(4);

  /// `tint`: Vector4, at byte 16.
  final Float32List tint = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'params': params,
    'tint': tint,
  };
}

/// `CameraVelocityInfo`.
final class CameraVelocityInfoBlock extends UniformBlock {
  CameraVelocityInfoBlock() : super('CameraVelocityInfo');

  /// `inverse_view_projection`: Matrix, at byte 0.
  final Float32List inverseViewProjection = Float32List(16);

  /// `previous_view_projection`: Matrix, at byte 64.
  final Float32List previousViewProjection = Float32List(16);

  /// `camera`: Vector4, at byte 128.
  final Float32List camera = Float32List(4);

  /// `forward`: Vector4, at byte 144.
  final Float32List forward = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'inverse_view_projection': inverseViewProjection,
    'previous_view_projection': previousViewProjection,
    'camera': camera,
    'forward': forward,
  };
}

/// `CompositeInfo`.
final class CompositeInfoBlock extends UniformBlock {
  CompositeInfoBlock() : super('CompositeInfo');

  /// `params`: Vector4, at byte 0.
  final Float32List params = Float32List(4);

  /// `ao_texel`: Vector4, at byte 16.
  final Float32List aoTexel = Float32List(4);

  /// `look`: Vector4, at byte 32.
  final Float32List look = Float32List(4);

  /// `look_more`: Vector4, at byte 48.
  final Float32List lookMore = Float32List(4);

  /// `output_encode`: Vector4, at byte 64.
  final Float32List outputEncode = Float32List(4);

  /// `lift`: Vector4, at byte 80.
  final Float32List lift = Float32List(4);

  /// `gamma`: Vector4, at byte 96.
  final Float32List gamma = Float32List(4);

  /// `gain`: Vector4, at byte 112.
  final Float32List gain = Float32List(4);

  /// `contact`: Vector4, at byte 128.
  final Float32List contact = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'params': params,
    'ao_texel': aoTexel,
    'look': look,
    'look_more': lookMore,
    'output_encode': outputEncode,
    'lift': lift,
    'gamma': gamma,
    'gain': gain,
    'contact': contact,
  };
}

/// `ContactShadowInfo`.
final class ContactShadowInfoBlock extends UniformBlock {
  ContactShadowInfoBlock() : super('ContactShadowInfo');

  /// `inverse_view_projection`: Matrix, at byte 0.
  final Float32List inverseViewProjection = Float32List(16);

  /// `view_projection`: Matrix, at byte 64.
  final Float32List viewProjection = Float32List(16);

  /// `params`: Vector4, at byte 128.
  final Float32List params = Float32List(4);

  /// `camera`: Vector4, at byte 144.
  final Float32List camera = Float32List(4);

  /// `forward`: Vector4, at byte 160.
  final Float32List forward = Float32List(4);

  /// `to_light`: Vector4, at byte 176.
  final Float32List toLight = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'inverse_view_projection': inverseViewProjection,
    'view_projection': viewProjection,
    'params': params,
    'camera': camera,
    'forward': forward,
    'to_light': toLight,
  };
}

/// `ConvolveInfo`.
final class ConvolveInfoBlock extends UniformBlock {
  ConvolveInfoBlock() : super('ConvolveInfo');

  /// `probe`: Vector4, at byte 0.
  final Float32List probe = Float32List(4);

  /// `tiles`: Vector4, at byte 16.
  final Float32List tiles = Float32List(4);

  /// `atlas`: Vector4, at byte 32.
  final Float32List atlas = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'probe': probe,
    'tiles': tiles,
    'atlas': atlas,
  };
}

/// `DofInfo`.
final class DofInfoBlock extends UniformBlock {
  DofInfoBlock() : super('DofInfo');

  /// `lens`: Vector4, at byte 0.
  final Float32List lens = Float32List(4);

  /// `params`: Vector4, at byte 16.
  final Float32List params = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'lens': lens,
    'params': params,
  };
}

/// `FieldDecayInfo`.
final class FieldDecayInfoBlock extends UniformBlock {
  FieldDecayInfoBlock() : super('FieldDecayInfo');

  /// `params`: Vector4, at byte 0.
  final Float32List params = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'params': params,
  };
}

/// `FogInfo`.
final class FogInfoBlock extends UniformBlock {
  FogInfoBlock() : super('FogInfo');

  /// `fog`: Vector4, at byte 0.
  final Float32List fog = Float32List(4);

  /// `eye`: Vector4, at byte 16.
  final Float32List eye = Float32List(4);

  /// `forward`: Vector4, at byte 32.
  final Float32List forward = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'fog': fog,
    'eye': eye,
    'forward': forward,
  };
}

/// `FragCoordInfo`.
final class FragCoordInfoBlock extends UniformBlock {
  FragCoordInfoBlock() : super('FragCoordInfo');

  /// `origin`: Vector4, at byte 0.
  final Float32List origin = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'origin': origin,
  };
}

/// `FragInfo`.
final class FragInfoBlock extends UniformBlock {
  FragInfoBlock() : super('FragInfo');

  /// `light_position`: 8 × Vector4, at byte 0.
  final Float32List lightPosition = Float32List(32);

  /// `light_color`: 8 × Vector4, at byte 128.
  final Float32List lightColor = Float32List(32);

  /// `light_direction`: 8 × Vector4, at byte 256.
  final Float32List lightDirection = Float32List(32);

  /// `light_cone`: 8 × Vector4, at byte 384.
  final Float32List lightCone = Float32List(32);

  /// `base_color`: Vector4, at byte 512.
  final Float32List baseColor = Float32List(4);

  /// `emissive`: Vector4, at byte 528.
  final Float32List emissive = Float32List(4);

  /// `camera_position`: Vector4, at byte 544.
  final Float32List cameraPosition = Float32List(4);

  /// `material`: Vector4, at byte 560.
  final Float32List material = Float32List(4);

  /// `material2`: Vector4, at byte 576.
  final Float32List material2 = Float32List(4);

  /// `frame_params`: Vector4, at byte 592.
  final Float32List frameParams = Float32List(4);

  /// `shadow_params`: Vector4, at byte 608.
  final Float32List shadowParams = Float32List(4);

  /// `shadow_matrix`: Matrix, at byte 624.
  final Float32List shadowMatrix = Float32List(16);

  /// `shadow_matrix_far`: Matrix, at byte 688.
  final Float32List shadowMatrixFar = Float32List(16);

  /// `shadow_matrix_farthest`: Matrix, at byte 752.
  final Float32List shadowMatrixFarthest = Float32List(16);

  /// `shadow_cascades`: Vector4, at byte 816.
  final Float32List shadowCascades = Float32List(4);

  /// `ambient_sky`: Vector4, at byte 832.
  final Float32List ambientSky = Float32List(4);

  /// `ambient_ground`: Vector4, at byte 848.
  final Float32List ambientGround = Float32List(4);

  /// `shadow_bias`: Vector4, at byte 864.
  final Float32List shadowBias = Float32List(4);

  /// `target_origin`: Vector4, at byte 880.
  final Float32List targetOrigin = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'light_position': lightPosition,
    'light_color': lightColor,
    'light_direction': lightDirection,
    'light_cone': lightCone,
    'base_color': baseColor,
    'emissive': emissive,
    'camera_position': cameraPosition,
    'material': material,
    'material2': material2,
    'frame_params': frameParams,
    'shadow_params': shadowParams,
    'shadow_matrix': shadowMatrix,
    'shadow_matrix_far': shadowMatrixFar,
    'shadow_matrix_farthest': shadowMatrixFarthest,
    'shadow_cascades': shadowCascades,
    'ambient_sky': ambientSky,
    'ambient_ground': ambientGround,
    'shadow_bias': shadowBias,
    'target_origin': targetOrigin,
  };
}

/// `FrameInfo`.
final class FrameInfoBlock extends UniformBlock {
  FrameInfoBlock() : super('FrameInfo');

  /// `mvp`: Matrix, at byte 0.
  final Float32List mvp = Float32List(16);

  /// `model`: Matrix, at byte 64.
  final Float32List model = Float32List(16);

  /// `normal_matrix`: Matrix, at byte 128.
  final Float32List normalMatrix = Float32List(16);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'mvp': mvp,
    'model': model,
    'normal_matrix': normalMatrix,
  };
}

/// `FxaaInfo`.
final class FxaaInfoBlock extends UniformBlock {
  FxaaInfoBlock() : super('FxaaInfo');

  /// `params`: Vector4, at byte 0.
  final Float32List params = Float32List(4);

  /// `sharpen`: Vector4, at byte 16.
  final Float32List sharpen = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'params': params,
    'sharpen': sharpen,
  };
}

/// `IdInfo`.
final class IdInfoBlock extends UniformBlock {
  IdInfoBlock() : super('IdInfo');

  /// `id`: Vector4, at byte 0.
  final Float32List id = Float32List(4);

  /// `mask`: Vector4, at byte 16.
  final Float32List mask = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'id': id,
    'mask': mask,
  };
}

/// `IrradianceInfo`.
final class IrradianceInfoBlock extends UniformBlock {
  IrradianceInfoBlock() : super('IrradianceInfo');

  /// `origin`: Vector4, at byte 0.
  final Float32List origin = Float32List(4);

  /// `spacing`: Vector4, at byte 16.
  final Float32List spacing = Float32List(4);

  /// `counts`: Vector4, at byte 32.
  final Float32List counts = Float32List(4);

  /// `tiles`: Vector4, at byte 48.
  final Float32List tiles = Float32List(4);

  /// `atlas`: Vector4, at byte 64.
  final Float32List atlas = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'origin': origin,
    'spacing': spacing,
    'counts': counts,
    'tiles': tiles,
    'atlas': atlas,
  };
}

/// `LayerInfo`.
final class LayerInfoBlock extends UniformBlock {
  LayerInfoBlock() : super('LayerInfo');

  /// `specular`: Vector4, at byte 0.
  final Float32List specular = Float32List(4);

  /// `coat`: Vector4, at byte 16.
  final Float32List coat = Float32List(4);

  /// `sheen`: Vector4, at byte 32.
  final Float32List sheen = Float32List(4);

  /// `anisotropy`: Vector4, at byte 48.
  final Float32List anisotropy = Float32List(4);

  /// `transmission`: Vector4, at byte 64.
  final Float32List transmission = Float32List(4);

  /// `attenuation`: Vector4, at byte 80.
  final Float32List attenuation = Float32List(4);

  /// `iridescence`: Vector4, at byte 96.
  final Float32List iridescence = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'specular': specular,
    'coat': coat,
    'sheen': sheen,
    'anisotropy': anisotropy,
    'transmission': transmission,
    'attenuation': attenuation,
    'iridescence': iridescence,
  };
}

/// `LightListInfo`.
final class LightListInfoBlock extends UniformBlock {
  LightListInfoBlock() : super('LightListInfo');

  /// `list`: Vector4, at byte 0.
  final Float32List list = Float32List(4);

  /// `indices`: 6 × Vector4, at byte 16.
  final Float32List indices = Float32List(24);

  /// `scales`: 6 × Vector4, at byte 112.
  final Float32List scales = Float32List(24);

  /// `cluster_view_projection`: Matrix, at byte 208.
  final Float32List clusterViewProjection = Float32List(16);

  /// `cluster_grid`: Vector4, at byte 272.
  final Float32List clusterGrid = Float32List(4);

  /// `cluster_depth`: Vector4, at byte 288.
  final Float32List clusterDepth = Float32List(4);

  /// `slot_rows`: 2 × Vector4, at byte 304.
  final Float32List slotRows = Float32List(8);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'list': list,
    'indices': indices,
    'scales': scales,
    'cluster_view_projection': clusterViewProjection,
    'cluster_grid': clusterGrid,
    'cluster_depth': clusterDepth,
    'slot_rows': slotRows,
  };
}

/// `LineInfo`.
final class LineInfoBlock extends UniformBlock {
  LineInfoBlock() : super('LineInfo');

  /// `view_projection`: Matrix, at byte 0.
  final Float32List viewProjection = Float32List(16);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'view_projection': viewProjection,
  };
}

/// `LuminanceInfo`.
final class LuminanceInfoBlock extends UniformBlock {
  LuminanceInfoBlock() : super('LuminanceInfo');

  /// `params`: Vector4, at byte 0.
  final Float32List params = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'params': params,
  };
}

/// `MaskInfo`.
final class MaskInfoBlock extends UniformBlock {
  MaskInfoBlock() : super('MaskInfo');

  /// `mask`: Vector4, at byte 0.
  final Float32List mask = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'mask': mask,
  };
}

/// `MaterialParams`.
final class MaterialParamsBlock extends UniformBlock {
  MaterialParamsBlock() : super('MaterialParams');

  /// `viewport`: Vector4, at byte 0.
  final Float32List viewport = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'viewport': viewport,
  };
}

/// `MorphInfo`.
final class MorphInfoBlock extends UniformBlock {
  MorphInfoBlock() : super('MorphInfo');

  /// `morph_weights`: 2 × Vector4, at byte 0.
  final Float32List morphWeights = Float32List(8);

  /// `morph_params`: Vector4, at byte 32.
  final Float32List morphParams = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'morph_weights': morphWeights,
    'morph_params': morphParams,
  };
}

/// `MorphInstanceInfo`.
final class MorphInstanceInfoBlock extends UniformBlock {
  MorphInstanceInfoBlock() : super('MorphInstanceInfo');

  /// `instance_params`: Vector4, at byte 0.
  final Float32List instanceParams = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'instance_params': instanceParams,
  };
}

/// `NoiseInfo`.
final class NoiseInfoBlock extends UniformBlock {
  NoiseInfoBlock() : super('NoiseInfo');

  /// `noise`: Vector4, at byte 0.
  final Float32List noise = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'noise': noise,
  };
}

/// `ParticleInfo`.
final class ParticleInfoBlock extends UniformBlock {
  ParticleInfoBlock() : super('ParticleInfo');

  /// `view_projection`: Matrix, at byte 0.
  final Float32List viewProjection = Float32List(16);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'view_projection': viewProjection,
  };
}

/// `ParticleMeshInfo`.
final class ParticleMeshInfoBlock extends UniformBlock {
  ParticleMeshInfoBlock() : super('ParticleMeshInfo');

  /// `view_projection`: Matrix, at byte 0.
  final Float32List viewProjection = Float32List(16);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'view_projection': viewProjection,
  };
}

/// `PointShadow`.
final class PointShadowBlock extends UniformBlock {
  PointShadowBlock() : super('PointShadow');

  /// `faces`: 36 × Matrix, at byte 0.
  final Float32List faces = Float32List(576);

  /// `lights`: 6 × Vector4, at byte 2304.
  final Float32List lights = Float32List(24);

  /// `slots`: 8 × Vector4, at byte 2400.
  final Float32List slots = Float32List(32);

  /// `params`: Vector4, at byte 2528.
  final Float32List params = Float32List(4);

  /// `params2`: Vector4, at byte 2544.
  final Float32List params2 = Float32List(4);

  /// `params3`: Vector4, at byte 2560.
  final Float32List params3 = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'faces': faces,
    'lights': lights,
    'slots': slots,
    'params': params,
    'params2': params2,
    'params3': params3,
  };
}

/// `PrevFrameInfo`.
final class PrevFrameInfoBlock extends UniformBlock {
  PrevFrameInfoBlock() : super('PrevFrameInfo');

  /// `current_mvp`: Matrix, at byte 0.
  final Float32List currentMvp = Float32List(16);

  /// `previous_mvp`: Matrix, at byte 64.
  final Float32List previousMvp = Float32List(16);

  /// `previous_morph_weights`: 2 × Vector4, at byte 128.
  final Float32List previousMorphWeights = Float32List(8);

  /// `camera`: Vector4, at byte 160.
  final Float32List camera = Float32List(4);

  /// `forward`: Vector4, at byte 176.
  final Float32List forward = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'current_mvp': currentMvp,
    'previous_mvp': previousMvp,
    'previous_morph_weights': previousMorphWeights,
    'camera': camera,
    'forward': forward,
  };
}

/// `ProbeInfo`.
final class ProbeInfoBlock extends UniformBlock {
  ProbeInfoBlock() : super('ProbeInfo');

  /// `params`: Vector4, at byte 0.
  final Float32List params = Float32List(4);

  /// `at`: Vector4, at byte 0.
  final Float32List at = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'params': params,
    'at': at,
  };
}

/// `ReflectionInfo`.
final class ReflectionInfoBlock extends UniformBlock {
  ReflectionInfoBlock() : super('ReflectionInfo');

  /// `view_projection`: Matrix, at byte 0.
  final Float32List viewProjection = Float32List(16);

  /// `inverse_view_projection`: Matrix, at byte 64.
  final Float32List inverseViewProjection = Float32List(16);

  /// `camera`: Vector4, at byte 128.
  final Float32List camera = Float32List(4);

  /// `forward`: Vector4, at byte 144.
  final Float32List forward = Float32List(4);

  /// `params`: Vector4, at byte 160.
  final Float32List params = Float32List(4);

  /// `screen`: Vector4, at byte 176.
  final Float32List screen = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'view_projection': viewProjection,
    'inverse_view_projection': inverseViewProjection,
    'camera': camera,
    'forward': forward,
    'params': params,
    'screen': screen,
  };
}

/// `ShadeInfo`.
final class ShadeInfoBlock extends UniformBlock {
  ShadeInfoBlock() : super('ShadeInfo');

  /// `params`: Vector4, at byte 0.
  final Float32List params = Float32List(4);

  /// `screen`: Vector4, at byte 16.
  final Float32List screen = Float32List(4);

  /// `light`: Vector4, at byte 32.
  final Float32List light = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'params': params,
    'screen': screen,
    'light': light,
  };
}

/// `ShadowCopyInfo`.
final class ShadowCopyInfoBlock extends UniformBlock {
  ShadowCopyInfoBlock() : super('ShadowCopyInfo');

  /// `tile`: Vector4, at byte 0.
  final Float32List tile = Float32List(4);

  /// `shift`: Vector4, at byte 16.
  final Float32List shift = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'tile': tile,
    'shift': shift,
  };
}

/// `ShadowLight`.
final class ShadowLightBlock extends UniformBlock {
  ShadowLightBlock() : super('ShadowLight');

  /// `light`: Vector4, at byte 0.
  final Float32List light = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'light': light,
  };
}

/// `ShaftInfo`.
final class ShaftInfoBlock extends UniformBlock {
  ShaftInfoBlock() : super('ShaftInfo');

  /// `inverse_view_projection`: Matrix, at byte 0.
  final Float32List inverseViewProjection = Float32List(16);

  /// `shadow_matrix`: Matrix, at byte 64.
  final Float32List shadowMatrix = Float32List(16);

  /// `shadow_matrix_far`: Matrix, at byte 128.
  final Float32List shadowMatrixFar = Float32List(16);

  /// `shadow_matrix_farthest`: Matrix, at byte 192.
  final Float32List shadowMatrixFarthest = Float32List(16);

  /// `camera`: Vector4, at byte 256.
  final Float32List camera = Float32List(4);

  /// `forward`: Vector4, at byte 272.
  final Float32List forward = Float32List(4);

  /// `scatter`: Vector4, at byte 288.
  final Float32List scatter = Float32List(4);

  /// `cascades`: Vector4, at byte 304.
  final Float32List cascades = Float32List(4);

  /// `sun`: Vector4, at byte 320.
  final Float32List sun = Float32List(4);

  /// `bias`: Vector4, at byte 336.
  final Float32List bias = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'inverse_view_projection': inverseViewProjection,
    'shadow_matrix': shadowMatrix,
    'shadow_matrix_far': shadowMatrixFar,
    'shadow_matrix_farthest': shadowMatrixFarthest,
    'camera': camera,
    'forward': forward,
    'scatter': scatter,
    'cascades': cascades,
    'sun': sun,
    'bias': bias,
  };
}

/// `SkinInfo`.
final class SkinInfoBlock extends UniformBlock {
  SkinInfoBlock() : super('SkinInfo');

  /// `joint_matrices`: 64 × Matrix, at byte 0.
  final Float32List jointMatrices = Float32List(1024);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'joint_matrices': jointMatrices,
  };
}

/// `SsaoBlurInfo`.
final class SsaoBlurInfoBlock extends UniformBlock {
  SsaoBlurInfoBlock() : super('SsaoBlurInfo');

  /// `params`: Vector4, at byte 0.
  final Float32List params = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'params': params,
  };
}

/// `SsaoInfo`.
final class SsaoInfoBlock extends UniformBlock {
  SsaoInfoBlock() : super('SsaoInfo');

  /// `inverse_view_projection`: Matrix, at byte 0.
  final Float32List inverseViewProjection = Float32List(16);

  /// `view_projection`: Matrix, at byte 64.
  final Float32List viewProjection = Float32List(16);

  /// `params`: Vector4, at byte 128.
  final Float32List params = Float32List(4);

  /// `screen`: Vector4, at byte 144.
  final Float32List screen = Float32List(4);

  /// `camera`: Vector4, at byte 160.
  final Float32List camera = Float32List(4);

  /// `forward`: Vector4, at byte 176.
  final Float32List forward = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'inverse_view_projection': inverseViewProjection,
    'view_projection': viewProjection,
    'params': params,
    'screen': screen,
    'camera': camera,
    'forward': forward,
  };
}

/// `TemporalInfo`.
final class TemporalInfoBlock extends UniformBlock {
  TemporalInfoBlock() : super('TemporalInfo');

  /// `scene_texel`: Vector4, at byte 0.
  final Float32List sceneTexel = Float32List(4);

  /// `jitter`: Vector4, at byte 16.
  final Float32List jitter = Float32List(4);

  /// `params`: Vector4, at byte 32.
  final Float32List params = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'scene_texel': sceneTexel,
    'jitter': jitter,
    'params': params,
  };
}

/// `VelocityInfo`.
final class VelocityInfoBlock extends UniformBlock {
  VelocityInfoBlock() : super('VelocityInfo');

  /// `target`: Vector4, at byte 0.
  final Float32List target = Float32List(4);

  @override
  late final Map<String, Float32List> members = <String, Float32List>{
    'target': target,
  };
}
