// GENERATED by flutter3d_impeller/tool/stage_bindings.dart.
// Do not edit; run the tool after any shader edit.

/// How impellerc lays out the uniform blocks of every stage in
/// the engine's bundle: each member's byte offset, byte length,
/// element count and reflected type, in declaration order.
/// Per stage, because one block name can be wider in one stage
/// than another.
library;

/// One member of a uniform block.
typedef UniformMemberLayout = ({
  int offset,
  int byteLength,
  int elements,
  String type,
});

const Map<String, Map<String, Map<String, UniformMemberLayout>>>
uniformBlocks = <String, Map<String, Map<String, UniformMemberLayout>>>{
  'BlinnPhong': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'FragInfo': <String, UniformMemberLayout>{
      'light_position': (
        offset: 0,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_color': (
        offset: 128,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_direction': (
        offset: 256,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_cone': (
        offset: 384,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'base_color': (offset: 512, byteLength: 16, elements: 1, type: 'Vector4'),
      'emissive': (offset: 528, byteLength: 16, elements: 1, type: 'Vector4'),
      'camera_position': (
        offset: 544,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'material': (offset: 560, byteLength: 16, elements: 1, type: 'Vector4'),
      'material2': (offset: 576, byteLength: 16, elements: 1, type: 'Vector4'),
      'frame_params': (
        offset: 592,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_params': (
        offset: 608,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_matrix': (
        offset: 624,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_far': (
        offset: 688,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_farthest': (
        offset: 752,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_cascades': (
        offset: 816,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_sky': (
        offset: 832,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_ground': (
        offset: 848,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_bias': (
        offset: 864,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'target_origin': (
        offset: 880,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
    'IrradianceInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'spacing': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'counts': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
      'tiles': (offset: 48, byteLength: 16, elements: 1, type: 'Vector4'),
      'atlas': (offset: 64, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'LightListInfo': <String, UniformMemberLayout>{
      'list': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'indices': (offset: 16, byteLength: 96, elements: 6, type: 'Vector4'),
      'scales': (offset: 112, byteLength: 96, elements: 6, type: 'Vector4'),
      'cluster_view_projection': (
        offset: 208,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'cluster_grid': (
        offset: 272,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'cluster_depth': (
        offset: 288,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'slot_rows': (offset: 304, byteLength: 32, elements: 2, type: 'Vector4'),
    },
    'PointShadow': <String, UniformMemberLayout>{
      'faces': (offset: 0, byteLength: 2304, elements: 36, type: 'Matrix'),
      'lights': (offset: 2304, byteLength: 96, elements: 6, type: 'Vector4'),
      'slots': (offset: 2400, byteLength: 128, elements: 8, type: 'Vector4'),
      'params': (offset: 2528, byteLength: 16, elements: 1, type: 'Vector4'),
      'params2': (offset: 2544, byteLength: 16, elements: 1, type: 'Vector4'),
      'params3': (offset: 2560, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'BloomDownsample': <String, Map<String, UniformMemberLayout>>{
    'BloomInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'BloomThreshold': <String, Map<String, UniformMemberLayout>>{
    'BloomInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'BloomUpsample': <String, Map<String, UniformMemberLayout>>{
    'BloomInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'tint': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'CameraVelocity': <String, Map<String, UniformMemberLayout>>{
    'CameraVelocityInfo': <String, UniformMemberLayout>{
      'inverse_view_projection': (
        offset: 0,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'previous_view_projection': (
        offset: 64,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'camera': (offset: 128, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 144, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Composite': <String, Map<String, UniformMemberLayout>>{
    'CompositeInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'ao_texel': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'look': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
      'look_more': (offset: 48, byteLength: 16, elements: 1, type: 'Vector4'),
      'output_encode': (
        offset: 64,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'lift': (offset: 80, byteLength: 16, elements: 1, type: 'Vector4'),
      'gamma': (offset: 96, byteLength: 16, elements: 1, type: 'Vector4'),
      'gain': (offset: 112, byteLength: 16, elements: 1, type: 'Vector4'),
      'contact': (offset: 128, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'FragCoordInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ContactShadow': <String, Map<String, UniformMemberLayout>>{
    'ContactShadowInfo': <String, UniformMemberLayout>{
      'inverse_view_projection': (
        offset: 0,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'view_projection': (
        offset: 64,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'params': (offset: 128, byteLength: 16, elements: 1, type: 'Vector4'),
      'camera': (offset: 144, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 160, byteLength: 16, elements: 1, type: 'Vector4'),
      'to_light': (offset: 176, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'FragCoordInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'NoiseInfo': <String, UniformMemberLayout>{
      'noise': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'DebugLineVertex': <String, Map<String, UniformMemberLayout>>{
    'LineInfo': <String, UniformMemberLayout>{
      'view_projection': (
        offset: 0,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
  },
  'DepthOfField': <String, Map<String, UniformMemberLayout>>{
    'DofInfo': <String, UniformMemberLayout>{
      'lens': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'params': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'FragCoordInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Easu': <String, Map<String, UniformMemberLayout>>{
    'EasuInfo': <String, UniformMemberLayout>{
      'source': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'params': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'FragCoordInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'EvsmFilter': <String, Map<String, UniformMemberLayout>>{
    'EvsmFilterInfo': <String, UniformMemberLayout>{
      'axis': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'tile': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'FieldDecay': <String, Map<String, UniformMemberLayout>>{
    'FieldDecayInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Fxaa': <String, Map<String, UniformMemberLayout>>{
    'FxaaInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'sharpen': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'IrradianceConvolve': <String, Map<String, UniformMemberLayout>>{
    'ConvolveInfo': <String, UniformMemberLayout>{
      'probe': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'tiles': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'atlas': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Lambert': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'FragInfo': <String, UniformMemberLayout>{
      'light_position': (
        offset: 0,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_color': (
        offset: 128,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_direction': (
        offset: 256,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_cone': (
        offset: 384,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'base_color': (offset: 512, byteLength: 16, elements: 1, type: 'Vector4'),
      'emissive': (offset: 528, byteLength: 16, elements: 1, type: 'Vector4'),
      'camera_position': (
        offset: 544,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'material': (offset: 560, byteLength: 16, elements: 1, type: 'Vector4'),
      'material2': (offset: 576, byteLength: 16, elements: 1, type: 'Vector4'),
      'frame_params': (
        offset: 592,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_params': (
        offset: 608,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_matrix': (
        offset: 624,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_far': (
        offset: 688,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_farthest': (
        offset: 752,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_cascades': (
        offset: 816,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_sky': (
        offset: 832,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_ground': (
        offset: 848,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_bias': (
        offset: 864,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'target_origin': (
        offset: 880,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
    'IrradianceInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'spacing': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'counts': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
      'tiles': (offset: 48, byteLength: 16, elements: 1, type: 'Vector4'),
      'atlas': (offset: 64, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'LightListInfo': <String, UniformMemberLayout>{
      'list': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'indices': (offset: 16, byteLength: 96, elements: 6, type: 'Vector4'),
      'scales': (offset: 112, byteLength: 96, elements: 6, type: 'Vector4'),
      'cluster_view_projection': (
        offset: 208,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'cluster_grid': (
        offset: 272,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'cluster_depth': (
        offset: 288,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'slot_rows': (offset: 304, byteLength: 32, elements: 2, type: 'Vector4'),
    },
    'PointShadow': <String, UniformMemberLayout>{
      'faces': (offset: 0, byteLength: 2304, elements: 36, type: 'Matrix'),
      'lights': (offset: 2304, byteLength: 96, elements: 6, type: 'Vector4'),
      'slots': (offset: 2400, byteLength: 128, elements: 8, type: 'Vector4'),
      'params': (offset: 2528, byteLength: 16, elements: 1, type: 'Vector4'),
      'params2': (offset: 2544, byteLength: 16, elements: 1, type: 'Vector4'),
      'params3': (offset: 2560, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'LightShafts': <String, Map<String, UniformMemberLayout>>{
    'FragCoordInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'NoiseInfo': <String, UniformMemberLayout>{
      'noise': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'ShaftInfo': <String, UniformMemberLayout>{
      'inverse_view_projection': (
        offset: 0,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix': (
        offset: 64,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_far': (
        offset: 128,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_farthest': (
        offset: 192,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'camera': (offset: 256, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 272, byteLength: 16, elements: 1, type: 'Vector4'),
      'scatter': (offset: 288, byteLength: 16, elements: 1, type: 'Vector4'),
      'cascades': (offset: 304, byteLength: 16, elements: 1, type: 'Vector4'),
      'sun': (offset: 320, byteLength: 16, elements: 1, type: 'Vector4'),
      'bias': (offset: 336, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'LocalExposure': <String, Map<String, UniformMemberLayout>>{
    'LocalExposureInfo': <String, UniformMemberLayout>{
      'stops': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'LocalExposureBlur': <String, Map<String, UniformMemberLayout>>{
    'LocalExposureBlurInfo': <String, UniformMemberLayout>{
      'step': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'stops': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Luminance': <String, Map<String, UniformMemberLayout>>{
    'LuminanceInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'MeshInstancedVertex': <String, Map<String, UniformMemberLayout>>{
    'FrameInfo': <String, UniformMemberLayout>{
      'mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'model': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'normal_matrix': (
        offset: 128,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
    'MorphInfo': <String, UniformMemberLayout>{
      'morph_weights': (
        offset: 0,
        byteLength: 32,
        elements: 2,
        type: 'Vector4',
      ),
      'morph_params': (
        offset: 32,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
    'MorphInstanceInfo': <String, UniformMemberLayout>{
      'instance_params': (
        offset: 0,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
  },
  'MeshLightmappedVertex': <String, Map<String, UniformMemberLayout>>{
    'FrameInfo': <String, UniformMemberLayout>{
      'mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'model': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'normal_matrix': (
        offset: 128,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
    'MorphInfo': <String, UniformMemberLayout>{
      'morph_weights': (
        offset: 0,
        byteLength: 32,
        elements: 2,
        type: 'Vector4',
      ),
      'morph_params': (
        offset: 32,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
  },
  'MeshSkinnedVertex': <String, Map<String, UniformMemberLayout>>{
    'FrameInfo': <String, UniformMemberLayout>{
      'mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'model': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'normal_matrix': (
        offset: 128,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
    'MorphInfo': <String, UniformMemberLayout>{
      'morph_weights': (
        offset: 0,
        byteLength: 32,
        elements: 2,
        type: 'Vector4',
      ),
      'morph_params': (
        offset: 32,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
    'SkinInfo': <String, UniformMemberLayout>{
      'joint_matrices': (
        offset: 0,
        byteLength: 4096,
        elements: 64,
        type: 'Matrix',
      ),
    },
  },
  'MeshVertex': <String, Map<String, UniformMemberLayout>>{
    'FrameInfo': <String, UniformMemberLayout>{
      'mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'model': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'normal_matrix': (
        offset: 128,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
    'MorphInfo': <String, UniformMemberLayout>{
      'morph_weights': (
        offset: 0,
        byteLength: 32,
        elements: 2,
        type: 'Vector4',
      ),
      'morph_params': (
        offset: 32,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
  },
  'MotionBlur': <String, Map<String, UniformMemberLayout>>{
    'FragCoordInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'MotionBlurInfo': <String, UniformMemberLayout>{
      'scene': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'params': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'tiles': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'NoiseInfo': <String, UniformMemberLayout>{
      'noise': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Normals': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ObjectId': <String, Map<String, UniformMemberLayout>>{
    'IdInfo': <String, UniformMemberLayout>{
      'id': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'mask': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Particle': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ParticleMesh': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ParticleMeshVertex': <String, Map<String, UniformMemberLayout>>{
    'ParticleMeshInfo': <String, UniformMemberLayout>{
      'view_projection': (
        offset: 0,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
  },
  'ParticleTextured': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ParticleVertex': <String, Map<String, UniformMemberLayout>>{
    'ParticleInfo': <String, UniformMemberLayout>{
      'view_projection': (
        offset: 0,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
  },
  'Pbr': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'FragInfo': <String, UniformMemberLayout>{
      'light_position': (
        offset: 0,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_color': (
        offset: 128,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_direction': (
        offset: 256,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_cone': (
        offset: 384,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'base_color': (offset: 512, byteLength: 16, elements: 1, type: 'Vector4'),
      'emissive': (offset: 528, byteLength: 16, elements: 1, type: 'Vector4'),
      'camera_position': (
        offset: 544,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'material': (offset: 560, byteLength: 16, elements: 1, type: 'Vector4'),
      'material2': (offset: 576, byteLength: 16, elements: 1, type: 'Vector4'),
      'frame_params': (
        offset: 592,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_params': (
        offset: 608,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_matrix': (
        offset: 624,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_far': (
        offset: 688,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_farthest': (
        offset: 752,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_cascades': (
        offset: 816,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_sky': (
        offset: 832,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_ground': (
        offset: 848,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_bias': (
        offset: 864,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'target_origin': (
        offset: 880,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
    'IrradianceInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'spacing': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'counts': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
      'tiles': (offset: 48, byteLength: 16, elements: 1, type: 'Vector4'),
      'atlas': (offset: 64, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'LightListInfo': <String, UniformMemberLayout>{
      'list': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'indices': (offset: 16, byteLength: 96, elements: 6, type: 'Vector4'),
      'scales': (offset: 112, byteLength: 96, elements: 6, type: 'Vector4'),
      'cluster_view_projection': (
        offset: 208,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'cluster_grid': (
        offset: 272,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'cluster_depth': (
        offset: 288,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'slot_rows': (offset: 304, byteLength: 32, elements: 2, type: 'Vector4'),
    },
    'PointShadow': <String, UniformMemberLayout>{
      'faces': (offset: 0, byteLength: 2304, elements: 36, type: 'Matrix'),
      'lights': (offset: 2304, byteLength: 96, elements: 6, type: 'Vector4'),
      'slots': (offset: 2400, byteLength: 128, elements: 8, type: 'Vector4'),
      'params': (offset: 2528, byteLength: 16, elements: 1, type: 'Vector4'),
      'params2': (offset: 2544, byteLength: 16, elements: 1, type: 'Vector4'),
      'params3': (offset: 2560, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'PolylineVertex': <String, Map<String, UniformMemberLayout>>{
    'FrameInfo': <String, UniformMemberLayout>{
      'mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'model': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'normal_matrix': (
        offset: 128,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
    'MaterialParams': <String, UniformMemberLayout>{
      'viewport': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ProbePrefilter': <String, Map<String, UniformMemberLayout>>{
    'ProbeInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Reflections': <String, Map<String, UniformMemberLayout>>{
    'FragCoordInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'NoiseInfo': <String, UniformMemberLayout>{
      'noise': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'ReflectionInfo': <String, UniformMemberLayout>{
      'view_projection': (
        offset: 0,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'inverse_view_projection': (
        offset: 64,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'camera': (offset: 128, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 144, byteLength: 16, elements: 1, type: 'Vector4'),
      'params': (offset: 160, byteLength: 16, elements: 1, type: 'Vector4'),
      'screen': (offset: 176, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ShadowCopy': <String, Map<String, UniformMemberLayout>>{
    'ShadowCopyInfo': <String, UniformMemberLayout>{
      'tile': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'shift': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ShadowDepthMasked': <String, Map<String, UniformMemberLayout>>{
    'MaskInfo': <String, UniformMemberLayout>{
      'mask': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ShadowDistance': <String, Map<String, UniformMemberLayout>>{
    'ShadowLight': <String, UniformMemberLayout>{
      'light': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ShadowDistanceMasked': <String, Map<String, UniformMemberLayout>>{
    'MaskInfo': <String, UniformMemberLayout>{
      'mask': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'ShadowLight': <String, UniformMemberLayout>{
      'light': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Splat': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Ssao': <String, Map<String, UniformMemberLayout>>{
    'NoiseInfo': <String, UniformMemberLayout>{
      'noise': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'SsaoInfo': <String, UniformMemberLayout>{
      'inverse_view_projection': (
        offset: 0,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'view_projection': (
        offset: 64,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'params': (offset: 128, byteLength: 16, elements: 1, type: 'Vector4'),
      'screen': (offset: 144, byteLength: 16, elements: 1, type: 'Vector4'),
      'camera': (offset: 160, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 176, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'SsaoBlur': <String, Map<String, UniformMemberLayout>>{
    'SsaoBlurInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'TemporalAccumulate': <String, Map<String, UniformMemberLayout>>{
    'AccumulateInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'TemporalResolve': <String, Map<String, UniformMemberLayout>>{
    'TemporalInfo': <String, UniformMemberLayout>{
      'scene_texel': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'jitter': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'params': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Toon': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'FragInfo': <String, UniformMemberLayout>{
      'light_position': (
        offset: 0,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_color': (
        offset: 128,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_direction': (
        offset: 256,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_cone': (
        offset: 384,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'base_color': (offset: 512, byteLength: 16, elements: 1, type: 'Vector4'),
      'emissive': (offset: 528, byteLength: 16, elements: 1, type: 'Vector4'),
      'camera_position': (
        offset: 544,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'material': (offset: 560, byteLength: 16, elements: 1, type: 'Vector4'),
      'material2': (offset: 576, byteLength: 16, elements: 1, type: 'Vector4'),
      'frame_params': (
        offset: 592,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_params': (
        offset: 608,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_matrix': (
        offset: 624,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_far': (
        offset: 688,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_farthest': (
        offset: 752,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_cascades': (
        offset: 816,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_sky': (
        offset: 832,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_ground': (
        offset: 848,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_bias': (
        offset: 864,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'target_origin': (
        offset: 880,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
    'IrradianceInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'spacing': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'counts': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
      'tiles': (offset: 48, byteLength: 16, elements: 1, type: 'Vector4'),
      'atlas': (offset: 64, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'LightListInfo': <String, UniformMemberLayout>{
      'list': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'indices': (offset: 16, byteLength: 96, elements: 6, type: 'Vector4'),
      'scales': (offset: 112, byteLength: 96, elements: 6, type: 'Vector4'),
      'cluster_view_projection': (
        offset: 208,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'cluster_grid': (
        offset: 272,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'cluster_depth': (
        offset: 288,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'slot_rows': (offset: 304, byteLength: 32, elements: 2, type: 'Vector4'),
    },
    'PointShadow': <String, UniformMemberLayout>{
      'faces': (offset: 0, byteLength: 2304, elements: 36, type: 'Matrix'),
      'lights': (offset: 2304, byteLength: 96, elements: 6, type: 'Vector4'),
      'slots': (offset: 2400, byteLength: 128, elements: 8, type: 'Vector4'),
      'params': (offset: 2528, byteLength: 16, elements: 1, type: 'Vector4'),
      'params2': (offset: 2544, byteLength: 16, elements: 1, type: 'Vector4'),
      'params3': (offset: 2560, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Unlit': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'FragInfo': <String, UniformMemberLayout>{
      'light_position': (
        offset: 0,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_color': (
        offset: 128,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_direction': (
        offset: 256,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_cone': (
        offset: 384,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'base_color': (offset: 512, byteLength: 16, elements: 1, type: 'Vector4'),
      'emissive': (offset: 528, byteLength: 16, elements: 1, type: 'Vector4'),
      'camera_position': (
        offset: 544,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'material': (offset: 560, byteLength: 16, elements: 1, type: 'Vector4'),
      'material2': (offset: 576, byteLength: 16, elements: 1, type: 'Vector4'),
      'frame_params': (
        offset: 592,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_params': (
        offset: 608,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_matrix': (
        offset: 624,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_far': (
        offset: 688,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_farthest': (
        offset: 752,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_cascades': (
        offset: 816,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_sky': (
        offset: 832,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_ground': (
        offset: 848,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_bias': (
        offset: 864,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'target_origin': (
        offset: 880,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
  },
  'Velocity': <String, Map<String, UniformMemberLayout>>{
    'VelocityInfo': <String, UniformMemberLayout>{
      'target': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'VelocityInstancedVertex': <String, Map<String, UniformMemberLayout>>{
    'FrameInfo': <String, UniformMemberLayout>{
      'mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'model': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'normal_matrix': (
        offset: 128,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
    'MorphInfo': <String, UniformMemberLayout>{
      'morph_weights': (
        offset: 0,
        byteLength: 32,
        elements: 2,
        type: 'Vector4',
      ),
      'morph_params': (
        offset: 32,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
    'PrevFrameInfo': <String, UniformMemberLayout>{
      'current_mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'previous_mvp': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'previous_morph_weights': (
        offset: 128,
        byteLength: 32,
        elements: 2,
        type: 'Vector4',
      ),
      'camera': (offset: 160, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 176, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'VelocityNeighborMax': <String, Map<String, UniformMemberLayout>>{
    'NeighborMaxInfo': <String, UniformMemberLayout>{
      'texel': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'VelocitySkinnedVertex': <String, Map<String, UniformMemberLayout>>{
    'FrameInfo': <String, UniformMemberLayout>{
      'mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'model': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'normal_matrix': (
        offset: 128,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
    'MorphInfo': <String, UniformMemberLayout>{
      'morph_weights': (
        offset: 0,
        byteLength: 32,
        elements: 2,
        type: 'Vector4',
      ),
      'morph_params': (
        offset: 32,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
    'PrevFrameInfo': <String, UniformMemberLayout>{
      'current_mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'previous_mvp': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'previous_morph_weights': (
        offset: 128,
        byteLength: 32,
        elements: 2,
        type: 'Vector4',
      ),
      'camera': (offset: 160, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 176, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'SkinInfo': <String, UniformMemberLayout>{
      'joint_matrices': (
        offset: 0,
        byteLength: 4096,
        elements: 64,
        type: 'Matrix',
      ),
    },
  },
  'VelocityTileMax': <String, Map<String, UniformMemberLayout>>{
    'TileMaxInfo': <String, UniformMemberLayout>{
      'source': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'params': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'target': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'VelocityVertex': <String, Map<String, UniformMemberLayout>>{
    'FrameInfo': <String, UniformMemberLayout>{
      'mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'model': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'normal_matrix': (
        offset: 128,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
    },
    'MorphInfo': <String, UniformMemberLayout>{
      'morph_weights': (
        offset: 0,
        byteLength: 32,
        elements: 2,
        type: 'Vector4',
      ),
      'morph_params': (
        offset: 32,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
    'PrevFrameInfo': <String, UniformMemberLayout>{
      'current_mvp': (offset: 0, byteLength: 64, elements: 1, type: 'Matrix'),
      'previous_mvp': (offset: 64, byteLength: 64, elements: 1, type: 'Matrix'),
      'previous_morph_weights': (
        offset: 128,
        byteLength: 32,
        elements: 2,
        type: 'Vector4',
      ),
      'camera': (offset: 160, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 176, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'VertexTextureProbeVertex': <String, Map<String, UniformMemberLayout>>{
    'ProbeInfo': <String, UniformMemberLayout>{
      'at': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'ViewportShade': <String, Map<String, UniformMemberLayout>>{
    'ShadeInfo': <String, UniformMemberLayout>{
      'params': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'screen': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'light': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'VolumetricFog': <String, Map<String, UniformMemberLayout>>{
    'FragCoordInfo': <String, UniformMemberLayout>{
      'origin': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'NoiseInfo': <String, UniformMemberLayout>{
      'noise': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'VolumeFogInfo': <String, UniformMemberLayout>{
      'inverse_view_projection': (
        offset: 0,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix': (
        offset: 64,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_far': (
        offset: 128,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_farthest': (
        offset: 192,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'cluster_view_projection': (
        offset: 256,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'camera': (offset: 320, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 336, byteLength: 16, elements: 1, type: 'Vector4'),
      'sun': (offset: 352, byteLength: 16, elements: 1, type: 'Vector4'),
      'sun_radiance': (
        offset: 368,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'cascades': (offset: 384, byteLength: 16, elements: 1, type: 'Vector4'),
      'bias': (offset: 400, byteLength: 16, elements: 1, type: 'Vector4'),
      'medium': (offset: 416, byteLength: 16, elements: 1, type: 'Vector4'),
      'albedo': (offset: 432, byteLength: 16, elements: 1, type: 'Vector4'),
      'ambient': (offset: 448, byteLength: 16, elements: 1, type: 'Vector4'),
      'cluster_grid': (
        offset: 464,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'cluster_depth': (
        offset: 480,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'list': (offset: 496, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'VolumetricFogUpsample': <String, Map<String, UniformMemberLayout>>{
    'FogUpsampleInfo': <String, UniformMemberLayout>{
      'size': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
    },
  },
  'Xray': <String, Map<String, UniformMemberLayout>>{
    'FogInfo': <String, UniformMemberLayout>{
      'fog': (offset: 0, byteLength: 16, elements: 1, type: 'Vector4'),
      'eye': (offset: 16, byteLength: 16, elements: 1, type: 'Vector4'),
      'forward': (offset: 32, byteLength: 16, elements: 1, type: 'Vector4'),
    },
    'FragInfo': <String, UniformMemberLayout>{
      'light_position': (
        offset: 0,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_color': (
        offset: 128,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_direction': (
        offset: 256,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'light_cone': (
        offset: 384,
        byteLength: 128,
        elements: 8,
        type: 'Vector4',
      ),
      'base_color': (offset: 512, byteLength: 16, elements: 1, type: 'Vector4'),
      'emissive': (offset: 528, byteLength: 16, elements: 1, type: 'Vector4'),
      'camera_position': (
        offset: 544,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'material': (offset: 560, byteLength: 16, elements: 1, type: 'Vector4'),
      'material2': (offset: 576, byteLength: 16, elements: 1, type: 'Vector4'),
      'frame_params': (
        offset: 592,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_params': (
        offset: 608,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_matrix': (
        offset: 624,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_far': (
        offset: 688,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_matrix_farthest': (
        offset: 752,
        byteLength: 64,
        elements: 1,
        type: 'Matrix',
      ),
      'shadow_cascades': (
        offset: 816,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_sky': (
        offset: 832,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'ambient_ground': (
        offset: 848,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'shadow_bias': (
        offset: 864,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
      'target_origin': (
        offset: 880,
        byteLength: 16,
        elements: 1,
        type: 'Vector4',
      ),
    },
  },
};
