/// Typed accessors for materials written in the material language — item 22
/// of `tasks/1.0-scope-additions.md`.
///
/// **A class per material, generated from its source.** A `uniform` reaches
/// the shader as a member of `MaterialParams`, which the engine fills from
/// `RenderMaterial.parameters` — a map from a member's name to its floats. A game
/// writing `parameters['tiem']![0] = t` compiles and moves nothing; one
/// writing `SeabedParameters(material.parameters).time = t` does not compile
/// when the name is wrong, and says what type the member is. The map stays:
/// it is what the renderer binds, and what a data plugin, which has no Dart
/// to generate, writes.
///
/// Each class is an extension type over that very map, so it costs nothing
/// and writes through: one `SeabedParameters` over a material's parameters and
/// the material is moved.
library;

import 'package:flutter3d_core/formats.dart';

/// The Dart of one library holding a typed accessor for every source in
/// [programs] that has a `uniform`, in the order given.
///
/// [from] names, per program, the file it was read from, for the doc
/// comment; [header] is the generated-file line the library opens with.
String generateMaterialAccessors(
  List<MaterialProgram> programs, {
  Map<String, String> from = const <String, String>{},
  String header =
      '// GENERATED by flutter3d_build from the material sources. Do not '
      'edit;\n// change the .f3dmat and build again.',
}) {
  final out = StringBuffer()
    ..writeln(header)
    ..writeln()
    ..writeln(
      '/// Typed accessors for the uniforms of the materials written in',
    )
    ..writeln('/// the material language — one per material, over the')
    ..writeln('/// `RenderMaterial.parameters` map the renderer binds.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln("import 'package:vector_math/vector_math.dart';");
  for (final program in programs) {
    final uniforms = <MaterialParameter>[
      for (final parameter in program.parameters)
        if (parameter.uniform) parameter,
    ];
    if (uniforms.isEmpty) continue;
    final type = materialAccessorName(program.name);
    final source = from[program.name];
    out
      ..writeln()
      ..writeln(
        '/// The uniforms of the ${program.kind} `${program.name}`'
        '${source == null ? '' : ', from `$source`'}, typed.',
      )
      ..writeln('///')
      ..writeln(
        '/// Over [parameters], which it reads and writes in place: the',
      )
      ..writeln(
        '/// map a `RenderMaterial` is drawn with, or a `FullscreenEffect`\'s',
      )
      ..writeln(
        '/// `MaterialParams`. A member the map lacks is added at nought.',
      )
      ..writeln('extension type $type(Map<String, Float32List> parameters) {')
      ..writeln('  /// The material\'s name in its bundle.')
      ..writeln("  static const String materialName = '${program.name}';")
      ..writeln()
      ..writeln('  /// Every uniform at its declared default, a fresh map each')
      ..writeln('  /// call — what `BundledMaterials.parameters` starts from.')
      ..writeln('  static Map<String, Float32List> defaults() =>')
      ..writeln('      <String, Float32List>{');
    for (final uniform in uniforms) {
      out.writeln(
        "        '${uniform.name}': Float32List.fromList(<double>"
        '[${uniform.defaultValue.map(_literal).join(', ')}]),',
      );
    }
    out
      ..writeln('      };')
      ..writeln();
    for (final uniform in uniforms) {
      final name = _member(uniform.name);
      final width = uniform.type.components;
      final defaults = uniform.defaultValue.map(_literal).join(', ');
      out.writeln(
        '  /// `uniform ${uniform.type} $name`, $defaults by default.',
      );
      switch (width) {
        case 1:
          out
            ..writeln("  double get $name => _at('${uniform.name}', 1)[0];")
            ..writeln()
            ..writeln(
              "  set $name(double value) => _at('${uniform.name}', 1)[0] = "
              'value;',
            );
        default:
          final vector = 'Vector$width';
          out
            ..writeln(
              "  $vector get $name => "
              "$vector.array(_at('${uniform.name}', $width));",
            )
            ..writeln()
            ..writeln(
              "  set $name($vector value) => _at('${uniform.name}', $width)"
              '.setAll(0, value.storage);',
            );
      }
      out.writeln();
    }
    out
      ..writeln('  Float32List _at(String name, int length) =>')
      ..writeln('      parameters[name] ??= Float32List(length);')
      ..writeln('}');
  }
  return out.toString();
}

/// The accessor type for material [name]: its name with `Parameters` after it.
String materialAccessorName(String name) => '${name}Parameters';

/// A uniform's member name, or it with `Value` after it where Dart or the
/// accessor already has the name.
String _member(String name) => _taken.contains(name) ? '${name}Value' : name;

const Set<String> _taken = <String>{
  // The accessor's own.
  'parameters', 'defaults', 'materialName', '_at',
  // Object's.
  'hashCode', 'runtimeType', 'toString', 'noSuchMethod',
  // Dart's words the language does not already refuse.
  'abstract', 'as', 'assert', 'async', 'await', 'base', 'class', 'covariant',
  'deferred', 'dynamic', 'enum', 'export', 'extends', 'extension',
  'external', 'factory', 'final', 'finally', 'Function', 'get', 'hide',
  'implements', 'import', 'interface', 'is', 'late', 'library', 'mixin',
  'new', 'null', 'of', 'on', 'operator', 'part', 'required', 'rethrow',
  'sealed', 'set', 'show', 'static', 'super', 'sync', 'this', 'throw', 'try',
  'type', 'typedef', 'var', 'when', 'with', 'yield',
};

String _literal(double value) {
  final text = value.toString();
  return text.contains('.') || text.contains('e') ? text : '$text.0';
}
