/// What this game ships that somebody else made.
///
/// The ledger, the class and the screen are `flutter3d_game_ui/screens.dart`' — see
/// `CreditLedger` there. What is here is the list, which is this game's alone.
library;

import 'package:flutter3d_game_ui/screens.dart';

/// Everything the game ships that somebody else made.
///
/// The textures and every sound are generated by `tool/make_textures.py` and
/// `tool/make_sounds.py`, so they are the repository's own and are not here.
/// That was the point of generating them.
const CreditLedger credits = CreditLedger(<Credit>[
  Credit(
    file: 'models/penguin.glb',
    work: 'Weathered penguin-bot',
    author: 'epilogueronin',
    source:
        'https://sketchfab.com/3d-models/weathered-penguin-bot-33afc2b450dd4c188b307c82f3b2cbc3',
    license: 'CC BY 4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    modified: true,
  ),
  Credit(
    file: 'models/coin.glb',
    work: 'Stylized Coin',
    author: 'BarracudaByte',
    source:
        'https://sketchfab.com/3d-models/stylized-coin-8cd6f95c44994ed5944a42892d0ffc10',
    license: 'CC BY 4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
    modified: true,
  ),
  Credit(
    file: 'models/key.glb',
    work: 'A key',
    // **The one asset here that nobody had to be asked for.** The key that
    // used to sit in this slot came from an archive with no licence file, no
    // author and no trail back to one, and it was the only thing standing
    // between this game and a release. It is generated now — the provenance
    // is a script in this repository, and `tool/make_key.py` says why at
    // length.
    author: 'this repository',
    source: 'apps/flutter3d_demo_platformer/tool/make_key.py',
    license: 'CC0 1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
  ),
]);
