/// What this game ships that somebody else made.
///
/// The class and the screen are `flutter3d_ui`'s — see `Credit` there, and the
/// reason it moved. What is here is the list, which is this game's alone.
library;

import 'package:flutter3d_app/flutter3d_app.dart'; // Credit, from flutter3d_ui

/// Everything the game ships that somebody else made.
///
/// The textures and every sound are generated by `tool/make_textures.py` and
/// `tool/make_sounds.py`, so they are the repository's own and are not here.
/// That was the point of generating them.
abstract final class Credits {
  static const List<Credit> models = <Credit>[
    Credit(
      file: 'models/penguin.glb',
      work: 'Weathered penguin-bot',
      author: 'epilogueronin',
      source:
          'https://sketchfab.com/3d-models/weathered-penguin-bot-33afc2b450dd4c188b307c82f3b2cbc3',
      licence: 'CC BY 4.0',
      licenceUrl: 'http://creativecommons.org/licenses/by/4.0/',
      modified: true,
    ),
    Credit(
      file: 'models/coin.glb',
      work: 'Stylized Coin',
      author: 'BarracudaByte',
      source:
          'https://sketchfab.com/3d-models/stylized-coin-8cd6f95c44994ed5944a42892d0ffc10',
      licence: 'CC BY 4.0',
      licenceUrl: 'http://creativecommons.org/licenses/by/4.0/',
      modified: true,
    ),
    Credit(
      file: 'models/key.glb',
      work: 'A key',
      // **The one asset here that nobody had to be asked for.** The key that
      // used to sit in this slot came from an archive with no licence file, no
      // author and no trail back to one, and it was the only thing standing
      // between this game and a release. It is generated now — the provenance
      // is a script in this repository, and `tool/make_key.py` says why at
      // length.
      author: 'this repository',
      source: 'apps/flutter3d_demo_platformer/tool/make_key.py',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    ),
  ];

  /// The ones whose licence makes naming the author a condition.
  static List<Credit> get owed =>
      models.where((Credit c) => c.owesAttribution).toList();

  /// The ones that cannot be credited because nobody knows who made them.
  ///
  /// **Empty now, and it took generating a key to get there.** While this list
  /// has anything in it the game cannot be released, whatever the credits screen
  /// says — so the way it emptied was not finding the author of the old key,
  /// which nobody could, but replacing it with one this repository made.
  ///
  /// It stays, because the next asset dropped into `assets/models` is one
  /// somebody found somewhere, and `credits_test.dart` reads the directory.
  static List<Credit> get untraced =>
      models.where((Credit c) => !c.traced).toList();
}
