/// Measures a `QualityTable` on whatever device it is handed — `N2`.
///
/// **Offline, once per device class.** Every setting of
/// `QualitySetting.grid` is rendered over the same scenes as full quality;
/// its cost is its frame time over full quality's, its FLIP the mean
/// perceptual difference of its pictures against full quality's. The frame
/// time is the sum of the passes' GPU times where the device measures them
/// (H2) and the renderer's own wall-clock time where it does not.
///
/// Pure Dart on purpose, like [flip]: it runs on the software device from a
/// `dart run` tool, and on a phone's GPU from inside an application, from
/// the same code.
library;

import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter3d_core/flutter3d_core.dart';

import 'flip.dart';

/// One scene to measure: built on the device it will be drawn on, with the
/// settings it considers full quality.
typedef QualityScene =
    ({Scene scene, RenderView view, RenderSettings settings}) Function(
      GraphicsDevice device,
    );

/// A row of [QualitySetting.grid], measured.
typedef QualityMeasurement = ({
  QualitySetting setting,
  double cost,
  double flip,
});

/// Renders [scenes] at every setting of [QualitySetting.grid] on [device], at
/// [width] × [height], and returns a measurement per setting in grid order.
///
/// Each (scene, setting) gets its own renderer and [settle] frames, so a
/// temporal history or an amortised probe has settled. Then the settings
/// take turns, one frame each, [samples] rounds, and a setting's time is the
/// fastest of its frames: whatever else the machine was doing slowed some
/// frames of every setting alike rather than all frames of one, and the
/// fastest frame is the one nearest what the setting itself costs. The
/// picture is the last frame's; one drawn smaller (a render scale with
/// nothing upscaling it) is stretched back to full size as the presenter
/// would.
Future<List<QualityMeasurement>> measureQualityTable({
  required GraphicsDevice device,
  required int width,
  required int height,
  required List<QualityScene> scenes,
  int settle = 4,
  int samples = 7,
}) async {
  // Per scene: the full-quality time and picture everything is judged by.
  final fullTimes = <double>[];
  final fullPictures = <Uint8List>[];
  final measured = <List<({double micros, Uint8List picture})>>[];
  for (final build in scenes) {
    final perSetting = await _measureScene(
      device: device,
      width: width,
      height: height,
      build: build,
      settle: settle,
      samples: samples,
    );
    fullTimes.add(perSetting.first.micros);
    fullPictures.add(perSetting.first.picture);
    measured.add(perSetting);
  }

  return <QualityMeasurement>[
    for (final (i, setting) in QualitySetting.grid.indexed)
      (
        setting: setting,
        cost: i == 0
            ? 1.0
            : <double>[
                    for (final (s, rows) in measured.indexed)
                      rows[i].micros / fullTimes[s],
                  ].reduce((double a, double b) => a + b) /
                  scenes.length,
        flip: i == 0
            ? 0.0
            : <double>[
                    for (final (s, rows) in measured.indexed)
                      flip(
                        fullPictures[s],
                        rows[i].picture,
                        width: width,
                        height: height,
                      ).mean,
                  ].reduce((double a, double b) => a + b) /
                  scenes.length,
      ),
  ];
}

/// The Dart source of `flutter3d_core`'s `tables/quality_tables.dart`: one
/// list of costs and one of FLIPs per [DeviceClass], in grid order.
///
/// [tables] maps each class to its measurements and whether they were taken
/// on a device of that class.
String qualityTablesSource(
  Map<DeviceClass, ({List<QualityMeasurement> rows, bool measured})> tables, {
  String note = '',
}) {
  String row(List<double> values) =>
      '  <double>[${values.map((double v) => v.toStringAsFixed(4)).join(', ')}],';
  final classes = DeviceClass.values;
  for (final deviceClass in classes) {
    final rows = tables[deviceClass]?.rows;
    if (rows == null || rows.length != QualitySetting.grid.length) {
      throw ArgumentError('no full grid of measurements for $deviceClass');
    }
  }
  return <String>[
    '// GENERATED by flutter3d_testing/tool/quality_table.dart. Do not edit by hand.',
    '//',
    '// ignore_for_file: lines_longer_than_80_chars',
    '',
    if (note.isNotEmpty)
      ...note.split('\n').map((String l) => '/// $l'.trimRight()),
    if (note.isNotEmpty) 'library;',
    if (note.isNotEmpty) '',
    '/// Per `DeviceClass`, whether the rows were measured on that class.',
    'const List<bool> qualityMeasured = <bool>[${classes.map((DeviceClass c) => tables[c]!.measured).join(', ')}];',
    '',
    '/// Per `DeviceClass`, each `QualitySetting.grid` row\'s frame time over full',
    '/// quality\'s.',
    'const List<List<double>> qualityCost = <List<double>>[',
    for (final c in classes)
      row(<double>[for (final m in tables[c]!.rows) m.cost]),
    '];',
    '',
    '/// Per `DeviceClass`, each `QualitySetting.grid` row\'s mean FLIP against',
    '/// full quality.',
    'const List<List<double>> qualityFlip = <List<double>>[',
    for (final c in classes)
      row(<double>[for (final m in tables[c]!.rows) m.flip]),
    '];',
    '',
  ].join('\n');
}

/// Every setting of the grid over one scene: the fastest of [samples]
/// interleaved frames, and the last frame's picture.
Future<List<({double micros, Uint8List picture})>> _measureScene({
  required GraphicsDevice device,
  required int width,
  required int height,
  required QualityScene build,
  required int settle,
  required int samples,
}) async {
  final draws = <FrameResult Function()>[
    for (final setting in QualitySetting.grid)
      _drawer(device, width, height, build, setting),
  ];
  for (final draw in draws) {
    for (var i = 0; i < settle; i++) {
      draw();
    }
  }
  final fastest = List<double>.filled(draws.length, double.infinity);
  final last = List<FrameResult?>.filled(draws.length, null);
  for (var round = 0; round < samples; round++) {
    for (final (i, draw) in draws.indexed) {
      final result = draw();
      fastest[i] = math.min(fastest[i], _frameMicros(result));
      last[i] = result;
    }
  }

  return <({double micros, Uint8List picture})>[
    for (final (i, result) in last.indexed)
      (
        micros: fastest[i],
        picture: await _picture(device, result!, width, height),
      ),
  ];
}

/// Draws [build] at [setting] with a renderer of its own, one frame a call.
FrameResult Function() _drawer(
  GraphicsDevice device,
  int width,
  int height,
  QualityScene build,
  QualitySetting setting,
) {
  final subject = build(device);
  final renderer = Renderer.create(device: device);
  final settings = setting.apply(subject.settings);
  return () => renderer.render(
    width: width,
    height: height,
    scene: subject.scene,
    views: <RenderView>[subject.view],
    settings: settings,
  );
}

/// [result]'s frame as RGBA bytes at [width] × [height].
Future<Uint8List> _picture(
  GraphicsDevice device,
  FrameResult result,
  int width,
  int height,
) async {
  final bytes = await device.readPixels(result.frame);
  if (bytes == null) {
    throw StateError('the device could not read back the frame');
  }
  return _stretch(
    bytes.buffer.asUint8List(bytes.offsetInBytes, bytes.lengthInBytes),
    result.frame.width,
    result.frame.height,
    width,
    height,
  );
}

/// The GPU's time where every pass reports one, the renderer's otherwise.
double _frameMicros(FrameResult result) {
  final gpu = result.passes.map((FramePass p) => p.gpuMicros).toList();
  return gpu.isNotEmpty && gpu.every((int? m) => m != null)
      ? gpu.fold<int>(0, (int sum, int? m) => sum + m!).toDouble()
      : result.cpuMicros.toDouble();
}

/// [pixels] (RGBA, [w] × [h]) resampled bilinearly to [width] × [height].
Uint8List _stretch(Uint8List pixels, int w, int h, int width, int height) {
  if (w == width && h == height) return Uint8List.fromList(pixels);
  final out = Uint8List(width * height * 4);
  for (var y = 0; y < height; y++) {
    final sy = ((y + 0.5) * h / height - 0.5).clamp(0.0, h - 1.0);
    final y0 = sy.floor();
    final y1 = (y0 + 1).clamp(0, h - 1);
    final fy = sy - y0;
    for (var x = 0; x < width; x++) {
      final sx = ((x + 0.5) * w / width - 0.5).clamp(0.0, w - 1.0);
      final x0 = sx.floor();
      final x1 = (x0 + 1).clamp(0, w - 1);
      final fx = sx - x0;
      for (var c = 0; c < 4; c++) {
        final top =
            pixels[(y0 * w + x0) * 4 + c] * (1 - fx) +
            pixels[(y0 * w + x1) * 4 + c] * fx;
        final bottom =
            pixels[(y1 * w + x0) * 4 + c] * (1 - fx) +
            pixels[(y1 * w + x1) * 4 + c] * fx;
        out[(y * width + x) * 4 + c] = (top * (1 - fy) + bottom * fy).round();
      }
    }
  }
  return out;
}
