/// `flutter3d_lints/lib/src/migration/table.g.dart`, written from the
/// migration tables: the entries the analyzer plugin and `dart run
/// flutter3d_lints:migrate` check a resolved project against — `rewrite`,
/// `implementsToWith` and `manual`.
///
/// The plugin cannot read this package's YAML (it does not depend on it, and
/// the analysis server runs it apart from any project), so the table is
/// compiled into it as constants.
library;

import 'table.dart';

/// Which uses a manual entry is about, when the entry does not say:
/// a new case of a sealed type or a new enum value breaks `switch`es; a
/// change only an implementer feels breaks the `implements` clauses; the
/// rest breaks every use.
({String match, String? switchOver}) inferMatch(MigrationEntry e) {
  final explicit = e.fields['match'] as String?;
  final over = RegExp(
    r'^`(\w+)` has (?:a new case|new values|a new value)',
  ).firstMatch(e.text)?.group(1);
  if (explicit != null) return (match: explicit, switchOver: over);
  if (over != null) return (match: 'switches', switchOver: over);
  if (RegExp(
    r'Only (code that implements|a backend of your own|an encoder of your own)',
  ).hasMatch(e.text)) {
    return (match: 'subtypes', switchOver: null);
  }
  return (match: 'uses', switchOver: null);
}

/// The first sentence of [text]: what a diagnostic says.
String firstSentence(String text) {
  final flat = text.replaceAll(RegExp(r'\s+'), ' ').trim();
  var inCode = false;
  for (var i = 0; i < flat.length - 1; i++) {
    if (flat[i] == '`') inCode = !inCode;
    if (!inCode && flat[i] == '.' && flat[i + 1] == ' ') {
      return flat.substring(0, i + 1);
    }
  }
  return flat;
}

String _string(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

/// The Dart source of the plugin's table, from [tables].
String generateLintsTable(
  List<MigrationTable> tables, {
  required String stamp,
}) {
  final out = StringBuffer()
    ..writeln(
      '// GENERATED by `dart run tool/generate_migrations.dart` in '
      'flutter3d_build, from',
    )
    ..writeln('// flutter3d_build/lib/migrations/*.yaml. Do not edit.')
    ..writeln('// table-stamp: $stamp')
    ..writeln()
    ..writeln("import 'migration_rule.dart';")
    ..writeln()
    ..writeln(
      '/// Every migration the plugin and the batch migrator check a '
      'resolved',
    )
    ..writeln('/// project against.')
    ..writeln('const List<MigrationRule> migrationRules = <MigrationRule>[');
  for (final table in tables) {
    for (final e in table.entries) {
      final kind = switch (e.kind) {
        'rewrite' => 'rewrite',
        'implementsToWith' => 'implementsToWith',
        'manual' => 'manual',
        _ => null,
      };
      if (kind == null) continue;
      final (:match, :switchOver) = inferMatch(e);
      final members = <String>[
        for (final m in (e.fields['members'] as List<Object?>?) ?? const [])
          '$m',
      ];
      final message = switch (e.kind) {
        'implementsToWith' =>
          '`${e.topName}` is a base mixin class in ${table.to}: a class '
              'mixes it in with `with` and is `base`, `final` or `sealed` '
              'itself.',
        'rewrite' when e.text.isEmpty =>
          '`${e.symbol}` is deprecated in ${table.to}; the fix asks the same '
              'receiver `${e.template!.replaceAll(RegExp(r'\s+'), ' ').replaceAll('{target}.', '').replaceAll('{target}', 'it').replaceAll('{0}', '…')}` '
              'instead.',
        _ => firstSentence(e.text),
      };
      out
        ..writeln('  MigrationRule(')
        ..writeln('    id: ${_string(e.id)},')
        ..writeln('    kind: MigrationKind.$kind,')
        ..writeln('    package: ${_string(e.package)},')
        ..writeln('    type: ${_string(e.topName)},');
      if (e.member != null) out.writeln('    member: ${_string(e.member!)},');
      if (e.template != null) {
        out.writeln(
          '    template: '
          '${_string(e.template!.replaceAll(RegExp(r'\s+'), ' ').trim())},',
        );
      }
      if (e.imports.isNotEmpty) {
        out.writeln(
          '    imports: <String>[${e.imports.map(_string).join(', ')}],',
        );
      }
      if (switchOver != null) {
        out.writeln('    switchOver: ${_string(switchOver)},');
      }
      if (match != 'uses') out.writeln('    match: MigrationMatch.$match,');
      if (members.isNotEmpty) {
        out.writeln(
          '    members: <String>[${members.map(_string).join(', ')}],',
        );
      }
      out
        ..writeln('    message: ${_string(message)},')
        ..writeln('    link: ${_string(table.linkFor(e))},')
        ..writeln('  ),');
    }
  }
  out.writeln('];');
  return out.toString();
}
