/// What a level that will not load does to the game.
///
///     flutter test test/level_error_test.dart
///
/// **It used to do nothing, for ever.** `_loadLevel` had no `catch` and
/// `_initError` covers only the device and the renderer, so a malformed
/// document, a missing texture or a save naming a level that has since been
/// renamed left a black screen with no message, no log a player could see and
/// no way out. Every one of those is a mistake made while *editing content*,
/// which is the most likely mistake this game has — the level documents are
/// generated by a Python script that somebody edits.
///
/// The claim left here is that **the load really does throw** — a `try`
/// around something that cannot throw is a comment pretending to be code.
/// The screen that says so moved to `flutter3d_ui` with the widget, which
/// four applications had each written a version of; its tests went with it.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter3d_game/flutter3d_game.dart';
import 'package:flutter3d_game_platformer/flutter3d_game_platformer.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('a level document that is wrong', () {
    test('throws rather than loading something empty', () {
      // Read the shipped level, break it the way an editor would, and check
      // that somebody objects. Mutation-proof by construction: if the reader
      // ever starts shrugging this off, the `catch` in `main.dart` becomes
      // decoration and this test says so.
      final good =
          jsonDecode(File('assets/levels/first_steps.json').readAsStringSync())
              as Map<String, Object?>;

      // A brush with no size, which is what a hand-edited document looks like
      // when a line goes missing.
      final brushes = List<Object?>.from(good['brushes']! as List<Object?>);
      brushes[0] = <String, Object?>{
        'at': <double>[0.0, 0.0, 0.0],
        'material': 'rock',
      };

      expect(
        () => Level.fromJson(<String, Object?>{...good, 'brushes': brushes}),
        throwsA(anything),
      );
    });

    test('and a level with nowhere to start is refused', () {
      // `assertValid` is what `LevelLoader.load` calls, so this is the second
      // of the two ways the shipped path throws: a document that parsed and is
      // still not a level.
      //
      // **A missing material is not one of them**, and that was worth finding
      // out by trying: emptying the material table leaves the validator with
      // plenty to say and `assertValid` silent, because those issues are
      // warnings. The level loads and draws untextured. Deleting the player's
      // spawn is an error, and this is the shape of the mistake a generator
      // makes.
      final good =
          jsonDecode(File('assets/levels/first_steps.json').readAsStringSync())
              as Map<String, Object?>;
      final entities = <Object?>[
        for (final entity in good['entities']! as List<Object?>)
          if ((entity! as Map<String, Object?>)['type'] != 'player_spawn')
            entity,
      ];
      final level = Level.fromJson(<String, Object?>{
        ...good,
        'entities': entities,
      });

      expect(
        () => LevelValidator(
          registry: platformerRegistry(),
          rules: platformerRules(),
        ).assertValid(level),
        throwsA(isA<LevelFormatException>()),
      );
    });
  });
}
