/// Writes the core's material and constant header from the Dart catalogue.
///
///     dart run tool/gen_materials.dart          # write it
///     dart run tool/gen_materials.dart --check  # exit 1 if it is out of date
///
/// **The catalogue is the one place a substance's number is written**
/// (`flutter3d_matter`'s `Materials`), with the constants of nature
/// (`physical_constants.dart`) and the standard world's defaults
/// (`standard_world.dart`). The C core reads all three from
/// `csrc/src/f3d_materials.g.h`, which this writes: water's density in
/// `f3d_shallow.c`, the heat presets in `f3d_heat.c`, σ wherever a surface
/// radiates, 9.81 where a world is made. A structure rule runs `--check`, so
/// a number changed on one side and not the other does not get in.
///
/// Each number of a built-in's mechanical, fluid, thermal, acoustic, optical
/// and electrical groups becomes `F3D_MAT_<NAME>_<FIELD>`, the name and field
/// in upper snake case (`f3d.oliveOil`'s viscosity is
/// `F3D_MAT_OLIVE_OIL_VISCOSITY`); lists and colours stay in Dart. A plugin's
/// material is not here: the core has it from the view that is made of it
/// (`NativeLiquidProperties.of`, `NativeMaterial.of`) when the thing that
/// needs it is made.
library;

import 'dart:io';

import 'package:flutter3d_matter/flutter3d_matter.dart';

/// Where the header goes, from the package root.
const String headerPath = 'csrc/src/f3d_materials.g.h';

/// The header's text.
String generateMaterialsHeader() {
  final out = StringBuffer()
    ..writeln(
      '/* Generated by tool/gen_materials.dart from flutter3d_physics\'',
    )
    ..writeln(
      ' * material catalogue, constants and standard world. Do not edit:',
    )
    ..writeln(' * change the Dart and run `dart run tool/gen_materials.dart`.')
    ..writeln(' *')
    ..writeln(
      ' * Every value is in SI, as the catalogue documents it, and each',
    )
    ..writeln(' * material\'s sources are on its entry in materials.dart. */')
    ..writeln('#ifndef F3D_MATERIALS_G_H')
    ..writeln('#define F3D_MATERIALS_G_H')
    ..writeln()
    ..writeln('/* Constants of nature (physical_constants.dart). */')
    ..writeln(_define('F3D_STEFAN_BOLTZMANN', stefanBoltzmann))
    ..writeln(_define('F3D_GAS_CONSTANT', molarGasConstant))
    ..writeln(_define('F3D_MOLAR_MASS_OF_DRY_AIR', molarMassOfDryAir))
    ..writeln()
    ..writeln('/* A world nobody configured (standard_world.dart). */')
    ..writeln(_define('F3D_STANDARD_GRAVITY', standardGravity))
    ..writeln(_define('F3D_STANDARD_AIR_TEMPERATURE', standardAirTemperature))
    ..writeln(_define('F3D_STANDARD_AIR_DENSITY', standardAirDensity))
    ..writeln(_define('F3D_STANDARD_ATMOSPHERE', standardAtmosphere));
  for (final material in Materials.all) {
    final name = _snake(material.id.substring('f3d.'.length));
    out
      ..writeln()
      ..writeln(
        '/* ${material.id}: ${material.name}, at '
        '${_literal(material.temperature)} K. */',
      );
    for (final group in <PropertyGroup?>[
      material.mechanical,
      material.fluid,
      material.thermal,
      material.acoustic,
      material.optical,
      material.electrical,
    ]) {
      if (group == null) continue;
      for (final MapEntry(:key, :value) in group.toJson().entries) {
        if (value is! num) continue;
        out.writeln(
          _define('F3D_MAT_${name}_${_snake(key)}', value.toDouble()),
        );
      }
    }
  }
  out
    ..writeln()
    ..writeln('#endif');
  return out.toString();
}

String _define(String name, double value) =>
    '#define $name F3D_R(${_literal(value)})';

/// [value] as a C literal that is the same double: Dart's shortest
/// round-trip form, with a point where it has none.
String _literal(double value) {
  final text = value.toString();
  return text.contains('.') || text.contains('e') ? text : '$text.0';
}

/// `oliveOil` → `OLIVE_OIL`.
String _snake(String camel) => camel
    .replaceAllMapped(
      RegExp('([a-z0-9])([A-Z])'),
      (Match m) => '${m[1]}_${m[2]}',
    )
    .toUpperCase();

void main(List<String> args) {
  final root = File.fromUri(Platform.script).parent.parent;
  final file = File('${root.path}/$headerPath');
  final text = generateMaterialsHeader();
  if (args.contains('--check')) {
    final now = file.existsSync()
        ? file.readAsStringSync().replaceAll('\r\n', '\n')
        : '';
    if (now != text) {
      stderr.writeln(
        '$headerPath is out of date: run `dart run tool/gen_materials.dart` '
        'in flutter3d_physics_native',
      );
      exitCode = 1;
    }
    return;
  }
  file.writeAsStringSync(text);
}
