#!/usr/bin/env bash
# Writes site/docs-dist/index.html from whatever package trees are there.
#
# Split out of build-docs.sh so the landing page can be changed without a
# full dartdoc run behind it. Called at the end of that script;
# safe to run on its own.
#
# The list comes from the directories on disk rather than from a list in this
# file, because a hand-kept list is what goes stale the day somebody adds a
# package — and each line is the package's pubspec description, which is already
# the sentence pub.dev would show, so there is no second summary to keep true.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
repo="$(cd "$here/.." && pwd)"
out="$here/docs-dist"
github='https://github.com/pleiondev/flutter3d'
linkedin='https://www.linkedin.com/in/dmitrii-zolotov'
email='dmitrii.zolotov@gmail.com'

# Same icon row as the main site's layout() in build.mjs — kept in sync by
# hand since this landing page is generated by a different tool. Sizes are
# set on the <svg> itself, not just in CSS: a stale cached stylesheet must
# not leave these at the browser's ~150px replaced-element default.
icon_mail='<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2Z"/><path d="m22 6-10 7L2 6"/></svg>'
icon_feedback='<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>'
icon_linkedin='<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>'
icon_github='<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>'
icon_links=$(cat <<ICONS
<div class="icon-links">
  <a class="icon-link" href="mailto:$email?subject=Question%20about%20flutter3d" rel="noopener" aria-label="Email a question" title="Email a question">$icon_mail</a>
  <a class="icon-link" href="mailto:$email?subject=Feedback%20on%20flutter3d" rel="noopener" aria-label="Send feedback" title="Send feedback">$icon_feedback</a>
  <a class="icon-link" href="$linkedin" rel="noopener" aria-label="LinkedIn" title="LinkedIn">$icon_linkedin</a>
  <a class="icon-link" href="$github" rel="noopener" aria-label="GitHub" title="GitHub">$icon_github</a>
</div>
ICONS
)

rows=''
count=0
for tree in "$out"/*/; do
  name="$(basename "$tree")"
  [ -f "$repo/packages/$name/pubspec.yaml" ] || continue
  description="$(
    python3 - "$repo/packages/$name/pubspec.yaml" <<'PY'
import re, sys
text = open(sys.argv[1], encoding='utf-8').read()
match = re.search(r'^description:\s*(?:>-\s*\n((?:[ \t]+.*\n)+)|(.*)$)', text, re.M)
raw = (match.group(1) or match.group(2) or '') if match else ''
out = ' '.join(raw.split()).strip().strip('"')
print(out.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;'))
PY
  )"
  rows+="    <li><a href=\"/docs/$name/\"><code>$name</code><span>$description</span></a></li>"$'\n'
  count=$((count + 1))
done

cat > "$out/index.html" <<HTML
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>API reference · flutter3d</title>
<meta name="description" content="Generated Dart API documentation for every flutter3d package.">
<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="/assets/site.css">
<style>
  /* Deliberately not the site's three-column shell. This page has no sidebar
     and no table of contents, and borrowing a grid built for both leaves the
     content depending on rules about columns that are not here. */
  .api-shell { max-width: 940px; margin: 0 auto; padding: 40px 22px 80px; }
  .api-shell h1 { margin: 0 0 .6rem; }
  .api-list { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
              gap: 14px; margin: 2rem 0 2.6rem; padding: 0; list-style: none; }
  .api-list li { margin: 0; }
  .api-list a { display: block; height: 100%; padding: 16px 17px;
                background: var(--surface); border: 1px solid var(--border);
                border-radius: var(--radius); text-decoration: none; color: var(--text);
                transition: border-color .14s, transform .14s; }
  .api-list a:hover { border-color: var(--amber-dim); transform: translateY(-2px); }
  .api-list code { display: block; margin-bottom: 6px; padding: 0; background: none;
                   font: 600 15px/1.3 var(--mono); letter-spacing: -.01em; color: var(--amber); }
  .api-list span { display: block; font-size: 14px; line-height: 1.55; color: var(--muted); }
</style>
</head>
<body class="doc">
<header class="topbar">
  <a class="brand" href="/">
    <span class="brand-mark" aria-hidden="true"></span>
    <span class="brand-name">flutter3d</span>
  </a>
  <div class="topbar-meta">
    <a class="chip chip-link" href="/">Documentation</a>
    <a class="chip chip-link" href="/reference/packages/">What each package is for</a>
    $icon_links
  </div>
</header>

<main class="api-shell">
  <h1>API reference</h1>
  <p class="lead">Generated from the source with <code>dart doc</code>, one tree per
     package. For what a package is <em>for</em> rather than what it exports, start
     at the <a href="/reference/packages/">package index</a>; for how the pieces fit
     together, read
     <a href="$github/blob/main/ARCHITECTURE.md" rel="noopener">ARCHITECTURE.md</a>.</p>

  <ul class="api-list">
$rows  </ul>

  <footer class="foot">
    <p class="foot-legal">
      An independent implementation of a 3D engine for Flutter, not affiliated
      with the Flutter team.<br>
      &copy; 2026 Dmitrii Zolotov. Released under the
      <a href="$github/blob/main/LICENSE" rel="noopener">MIT licence</a>.
    </p>
  </footer>
</main>

<script src="/assets/site.js"></script>
</body>
</html>
HTML

echo "index lists $count packages"
