/// What a level that will not load does to the game.
///
///     flutter test test/level_error_test.dart
///
/// **It used to do nothing, for ever.** `_loadLevel` had no `catch` and
/// `_initError` covers only the device and the renderer, so a malformed
/// document, a missing texture or a save naming a level that has since been
/// renamed left a black screen with no message, no log a player could see and
/// no way out. Every one of those is a mistake made while *editing content*,
/// which is the most likely mistake this game has — the level documents are
/// generated by a Python script that somebody edits.
///
/// Two claims, because a `try` around something that cannot throw is a comment
/// pretending to be code: **the load really does throw**, and **the screen
/// really does say so and offer a way out**.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter3d_game/flutter3d_game.dart';
import 'package:flutter3d_game_platformer/flutter3d_game_platformer.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:platformer/src/hud.dart';

void main() {
  group('a level document that is wrong', () {
    test('throws rather than loading something empty', () {
      // Read the shipped level, break it the way an editor would, and check
      // that somebody objects. Mutation-proof by construction: if the reader
      // ever starts shrugging this off, the `catch` in `main.dart` becomes
      // decoration and this test says so.
      final good = jsonDecode(
        File('assets/levels/first_steps.json').readAsStringSync(),
      ) as Map<String, Object?>;

      // A brush with no size, which is what a hand-edited document looks like
      // when a line goes missing.
      final brushes = List<Object?>.from(good['brushes']! as List<Object?>);
      brushes[0] = <String, Object?>{
        'at': <double>[0.0, 0.0, 0.0],
        'material': 'rock',
      };

      expect(
        () => Level.fromJson(<String, Object?>{...good, 'brushes': brushes}),
        throwsA(anything),
      );
    });

    test('and a level with nowhere to start is refused', () {
      // `assertValid` is what `LevelLoader.load` calls, so this is the second
      // of the two ways the shipped path throws: a document that parsed and is
      // still not a level.
      //
      // **A missing material is not one of them**, and that was worth finding
      // out by trying: emptying the material table leaves the validator with
      // plenty to say and `assertValid` silent, because those issues are
      // warnings. The level loads and draws untextured. Deleting the player's
      // spawn is an error, and this is the shape of the mistake a generator
      // makes.
      final good = jsonDecode(
        File('assets/levels/first_steps.json').readAsStringSync(),
      ) as Map<String, Object?>;
      final entities = <Object?>[
        for (final entity in good['entities']! as List<Object?>)
          if ((entity! as Map<String, Object?>)['type'] != 'player_spawn')
            entity,
      ];
      final level = Level.fromJson(<String, Object?>{
        ...good,
        'entities': entities,
      });

      expect(
        () => LevelValidator(
          registry: platformerRegistry(),
          rules: platformerRules(),
        ).assertValid(level),
        throwsA(isA<LevelFormatException>()),
      );
    });
  });

  group('the screen that says so', () {
    testWidgets('names the level and the reason', (WidgetTester tester) async {
      await tester.pumpWidget(
        MaterialApp(
          home: LevelErrorScreen(
            asset: 'assets/levels/ascent.json',
            error: 'brush 0 has no size',
            onStartOver: () {},
          ),
        ),
      );

      expect(find.textContaining('would not load'), findsOneWidget);
      expect(find.text('assets/levels/ascent.json'), findsOneWidget);
      expect(find.textContaining('brush 0 has no size'), findsOneWidget);
    });

    testWidgets('and offers the only thing that can help', (
      WidgetTester tester,
    ) async {
      // **The failing level is usually the saved one.** A player whose save
      // points at a level that will not read cannot be rescued by retrying it,
      // only by throwing the run away — and they cannot do that from a black
      // screen.
      var started = 0;
      await tester.pumpWidget(
        MaterialApp(
          home: LevelErrorScreen(
            asset: 'assets/levels/ascent.json',
            error: 'anything',
            onStartOver: () => started++,
          ),
        ),
      );

      await tester.tap(find.textContaining('start again'));
      expect(started, 1);
    });
  });
}
