// GENERATED CODE - DO NOT MODIFY BY HAND
// Consider adding this file to your .gitignore.

import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';


import 'lod_screen_fraction_test.dart' as _a;
import 'l10n_no_hardcoded_cyrillic_test.dart' as _b;
import 'properties_sections_test.dart' as _c;
import 'import_screen_test.dart' as _d;
import 'ui/animation_panel_test.dart' as _e;
import 'ui/actions_list_test.dart' as _f;
import 'ui/texture_graph_panel_test.dart' as _g;
import 'ui/curve_editor_test.dart' as _h;
import 'ui/job_button_test.dart' as _i;
import 'ui/bend_slider_bar_test.dart' as _j;
import 'ui/shell_for_width_test.dart' as _k;
import 'ui/uv_screen_test.dart' as _l;
import 'ui/uv_layout_view_test.dart' as _m;
import 'ui/lod_zone_bar_test.dart' as _n;
import 'ui/constraints_list_test.dart' as _o;
import 'ui/morphs_panel_test.dart' as _p;
import 'ui/lod_screen_test.dart' as _q;
import 'ui/transport_bar_test.dart' as _r;
import 'ui/weight_paint_panel_test.dart' as _s;
import 'ui/budget_bars_test.dart' as _t;
import 'ui/undo_redo_buttons_test.dart' as _u;
import 'ui/simulation_cache_strip_test.dart' as _v;
import 'ui/transform_readout_test.dart' as _w;
import 'ui/animation_screen_test.dart' as _x;
import 'ui/metrics_overlay_test.dart' as _y;
import 'ui/timeline_panel_test.dart' as _z;
import 'ui/skeleton_tree_test.dart' as _A;
import 'ui/game_preview_screen_test.dart' as _B;
import 'ui/animation_bottom_test.dart' as _C;
import 'ui/autorig_dialog_test.dart' as _D;
import 'ui/uv_unwrap_panel_test.dart' as _E;
import 'scene_sync_test.dart' as _F;
import 'report_problem_test.dart' as _G;
import 'weight_paint_session_test.dart' as _H;
import 'file_import_test.dart' as _I;
import 'viewport_look_and_modal_test.dart' as _J;
import 'touch_shells_test.dart' as _K;
import 'shell_test.dart' as _L;
import 'main_recovery_test.dart' as _M;
import 'project_files_io_test.dart' as _N;
import 'import_defaults_test.dart' as _O;
import 'mesh_health_test.dart' as _P;
import 'simulation_playback_bench_test.dart' as _Q;
import 'material_panel_test.dart' as _R;
import 'morphs_and_brush_test.dart' as _S;
import 'material_file_writer_test.dart' as _T;
import 'autorig_markers_test.dart' as _U;
import 'texture_slot_test.dart' as _V;
import 'retarget_screen_golden_test.dart' as _W;
import 'recent_projects_test.dart' as _X;
import 'gltf_siblings_test.dart' as _Z;
import 'weight_gradient_frame_test.dart' as _aa;
import 'gizmo_wiring_test.dart' as _ba;
import 'transform_session_test.dart' as _ca;
import 'tools_test.dart' as _da;
import 'pivot_space_chips_test.dart' as _fa;
import 'properties_panel_select_crash_test.dart' as _ga;
import 'modeler_ui_actions_test.dart' as _ha;
import 'material_pool_test.dart' as _ia;
import 'theme_test.dart' as _ja;
import 'outliner_test.dart' as _ka;
import 'shape_key_state_test.dart' as _la;
import 'export_screen_test.dart' as _ma;
import 'cabinet_link_test.dart' as _na;
import 'transform_gizmo_test.dart' as _oa;
import 'simulation_playback_test.dart' as _pa;
import 'save_as_dialog_test.dart' as _qa;
import 'game_preview_frame_test.dart' as _ra;
import 'object_picking_test.dart' as _sa;
import 'remote_gallery_test.dart' as _ta;
import 'crash_handling_test.dart' as _ua;
import 'ground_grid_test.dart' as _va;
import 'viewport_element_gestures_test.dart' as _wa;
import 'display_modes_test.dart' as _xa;
import 'window_chrome_test.dart' as _ya;
import 'scene_shadows_panel_test.dart' as _za;
import 'l10n_arb_keys_test.dart' as _Aa;
import 'scene_frame_test.dart' as _Ba;
import 'gizmo_handles_test.dart' as _Ca;
import 'orbit_gestures_test.dart' as _Da;
import 'outliner_semantics_test.dart' as _Ea;
import 'selection_key_bindings_test.dart' as _Fa;
import 'orientation_dial_test.dart' as _Ga;
import 'scene_post_panel_test.dart' as _Ha;
import 'settings_test.dart' as _Ia;
import 'export_anyway_dialog_test.dart' as _Ja;
import 'transform_dispatch_test.dart' as _Ka;
import 'selection_rules_test.dart' as _La;
import 'input_policy_test.dart' as _Ma;
import 'value_drag_test.dart' as _Na;
import 'restore_autosave_dialog_test.dart' as _Oa;
import 'sandbox_probe_io_test.dart' as _Pa;
import 'panel_labels_test.dart' as _Qa;
import 'exporting_test.dart' as _Ra;
import 'frame_test.dart' as _Sa;
import 'autosaving_test.dart' as _Ta;
import 'l10n_no_literal_ui_text_test.dart' as _Ua;
import 'scene_mode_test.dart' as _Va;
import 'lathe_dialog_test.dart' as _Wa;
import 'gizmo_through_geometry_frame_test.dart' as _Xa;
import 'environment_summary_test.dart' as _Ya;
import 'top_bar_actions_test.dart' as _Za;
import 'l10n_tool_strings_test.dart' as _ab;
import 'mesh_overlay_frame_test.dart' as _bb;
import 'curve_editor_golden_test.dart' as _cb;
import 'paint_upload_test.dart' as _db;
import 'object_row_test.dart' as _eb;
import 'mesh_material_colour_frame_test.dart' as _fb;
import 'agent_badge_test.dart' as _gb;
import 'mesh_overlay_builder_test.dart' as _hb;
import 'weight_gradient_test.dart' as _ib;
import 'element_picking_test.dart' as _jb;
import 'retarget_frame_test.dart' as _kb;
import 'console_log_test.dart' as _lb;
import 'texture_info_upload_test.dart' as _mb;
import 'scene_light_picking_test.dart' as _nb;
import 'modeler_cubit_test.dart' as _ob;
import 'uv_seam_test.dart' as _pb;
import 'close_guard_test.dart' as _qb;
import 'keymap_test.dart' as _rb;
import 'theme_accent_literals_test.dart' as _sb;
import 'light_gizmos_test.dart' as _tb;
import 'modeler_keys_test.dart' as _ub;
import 'image_decoder_parity_test.dart' as _vb;
import 'dock_layout_test.dart' as _wb;
import 'geometry_snap_test.dart' as _xb;
import 'cabinet_save_test.dart' as _yb;
import 'outliner_depth_test.dart' as _zb;
import 'transport_bar_golden_test.dart' as _Ab;
import 'gallery_screen_test.dart' as _Bb;
import 'measurement_runs_test.dart' as _Cb;
import 'scene_environment_panel_test.dart' as _Db;
import 'preview_capture_test.dart' as _Eb;
import 'scene_mode_ux_test.dart' as _Fb;
import 'console_panel_test.dart' as _Gb;
import 'autorig_frame_test.dart' as _Hb;
import 'timeline_preview_wiring_test.dart' as _Ib;
import 'selection_box_test.dart' as _Jb;
import 'clip_library_test.dart' as _Kb;
import 'gizmo_drag_events_test.dart' as _Lb;
import 'launch_screen_test.dart' as _Mb;
import 'profile_editing_test.dart' as _Nb;
import 'pro_panels_test.dart' as _Ob;
import 'element_picker_cache_test.dart' as _Pb;
import 'draw_call_guard_test.dart' as _Qb;
import 'viewport_metrics_test.dart' as _Rb;
import 'unsaved_changes_dialog_test.dart' as _Sb;
import 'transform_fields_test.dart' as _Tb;
import 'opening_report_test.dart' as _Ub;
import 'import_plan_test.dart' as _Vb;
import 'shortcut_help_test.dart' as _Wb;
import 'clip_tracks_bar_test.dart' as _Xb;
import 'measurement_report_overlay_test.dart' as _Yb;
import 'material_editing_test.dart' as _Zb;
import 'properties_panel_test.dart' as _ac;
import 'timeline_playback_test.dart' as _bc;
import 'keyboard_shortcuts_test.dart' as _cc;
import 'sculpt_session_test.dart' as _dc;
import 'recovery_dialog_test.dart' as _ec;
import 'panel_test.dart' as _fc;
import 'animation_wiring_test.dart' as _gc;
import 'command_palette_test.dart' as _hc;
import 'agent_session_panel_test.dart' as _ic;
import 'opening_test.dart' as _jc;
import 'open_report_test.dart' as _kc;
import 'transform_rows_test.dart' as _lc;
import 'tool_commands_test.dart' as _mc;
import 'weight_legend_test.dart' as _nc;
import 'play_session_test.dart' as _oc;
import 'accessibility_test.dart' as _pc;
import 'linked_materials_test.dart' as _qc;
import 'retarget_panel_test.dart' as _rc;
import 'workspace_test.dart' as _sc;
import 'contrast_test.dart' as _tc;
import 'material_studio_environment_test.dart' as _uc;
import 'shortcut_help_screen_test.dart' as _vc;
import 'status_line_test.dart' as _wc;
import 'transform_modal_test.dart' as _xc;
import 'legal_documents_test.dart' as _yc;
import 'scene_source_panel_test.dart' as _zc;
import 'shell_layout_test.dart' as _Ac;
import 'game_preview_settings_test.dart' as _Bc;
import 'label_value_row_test.dart' as _Cc;
import 'weight_mirror_test.dart' as _Dc;
import 'sculpt_upload_test.dart' as _Ec;
import 'joint_picking_test.dart' as _Fc;
import 'layout_class_test.dart' as _Hc;
import 'gallery_catalogue_test.dart' as _Ic;
import 'job_runner_test.dart' as _Jc;
import 'modifier_stack_panel_test.dart' as _Kc;
import 'scene_multi_asset_export_test.dart' as _Lc;
import 'start_screen_test.dart' as _Mc;
import 'timeline_golden_test.dart' as _Oc;
import 'modifier_mirror_array_frame_test.dart' as _Pc;
import 'brush_hit_test.dart' as _Qc;
import 'profile_editor_test.dart' as _Rc;
import 'file_drop_io_test.dart' as _Sc;
import 'name_field_test.dart' as _Tc;
import 'sculpt_budget_test.dart' as _Uc;
import 'profile_limits_test.dart' as _Wc;

void main() {
  goldenFileComparator = _TestOptimizationAwareGoldenFileComparator(goldenFileComparator as LocalFileComparator);
  group('lod_screen_fraction_test.dart', () { _a.main(); });
  group('l10n_no_hardcoded_cyrillic_test.dart', () { _b.main(); });
  group('properties_sections_test.dart', () { _c.main(); });
  group('import_screen_test.dart', () { _d.main(); });
  group('ui/animation_panel_test.dart', () { _e.main(); });
  group('ui/actions_list_test.dart', () { _f.main(); });
  group('ui/texture_graph_panel_test.dart', () { _g.main(); });
  group('ui/curve_editor_test.dart', () { _h.main(); });
  group('ui/job_button_test.dart', () { _i.main(); });
  group('ui/bend_slider_bar_test.dart', () { _j.main(); });
  group('ui/shell_for_width_test.dart', () { _k.main(); });
  group('ui/uv_screen_test.dart', () { _l.main(); });
  group('ui/uv_layout_view_test.dart', () { _m.main(); });
  group('ui/lod_zone_bar_test.dart', () { _n.main(); });
  group('ui/constraints_list_test.dart', () { _o.main(); });
  group('ui/morphs_panel_test.dart', () { _p.main(); });
  group('ui/lod_screen_test.dart', () { _q.main(); });
  group('ui/transport_bar_test.dart', () { _r.main(); });
  group('ui/weight_paint_panel_test.dart', () { _s.main(); });
  group('ui/budget_bars_test.dart', () { _t.main(); });
  group('ui/undo_redo_buttons_test.dart', () { _u.main(); });
  group('ui/simulation_cache_strip_test.dart', () { _v.main(); });
  group('ui/transform_readout_test.dart', () { _w.main(); });
  group('ui/animation_screen_test.dart', () { _x.main(); });
  group('ui/metrics_overlay_test.dart', () { _y.main(); });
  group('ui/timeline_panel_test.dart', () { _z.main(); });
  group('ui/skeleton_tree_test.dart', () { _A.main(); });
  group('ui/game_preview_screen_test.dart', () { _B.main(); });
  group('ui/animation_bottom_test.dart', () { _C.main(); });
  group('ui/autorig_dialog_test.dart', () { _D.main(); });
  group('ui/uv_unwrap_panel_test.dart', () { _E.main(); });
  group('scene_sync_test.dart', () { _F.main(); });
  group('report_problem_test.dart', () { _G.main(); });
  group('weight_paint_session_test.dart', () { _H.main(); });
  group('file_import_test.dart', () { _I.main(); });
  group('viewport_look_and_modal_test.dart', () { _J.main(); });
  group('touch_shells_test.dart', () { _K.main(); });
  group('shell_test.dart', () { _L.main(); });
  group('main_recovery_test.dart', () { _M.main(); });
  group('project_files_io_test.dart', () { _N.main(); });
  group('import_defaults_test.dart', () { _O.main(); });
  group('mesh_health_test.dart', () { _P.main(); });
  group('simulation_playback_bench_test.dart', () { _Q.main(); });
  group('material_panel_test.dart', () { _R.main(); });
  group('morphs_and_brush_test.dart', () { _S.main(); });
  group('material_file_writer_test.dart', () { _T.main(); });
  group('autorig_markers_test.dart', () { _U.main(); });
  group('texture_slot_test.dart', () { _V.main(); });
  group('retarget_screen_golden_test.dart', () { _W.main(); });
  group('recent_projects_test.dart', () { _X.main(); });
  group('gltf_siblings_test.dart', () { _Z.main(); });
  group('weight_gradient_frame_test.dart', () { _aa.main(); });
  group('gizmo_wiring_test.dart', () { _ba.main(); });
  group('transform_session_test.dart', () { _ca.main(); });
  group('tools_test.dart', () { _da.main(); });
  group('pivot_space_chips_test.dart', () { _fa.main(); });
  group('properties_panel_select_crash_test.dart', () { _ga.main(); });
  group('modeler_ui_actions_test.dart', () { _ha.main(); });
  group('material_pool_test.dart', () { _ia.main(); });
  group('theme_test.dart', () { _ja.main(); });
  group('outliner_test.dart', () { _ka.main(); });
  group('shape_key_state_test.dart', () { _la.main(); });
  group('export_screen_test.dart', () { _ma.main(); });
  group('cabinet_link_test.dart', () { _na.main(); });
  group('transform_gizmo_test.dart', () { _oa.main(); });
  group('simulation_playback_test.dart', () { _pa.main(); });
  group('save_as_dialog_test.dart', () { _qa.main(); });
  group('game_preview_frame_test.dart', () { _ra.main(); });
  group('object_picking_test.dart', () { _sa.main(); });
  group('remote_gallery_test.dart', () { _ta.main(); });
  group('crash_handling_test.dart', () { _ua.main(); });
  group('ground_grid_test.dart', () { _va.main(); });
  group('viewport_element_gestures_test.dart', () { _wa.main(); });
  group('display_modes_test.dart', () { _xa.main(); });
  group('window_chrome_test.dart', () { _ya.main(); });
  group('scene_shadows_panel_test.dart', () { _za.main(); });
  group('l10n_arb_keys_test.dart', () { _Aa.main(); });
  group('scene_frame_test.dart', () { _Ba.main(); });
  group('gizmo_handles_test.dart', () { _Ca.main(); });
  group('orbit_gestures_test.dart', () { _Da.main(); });
  group('outliner_semantics_test.dart', () { _Ea.main(); });
  group('selection_key_bindings_test.dart', () { _Fa.main(); });
  group('orientation_dial_test.dart', () { _Ga.main(); });
  group('scene_post_panel_test.dart', () { _Ha.main(); });
  group('settings_test.dart', () { _Ia.main(); });
  group('export_anyway_dialog_test.dart', () { _Ja.main(); });
  group('transform_dispatch_test.dart', () { _Ka.main(); });
  group('selection_rules_test.dart', () { _La.main(); });
  group('input_policy_test.dart', () { _Ma.main(); });
  group('value_drag_test.dart', () { _Na.main(); });
  group('restore_autosave_dialog_test.dart', () { _Oa.main(); });
  group('sandbox_probe_io_test.dart', () { _Pa.main(); });
  group('panel_labels_test.dart', () { _Qa.main(); });
  group('exporting_test.dart', () { _Ra.main(); });
  group('frame_test.dart', () { _Sa.main(); });
  group('autosaving_test.dart', () { _Ta.main(); });
  group('l10n_no_literal_ui_text_test.dart', () { _Ua.main(); });
  group('scene_mode_test.dart', () { _Va.main(); });
  group('lathe_dialog_test.dart', () { _Wa.main(); });
  group('gizmo_through_geometry_frame_test.dart', () { _Xa.main(); });
  group('environment_summary_test.dart', () { _Ya.main(); });
  group('top_bar_actions_test.dart', () { _Za.main(); });
  group('l10n_tool_strings_test.dart', () { _ab.main(); });
  group('mesh_overlay_frame_test.dart', () { _bb.main(); });
  group('curve_editor_golden_test.dart', () { _cb.main(); });
  group('paint_upload_test.dart', () { _db.main(); });
  group('object_row_test.dart', () { _eb.main(); });
  group('mesh_material_colour_frame_test.dart', () { _fb.main(); });
  group('agent_badge_test.dart', () { _gb.main(); });
  group('mesh_overlay_builder_test.dart', () { _hb.main(); });
  group('weight_gradient_test.dart', () { _ib.main(); });
  group('element_picking_test.dart', () { _jb.main(); });
  group('retarget_frame_test.dart', () { _kb.main(); });
  group('console_log_test.dart', () { _lb.main(); });
  group('texture_info_upload_test.dart', () { _mb.main(); });
  group('scene_light_picking_test.dart', () { _nb.main(); });
  group('modeler_cubit_test.dart', () { _ob.main(); });
  group('uv_seam_test.dart', () { _pb.main(); });
  group('close_guard_test.dart', () { _qb.main(); });
  group('keymap_test.dart', () { _rb.main(); });
  group('theme_accent_literals_test.dart', () { _sb.main(); });
  group('light_gizmos_test.dart', () { _tb.main(); });
  group('modeler_keys_test.dart', () { _ub.main(); });
  group('image_decoder_parity_test.dart', () { _vb.main(); });
  group('dock_layout_test.dart', () { _wb.main(); });
  group('geometry_snap_test.dart', () { _xb.main(); });
  group('cabinet_save_test.dart', () { _yb.main(); });
  group('outliner_depth_test.dart', () { _zb.main(); });
  group('transport_bar_golden_test.dart', () { _Ab.main(); });
  group('gallery_screen_test.dart', () { _Bb.main(); });
  group('measurement_runs_test.dart', () { _Cb.main(); });
  group('scene_environment_panel_test.dart', () { _Db.main(); });
  group('preview_capture_test.dart', () { _Eb.main(); });
  group('scene_mode_ux_test.dart', () { _Fb.main(); });
  group('console_panel_test.dart', () { _Gb.main(); });
  group('autorig_frame_test.dart', () { _Hb.main(); });
  group('timeline_preview_wiring_test.dart', () { _Ib.main(); });
  group('selection_box_test.dart', () { _Jb.main(); });
  group('clip_library_test.dart', () { _Kb.main(); });
  group('gizmo_drag_events_test.dart', () { _Lb.main(); });
  group('launch_screen_test.dart', () { _Mb.main(); });
  group('profile_editing_test.dart', () { _Nb.main(); });
  group('pro_panels_test.dart', () { _Ob.main(); });
  group('element_picker_cache_test.dart', () { _Pb.main(); });
  group('draw_call_guard_test.dart', () { _Qb.main(); });
  group('viewport_metrics_test.dart', () { _Rb.main(); });
  group('unsaved_changes_dialog_test.dart', () { _Sb.main(); });
  group('transform_fields_test.dart', () { _Tb.main(); });
  group('opening_report_test.dart', () { _Ub.main(); });
  group('import_plan_test.dart', () { _Vb.main(); });
  group('shortcut_help_test.dart', () { _Wb.main(); });
  group('clip_tracks_bar_test.dart', () { _Xb.main(); });
  group('measurement_report_overlay_test.dart', () { _Yb.main(); });
  group('material_editing_test.dart', () { _Zb.main(); });
  group('properties_panel_test.dart', () { _ac.main(); });
  group('timeline_playback_test.dart', () { _bc.main(); });
  group('keyboard_shortcuts_test.dart', () { _cc.main(); });
  group('sculpt_session_test.dart', () { _dc.main(); });
  group('recovery_dialog_test.dart', () { _ec.main(); });
  group('panel_test.dart', () { _fc.main(); });
  group('animation_wiring_test.dart', () { _gc.main(); });
  group('command_palette_test.dart', () { _hc.main(); });
  group('agent_session_panel_test.dart', () { _ic.main(); });
  group('opening_test.dart', () { _jc.main(); });
  group('open_report_test.dart', () { _kc.main(); });
  group('transform_rows_test.dart', () { _lc.main(); });
  group('tool_commands_test.dart', () { _mc.main(); });
  group('weight_legend_test.dart', () { _nc.main(); });
  group('play_session_test.dart', () { _oc.main(); });
  group('accessibility_test.dart', () { _pc.main(); });
  group('linked_materials_test.dart', () { _qc.main(); });
  group('retarget_panel_test.dart', () { _rc.main(); });
  group('workspace_test.dart', () { _sc.main(); });
  group('contrast_test.dart', () { _tc.main(); });
  group('material_studio_environment_test.dart', () { _uc.main(); });
  group('shortcut_help_screen_test.dart', () { _vc.main(); });
  group('status_line_test.dart', () { _wc.main(); });
  group('transform_modal_test.dart', () { _xc.main(); });
  group('legal_documents_test.dart', () { _yc.main(); });
  group('scene_source_panel_test.dart', () { _zc.main(); });
  group('shell_layout_test.dart', () { _Ac.main(); });
  group('game_preview_settings_test.dart', () { _Bc.main(); });
  group('label_value_row_test.dart', () { _Cc.main(); });
  group('weight_mirror_test.dart', () { _Dc.main(); });
  group('sculpt_upload_test.dart', () { _Ec.main(); });
  group('joint_picking_test.dart', () { _Fc.main(); });
  group('layout_class_test.dart', () { _Hc.main(); });
  group('gallery_catalogue_test.dart', () { _Ic.main(); });
  group('job_runner_test.dart', () { _Jc.main(); });
  group('modifier_stack_panel_test.dart', () { _Kc.main(); });
  group('scene_multi_asset_export_test.dart', () { _Lc.main(); });
  group('start_screen_test.dart', () { _Mc.main(); });
  group('timeline_golden_test.dart', () { _Oc.main(); });
  group('modifier_mirror_array_frame_test.dart', () { _Pc.main(); });
  group('brush_hit_test.dart', () { _Qc.main(); });
  group('profile_editor_test.dart', () { _Rc.main(); });
  group('file_drop_io_test.dart', () { _Sc.main(); });
  group('name_field_test.dart', () { _Tc.main(); });
  group('sculpt_budget_test.dart', () { _Uc.main(); });
  group('profile_limits_test.dart', () { _Wc.main(); });
}


class _TestOptimizationAwareGoldenFileComparator extends GoldenFileComparator {
  final List<String> goldenFilePaths;
  final LocalFileComparator previousGoldenFileComparator;

  _TestOptimizationAwareGoldenFileComparator(this.previousGoldenFileComparator)
      : goldenFilePaths = _goldenFilePaths;

  static List<String> get _goldenFilePaths =>
      Directory.fromUri((goldenFileComparator as LocalFileComparator).basedir)
          .listSync(recursive: true, followLinks: true)
          .whereType<File>()
          .map((file) => file.path)
          .where((path) => path.endsWith('.png'))
          .toList();
  @override
  Future<bool> compare(Uint8List imageBytes, Uri golden)  => previousGoldenFileComparator.compare(imageBytes, golden);

  @override
  Uri getTestUri(Uri key, int? version) {
    final keyString = key.toFilePath();
    return Uri.parse(goldenFilePaths
        .singleWhere((goldenFilePath) => goldenFilePath.endsWith(keyString)));
  }

  @override
  Future<void> update(Uri golden, Uint8List imageBytes) => previousGoldenFileComparator.update(golden, imageBytes);

}
