/// The pictures the six tutorial pages ask for by name, taken headlessly.
///
///     flutter test test/tutorial_case_screenshots_test.dart
///     flutter test test/tutorial_case_screenshots_test.dart --update-goldens
///
/// **What each page is missing, and why it said it could not have it.** Every
/// page carries a "Notes on this page" section listing the pictures that are
/// placeholders — a flat colour with "screenshot pending" written on it — and
/// gives the same reason for all of them: the chrome around the 3D content
/// needs a real window, and the session that wrote the pages could not open
/// one. The recipe each page then offers is `flutter run -d macos` followed
/// by a screencapture script.
///
/// That reason does not hold. The editor opens the software rasteriser in a
/// headless `flutter test` and its frames reach the widget tree as an
/// ordinary image, so the whole application — panels, dialogs and the real 3D
/// between them — can be photographed here. And a picture taken this way is
/// better than one taken by hand: it is regenerated by a command, so it
/// cannot quietly go stale the way `doc/modeler-tutorial-gaps.md`'s own last
/// section records the "expected result" renders doing.
///
/// **Each case is opened from its own committed document** — the same
/// `caseN.f3dproj` `tutorial_scenarios_test.dart` replays — through the real
/// Open button and the real import screen, so what is photographed is the
/// application doing the thing the page describes rather than a widget
/// assembled for the camera.
library;

import 'dart:io';
import 'dart:typed_data';

import 'package:file_selector_platform_interface/file_selector_platform_interface.dart';
import 'package:flutter/material.dart' hide Matrix4;
import 'package:flutter3d_modeler/src/ui/tools.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:plugin_platform_interface/plugin_platform_interface.dart';

import 'tutorial_screenshots_support.dart';

/// A picker that hands back one in-memory file, the way a person choosing a
/// real one in a real dialog hands `openModel` the same two things.
final class _FakePicker extends FileSelectorPlatform
    with MockPlatformInterfaceMixin {
  _FakePicker(this.bytes, this.name);

  final Uint8List bytes;
  final String name;

  @override
  Future<XFile?> openFile({
    List<XTypeGroup>? acceptedTypeGroups,
    String? initialDirectory,
    String? confirmButtonText,
  }) async => XFile.fromData(bytes, path: name);
}

/// Where the six committed case documents live.
const String _fixtures =
    '../../packages/flutter3d_model_mcp/test/fixtures/tutorial';

/// The teapot case 1 actually imports — a real STL, which is what puts the
/// import screen on the screen at all.
///
/// **A project file does not go through it, and should not.** Opening a
/// `.f3dproj` is reopening a document that already answered every question
/// the import screen asks; only a mesh file — an STL, a glTF, an OBJ — has a
/// unit and a cleanup choice still to make. So the picture of that screen is
/// taken over a real import, and the pictures of the editor are taken over
/// the case's own saved document.
const String _teapot = '../../packages/flutter3d_samples/assets/teapot.stl';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  useTolerantGoldens('tutorial_case_screenshots_test.dart');

  late FileSelectorPlatform previousPicker;
  setUp(() => previousPicker = FileSelectorPlatform.instance);
  tearDown(() => FileSelectorPlatform.instance = previousPicker);

  bool fonts = false;
  setUpAll(() async {
    fonts = await loadSdkFonts();
  });

  /// Opens `caseN.f3dproj` through the real Open button, stopping either at
  /// the import screen or after confirming it.
  Future<void> openThrough(
    WidgetTester tester,
    String path,
    String name, {
    bool stopAtImportScreen = false,
  }) async {
    FileSelectorPlatform.instance = _FakePicker(
      File(path).readAsBytesSync(),
      name,
    );
    await tester.tap(find.widgetWithText(TextButton, 'Open'));
    for (var i = 0; i < 6; i++) {
      await tester.pump();
    }
    await tester.pump(const Duration(milliseconds: 400));
    if (stopAtImportScreen) return;
    // Only a mesh file is asked the unit and the cleanup questions; a
    // project file is already a document and goes straight in.
    if (find.widgetWithText(FilledButton, 'Import').evaluate().isNotEmpty) {
      await tester.tap(find.widgetWithText(FilledButton, 'Import'));
      for (var i = 0; i < 6; i++) {
        await tester.pump();
      }
    }
    // Twice: the document lands on one frame and the scene it builds is
    // rasterised and decoded over the next two.
    await settleFrames(tester);
    await settleFrames(tester);
  }

  Future<void> openCase(WidgetTester tester, String file) =>
      openThrough(tester, '$_fixtures/$file', file);

  /// Selects the first object in the outliner, which is what puts the
  /// transform, modifier and material sections on the panel.
  Future<void> selectFirstObject(WidgetTester tester) async {
    final Finder rows = find.byType(InkWell);
    await tester.tap(
      find.descendant(of: find.byType(Scrollable), matching: rows).first,
    );
    await settleFrames(tester);
  }

  group('a prop from a scan', () {
    const String case1 = 'case1.f3dproj';

    testWidgets('01-start-screen', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openByTooltip(
        tester,
        'Start screen — open a file or start a new project',
      );
      await shootWindow(tester, 'prop-from-a-scan/01-start-screen');
    });

    testWidgets('02-import-dialog', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openThrough(
        tester,
        _teapot,
        'teapot.stl',
        stopAtImportScreen: true,
      );
      await shootWindow(tester, 'prop-from-a-scan/02-import-dialog');
    });

    testWidgets('03-material-panel', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case1);
      await selectFirstObject(tester);
      await shootWindow(tester, 'prop-from-a-scan/03-material-panel');
    });

    testWidgets('04-export-dialog', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case1);
      await openExportScreen(tester);
      await shootWindow(tester, 'prop-from-a-scan/04-export-dialog');
    });
  });

  group('a vase from a profile', () {
    const String case2 = 'case2.f3dproj';

    testWidgets('02-mesh-edit-toolbar', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case2);
      await selectFirstObject(tester);
      await switchMode(tester, ModelerMode.mesh);
      await shootWindow(tester, 'vase-from-a-profile/02-mesh-edit-toolbar');
    });

    testWidgets('03-modifier-stack', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case2);
      await selectFirstObject(tester);
      await shootWindow(tester, 'vase-from-a-profile/03-modifier-stack');
    });

    testWidgets('04-material-texture-panel', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case2);
      await selectFirstObject(tester);
      await switchMode(tester, ModelerMode.material);
      await shootWindow(
        tester,
        'vase-from-a-profile/04-material-texture-panel',
      );
    });
  });

  group('a lit corner', () {
    const String case3 = 'case3.f3dproj';

    testWidgets('01-scene-viewport-gizmo', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case3);
      await selectFirstObject(tester);
      await shootWindow(tester, 'a-lit-corner/01-scene-viewport-gizmo');
    });

    testWidgets('02-scene-mode-panel', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case3);
      await switchMode(tester, ModelerMode.scene);
      await shootWindow(tester, 'a-lit-corner/02-scene-mode-panel');
    });

    testWidgets('04-export-two-nodes', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case3);
      await openExportScreen(tester);
      await shootWindow(tester, 'a-lit-corner/04-export-two-nodes');
    });
  });

  group('a character from a bare mesh', () {
    const String case4 = 'case4.f3dproj';

    testWidgets('04-pose-and-keys', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case4);
      await switchMode(tester, ModelerMode.animation);
      await shootWindow(tester, 'character-from-a-bare-mesh/04-pose-and-keys');
    });

    testWidgets('03-bend-slider', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case4);
      await switchMode(tester, ModelerMode.animation);
      await switchAnimationSubmode(tester, AnimationSubmode.weights);
      await shootWindow(tester, 'character-from-a-bare-mesh/03-bend-slider');
    });

    testWidgets('05-morphs-panel', (WidgetTester tester) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case4);
      await switchMode(tester, ModelerMode.animation);
      await switchAnimationSubmode(tester, AnimationSubmode.morphs);
      await shootWindow(tester, 'character-from-a-bare-mesh/05-morphs-panel');
    });
  });

  group('borrowing a walk', () {
    const String case5 = 'case5.f3dproj';

    testWidgets('01-clip-library and 02-bone-map-and-viewports', (
      WidgetTester tester,
    ) async {
      await launchModeller(tester, fonts: fonts);
      await openCase(tester, case5);
      await switchMode(tester, ModelerMode.animation);
      await switchAnimationSubmode(tester, AnimationSubmode.retarget);
      // One picture: the retarget screen is the clip library, the two
      // viewports and the bone map at once, which is what both placeholders
      // were standing in for either half of.
      await shootWindow(tester, 'borrowing-a-walk/01-clip-library');
    });
  });
}
