// GENERATED by tool/generate_compute_shaders.dart. Do not edit.
//
// Source: flutter3d.compute.json in package:flutter3d_shaders,
// through glslangValidator and naga.
library;

import 'src/webgpu_bundle_section.dart';
import 'src/webgpu_compute_stage.dart';

/// The engine's compute stages, in WGSL, with their bindings.
const Map<String, WebGpuComputeStage>
engineComputeShaders = <String, WebGpuComputeStage>{
  'PrefixSum': WebGpuComputeStage(
    wgsl: r'''
struct Values {
    values: array<u32>,
}

var<private> gl_LocalInvocationID_1: vec3<u32>;
@group(0) @binding(0) 
var<storage, read_write> values_buffer: Values;
var<workgroup> partial: array<u32, 256>;

fn main_1() {
    var i: u32;
    var base: u32;
    var s0_: u32;
    var s1_: u32;
    var s2_: u32;
    var s3_: u32;
    var offset: u32;
    var add: u32;
    var local: u32;
    var before: u32;
    var local_1: u32;

    let _e24 = gl_LocalInvocationID_1[0u];
    i = _e24;
    let _e25 = i;
    base = (_e25 * 4u);
    let _e27 = base;
    let _e30 = values_buffer.values[_e27];
    s0_ = _e30;
    let _e31 = s0_;
    let _e32 = base;
    let _e36 = values_buffer.values[(_e32 + 1u)];
    s1_ = (_e31 + _e36);
    let _e38 = s1_;
    let _e39 = base;
    let _e43 = values_buffer.values[(_e39 + 2u)];
    s2_ = (_e38 + _e43);
    let _e45 = s2_;
    let _e46 = base;
    let _e50 = values_buffer.values[(_e46 + 3u)];
    s3_ = (_e45 + _e50);
    let _e52 = i;
    let _e53 = s3_;
    partial[_e52] = _e53;
    workgroupBarrier();
    offset = 1u;
    loop {
        let _e55 = offset;
        if (_e55 < 256u) {
            let _e57 = i;
            let _e58 = offset;
            if (_e57 >= _e58) {
                let _e60 = i;
                let _e61 = offset;
                let _e64 = partial[(_e60 - _e61)];
                local = _e64;
            } else {
                local = 0u;
            }
            let _e65 = local;
            add = _e65;
            workgroupBarrier();
            let _e66 = i;
            let _e67 = add;
            let _e69 = partial[_e66];
            partial[_e66] = (_e69 + _e67);
            workgroupBarrier();
            continue;
        } else {
            break;
        }
        continuing {
            let _e72 = offset;
            offset = (_e72 << bitcast<u32>(1u));
        }
    }
    let _e75 = i;
    if (_e75 == 0u) {
        local_1 = 0u;
    } else {
        let _e77 = i;
        let _e80 = partial[(_e77 - 1u)];
        local_1 = _e80;
    }
    let _e81 = local_1;
    before = _e81;
    let _e82 = base;
    let _e83 = before;
    let _e84 = s0_;
    values_buffer.values[_e82] = (_e83 + _e84);
    let _e88 = base;
    let _e90 = before;
    let _e91 = s1_;
    values_buffer.values[(_e88 + 1u)] = (_e90 + _e91);
    let _e95 = base;
    let _e97 = before;
    let _e98 = s2_;
    values_buffer.values[(_e95 + 2u)] = (_e97 + _e98);
    let _e102 = base;
    let _e104 = before;
    let _e105 = s3_;
    values_buffer.values[(_e102 + 3u)] = (_e104 + _e105);
    return;
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(local_invocation_id) gl_LocalInvocationID: vec3<u32>) {
    gl_LocalInvocationID_1 = gl_LocalInvocationID;
    main_1();
}
''',
    workgroupSize: (256, 1, 1),
    storage: <WebGpuStorageBinding>[
      WebGpuStorageBinding(
        name: 'Values',
        group: 0,
        binding: 0,
        readOnly: false,
      ),
    ],
    blocks: <WebGpuBlock>[],
  ),
  'SplatSortCount': WebGpuComputeStage(
    wgsl: r'''
struct SortInfo {
    sort: vec4<f32>,
}

struct SortKeys {
    keys: array<u32>,
}

struct SortCounts {
    counts: array<u32>,
}

@group(0) @binding(2) 
var<uniform> sort_info: SortInfo;
var<private> gl_WorkGroupID_1: vec3<u32>;
var<private> gl_LocalInvocationID_1: vec3<u32>;
var<workgroup> digits: array<u32, 256>;
@group(0) @binding(0) 
var<storage> keys_buffer: SortKeys;
@group(0) @binding(1) 
var<storage, read_write> counts_buffer: SortCounts;

fn main_1() {
    var count: u32;
    var shift: u32;
    var tiles: u32;
    var tile: u32;
    var t: u32;
    var i: u32;
    var local: u32;
    var n: u32;
    var j: u32;

    let _e26 = sort_info.sort[0u];
    count = u32(_e26);
    let _e30 = sort_info.sort[1u];
    shift = u32(_e30);
    let _e34 = sort_info.sort[2u];
    tiles = u32(_e34);
    let _e37 = gl_WorkGroupID_1[0u];
    tile = _e37;
    let _e39 = gl_LocalInvocationID_1[0u];
    t = _e39;
    let _e40 = tile;
    let _e42 = t;
    i = ((_e40 * 256u) + _e42);
    let _e44 = t;
    let _e45 = i;
    let _e46 = count;
    if (_e45 < _e46) {
        let _e48 = i;
        let _e51 = keys_buffer.keys[_e48];
        let _e52 = shift;
        local = ((_e51 >> bitcast<u32>(_e52)) & 255u);
    } else {
        local = 256u;
    }
    let _e56 = local;
    digits[_e44] = _e56;
    workgroupBarrier();
    n = 0u;
    j = 0u;
    loop {
        let _e58 = j;
        if (_e58 < 256u) {
            let _e60 = j;
            let _e62 = digits[_e60];
            let _e63 = t;
            if (_e62 == _e63) {
                let _e65 = n;
                n = (_e65 + bitcast<u32>(1i));
            }
            continue;
        } else {
            break;
        }
        continuing {
            let _e68 = j;
            j = (_e68 + bitcast<u32>(1i));
        }
    }
    let _e71 = t;
    let _e72 = tiles;
    let _e74 = tile;
    let _e76 = n;
    counts_buffer.counts[((_e71 * _e72) + _e74)] = _e76;
    return;
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(workgroup_id) gl_WorkGroupID: vec3<u32>, @builtin(local_invocation_id) gl_LocalInvocationID: vec3<u32>) {
    gl_WorkGroupID_1 = gl_WorkGroupID;
    gl_LocalInvocationID_1 = gl_LocalInvocationID;
    main_1();
}
''',
    workgroupSize: (256, 1, 1),
    storage: <WebGpuStorageBinding>[
      WebGpuStorageBinding(
        name: 'SortKeys',
        group: 0,
        binding: 0,
        readOnly: true,
      ),
      WebGpuStorageBinding(
        name: 'SortCounts',
        group: 0,
        binding: 1,
        readOnly: false,
      ),
    ],
    blocks: <WebGpuBlock>[
      WebGpuBlock(
        name: 'SortInfo',
        group: 0,
        binding: 2,
        sizeInBytes: 16,
        members: <WebGpuBlockMember>[
          WebGpuBlockMember(name: 'sort', offsetInBytes: 0, sizeInBytes: 16),
        ],
      ),
    ],
  ),
  'SplatSortScan': WebGpuComputeStage(
    wgsl: r'''
struct SortInfo {
    sort: vec4<f32>,
}

struct SortCounts {
    counts: array<u32>,
}

@group(0) @binding(1) 
var<uniform> sort_info: SortInfo;
var<private> gl_LocalInvocationID_1: vec3<u32>;
@group(0) @binding(0) 
var<storage, read_write> counts_buffer: SortCounts;
var<workgroup> partial: array<u32, 256>;

fn main_1() {
    var total: u32;
    var t: u32;
    var carry: u32;
    var base: u32;
    var at: u32;
    var v0_: u32;
    var local: u32;
    var v1_: u32;
    var local_1: u32;
    var v2_: u32;
    var local_2: u32;
    var v3_: u32;
    var local_3: u32;
    var offset: u32;
    var add: u32;
    var local_4: u32;
    var before: u32;
    var local_5: u32;

    let _e35 = sort_info.sort[2u];
    total = (256u * u32(_e35));
    let _e39 = gl_LocalInvocationID_1[0u];
    t = _e39;
    carry = 0u;
    base = 0u;
    loop {
        let _e40 = base;
        let _e41 = total;
        if (_e40 < _e41) {
            let _e43 = base;
            let _e44 = t;
            at = (_e43 + (_e44 * 4u));
            let _e47 = at;
            let _e48 = total;
            if (_e47 < _e48) {
                let _e50 = at;
                let _e53 = counts_buffer.counts[_e50];
                local = _e53;
            } else {
                local = 0u;
            }
            let _e54 = local;
            v0_ = _e54;
            let _e55 = at;
            let _e57 = total;
            if ((_e55 + 1u) < _e57) {
                let _e59 = at;
                let _e63 = counts_buffer.counts[(_e59 + 1u)];
                local_1 = _e63;
            } else {
                local_1 = 0u;
            }
            let _e64 = local_1;
            v1_ = _e64;
            let _e65 = at;
            let _e67 = total;
            if ((_e65 + 2u) < _e67) {
                let _e69 = at;
                let _e73 = counts_buffer.counts[(_e69 + 2u)];
                local_2 = _e73;
            } else {
                local_2 = 0u;
            }
            let _e74 = local_2;
            v2_ = _e74;
            let _e75 = at;
            let _e77 = total;
            if ((_e75 + 3u) < _e77) {
                let _e79 = at;
                let _e83 = counts_buffer.counts[(_e79 + 3u)];
                local_3 = _e83;
            } else {
                local_3 = 0u;
            }
            let _e84 = local_3;
            v3_ = _e84;
            let _e85 = t;
            let _e86 = v0_;
            let _e87 = v1_;
            let _e89 = v2_;
            let _e91 = v3_;
            partial[_e85] = (((_e86 + _e87) + _e89) + _e91);
            workgroupBarrier();
            offset = 1u;
            loop {
                let _e94 = offset;
                if (_e94 < 256u) {
                    let _e96 = t;
                    let _e97 = offset;
                    if (_e96 >= _e97) {
                        let _e99 = t;
                        let _e100 = offset;
                        let _e103 = partial[(_e99 - _e100)];
                        local_4 = _e103;
                    } else {
                        local_4 = 0u;
                    }
                    let _e104 = local_4;
                    add = _e104;
                    workgroupBarrier();
                    let _e105 = t;
                    let _e106 = add;
                    let _e108 = partial[_e105];
                    partial[_e105] = (_e108 + _e106);
                    workgroupBarrier();
                    continue;
                } else {
                    break;
                }
                continuing {
                    let _e111 = offset;
                    offset = (_e111 << bitcast<u32>(1u));
                }
            }
            let _e114 = carry;
            let _e115 = t;
            if (_e115 == 0u) {
                local_5 = 0u;
            } else {
                let _e117 = t;
                let _e120 = partial[(_e117 - 1u)];
                local_5 = _e120;
            }
            let _e121 = local_5;
            before = (_e114 + _e121);
            let _e123 = at;
            let _e124 = total;
            if (_e123 < _e124) {
                let _e126 = at;
                let _e127 = before;
                counts_buffer.counts[_e126] = _e127;
            }
            let _e130 = at;
            let _e132 = total;
            if ((_e130 + 1u) < _e132) {
                let _e134 = at;
                let _e136 = before;
                let _e137 = v0_;
                counts_buffer.counts[(_e134 + 1u)] = (_e136 + _e137);
            }
            let _e141 = at;
            let _e143 = total;
            if ((_e141 + 2u) < _e143) {
                let _e145 = at;
                let _e147 = before;
                let _e148 = v0_;
                let _e150 = v1_;
                counts_buffer.counts[(_e145 + 2u)] = ((_e147 + _e148) + _e150);
            }
            let _e154 = at;
            let _e156 = total;
            if ((_e154 + 3u) < _e156) {
                let _e158 = at;
                let _e160 = before;
                let _e161 = v0_;
                let _e163 = v1_;
                let _e165 = v2_;
                counts_buffer.counts[(_e158 + 3u)] = (((_e160 + _e161) + _e163) + _e165);
            }
            let _e170 = partial[255i];
            let _e171 = carry;
            carry = (_e171 + _e170);
            workgroupBarrier();
            continue;
        } else {
            break;
        }
        continuing {
            let _e173 = base;
            base = (_e173 + 1024u);
        }
    }
    return;
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(local_invocation_id) gl_LocalInvocationID: vec3<u32>) {
    gl_LocalInvocationID_1 = gl_LocalInvocationID;
    main_1();
}
''',
    workgroupSize: (256, 1, 1),
    storage: <WebGpuStorageBinding>[
      WebGpuStorageBinding(
        name: 'SortCounts',
        group: 0,
        binding: 0,
        readOnly: false,
      ),
    ],
    blocks: <WebGpuBlock>[
      WebGpuBlock(
        name: 'SortInfo',
        group: 0,
        binding: 1,
        sizeInBytes: 16,
        members: <WebGpuBlockMember>[
          WebGpuBlockMember(name: 'sort', offsetInBytes: 0, sizeInBytes: 16),
        ],
      ),
    ],
  ),
  'SplatSortScatter': WebGpuComputeStage(
    wgsl: r'''
struct SortInfo {
    sort: vec4<f32>,
}

struct SortKeysIn {
    keys: array<u32>,
}

struct SortOffsets {
    offsets: array<u32>,
}

struct SortOrderIn {
    order: array<u32>,
}

struct SortOrderOut {
    order: array<u32>,
}

struct SortKeysOut {
    keys: array<u32>,
}

@group(0) @binding(5) 
var<uniform> sort_info: SortInfo;
var<private> gl_WorkGroupID_1: vec3<u32>;
var<private> gl_LocalInvocationID_1: vec3<u32>;
@group(0) @binding(0) 
var<storage> keys_in: SortKeysIn;
var<workgroup> digits: array<u32, 256>;
@group(0) @binding(2) 
var<storage> offsets_buffer: SortOffsets;
@group(0) @binding(1) 
var<storage> order_in: SortOrderIn;
@group(0) @binding(4) 
var<storage, read_write> order_out: SortOrderOut;
@group(0) @binding(3) 
var<storage, read_write> keys_out: SortKeysOut;

fn main_1() {
    var count: u32;
    var shift: u32;
    var tiles: u32;
    var mode: u32;
    var tile: u32;
    var t: u32;
    var i: u32;
    var live: bool;
    var key: u32;
    var local: u32;
    var digit: u32;
    var local_1: u32;
    var rank: u32;
    var j: u32;
    var slot: u32;
    var splat: u32;
    var local_2: u32;
    var k: u32;

    let _e40 = sort_info.sort[0u];
    count = u32(_e40);
    let _e44 = sort_info.sort[1u];
    shift = u32(_e44);
    let _e48 = sort_info.sort[2u];
    tiles = u32(_e48);
    let _e52 = sort_info.sort[3u];
    mode = u32(_e52);
    let _e55 = gl_WorkGroupID_1[0u];
    tile = _e55;
    let _e57 = gl_LocalInvocationID_1[0u];
    t = _e57;
    let _e58 = tile;
    let _e60 = t;
    i = ((_e58 * 256u) + _e60);
    let _e62 = i;
    let _e63 = count;
    live = (_e62 < _e63);
    let _e65 = live;
    if _e65 {
        let _e66 = i;
        let _e69 = keys_in.keys[_e66];
        local = _e69;
    } else {
        local = 0u;
    }
    let _e70 = local;
    key = _e70;
    let _e71 = live;
    if _e71 {
        let _e72 = key;
        let _e73 = shift;
        local_1 = ((_e72 >> bitcast<u32>(_e73)) & 255u);
    } else {
        local_1 = 256u;
    }
    let _e77 = local_1;
    digit = _e77;
    let _e78 = t;
    let _e79 = digit;
    digits[_e78] = _e79;
    workgroupBarrier();
    let _e81 = live;
    if _e81 {
        rank = 0u;
        j = 0u;
        loop {
            let _e82 = j;
            let _e83 = t;
            if (_e82 < _e83) {
                let _e85 = j;
                let _e87 = digits[_e85];
                let _e88 = digit;
                if (_e87 == _e88) {
                    let _e90 = rank;
                    rank = (_e90 + bitcast<u32>(1i));
                }
                continue;
            } else {
                break;
            }
            continuing {
                let _e93 = j;
                j = (_e93 + bitcast<u32>(1i));
            }
        }
        let _e96 = digit;
        let _e97 = tiles;
        let _e99 = tile;
        let _e103 = offsets_buffer.offsets[((_e96 * _e97) + _e99)];
        let _e104 = rank;
        slot = (_e103 + _e104);
        let _e106 = mode;
        if (_e106 == 0u) {
            let _e108 = i;
            local_2 = _e108;
        } else {
            let _e109 = i;
            let _e112 = order_in.order[_e109];
            local_2 = _e112;
        }
        let _e113 = local_2;
        splat = _e113;
        let _e114 = mode;
        if (_e114 == 2u) {
            k = 0u;
            loop {
                let _e116 = k;
                if (_e116 < 6u) {
                    let _e118 = slot;
                    let _e120 = k;
                    let _e122 = splat;
                    let _e124 = k;
                    order_out.order[((_e118 * 6u) + _e120)] = ((_e122 * 6u) + _e124);
                    continue;
                } else {
                    break;
                }
                continuing {
                    let _e128 = k;
                    k = (_e128 + bitcast<u32>(1i));
                }
            }
        } else {
            let _e131 = slot;
            let _e132 = key;
            keys_out.keys[_e131] = _e132;
            let _e135 = slot;
            let _e136 = splat;
            order_out.order[_e135] = _e136;
        }
    }
    return;
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(workgroup_id) gl_WorkGroupID: vec3<u32>, @builtin(local_invocation_id) gl_LocalInvocationID: vec3<u32>) {
    gl_WorkGroupID_1 = gl_WorkGroupID;
    gl_LocalInvocationID_1 = gl_LocalInvocationID;
    main_1();
}
''',
    workgroupSize: (256, 1, 1),
    storage: <WebGpuStorageBinding>[
      WebGpuStorageBinding(
        name: 'SortKeysIn',
        group: 0,
        binding: 0,
        readOnly: true,
      ),
      WebGpuStorageBinding(
        name: 'SortOrderIn',
        group: 0,
        binding: 1,
        readOnly: true,
      ),
      WebGpuStorageBinding(
        name: 'SortOffsets',
        group: 0,
        binding: 2,
        readOnly: true,
      ),
      WebGpuStorageBinding(
        name: 'SortKeysOut',
        group: 0,
        binding: 3,
        readOnly: false,
      ),
      WebGpuStorageBinding(
        name: 'SortOrderOut',
        group: 0,
        binding: 4,
        readOnly: false,
      ),
    ],
    blocks: <WebGpuBlock>[
      WebGpuBlock(
        name: 'SortInfo',
        group: 0,
        binding: 5,
        sizeInBytes: 16,
        members: <WebGpuBlockMember>[
          WebGpuBlockMember(name: 'sort', offsetInBytes: 0, sizeInBytes: 16),
        ],
      ),
    ],
  ),
};
