// Generated by tool/gen_core.dart from csrc/include/f3d_physics.h: do not edit.
//
// The core's calls natively: through dart:ffi, a pointer an address.
// ignore_for_file: non_constant_identifier_names
@DefaultAsset('package:flutter3d_physics_native/src/core/calls_native.g.dart')
library;

import 'dart:ffi';

@Native<Uint32 Function()>(symbol: 'f3d_abi_version', isLeaf: true)
external int _f3d_abi_version();
int f3d_abi_version() => _f3d_abi_version();

@Native<Uint32 Function()>(symbol: 'f3d_real_bytes', isLeaf: true)
external int _f3d_real_bytes();
int f3d_real_bytes() => _f3d_real_bytes();

@Native<Pointer<Void> Function(Uint32)>(symbol: 'f3d_buffer_alloc')
external Pointer<Void> _f3d_buffer_alloc(int bytes);
int f3d_buffer_alloc(int bytes) => _f3d_buffer_alloc(bytes).address;

@Native<Void Function(Pointer<Void>)>(symbol: 'f3d_buffer_free')
external void _f3d_buffer_free(Pointer<Void> buffer);
void f3d_buffer_free(int buffer) =>
    _f3d_buffer_free(Pointer.fromAddress(buffer));

@Native<Pointer<Void> Function()>(symbol: 'f3d_world_create')
external Pointer<Void> _f3d_world_create();
int f3d_world_create() => _f3d_world_create().address;

@Native<Void Function(Pointer<Void>)>(symbol: 'f3d_world_destroy')
external void _f3d_world_destroy(Pointer<Void> world);
void f3d_world_destroy(int world) =>
    _f3d_world_destroy(Pointer.fromAddress(world));

@Native<Void Function(Pointer<Void>, Float, Float, Float)>(
  symbol: 'f3d_world_set_gravity',
  isLeaf: true,
)
external void _f3d_world_set_gravity(
  Pointer<Void> world,
  double x,
  double y,
  double z,
);
void f3d_world_set_gravity(int world, double x, double y, double z) =>
    _f3d_world_set_gravity(Pointer.fromAddress(world), x, y, z);

@Native<Void Function(Pointer<Void>, Pointer<Void>)>(
  symbol: 'f3d_world_get_gravity',
  isLeaf: true,
)
external void _f3d_world_get_gravity(Pointer<Void> world, Pointer<Void> out);
void f3d_world_get_gravity(int world, int out) => _f3d_world_get_gravity(
  Pointer.fromAddress(world),
  Pointer.fromAddress(out),
);

@Native<Int32 Function(Pointer<Void>, Float, Float)>(
  symbol: 'f3d_world_set_air',
  isLeaf: true,
)
external int _f3d_world_set_air(
  Pointer<Void> world,
  double temperature,
  double density,
);
int f3d_world_set_air(int world, double temperature, double density) =>
    _f3d_world_set_air(Pointer.fromAddress(world), temperature, density);

@Native<Void Function(Pointer<Void>, Pointer<Void>)>(
  symbol: 'f3d_world_get_air',
  isLeaf: true,
)
external void _f3d_world_get_air(Pointer<Void> world, Pointer<Void> out);
void f3d_world_get_air(int world, int out) =>
    _f3d_world_get_air(Pointer.fromAddress(world), Pointer.fromAddress(out));

@Native<Void Function(Pointer<Void>, Float, Float, Float)>(
  symbol: 'f3d_world_set_wind',
  isLeaf: true,
)
external void _f3d_world_set_wind(
  Pointer<Void> world,
  double x,
  double y,
  double z,
);
void f3d_world_set_wind(int world, double x, double y, double z) =>
    _f3d_world_set_wind(Pointer.fromAddress(world), x, y, z);

@Native<
  Int32 Function(
    Pointer<Void>,
    Float,
    Float,
    Float,
    Float,
    Uint32,
    Uint32,
    Uint32,
    Pointer<Void>,
  )
>(symbol: 'f3d_world_set_wind_grid', isLeaf: true)
external int _f3d_world_set_wind_grid(
  Pointer<Void> world,
  double ox,
  double oy,
  double oz,
  double cell,
  int nx,
  int ny,
  int nz,
  Pointer<Void> velocities,
);
int f3d_world_set_wind_grid(
  int world,
  double ox,
  double oy,
  double oz,
  double cell,
  int nx,
  int ny,
  int nz,
  int velocities,
) => _f3d_world_set_wind_grid(
  Pointer.fromAddress(world),
  ox,
  oy,
  oz,
  cell,
  nx,
  ny,
  nz,
  Pointer.fromAddress(velocities),
);

@Native<Void Function(Pointer<Void>, Float, Float, Float, Pointer<Void>)>(
  symbol: 'f3d_world_sample_wind',
  isLeaf: true,
)
external void _f3d_world_sample_wind(
  Pointer<Void> world,
  double x,
  double y,
  double z,
  Pointer<Void> out,
);
void f3d_world_sample_wind(int world, double x, double y, double z, int out) =>
    _f3d_world_sample_wind(
      Pointer.fromAddress(world),
      x,
      y,
      z,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Float, Float)>(
  symbol: 'f3d_world_set_sleep',
  isLeaf: true,
)
external int _f3d_world_set_sleep(
  Pointer<Void> world,
  double speed,
  double time,
);
int f3d_world_set_sleep(int world, double speed, double time) =>
    _f3d_world_set_sleep(Pointer.fromAddress(world), speed, time);

@Native<Void Function(Pointer<Void>, Pointer<Void>)>(
  symbol: 'f3d_world_get_origin',
  isLeaf: true,
)
external void _f3d_world_get_origin(Pointer<Void> world, Pointer<Void> out);
void f3d_world_get_origin(int world, int out) =>
    _f3d_world_get_origin(Pointer.fromAddress(world), Pointer.fromAddress(out));

@Native<Void Function(Pointer<Void>, Double, Double, Double)>(
  symbol: 'f3d_world_shift_origin',
  isLeaf: true,
)
external void _f3d_world_shift_origin(
  Pointer<Void> world,
  double dx,
  double dy,
  double dz,
);
void f3d_world_shift_origin(int world, double dx, double dy, double dz) =>
    _f3d_world_shift_origin(Pointer.fromAddress(world), dx, dy, dz);

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_create_hull',
)
external int _f3d_world_create_hull(
  Pointer<Void> world,
  Pointer<Void> points,
  int count,
);
int f3d_world_create_hull(int world, int points, int count) =>
    _f3d_world_create_hull(
      Pointer.fromAddress(world),
      Pointer.fromAddress(points),
      count,
    );

@Native<
  Uint32 Function(Pointer<Void>, Pointer<Void>, Uint32, Pointer<Void>, Uint32)
>(symbol: 'f3d_world_create_mesh')
external int _f3d_world_create_mesh(
  Pointer<Void> world,
  Pointer<Void> vertices,
  int vertexCount,
  Pointer<Void> indices,
  int triangleCount,
);
int f3d_world_create_mesh(
  int world,
  int vertices,
  int vertexCount,
  int indices,
  int triangleCount,
) => _f3d_world_create_mesh(
  Pointer.fromAddress(world),
  Pointer.fromAddress(vertices),
  vertexCount,
  Pointer.fromAddress(indices),
  triangleCount,
);

@Native<
  Uint32 Function(
    Pointer<Void>,
    Pointer<Void>,
    Pointer<Void>,
    Pointer<Void>,
    Uint32,
  )
>(symbol: 'f3d_world_create_compound')
external int _f3d_world_create_compound(
  Pointer<Void> world,
  Pointer<Void> kinds,
  Pointer<Void> hulls,
  Pointer<Void> parts,
  int count,
);
int f3d_world_create_compound(
  int world,
  int kinds,
  int hulls,
  int parts,
  int count,
) => _f3d_world_create_compound(
  Pointer.fromAddress(world),
  Pointer.fromAddress(kinds),
  Pointer.fromAddress(hulls),
  Pointer.fromAddress(parts),
  count,
);

@Native<Int32 Function(Pointer<Void>, Uint32, Pointer<Void>)>(
  symbol: 'f3d_world_get_compound_offset',
  isLeaf: true,
)
external int _f3d_world_get_compound_offset(
  Pointer<Void> world,
  int compound,
  Pointer<Void> out,
);
int f3d_world_get_compound_offset(int world, int compound, int out) =>
    _f3d_world_get_compound_offset(
      Pointer.fromAddress(world),
      compound,
      Pointer.fromAddress(out),
    );

@Native<Uint32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_compound_part_count',
  isLeaf: true,
)
external int _f3d_world_compound_part_count(Pointer<Void> world, int compound);
int f3d_world_compound_part_count(int world, int compound) =>
    _f3d_world_compound_part_count(Pointer.fromAddress(world), compound);

@Native<Uint32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_mesh_triangle_count',
  isLeaf: true,
)
external int _f3d_world_mesh_triangle_count(Pointer<Void> world, int mesh);
int f3d_world_mesh_triangle_count(int world, int mesh) =>
    _f3d_world_mesh_triangle_count(Pointer.fromAddress(world), mesh);

@Native<Uint32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_mesh_internal_edges',
  isLeaf: true,
)
external int _f3d_world_mesh_internal_edges(Pointer<Void> world, int mesh);
int f3d_world_mesh_internal_edges(int world, int mesh) =>
    _f3d_world_mesh_internal_edges(Pointer.fromAddress(world), mesh);

@Native<Int32 Function(Pointer<Void>, Uint32, Pointer<Void>)>(
  symbol: 'f3d_world_get_hull_offset',
  isLeaf: true,
)
external int _f3d_world_get_hull_offset(
  Pointer<Void> world,
  int hull,
  Pointer<Void> out,
);
int f3d_world_get_hull_offset(int world, int hull, int out) =>
    _f3d_world_get_hull_offset(
      Pointer.fromAddress(world),
      hull,
      Pointer.fromAddress(out),
    );

@Native<Uint32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_hull_vertex_count',
  isLeaf: true,
)
external int _f3d_world_hull_vertex_count(Pointer<Void> world, int hull);
int f3d_world_hull_vertex_count(int world, int hull) =>
    _f3d_world_hull_vertex_count(Pointer.fromAddress(world), hull);

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_world_body_count',
  isLeaf: true,
)
external int _f3d_world_body_count(Pointer<Void> world);
int f3d_world_body_count(int world) =>
    _f3d_world_body_count(Pointer.fromAddress(world));

@Native<Void Function(Pointer<Void>, Float)>(symbol: 'f3d_world_step')
external void _f3d_world_step(Pointer<Void> world, double dt);
void f3d_world_step(int world, double dt) =>
    _f3d_world_step(Pointer.fromAddress(world), dt);

@Native<Int32 Function(Pointer<Void>, Uint32)>(symbol: 'f3d_world_set_threads')
external int _f3d_world_set_threads(Pointer<Void> world, int threads);
int f3d_world_set_threads(int world, int threads) =>
    _f3d_world_set_threads(Pointer.fromAddress(world), threads);

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_world_threads',
  isLeaf: true,
)
external int _f3d_world_threads(Pointer<Void> world);
int f3d_world_threads(int world) =>
    _f3d_world_threads(Pointer.fromAddress(world));

@Native<Int32 Function(Pointer<Void>, Int32)>(
  symbol: 'f3d_world_set_fast',
  isLeaf: true,
)
external int _f3d_world_set_fast(Pointer<Void> world, int fast);
int f3d_world_set_fast(int world, int fast) =>
    _f3d_world_set_fast(Pointer.fromAddress(world), fast);

@Native<Int32 Function(Pointer<Void>)>(symbol: 'f3d_world_fast', isLeaf: true)
external int _f3d_world_fast(Pointer<Void> world);
int f3d_world_fast(int world) => _f3d_world_fast(Pointer.fromAddress(world));

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_read_transforms',
  isLeaf: true,
)
external int _f3d_world_read_transforms(
  Pointer<Void> world,
  Pointer<Void> transforms,
  Pointer<Void> handles,
  int capacity,
);
int f3d_world_read_transforms(
  int world,
  int transforms,
  int handles,
  int capacity,
) => _f3d_world_read_transforms(
  Pointer.fromAddress(world),
  Pointer.fromAddress(transforms),
  Pointer.fromAddress(handles),
  capacity,
);

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_read_fires',
  isLeaf: true,
)
external int _f3d_world_read_fires(
  Pointer<Void> world,
  Pointer<Void> fires,
  Pointer<Void> handles,
  int capacity,
);
int f3d_world_read_fires(int world, int fires, int handles, int capacity) =>
    _f3d_world_read_fires(
      Pointer.fromAddress(world),
      Pointer.fromAddress(fires),
      Pointer.fromAddress(handles),
      capacity,
    );

@Native<
  Uint32 Function(
    Pointer<Void>,
    Pointer<Void>,
    Pointer<Void>,
    Pointer<Void>,
    Uint32,
  )
>(symbol: 'f3d_world_read_events', isLeaf: true)
external int _f3d_world_read_events(
  Pointer<Void> world,
  Pointer<Void> bodies,
  Pointer<Void> others,
  Pointer<Void> kinds,
  int capacity,
);
int f3d_world_read_events(
  int world,
  int bodies,
  int others,
  int kinds,
  int capacity,
) => _f3d_world_read_events(
  Pointer.fromAddress(world),
  Pointer.fromAddress(bodies),
  Pointer.fromAddress(others),
  Pointer.fromAddress(kinds),
  capacity,
);

@Native<Int32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_set_substeps',
  isLeaf: true,
)
external int _f3d_world_set_substeps(Pointer<Void> world, int substeps);
int f3d_world_set_substeps(int world, int substeps) =>
    _f3d_world_set_substeps(Pointer.fromAddress(world), substeps);

@Native<Int32 Function(Pointer<Void>, Int32)>(
  symbol: 'f3d_world_set_speculative',
  isLeaf: true,
)
external int _f3d_world_set_speculative(Pointer<Void> world, int enabled);
int f3d_world_set_speculative(int world, int enabled) =>
    _f3d_world_set_speculative(Pointer.fromAddress(world), enabled);

@Native<Int32 Function(Pointer<Void>, Float)>(
  symbol: 'f3d_world_set_contact_margin',
  isLeaf: true,
)
external int _f3d_world_set_contact_margin(Pointer<Void> world, double margin);
int f3d_world_set_contact_margin(int world, double margin) =>
    _f3d_world_set_contact_margin(Pointer.fromAddress(world), margin);

@Native<
  Uint32 Function(
    Pointer<Void>,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Pointer<Void>,
    Uint32,
  )
>(symbol: 'f3d_world_query_box', isLeaf: true)
external int _f3d_world_query_box(
  Pointer<Void> world,
  double lx,
  double ly,
  double lz,
  double hx,
  double hy,
  double hz,
  Pointer<Void> out,
  int capacity,
);
int f3d_world_query_box(
  int world,
  double lx,
  double ly,
  double lz,
  double hx,
  double hy,
  double hz,
  int out,
  int capacity,
) => _f3d_world_query_box(
  Pointer.fromAddress(world),
  lx,
  ly,
  lz,
  hx,
  hy,
  hz,
  Pointer.fromAddress(out),
  capacity,
);

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_world_contact_count',
  isLeaf: true,
)
external int _f3d_world_contact_count(Pointer<Void> world);
int f3d_world_contact_count(int world) =>
    _f3d_world_contact_count(Pointer.fromAddress(world));

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_read_contacts',
  isLeaf: true,
)
external int _f3d_world_read_contacts(
  Pointer<Void> world,
  Pointer<Void> contacts,
  Pointer<Void> pairs,
  int capacity,
);
int f3d_world_read_contacts(int world, int contacts, int pairs, int capacity) =>
    _f3d_world_read_contacts(
      Pointer.fromAddress(world),
      Pointer.fromAddress(contacts),
      Pointer.fromAddress(pairs),
      capacity,
    );

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_world_events_dropped',
  isLeaf: true,
)
external int _f3d_world_events_dropped(Pointer<Void> world);
int f3d_world_events_dropped(int world) =>
    _f3d_world_events_dropped(Pointer.fromAddress(world));

@Native<
  Uint32 Function(
    Pointer<Void>,
    Uint64,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
  )
>(symbol: 'f3d_vehicle_create')
external int _f3d_vehicle_create(
  Pointer<Void> world,
  int chassis,
  double ux,
  double uy,
  double uz,
  double fx,
  double fy,
  double fz,
);
int f3d_vehicle_create(
  int world,
  int chassis,
  double ux,
  double uy,
  double uz,
  double fx,
  double fy,
  double fz,
) => _f3d_vehicle_create(
  Pointer.fromAddress(world),
  chassis,
  ux,
  uy,
  uz,
  fx,
  fy,
  fz,
);

@Native<Int32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_vehicle_destroy',
  isLeaf: true,
)
external int _f3d_vehicle_destroy(Pointer<Void> world, int vehicle);
int f3d_vehicle_destroy(int world, int vehicle) =>
    _f3d_vehicle_destroy(Pointer.fromAddress(world), vehicle);

@Native<Int32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_vehicle_is_valid',
  isLeaf: true,
)
external int _f3d_vehicle_is_valid(Pointer<Void> world, int vehicle);
int f3d_vehicle_is_valid(int world, int vehicle) =>
    _f3d_vehicle_is_valid(Pointer.fromAddress(world), vehicle);

@Native<Int32 Function(Pointer<Void>, Uint32, Pointer<Void>)>(
  symbol: 'f3d_vehicle_add_wheel',
  isLeaf: true,
)
external int _f3d_vehicle_add_wheel(
  Pointer<Void> world,
  int vehicle,
  Pointer<Void> wheel,
);
int f3d_vehicle_add_wheel(int world, int vehicle, int wheel) =>
    _f3d_vehicle_add_wheel(
      Pointer.fromAddress(world),
      vehicle,
      Pointer.fromAddress(wheel),
    );

@Native<Int32 Function(Pointer<Void>, Uint32, Uint32, Float, Float, Float)>(
  symbol: 'f3d_vehicle_set_wheel',
  isLeaf: true,
)
external int _f3d_vehicle_set_wheel(
  Pointer<Void> world,
  int vehicle,
  int wheel,
  double steer,
  double drive,
  double brake,
);
int f3d_vehicle_set_wheel(
  int world,
  int vehicle,
  int wheel,
  double steer,
  double drive,
  double brake,
) => _f3d_vehicle_set_wheel(
  Pointer.fromAddress(world),
  vehicle,
  wheel,
  steer,
  drive,
  brake,
);

@Native<Uint32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_vehicle_wheel_count',
  isLeaf: true,
)
external int _f3d_vehicle_wheel_count(Pointer<Void> world, int vehicle);
int f3d_vehicle_wheel_count(int world, int vehicle) =>
    _f3d_vehicle_wheel_count(Pointer.fromAddress(world), vehicle);

@Native<Uint32 Function(Pointer<Void>, Uint32, Pointer<Void>, Uint32)>(
  symbol: 'f3d_vehicle_read_wheels',
  isLeaf: true,
)
external int _f3d_vehicle_read_wheels(
  Pointer<Void> world,
  int vehicle,
  Pointer<Void> out,
  int capacity,
);
int f3d_vehicle_read_wheels(int world, int vehicle, int out, int capacity) =>
    _f3d_vehicle_read_wheels(
      Pointer.fromAddress(world),
      vehicle,
      Pointer.fromAddress(out),
      capacity,
    );

@Native<
  Uint32 Function(
    Pointer<Void>,
    Uint32,
    Uint32,
    Float,
    Float,
    Float,
    Float,
    Pointer<Void>,
  )
>(symbol: 'f3d_water_create')
external int _f3d_water_create(
  Pointer<Void> world,
  int nx,
  int nz,
  double cell,
  double ox,
  double oy,
  double oz,
  Pointer<Void> ground,
);
int f3d_water_create(
  int world,
  int nx,
  int nz,
  double cell,
  double ox,
  double oy,
  double oz,
  int ground,
) => _f3d_water_create(
  Pointer.fromAddress(world),
  nx,
  nz,
  cell,
  ox,
  oy,
  oz,
  Pointer.fromAddress(ground),
);

@Native<Int32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_water_destroy',
  isLeaf: true,
)
external int _f3d_water_destroy(Pointer<Void> world, int water);
int f3d_water_destroy(int world, int water) =>
    _f3d_water_destroy(Pointer.fromAddress(world), water);

@Native<Int32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_water_is_valid',
  isLeaf: true,
)
external int _f3d_water_is_valid(Pointer<Void> world, int water);
int f3d_water_is_valid(int world, int water) =>
    _f3d_water_is_valid(Pointer.fromAddress(world), water);

@Native<Int32 Function(Pointer<Void>, Uint32, Pointer<Void>)>(
  symbol: 'f3d_water_set_ground',
  isLeaf: true,
)
external int _f3d_water_set_ground(
  Pointer<Void> world,
  int water,
  Pointer<Void> ground,
);
int f3d_water_set_ground(int world, int water, int ground) =>
    _f3d_water_set_ground(
      Pointer.fromAddress(world),
      water,
      Pointer.fromAddress(ground),
    );

@Native<
  Int32 Function(Pointer<Void>, Uint32, Float, Float, Float, Float, Float)
>(symbol: 'f3d_water_fill', isLeaf: true)
external int _f3d_water_fill(
  Pointer<Void> world,
  int water,
  double x0,
  double z0,
  double x1,
  double z1,
  double level,
);
int f3d_water_fill(
  int world,
  int water,
  double x0,
  double z0,
  double x1,
  double z1,
  double level,
) => _f3d_water_fill(Pointer.fromAddress(world), water, x0, z0, x1, z1, level);

@Native<Int32 Function(Pointer<Void>, Uint32, Float, Float, Float, Float)>(
  symbol: 'f3d_water_pour',
  isLeaf: true,
)
external int _f3d_water_pour(
  Pointer<Void> world,
  int water,
  double x,
  double z,
  double radius,
  double volume,
);
int f3d_water_pour(
  int world,
  int water,
  double x,
  double z,
  double radius,
  double volume,
) => _f3d_water_pour(Pointer.fromAddress(world), water, x, z, radius, volume);

@Native<
  Int32 Function(Pointer<Void>, Uint32, Uint32, Float, Float, Float, Float)
>(symbol: 'f3d_water_set_source', isLeaf: true)
external int _f3d_water_set_source(
  Pointer<Void> world,
  int water,
  int index,
  double x,
  double z,
  double radius,
  double rate,
);
int f3d_water_set_source(
  int world,
  int water,
  int index,
  double x,
  double z,
  double radius,
  double rate,
) => _f3d_water_set_source(
  Pointer.fromAddress(world),
  water,
  index,
  x,
  z,
  radius,
  rate,
);

@Native<Int32 Function(Pointer<Void>, Uint32, Float, Int32)>(
  symbol: 'f3d_water_set_bed',
  isLeaf: true,
)
external int _f3d_water_set_bed(
  Pointer<Void> world,
  int water,
  double roughness,
  int openEdges,
);
int f3d_water_set_bed(int world, int water, double roughness, int openEdges) =>
    _f3d_water_set_bed(Pointer.fromAddress(world), water, roughness, openEdges);

@Native<Int32 Function(Pointer<Void>, Uint32, Float, Float, Pointer<Void>)>(
  symbol: 'f3d_water_sample',
  isLeaf: true,
)
external int _f3d_water_sample(
  Pointer<Void> world,
  int water,
  double x,
  double z,
  Pointer<Void> out,
);
int f3d_water_sample(int world, int water, double x, double z, int out) =>
    _f3d_water_sample(
      Pointer.fromAddress(world),
      water,
      x,
      z,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint32, Pointer<Void>, Pointer<Void>)>(
  symbol: 'f3d_water_read',
  isLeaf: true,
)
external int _f3d_water_read(
  Pointer<Void> world,
  int water,
  Pointer<Void> surface,
  Pointer<Void> depth,
);
int f3d_water_read(int world, int water, int surface, int depth) =>
    _f3d_water_read(
      Pointer.fromAddress(world),
      water,
      Pointer.fromAddress(surface),
      Pointer.fromAddress(depth),
    );

@Native<Int32 Function(Pointer<Void>, Uint32, Pointer<Void>)>(
  symbol: 'f3d_water_read_flow',
  isLeaf: true,
)
external int _f3d_water_read_flow(
  Pointer<Void> world,
  int water,
  Pointer<Void> velocity,
);
int f3d_water_read_flow(int world, int water, int velocity) =>
    _f3d_water_read_flow(
      Pointer.fromAddress(world),
      water,
      Pointer.fromAddress(velocity),
    );

@Native<Int32 Function(Pointer<Void>, Uint32, Pointer<Void>, Pointer<Void>)>(
  symbol: 'f3d_water_volume',
  isLeaf: true,
)
external int _f3d_water_volume(
  Pointer<Void> world,
  int water,
  Pointer<Void> held,
  Pointer<Void> lost,
);
int f3d_water_volume(int world, int water, int held, int lost) =>
    _f3d_water_volume(
      Pointer.fromAddress(world),
      water,
      Pointer.fromAddress(held),
      Pointer.fromAddress(lost),
    );

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_read_spray',
  isLeaf: true,
)
external int _f3d_world_read_spray(
  Pointer<Void> world,
  Pointer<Void> spray,
  Pointer<Void> waters,
  int capacity,
);
int f3d_world_read_spray(int world, int spray, int waters, int capacity) =>
    _f3d_world_read_spray(
      Pointer.fromAddress(world),
      Pointer.fromAddress(spray),
      Pointer.fromAddress(waters),
      capacity,
    );

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_read_bubbles',
  isLeaf: true,
)
external int _f3d_world_read_bubbles(
  Pointer<Void> world,
  Pointer<Void> bubbles,
  Pointer<Void> waters,
  int capacity,
);
int f3d_world_read_bubbles(int world, int bubbles, int waters, int capacity) =>
    _f3d_world_read_bubbles(
      Pointer.fromAddress(world),
      Pointer.fromAddress(bubbles),
      Pointer.fromAddress(waters),
      capacity,
    );

@Native<Uint32 Function(Pointer<Void>, Uint64)>(symbol: 'f3d_multibody_create')
external int _f3d_multibody_create(Pointer<Void> world, int root);
int f3d_multibody_create(int world, int root) =>
    _f3d_multibody_create(Pointer.fromAddress(world), root);

@Native<Int32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_multibody_destroy',
  isLeaf: true,
)
external int _f3d_multibody_destroy(Pointer<Void> world, int multibody);
int f3d_multibody_destroy(int world, int multibody) =>
    _f3d_multibody_destroy(Pointer.fromAddress(world), multibody);

@Native<Int32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_multibody_is_valid',
  isLeaf: true,
)
external int _f3d_multibody_is_valid(Pointer<Void> world, int multibody);
int f3d_multibody_is_valid(int world, int multibody) =>
    _f3d_multibody_is_valid(Pointer.fromAddress(world), multibody);

@Native<
  Int32 Function(
    Pointer<Void>,
    Uint32,
    Uint32,
    Uint64,
    Int32,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
  )
>(symbol: 'f3d_multibody_add_link')
external int _f3d_multibody_add_link(
  Pointer<Void> world,
  int multibody,
  int parent,
  int body,
  int type,
  double ax,
  double ay,
  double az,
  double ux,
  double uy,
  double uz,
);
int f3d_multibody_add_link(
  int world,
  int multibody,
  int parent,
  int body,
  int type,
  double ax,
  double ay,
  double az,
  double ux,
  double uy,
  double uz,
) => _f3d_multibody_add_link(
  Pointer.fromAddress(world),
  multibody,
  parent,
  body,
  type,
  ax,
  ay,
  az,
  ux,
  uy,
  uz,
);

@Native<Int32 Function(Pointer<Void>, Uint32, Uint32, Int32, Float, Float)>(
  symbol: 'f3d_multibody_set_limits',
  isLeaf: true,
)
external int _f3d_multibody_set_limits(
  Pointer<Void> world,
  int multibody,
  int link,
  int enabled,
  double lower,
  double upper,
);
int f3d_multibody_set_limits(
  int world,
  int multibody,
  int link,
  int enabled,
  double lower,
  double upper,
) => _f3d_multibody_set_limits(
  Pointer.fromAddress(world),
  multibody,
  link,
  enabled,
  lower,
  upper,
);

@Native<Int32 Function(Pointer<Void>, Uint32, Uint32, Int32, Float, Float)>(
  symbol: 'f3d_multibody_set_motor',
  isLeaf: true,
)
external int _f3d_multibody_set_motor(
  Pointer<Void> world,
  int multibody,
  int link,
  int enabled,
  double speed,
  double force,
);
int f3d_multibody_set_motor(
  int world,
  int multibody,
  int link,
  int enabled,
  double speed,
  double force,
) => _f3d_multibody_set_motor(
  Pointer.fromAddress(world),
  multibody,
  link,
  enabled,
  speed,
  force,
);

@Native<Int32 Function(Pointer<Void>, Uint32, Uint32, Int32, Float, Float)>(
  symbol: 'f3d_multibody_set_cone',
  isLeaf: true,
)
external int _f3d_multibody_set_cone(
  Pointer<Void> world,
  int multibody,
  int link,
  int enabled,
  double swing,
  double twist,
);
int f3d_multibody_set_cone(
  int world,
  int multibody,
  int link,
  int enabled,
  double swing,
  double twist,
) => _f3d_multibody_set_cone(
  Pointer.fromAddress(world),
  multibody,
  link,
  enabled,
  swing,
  twist,
);

@Native<Uint32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_multibody_link_count',
  isLeaf: true,
)
external int _f3d_multibody_link_count(Pointer<Void> world, int multibody);
int f3d_multibody_link_count(int world, int multibody) =>
    _f3d_multibody_link_count(Pointer.fromAddress(world), multibody);

@Native<Uint32 Function(Pointer<Void>, Uint32)>(
  symbol: 'f3d_multibody_dof_count',
  isLeaf: true,
)
external int _f3d_multibody_dof_count(Pointer<Void> world, int multibody);
int f3d_multibody_dof_count(int world, int multibody) =>
    _f3d_multibody_dof_count(Pointer.fromAddress(world), multibody);

@Native<Int32 Function(Pointer<Void>, Uint32, Uint32, Pointer<Void>)>(
  symbol: 'f3d_multibody_read_joint',
  isLeaf: true,
)
external int _f3d_multibody_read_joint(
  Pointer<Void> world,
  int multibody,
  int link,
  Pointer<Void> out,
);
int f3d_multibody_read_joint(int world, int multibody, int link, int out) =>
    _f3d_multibody_read_joint(
      Pointer.fromAddress(world),
      multibody,
      link,
      Pointer.fromAddress(out),
    );

@Native<
  Uint64 Function(
    Pointer<Void>,
    Int32,
    Uint64,
    Uint64,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
  )
>(symbol: 'f3d_joint_create')
external int _f3d_joint_create(
  Pointer<Void> world,
  int type,
  int a,
  int b,
  double ax,
  double ay,
  double az,
  double ux,
  double uy,
  double uz,
);
int f3d_joint_create(
  int world,
  int type,
  int a,
  int b,
  double ax,
  double ay,
  double az,
  double ux,
  double uy,
  double uz,
) => _f3d_joint_create(
  Pointer.fromAddress(world),
  type,
  a,
  b,
  ax,
  ay,
  az,
  ux,
  uy,
  uz,
);

@Native<
  Uint64 Function(
    Pointer<Void>,
    Uint64,
    Uint64,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
  )
>(symbol: 'f3d_joint_create_distance')
external int _f3d_joint_create_distance(
  Pointer<Void> world,
  int a,
  int b,
  double ax,
  double ay,
  double az,
  double bx,
  double by,
  double bz,
);
int f3d_joint_create_distance(
  int world,
  int a,
  int b,
  double ax,
  double ay,
  double az,
  double bx,
  double by,
  double bz,
) => _f3d_joint_create_distance(
  Pointer.fromAddress(world),
  a,
  b,
  ax,
  ay,
  az,
  bx,
  by,
  bz,
);

@Native<Int32 Function(Pointer<Void>, Uint64)>(symbol: 'f3d_joint_destroy')
external int _f3d_joint_destroy(Pointer<Void> world, int joint);
int f3d_joint_destroy(int world, int joint) =>
    _f3d_joint_destroy(Pointer.fromAddress(world), joint);

@Native<Int32 Function(Pointer<Void>, Uint64)>(
  symbol: 'f3d_joint_is_valid',
  isLeaf: true,
)
external int _f3d_joint_is_valid(Pointer<Void> world, int joint);
int f3d_joint_is_valid(int world, int joint) =>
    _f3d_joint_is_valid(Pointer.fromAddress(world), joint);

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_world_joint_count',
  isLeaf: true,
)
external int _f3d_world_joint_count(Pointer<Void> world);
int f3d_world_joint_count(int world) =>
    _f3d_world_joint_count(Pointer.fromAddress(world));

@Native<Int32 Function(Pointer<Void>, Uint64, Int32, Float, Float)>(
  symbol: 'f3d_joint_set_limits',
  isLeaf: true,
)
external int _f3d_joint_set_limits(
  Pointer<Void> world,
  int joint,
  int enabled,
  double lower,
  double upper,
);
int f3d_joint_set_limits(
  int world,
  int joint,
  int enabled,
  double lower,
  double upper,
) => _f3d_joint_set_limits(
  Pointer.fromAddress(world),
  joint,
  enabled,
  lower,
  upper,
);

@Native<Int32 Function(Pointer<Void>, Uint64, Int32, Float)>(
  symbol: 'f3d_joint_set_cone',
  isLeaf: true,
)
external int _f3d_joint_set_cone(
  Pointer<Void> world,
  int joint,
  int enabled,
  double angle,
);
int f3d_joint_set_cone(int world, int joint, int enabled, double angle) =>
    _f3d_joint_set_cone(Pointer.fromAddress(world), joint, enabled, angle);

@Native<Int32 Function(Pointer<Void>, Uint64, Int32, Float)>(
  symbol: 'f3d_joint_set_friction',
  isLeaf: true,
)
external int _f3d_joint_set_friction(
  Pointer<Void> world,
  int joint,
  int enabled,
  double torque,
);
int f3d_joint_set_friction(int world, int joint, int enabled, double torque) =>
    _f3d_joint_set_friction(Pointer.fromAddress(world), joint, enabled, torque);

@Native<Int32 Function(Pointer<Void>, Uint64, Int32, Float, Float)>(
  symbol: 'f3d_joint_set_motor',
  isLeaf: true,
)
external int _f3d_joint_set_motor(
  Pointer<Void> world,
  int joint,
  int enabled,
  double speed,
  double maxForce,
);
int f3d_joint_set_motor(
  int world,
  int joint,
  int enabled,
  double speed,
  double maxForce,
) => _f3d_joint_set_motor(
  Pointer.fromAddress(world),
  joint,
  enabled,
  speed,
  maxForce,
);

@Native<Int32 Function(Pointer<Void>, Uint64, Int32, Float, Float)>(
  symbol: 'f3d_joint_set_spring',
  isLeaf: true,
)
external int _f3d_joint_set_spring(
  Pointer<Void> world,
  int joint,
  int enabled,
  double hertz,
  double damping,
);
int f3d_joint_set_spring(
  int world,
  int joint,
  int enabled,
  double hertz,
  double damping,
) => _f3d_joint_set_spring(
  Pointer.fromAddress(world),
  joint,
  enabled,
  hertz,
  damping,
);

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float, Float)>(
  symbol: 'f3d_joint_set_length',
  isLeaf: true,
)
external int _f3d_joint_set_length(
  Pointer<Void> world,
  int joint,
  double length,
  double least,
  double most,
);
int f3d_joint_set_length(
  int world,
  int joint,
  double length,
  double least,
  double most,
) => _f3d_joint_set_length(
  Pointer.fromAddress(world),
  joint,
  length,
  least,
  most,
);

@Native<Int32 Function(Pointer<Void>, Uint64, Int32)>(
  symbol: 'f3d_joint_set_collide',
  isLeaf: true,
)
external int _f3d_joint_set_collide(
  Pointer<Void> world,
  int joint,
  int collide,
);
int f3d_joint_set_collide(int world, int joint, int collide) =>
    _f3d_joint_set_collide(Pointer.fromAddress(world), joint, collide);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_joint_get_value',
  isLeaf: true,
)
external int _f3d_joint_get_value(
  Pointer<Void> world,
  int joint,
  Pointer<Void> out,
);
int f3d_joint_get_value(int world, int joint, int out) => _f3d_joint_get_value(
  Pointer.fromAddress(world),
  joint,
  Pointer.fromAddress(out),
);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_joint_get_swing',
  isLeaf: true,
)
external int _f3d_joint_get_swing(
  Pointer<Void> world,
  int joint,
  Pointer<Void> out,
);
int f3d_joint_get_swing(int world, int joint, int out) => _f3d_joint_get_swing(
  Pointer.fromAddress(world),
  joint,
  Pointer.fromAddress(out),
);

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float)>(
  symbol: 'f3d_joint_set_break',
  isLeaf: true,
)
external int _f3d_joint_set_break(
  Pointer<Void> world,
  int joint,
  double force,
  double torque,
);
int f3d_joint_set_break(int world, int joint, double force, double torque) =>
    _f3d_joint_set_break(Pointer.fromAddress(world), joint, force, torque);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_joint_get_torque',
  isLeaf: true,
)
external int _f3d_joint_get_torque(
  Pointer<Void> world,
  int joint,
  Pointer<Void> out,
);
int f3d_joint_get_torque(int world, int joint, int out) =>
    _f3d_joint_get_torque(
      Pointer.fromAddress(world),
      joint,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_joint_get_force',
  isLeaf: true,
)
external int _f3d_joint_get_force(
  Pointer<Void> world,
  int joint,
  Pointer<Void> out,
);
int f3d_joint_get_force(int world, int joint, int out) => _f3d_joint_get_force(
  Pointer.fromAddress(world),
  joint,
  Pointer.fromAddress(out),
);

@Native<
  Int32 Function(
    Pointer<Void>,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Uint32,
    Uint64,
    Pointer<Void>,
    Pointer<Void>,
  )
>(symbol: 'f3d_world_ray_cast')
external int _f3d_world_ray_cast(
  Pointer<Void> world,
  double ox,
  double oy,
  double oz,
  double dx,
  double dy,
  double dz,
  double maxDistance,
  int mask,
  int ignore,
  Pointer<Void> body,
  Pointer<Void> hit,
);
int f3d_world_ray_cast(
  int world,
  double ox,
  double oy,
  double oz,
  double dx,
  double dy,
  double dz,
  double maxDistance,
  int mask,
  int ignore,
  int body,
  int hit,
) => _f3d_world_ray_cast(
  Pointer.fromAddress(world),
  ox,
  oy,
  oz,
  dx,
  dy,
  dz,
  maxDistance,
  mask,
  ignore,
  Pointer.fromAddress(body),
  Pointer.fromAddress(hit),
);

@Native<
  Uint32 Function(
    Pointer<Void>,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Uint32,
    Uint64,
    Pointer<Void>,
    Pointer<Void>,
    Uint32,
  )
>(symbol: 'f3d_world_ray_cast_all')
external int _f3d_world_ray_cast_all(
  Pointer<Void> world,
  double ox,
  double oy,
  double oz,
  double dx,
  double dy,
  double dz,
  double maxDistance,
  int mask,
  int ignore,
  Pointer<Void> bodies,
  Pointer<Void> hits,
  int capacity,
);
int f3d_world_ray_cast_all(
  int world,
  double ox,
  double oy,
  double oz,
  double dx,
  double dy,
  double dz,
  double maxDistance,
  int mask,
  int ignore,
  int bodies,
  int hits,
  int capacity,
) => _f3d_world_ray_cast_all(
  Pointer.fromAddress(world),
  ox,
  oy,
  oz,
  dx,
  dy,
  dz,
  maxDistance,
  mask,
  ignore,
  Pointer.fromAddress(bodies),
  Pointer.fromAddress(hits),
  capacity,
);

@Native<
  Uint32 Function(
    Pointer<Void>,
    Int32,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Uint32,
    Uint64,
    Pointer<Void>,
    Uint32,
  )
>(symbol: 'f3d_world_overlap_shape')
external int _f3d_world_overlap_shape(
  Pointer<Void> world,
  int kind,
  double a,
  double b,
  double c,
  double rounding,
  double px,
  double py,
  double pz,
  double qx,
  double qy,
  double qz,
  double qw,
  int mask,
  int ignore,
  Pointer<Void> out,
  int capacity,
);
int f3d_world_overlap_shape(
  int world,
  int kind,
  double a,
  double b,
  double c,
  double rounding,
  double px,
  double py,
  double pz,
  double qx,
  double qy,
  double qz,
  double qw,
  int mask,
  int ignore,
  int out,
  int capacity,
) => _f3d_world_overlap_shape(
  Pointer.fromAddress(world),
  kind,
  a,
  b,
  c,
  rounding,
  px,
  py,
  pz,
  qx,
  qy,
  qz,
  qw,
  mask,
  ignore,
  Pointer.fromAddress(out),
  capacity,
);

@Native<
  Int32 Function(
    Pointer<Void>,
    Int32,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
    Uint32,
    Uint64,
    Pointer<Void>,
    Pointer<Void>,
  )
>(symbol: 'f3d_world_cast_shape')
external int _f3d_world_cast_shape(
  Pointer<Void> world,
  int kind,
  double a,
  double b,
  double c,
  double rounding,
  double px,
  double py,
  double pz,
  double qx,
  double qy,
  double qz,
  double qw,
  double tx,
  double ty,
  double tz,
  int mask,
  int ignore,
  Pointer<Void> body,
  Pointer<Void> hit,
);
int f3d_world_cast_shape(
  int world,
  int kind,
  double a,
  double b,
  double c,
  double rounding,
  double px,
  double py,
  double pz,
  double qx,
  double qy,
  double qz,
  double qw,
  double tx,
  double ty,
  double tz,
  int mask,
  int ignore,
  int body,
  int hit,
) => _f3d_world_cast_shape(
  Pointer.fromAddress(world),
  kind,
  a,
  b,
  c,
  rounding,
  px,
  py,
  pz,
  qx,
  qy,
  qz,
  qw,
  tx,
  ty,
  tz,
  mask,
  ignore,
  Pointer.fromAddress(body),
  Pointer.fromAddress(hit),
);

@Native<
  Uint32 Function(
    Pointer<Void>,
    Int32,
    Float,
    Float,
    Float,
    Pointer<Void>,
    Float,
    Float,
    Float,
    Pointer<Void>,
    Float,
    Float,
    Uint32,
    Uint32,
    Uint32,
    Uint64,
    Pointer<Void>,
    Pointer<Void>,
    Pointer<Void>,
  )
>(symbol: 'f3d_world_move_character')
external int _f3d_world_move_character(
  Pointer<Void> world,
  int kind,
  double a,
  double b,
  double c,
  Pointer<Void> position,
  double dx,
  double dy,
  double dz,
  Pointer<Void> velocity,
  double maxSlopeCos,
  double stepHeight,
  int mask,
  int fromAbove,
  int options,
  int ignore,
  Pointer<Void> groundBody,
  Pointer<Void> ground,
  Pointer<Void> steppedUp,
);
int f3d_world_move_character(
  int world,
  int kind,
  double a,
  double b,
  double c,
  int position,
  double dx,
  double dy,
  double dz,
  int velocity,
  double maxSlopeCos,
  double stepHeight,
  int mask,
  int fromAbove,
  int options,
  int ignore,
  int groundBody,
  int ground,
  int steppedUp,
) => _f3d_world_move_character(
  Pointer.fromAddress(world),
  kind,
  a,
  b,
  c,
  Pointer.fromAddress(position),
  dx,
  dy,
  dz,
  Pointer.fromAddress(velocity),
  maxSlopeCos,
  stepHeight,
  mask,
  fromAbove,
  options,
  ignore,
  Pointer.fromAddress(groundBody),
  Pointer.fromAddress(ground),
  Pointer.fromAddress(steppedUp),
);

@Native<Pointer<Void> Function(Uint32)>(symbol: 'f3d_particles_create')
external Pointer<Void> _f3d_particles_create(int capacity);
int f3d_particles_create(int capacity) =>
    _f3d_particles_create(capacity).address;

@Native<Void Function(Pointer<Void>)>(symbol: 'f3d_particles_destroy')
external void _f3d_particles_destroy(Pointer<Void> particles);
void f3d_particles_destroy(int particles) =>
    _f3d_particles_destroy(Pointer.fromAddress(particles));

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_particles_capacity',
  isLeaf: true,
)
external int _f3d_particles_capacity(Pointer<Void> particles);
int f3d_particles_capacity(int particles) =>
    _f3d_particles_capacity(Pointer.fromAddress(particles));

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_particles_emit',
  isLeaf: true,
)
external int _f3d_particles_emit(
  Pointer<Void> particles,
  Pointer<Void> particlesData,
  int count,
);
int f3d_particles_emit(int particles, int particlesData, int count) =>
    _f3d_particles_emit(
      Pointer.fromAddress(particles),
      Pointer.fromAddress(particlesData),
      count,
    );

@Native<Void Function(Pointer<Void>, Pointer<Void>, Float)>(
  symbol: 'f3d_particles_step',
  isLeaf: true,
)
external void _f3d_particles_step(
  Pointer<Void> particles,
  Pointer<Void> forces,
  double dt,
);
void f3d_particles_step(int particles, int forces, double dt) =>
    _f3d_particles_step(
      Pointer.fromAddress(particles),
      Pointer.fromAddress(forces),
      dt,
    );

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_particles_read',
  isLeaf: true,
)
external int _f3d_particles_read(
  Pointer<Void> particles,
  Pointer<Void> out,
  int capacity,
);
int f3d_particles_read(int particles, int out, int capacity) =>
    _f3d_particles_read(
      Pointer.fromAddress(particles),
      Pointer.fromAddress(out),
      capacity,
    );

@Native<Pointer<Void> Function(Uint32)>(symbol: 'f3d_debris_create')
external Pointer<Void> _f3d_debris_create(int capacity);
int f3d_debris_create(int capacity) => _f3d_debris_create(capacity).address;

@Native<Void Function(Pointer<Void>)>(symbol: 'f3d_debris_destroy')
external void _f3d_debris_destroy(Pointer<Void> debris);
void f3d_debris_destroy(int debris) =>
    _f3d_debris_destroy(Pointer.fromAddress(debris));

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_debris_capacity',
  isLeaf: true,
)
external int _f3d_debris_capacity(Pointer<Void> debris);
int f3d_debris_capacity(int debris) =>
    _f3d_debris_capacity(Pointer.fromAddress(debris));

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_debris_add',
  isLeaf: true,
)
external int _f3d_debris_add(
  Pointer<Void> debris,
  Pointer<Void> data,
  int count,
);
int f3d_debris_add(int debris, int data, int count) => _f3d_debris_add(
  Pointer.fromAddress(debris),
  Pointer.fromAddress(data),
  count,
);

@Native<Int32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_debris_set_statics',
  isLeaf: true,
)
external int _f3d_debris_set_statics(
  Pointer<Void> debris,
  Pointer<Void> data,
  int count,
);
int f3d_debris_set_statics(int debris, int data, int count) =>
    _f3d_debris_set_statics(
      Pointer.fromAddress(debris),
      Pointer.fromAddress(data),
      count,
    );

@Native<Void Function(Pointer<Void>, Pointer<Void>, Float)>(
  symbol: 'f3d_debris_step',
)
external void _f3d_debris_step(
  Pointer<Void> debris,
  Pointer<Void> settings,
  double dt,
);
void f3d_debris_step(int debris, int settings, double dt) => _f3d_debris_step(
  Pointer.fromAddress(debris),
  Pointer.fromAddress(settings),
  dt,
);

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_debris_read',
  isLeaf: true,
)
external int _f3d_debris_read(
  Pointer<Void> debris,
  Pointer<Void> out,
  int capacity,
);
int f3d_debris_read(int debris, int out, int capacity) => _f3d_debris_read(
  Pointer.fromAddress(debris),
  Pointer.fromAddress(out),
  capacity,
);

@Native<
  Pointer<Void> Function(
    Pointer<Void>,
    Uint32,
    Pointer<Void>,
    Pointer<Void>,
    Uint32,
  )
>(symbol: 'f3d_cloth_create')
external Pointer<Void> _f3d_cloth_create(
  Pointer<Void> points,
  int pointCount,
  Pointer<Void> edges,
  Pointer<Void> compliance,
  int edgeCount,
);
int f3d_cloth_create(
  int points,
  int pointCount,
  int edges,
  int compliance,
  int edgeCount,
) => _f3d_cloth_create(
  Pointer.fromAddress(points),
  pointCount,
  Pointer.fromAddress(edges),
  Pointer.fromAddress(compliance),
  edgeCount,
).address;

@Native<Void Function(Pointer<Void>)>(symbol: 'f3d_cloth_destroy')
external void _f3d_cloth_destroy(Pointer<Void> cloth);
void f3d_cloth_destroy(int cloth) =>
    _f3d_cloth_destroy(Pointer.fromAddress(cloth));

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_cloth_point_count',
  isLeaf: true,
)
external int _f3d_cloth_point_count(Pointer<Void> cloth);
int f3d_cloth_point_count(int cloth) =>
    _f3d_cloth_point_count(Pointer.fromAddress(cloth));

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_cloth_colour_count',
  isLeaf: true,
)
external int _f3d_cloth_colour_count(Pointer<Void> cloth);
int f3d_cloth_colour_count(int cloth) =>
    _f3d_cloth_colour_count(Pointer.fromAddress(cloth));

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_cloth_edge_count',
  isLeaf: true,
)
external int _f3d_cloth_edge_count(Pointer<Void> cloth);
int f3d_cloth_edge_count(int cloth) =>
    _f3d_cloth_edge_count(Pointer.fromAddress(cloth));

@Native<
  Void Function(
    Pointer<Void>,
    Pointer<Void>,
    Pointer<Void>,
    Pointer<Void>,
    Pointer<Void>,
  )
>(symbol: 'f3d_cloth_edges', isLeaf: true)
external void _f3d_cloth_edges(
  Pointer<Void> cloth,
  Pointer<Void> pairs,
  Pointer<Void> rest,
  Pointer<Void> compliance,
  Pointer<Void> colourStart,
);
void f3d_cloth_edges(
  int cloth,
  int pairs,
  int rest,
  int compliance,
  int colourStart,
) => _f3d_cloth_edges(
  Pointer.fromAddress(cloth),
  Pointer.fromAddress(pairs),
  Pointer.fromAddress(rest),
  Pointer.fromAddress(compliance),
  Pointer.fromAddress(colourStart),
);

@Native<Int32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_cloth_set_balls',
  isLeaf: true,
)
external int _f3d_cloth_set_balls(
  Pointer<Void> cloth,
  Pointer<Void> balls,
  int count,
);
int f3d_cloth_set_balls(int cloth, int balls, int count) =>
    _f3d_cloth_set_balls(
      Pointer.fromAddress(cloth),
      Pointer.fromAddress(balls),
      count,
    );

@Native<Void Function(Pointer<Void>, Uint32, Float, Float, Float)>(
  symbol: 'f3d_cloth_move_point',
  isLeaf: true,
)
external void _f3d_cloth_move_point(
  Pointer<Void> cloth,
  int index,
  double x,
  double y,
  double z,
);
void f3d_cloth_move_point(int cloth, int index, double x, double y, double z) =>
    _f3d_cloth_move_point(Pointer.fromAddress(cloth), index, x, y, z);

@Native<Void Function(Pointer<Void>, Pointer<Void>, Float)>(
  symbol: 'f3d_cloth_step',
)
external void _f3d_cloth_step(
  Pointer<Void> cloth,
  Pointer<Void> settings,
  double dt,
);
void f3d_cloth_step(int cloth, int settings, double dt) => _f3d_cloth_step(
  Pointer.fromAddress(cloth),
  Pointer.fromAddress(settings),
  dt,
);

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_cloth_read',
  isLeaf: true,
)
external int _f3d_cloth_read(
  Pointer<Void> cloth,
  Pointer<Void> out,
  int capacity,
);
int f3d_cloth_read(int cloth, int out, int capacity) => _f3d_cloth_read(
  Pointer.fromAddress(cloth),
  Pointer.fromAddress(out),
  capacity,
);

@Native<Int32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_cloth_set_triangles',
  isLeaf: true,
)
external int _f3d_cloth_set_triangles(
  Pointer<Void> cloth,
  Pointer<Void> corners,
  int count,
);
int f3d_cloth_set_triangles(int cloth, int corners, int count) =>
    _f3d_cloth_set_triangles(
      Pointer.fromAddress(cloth),
      Pointer.fromAddress(corners),
      count,
    );

@Native<Void Function(Pointer<Void>, Pointer<Void>)>(
  symbol: 'f3d_cloth_set_rest',
  isLeaf: true,
)
external void _f3d_cloth_set_rest(Pointer<Void> cloth, Pointer<Void> xyz);
void f3d_cloth_set_rest(int cloth, int xyz) =>
    _f3d_cloth_set_rest(Pointer.fromAddress(cloth), Pointer.fromAddress(xyz));

@Native<Void Function(Pointer<Void>, Pointer<Void>)>(
  symbol: 'f3d_cloth_set_compliance',
  isLeaf: true,
)
external void _f3d_cloth_set_compliance(
  Pointer<Void> cloth,
  Pointer<Void> compliance,
);
void f3d_cloth_set_compliance(int cloth, int compliance) =>
    _f3d_cloth_set_compliance(
      Pointer.fromAddress(cloth),
      Pointer.fromAddress(compliance),
    );

@Native<Void Function(Pointer<Void>, Pointer<Void>)>(
  symbol: 'f3d_cloth_set_lengths',
  isLeaf: true,
)
external void _f3d_cloth_set_lengths(Pointer<Void> cloth, Pointer<Void> length);
void f3d_cloth_set_lengths(int cloth, int length) => _f3d_cloth_set_lengths(
  Pointer.fromAddress(cloth),
  Pointer.fromAddress(length),
);

@Native<Int32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_cloth_set_obstacles',
  isLeaf: true,
)
external int _f3d_cloth_set_obstacles(
  Pointer<Void> cloth,
  Pointer<Void> records,
  int length,
);
int f3d_cloth_set_obstacles(int cloth, int records, int length) =>
    _f3d_cloth_set_obstacles(
      Pointer.fromAddress(cloth),
      Pointer.fromAddress(records),
      length,
    );

@Native<Void Function(Pointer<Void>, Pointer<Void>)>(
  symbol: 'f3d_cloth_write_state',
  isLeaf: true,
)
external void _f3d_cloth_write_state(Pointer<Void> cloth, Pointer<Void> state);
void f3d_cloth_write_state(int cloth, int state) => _f3d_cloth_write_state(
  Pointer.fromAddress(cloth),
  Pointer.fromAddress(state),
);

@Native<Void Function(Pointer<Void>, Pointer<Void>)>(
  symbol: 'f3d_cloth_read_state',
  isLeaf: true,
)
external void _f3d_cloth_read_state(Pointer<Void> cloth, Pointer<Void> state);
void f3d_cloth_read_state(int cloth, int state) => _f3d_cloth_read_state(
  Pointer.fromAddress(cloth),
  Pointer.fromAddress(state),
);

@Native<Void Function(Pointer<Void>, Pointer<Void>, Float)>(
  symbol: 'f3d_cloth_solve',
  isLeaf: true,
)
external void _f3d_cloth_solve(
  Pointer<Void> cloth,
  Pointer<Void> settings,
  double dt,
);
void f3d_cloth_solve(int cloth, int settings, double dt) => _f3d_cloth_solve(
  Pointer.fromAddress(cloth),
  Pointer.fromAddress(settings),
  dt,
);

@Native<Pointer<Void> Function(Uint32, Float)>(symbol: 'f3d_fluid_create')
external Pointer<Void> _f3d_fluid_create(int capacity, double spacing);
int f3d_fluid_create(int capacity, double spacing) =>
    _f3d_fluid_create(capacity, spacing).address;

@Native<Void Function(Pointer<Void>)>(symbol: 'f3d_fluid_destroy')
external void _f3d_fluid_destroy(Pointer<Void> fluid);
void f3d_fluid_destroy(int fluid) =>
    _f3d_fluid_destroy(Pointer.fromAddress(fluid));

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_fluid_capacity',
  isLeaf: true,
)
external int _f3d_fluid_capacity(Pointer<Void> fluid);
int f3d_fluid_capacity(int fluid) =>
    _f3d_fluid_capacity(Pointer.fromAddress(fluid));

@Native<Float Function(Pointer<Void>)>(
  symbol: 'f3d_fluid_rest_density',
  isLeaf: true,
)
external double _f3d_fluid_rest_density(Pointer<Void> fluid);
double f3d_fluid_rest_density(int fluid) =>
    _f3d_fluid_rest_density(Pointer.fromAddress(fluid));

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_fluid_add',
  isLeaf: true,
)
external int _f3d_fluid_add(Pointer<Void> fluid, Pointer<Void> data, int count);
int f3d_fluid_add(int fluid, int data, int count) => _f3d_fluid_add(
  Pointer.fromAddress(fluid),
  Pointer.fromAddress(data),
  count,
);

@Native<Void Function(Pointer<Void>, Pointer<Void>, Float)>(
  symbol: 'f3d_fluid_step',
)
external void _f3d_fluid_step(
  Pointer<Void> fluid,
  Pointer<Void> settings,
  double dt,
);
void f3d_fluid_step(int fluid, int settings, double dt) => _f3d_fluid_step(
  Pointer.fromAddress(fluid),
  Pointer.fromAddress(settings),
  dt,
);

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_fluid_read',
  isLeaf: true,
)
external int _f3d_fluid_read(
  Pointer<Void> fluid,
  Pointer<Void> out,
  int capacity,
);
int f3d_fluid_read(int fluid, int out, int capacity) => _f3d_fluid_read(
  Pointer.fromAddress(fluid),
  Pointer.fromAddress(out),
  capacity,
);

@Native<
  Int32 Function(Pointer<Void>, Uint32, Pointer<Void>, Uint32, Pointer<Void>)
>(symbol: 'f3d_liquid_particles', isLeaf: true)
external int _f3d_liquid_particles(
  Pointer<Void> state,
  int count,
  Pointer<Void> walls,
  int length,
  Pointer<Void> settings,
);
int f3d_liquid_particles(
  int state,
  int count,
  int walls,
  int length,
  int settings,
) => _f3d_liquid_particles(
  Pointer.fromAddress(state),
  count,
  Pointer.fromAddress(walls),
  length,
  Pointer.fromAddress(settings),
);

@Native<
  Int32 Function(Pointer<Void>, Uint32, Pointer<Void>, Uint32, Pointer<Void>)
>(symbol: 'f3d_liquid_parcels', isLeaf: true)
external int _f3d_liquid_parcels(
  Pointer<Void> parcels,
  int count,
  Pointer<Void> walls,
  int length,
  Pointer<Void> settings,
);
int f3d_liquid_parcels(
  int parcels,
  int count,
  int walls,
  int length,
  int settings,
) => _f3d_liquid_parcels(
  Pointer.fromAddress(parcels),
  count,
  Pointer.fromAddress(walls),
  length,
  Pointer.fromAddress(settings),
);

@Native<Void Function(Pointer<Void>, Uint32, Pointer<Void>)>(
  symbol: 'f3d_liquid_modes',
  isLeaf: true,
)
external void _f3d_liquid_modes(
  Pointer<Void> modes,
  int count,
  Pointer<Void> settings,
);
void f3d_liquid_modes(int modes, int count, int settings) => _f3d_liquid_modes(
  Pointer.fromAddress(modes),
  count,
  Pointer.fromAddress(settings),
);

@Native<Void Function(Pointer<Void>, Uint32, Float)>(
  symbol: 'f3d_liquid_pipes',
  isLeaf: true,
)
external void _f3d_liquid_pipes(Pointer<Void> pipes, int count, double dt);
void f3d_liquid_pipes(int pipes, int count, double dt) =>
    _f3d_liquid_pipes(Pointer.fromAddress(pipes), count, dt);

@Native<
  Int32 Function(Pointer<Void>, Uint32, Pointer<Void>, Uint32, Pointer<Void>)
>(symbol: 'f3d_liquid_floats', isLeaf: true)
external int _f3d_liquid_floats(
  Pointer<Void> bodies,
  int bodyCount,
  Pointer<Void> pushes,
  int count,
  Pointer<Void> settings,
);
int f3d_liquid_floats(
  int bodies,
  int bodyCount,
  int pushes,
  int count,
  int settings,
) => _f3d_liquid_floats(
  Pointer.fromAddress(bodies),
  bodyCount,
  Pointer.fromAddress(pushes),
  count,
  Pointer.fromAddress(settings),
);

@Native<Uint32 Function(Pointer<Void>)>(
  symbol: 'f3d_world_snapshot_size',
  isLeaf: true,
)
external int _f3d_world_snapshot_size(Pointer<Void> world);
int f3d_world_snapshot_size(int world) =>
    _f3d_world_snapshot_size(Pointer.fromAddress(world));

@Native<Uint32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_snapshot_write',
  isLeaf: true,
)
external int _f3d_world_snapshot_write(
  Pointer<Void> world,
  Pointer<Void> buffer,
  int size,
);
int f3d_world_snapshot_write(int world, int buffer, int size) =>
    _f3d_world_snapshot_write(
      Pointer.fromAddress(world),
      Pointer.fromAddress(buffer),
      size,
    );

@Native<Int32 Function(Pointer<Void>, Pointer<Void>, Uint32)>(
  symbol: 'f3d_world_restore',
)
external int _f3d_world_restore(
  Pointer<Void> world,
  Pointer<Void> buffer,
  int size,
);
int f3d_world_restore(int world, int buffer, int size) => _f3d_world_restore(
  Pointer.fromAddress(world),
  Pointer.fromAddress(buffer),
  size,
);

@Native<Uint64 Function(Pointer<Void>, Int32, Float, Float, Float, Float)>(
  symbol: 'f3d_body_create',
)
external int _f3d_body_create(
  Pointer<Void> world,
  int type,
  double px,
  double py,
  double pz,
  double mass,
);
int f3d_body_create(
  int world,
  int type,
  double px,
  double py,
  double pz,
  double mass,
) => _f3d_body_create(Pointer.fromAddress(world), type, px, py, pz, mass);

@Native<Int32 Function(Pointer<Void>, Uint64)>(
  symbol: 'f3d_body_destroy',
  isLeaf: true,
)
external int _f3d_body_destroy(Pointer<Void> world, int body);
int f3d_body_destroy(int world, int body) =>
    _f3d_body_destroy(Pointer.fromAddress(world), body);

@Native<Int32 Function(Pointer<Void>, Uint64)>(
  symbol: 'f3d_body_is_valid',
  isLeaf: true,
)
external int _f3d_body_is_valid(Pointer<Void> world, int body);
int f3d_body_is_valid(int world, int body) =>
    _f3d_body_is_valid(Pointer.fromAddress(world), body);

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float, Float)>(
  symbol: 'f3d_body_set_velocity',
  isLeaf: true,
)
external int _f3d_body_set_velocity(
  Pointer<Void> world,
  int body,
  double x,
  double y,
  double z,
);
int f3d_body_set_velocity(int world, int body, double x, double y, double z) =>
    _f3d_body_set_velocity(Pointer.fromAddress(world), body, x, y, z);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_velocity',
  isLeaf: true,
)
external int _f3d_body_get_velocity(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_velocity(int world, int body, int out) =>
    _f3d_body_get_velocity(
      Pointer.fromAddress(world),
      body,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float, Float)>(
  symbol: 'f3d_body_set_position',
  isLeaf: true,
)
external int _f3d_body_set_position(
  Pointer<Void> world,
  int body,
  double x,
  double y,
  double z,
);
int f3d_body_set_position(int world, int body, double x, double y, double z) =>
    _f3d_body_set_position(Pointer.fromAddress(world), body, x, y, z);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_position',
  isLeaf: true,
)
external int _f3d_body_get_position(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_position(int world, int body, int out) =>
    _f3d_body_get_position(
      Pointer.fromAddress(world),
      body,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_world_position',
  isLeaf: true,
)
external int _f3d_body_get_world_position(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_world_position(int world, int body, int out) =>
    _f3d_body_get_world_position(
      Pointer.fromAddress(world),
      body,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float, Float)>(
  symbol: 'f3d_body_set_angular_velocity',
  isLeaf: true,
)
external int _f3d_body_set_angular_velocity(
  Pointer<Void> world,
  int body,
  double x,
  double y,
  double z,
);
int f3d_body_set_angular_velocity(
  int world,
  int body,
  double x,
  double y,
  double z,
) => _f3d_body_set_angular_velocity(Pointer.fromAddress(world), body, x, y, z);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_angular_velocity',
  isLeaf: true,
)
external int _f3d_body_get_angular_velocity(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_angular_velocity(int world, int body, int out) =>
    _f3d_body_get_angular_velocity(
      Pointer.fromAddress(world),
      body,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float, Float, Float)>(
  symbol: 'f3d_body_set_orientation',
  isLeaf: true,
)
external int _f3d_body_set_orientation(
  Pointer<Void> world,
  int body,
  double x,
  double y,
  double z,
  double w,
);
int f3d_body_set_orientation(
  int world,
  int body,
  double x,
  double y,
  double z,
  double w,
) => _f3d_body_set_orientation(Pointer.fromAddress(world), body, x, y, z, w);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_orientation',
  isLeaf: true,
)
external int _f3d_body_get_orientation(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_orientation(int world, int body, int out) =>
    _f3d_body_get_orientation(
      Pointer.fromAddress(world),
      body,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Int32, Float, Float, Float)>(
  symbol: 'f3d_body_set_shape',
  isLeaf: true,
)
external int _f3d_body_set_shape(
  Pointer<Void> world,
  int body,
  int kind,
  double a,
  double b,
  double c,
);
int f3d_body_set_shape(
  int world,
  int body,
  int kind,
  double a,
  double b,
  double c,
) => _f3d_body_set_shape(Pointer.fromAddress(world), body, kind, a, b, c);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_inertia',
  isLeaf: true,
)
external int _f3d_body_get_inertia(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_inertia(int world, int body, int out) => _f3d_body_get_inertia(
  Pointer.fromAddress(world),
  body,
  Pointer.fromAddress(out),
);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_inertia_tensor',
  isLeaf: true,
)
external int _f3d_body_get_inertia_tensor(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_inertia_tensor(int world, int body, int out) =>
    _f3d_body_get_inertia_tensor(
      Pointer.fromAddress(world),
      body,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Float)>(
  symbol: 'f3d_body_set_rounding',
  isLeaf: true,
)
external int _f3d_body_set_rounding(
  Pointer<Void> world,
  int body,
  double radius,
);
int f3d_body_set_rounding(int world, int body, double radius) =>
    _f3d_body_set_rounding(Pointer.fromAddress(world), body, radius);

@Native<Int32 Function(Pointer<Void>, Uint64, Uint32)>(
  symbol: 'f3d_body_set_hull',
  isLeaf: true,
)
external int _f3d_body_set_hull(Pointer<Void> world, int body, int hull);
int f3d_body_set_hull(int world, int body, int hull) =>
    _f3d_body_set_hull(Pointer.fromAddress(world), body, hull);

@Native<Int32 Function(Pointer<Void>, Uint64, Uint32)>(
  symbol: 'f3d_body_set_compound',
  isLeaf: true,
)
external int _f3d_body_set_compound(
  Pointer<Void> world,
  int body,
  int compound,
);
int f3d_body_set_compound(int world, int body, int compound) =>
    _f3d_body_set_compound(Pointer.fromAddress(world), body, compound);

@Native<Int32 Function(Pointer<Void>, Uint64, Uint32)>(
  symbol: 'f3d_body_set_mesh',
  isLeaf: true,
)
external int _f3d_body_set_mesh(Pointer<Void> world, int body, int mesh);
int f3d_body_set_mesh(int world, int body, int mesh) =>
    _f3d_body_set_mesh(Pointer.fromAddress(world), body, mesh);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_mass',
  isLeaf: true,
)
external int _f3d_body_get_mass(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_mass(int world, int body, int out) => _f3d_body_get_mass(
  Pointer.fromAddress(world),
  body,
  Pointer.fromAddress(out),
);

@Native<Int32 Function(Pointer<Void>, Uint64, Int32)>(
  symbol: 'f3d_body_lock_rotation',
  isLeaf: true,
)
external int _f3d_body_lock_rotation(Pointer<Void> world, int body, int locked);
int f3d_body_lock_rotation(int world, int body, int locked) =>
    _f3d_body_lock_rotation(Pointer.fromAddress(world), body, locked);

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float)>(
  symbol: 'f3d_body_set_damping',
  isLeaf: true,
)
external int _f3d_body_set_damping(
  Pointer<Void> world,
  int body,
  double linear,
  double angular,
);
int f3d_body_set_damping(int world, int body, double linear, double angular) =>
    _f3d_body_set_damping(Pointer.fromAddress(world), body, linear, angular);

@Native<Int32 Function(Pointer<Void>, Uint64, Float)>(
  symbol: 'f3d_body_set_drag',
  isLeaf: true,
)
external int _f3d_body_set_drag(
  Pointer<Void> world,
  int body,
  double coefficient,
);
int f3d_body_set_drag(int world, int body, double coefficient) =>
    _f3d_body_set_drag(Pointer.fromAddress(world), body, coefficient);

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float, Float)>(
  symbol: 'f3d_body_apply_impulse',
  isLeaf: true,
)
external int _f3d_body_apply_impulse(
  Pointer<Void> world,
  int body,
  double x,
  double y,
  double z,
);
int f3d_body_apply_impulse(int world, int body, double x, double y, double z) =>
    _f3d_body_apply_impulse(Pointer.fromAddress(world), body, x, y, z);

@Native<
  Int32 Function(
    Pointer<Void>,
    Uint64,
    Float,
    Float,
    Float,
    Float,
    Float,
    Float,
  )
>(symbol: 'f3d_body_apply_impulse_at', isLeaf: true)
external int _f3d_body_apply_impulse_at(
  Pointer<Void> world,
  int body,
  double x,
  double y,
  double z,
  double px,
  double py,
  double pz,
);
int f3d_body_apply_impulse_at(
  int world,
  int body,
  double x,
  double y,
  double z,
  double px,
  double py,
  double pz,
) => _f3d_body_apply_impulse_at(
  Pointer.fromAddress(world),
  body,
  x,
  y,
  z,
  px,
  py,
  pz,
);

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float, Float)>(
  symbol: 'f3d_body_add_force',
  isLeaf: true,
)
external int _f3d_body_add_force(
  Pointer<Void> world,
  int body,
  double x,
  double y,
  double z,
);
int f3d_body_add_force(int world, int body, double x, double y, double z) =>
    _f3d_body_add_force(Pointer.fromAddress(world), body, x, y, z);

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float, Float)>(
  symbol: 'f3d_body_add_torque',
  isLeaf: true,
)
external int _f3d_body_add_torque(
  Pointer<Void> world,
  int body,
  double x,
  double y,
  double z,
);
int f3d_body_add_torque(int world, int body, double x, double y, double z) =>
    _f3d_body_add_torque(Pointer.fromAddress(world), body, x, y, z);

@Native<Int32 Function(Pointer<Void>, Uint64, Int32)>(
  symbol: 'f3d_body_set_bullet',
  isLeaf: true,
)
external int _f3d_body_set_bullet(Pointer<Void> world, int body, int bullet);
int f3d_body_set_bullet(int world, int body, int bullet) =>
    _f3d_body_set_bullet(Pointer.fromAddress(world), body, bullet);

@Native<Int32 Function(Pointer<Void>, Uint64, Float)>(
  symbol: 'f3d_body_set_friction',
  isLeaf: true,
)
external int _f3d_body_set_friction(
  Pointer<Void> world,
  int body,
  double friction,
);
int f3d_body_set_friction(int world, int body, double friction) =>
    _f3d_body_set_friction(Pointer.fromAddress(world), body, friction);

@Native<Int32 Function(Pointer<Void>, Uint64, Float)>(
  symbol: 'f3d_body_set_restitution',
  isLeaf: true,
)
external int _f3d_body_set_restitution(
  Pointer<Void> world,
  int body,
  double restitution,
);
int f3d_body_set_restitution(int world, int body, double restitution) =>
    _f3d_body_set_restitution(Pointer.fromAddress(world), body, restitution);

@Native<Int32 Function(Pointer<Void>, Uint64, Uint32, Uint32)>(
  symbol: 'f3d_body_set_collision_filter',
  isLeaf: true,
)
external int _f3d_body_set_collision_filter(
  Pointer<Void> world,
  int body,
  int layer,
  int mask,
);
int f3d_body_set_collision_filter(int world, int body, int layer, int mask) =>
    _f3d_body_set_collision_filter(
      Pointer.fromAddress(world),
      body,
      layer,
      mask,
    );

@Native<Int32 Function(Pointer<Void>, Uint64)>(
  symbol: 'f3d_body_is_asleep',
  isLeaf: true,
)
external int _f3d_body_is_asleep(Pointer<Void> world, int body);
int f3d_body_is_asleep(int world, int body) =>
    _f3d_body_is_asleep(Pointer.fromAddress(world), body);

@Native<Int32 Function(Pointer<Void>, Uint64)>(
  symbol: 'f3d_body_wake',
  isLeaf: true,
)
external int _f3d_body_wake(Pointer<Void> world, int body);
int f3d_body_wake(int world, int body) =>
    _f3d_body_wake(Pointer.fromAddress(world), body);

@Native<Int32 Function(Int32, Pointer<Void>)>(
  symbol: 'f3d_material_preset',
  isLeaf: true,
)
external int _f3d_material_preset(int kind, Pointer<Void> out);
int f3d_material_preset(int kind, int out) =>
    _f3d_material_preset(kind, Pointer.fromAddress(out));

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_set_material',
  isLeaf: true,
)
external int _f3d_body_set_material(
  Pointer<Void> world,
  int body,
  Pointer<Void> material,
);
int f3d_body_set_material(int world, int body, int material) =>
    _f3d_body_set_material(
      Pointer.fromAddress(world),
      body,
      Pointer.fromAddress(material),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Float)>(
  symbol: 'f3d_body_set_temperature',
  isLeaf: true,
)
external int _f3d_body_set_temperature(
  Pointer<Void> world,
  int body,
  double kelvin,
);
int f3d_body_set_temperature(int world, int body, double kelvin) =>
    _f3d_body_set_temperature(Pointer.fromAddress(world), body, kelvin);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_temperature',
  isLeaf: true,
)
external int _f3d_body_get_temperature(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_temperature(int world, int body, int out) =>
    _f3d_body_get_temperature(
      Pointer.fromAddress(world),
      body,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_surface_temperature',
  isLeaf: true,
)
external int _f3d_body_get_surface_temperature(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_surface_temperature(int world, int body, int out) =>
    _f3d_body_get_surface_temperature(
      Pointer.fromAddress(world),
      body,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Float)>(
  symbol: 'f3d_body_add_heat',
  isLeaf: true,
)
external int _f3d_body_add_heat(Pointer<Void> world, int body, double joules);
int f3d_body_add_heat(int world, int body, double joules) =>
    _f3d_body_add_heat(Pointer.fromAddress(world), body, joules);

@Native<Int32 Function(Pointer<Void>, Uint64, Uint32, Pointer<Void>)>(
  symbol: 'f3d_body_get_part_temperature',
  isLeaf: true,
)
external int _f3d_body_get_part_temperature(
  Pointer<Void> world,
  int body,
  int part,
  Pointer<Void> out,
);
int f3d_body_get_part_temperature(int world, int body, int part, int out) =>
    _f3d_body_get_part_temperature(
      Pointer.fromAddress(world),
      body,
      part,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Uint32, Float)>(
  symbol: 'f3d_body_set_part_temperature',
  isLeaf: true,
)
external int _f3d_body_set_part_temperature(
  Pointer<Void> world,
  int body,
  int part,
  double kelvin,
);
int f3d_body_set_part_temperature(
  int world,
  int body,
  int part,
  double kelvin,
) => _f3d_body_set_part_temperature(
  Pointer.fromAddress(world),
  body,
  part,
  kelvin,
);

@Native<Int32 Function(Pointer<Void>, Uint64, Uint32, Pointer<Void>)>(
  symbol: 'f3d_body_is_part_burning',
  isLeaf: true,
)
external int _f3d_body_is_part_burning(
  Pointer<Void> world,
  int body,
  int part,
  Pointer<Void> out,
);
int f3d_body_is_part_burning(int world, int body, int part, int out) =>
    _f3d_body_is_part_burning(
      Pointer.fromAddress(world),
      body,
      part,
      Pointer.fromAddress(out),
    );

@Native<Int32 Function(Pointer<Void>, Uint64, Float, Float, Float, Float)>(
  symbol: 'f3d_body_add_heat_at',
  isLeaf: true,
)
external int _f3d_body_add_heat_at(
  Pointer<Void> world,
  int body,
  double x,
  double y,
  double z,
  double joules,
);
int f3d_body_add_heat_at(
  int world,
  int body,
  double x,
  double y,
  double z,
  double joules,
) => _f3d_body_add_heat_at(Pointer.fromAddress(world), body, x, y, z, joules);

@Native<Int32 Function(Pointer<Void>, Uint64, Float)>(
  symbol: 'f3d_body_add_water',
  isLeaf: true,
)
external int _f3d_body_add_water(Pointer<Void> world, int body, double kg);
int f3d_body_add_water(int world, int body, double kg) =>
    _f3d_body_add_water(Pointer.fromAddress(world), body, kg);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_water',
  isLeaf: true,
)
external int _f3d_body_get_water(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_water(int world, int body, int out) => _f3d_body_get_water(
  Pointer.fromAddress(world),
  body,
  Pointer.fromAddress(out),
);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_fuel',
  isLeaf: true,
)
external int _f3d_body_get_fuel(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_fuel(int world, int body, int out) => _f3d_body_get_fuel(
  Pointer.fromAddress(world),
  body,
  Pointer.fromAddress(out),
);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_is_burning',
  isLeaf: true,
)
external int _f3d_body_is_burning(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_is_burning(int world, int body, int out) => _f3d_body_is_burning(
  Pointer.fromAddress(world),
  body,
  Pointer.fromAddress(out),
);

@Native<Int32 Function(Pointer<Void>, Uint64, Pointer<Void>)>(
  symbol: 'f3d_body_get_heat_release',
  isLeaf: true,
)
external int _f3d_body_get_heat_release(
  Pointer<Void> world,
  int body,
  Pointer<Void> out,
);
int f3d_body_get_heat_release(int world, int body, int out) =>
    _f3d_body_get_heat_release(
      Pointer.fromAddress(world),
      body,
      Pointer.fromAddress(out),
    );
