// Generated by tool/gen_core.dart from csrc/include/f3d_physics.h: do not edit.
//
// The core's calls in the browser: the WebAssembly module's exports, a
// pointer an offset into its memory, a 64-bit handle two 32-bit halves.
// ignore_for_file: non_constant_identifier_names
library;

import 'dart:js_interop';

import 'module_web.dart';

extension type _Exports(JSObject _) implements JSObject {
  @JS('f3d_abi_version')
  external JSNumber f3d_abi_version();
  @JS('f3d_real_bytes')
  external JSNumber f3d_real_bytes();
  @JS('f3d_buffer_alloc')
  external JSNumber f3d_buffer_alloc(JSNumber bytes);
  @JS('f3d_buffer_free')
  external void f3d_buffer_free(JSNumber buffer);
  @JS('f3d_world_create')
  external JSNumber f3d_world_create();
  @JS('f3d_world_destroy')
  external void f3d_world_destroy(JSNumber world);
  @JS('f3d_world_set_gravity')
  external void f3d_world_set_gravity(
    JSNumber world,
    JSNumber x,
    JSNumber y,
    JSNumber z,
  );
  @JS('f3d_world_get_gravity')
  external void f3d_world_get_gravity(JSNumber world, JSNumber out);
  @JS('f3d_world_set_air')
  external JSNumber f3d_world_set_air(
    JSNumber world,
    JSNumber temperature,
    JSNumber density,
  );
  @JS('f3d_world_get_air')
  external void f3d_world_get_air(JSNumber world, JSNumber out);
  @JS('f3d_world_set_wind')
  external void f3d_world_set_wind(
    JSNumber world,
    JSNumber x,
    JSNumber y,
    JSNumber z,
  );
  @JS('f3d_world_set_wind_grid')
  external JSNumber f3d_world_set_wind_grid(
    JSNumber world,
    JSNumber ox,
    JSNumber oy,
    JSNumber oz,
    JSNumber cell,
    JSNumber nx,
    JSNumber ny,
    JSNumber nz,
    JSNumber velocities,
  );
  @JS('f3d_world_sample_wind')
  external void f3d_world_sample_wind(
    JSNumber world,
    JSNumber x,
    JSNumber y,
    JSNumber z,
    JSNumber out,
  );
  @JS('f3d_world_set_sleep')
  external JSNumber f3d_world_set_sleep(
    JSNumber world,
    JSNumber speed,
    JSNumber time,
  );
  @JS('f3d_world_get_origin')
  external void f3d_world_get_origin(JSNumber world, JSNumber out);
  @JS('f3d_world_shift_origin')
  external void f3d_world_shift_origin(
    JSNumber world,
    JSNumber dx,
    JSNumber dy,
    JSNumber dz,
  );
  @JS('f3d_world_create_hull')
  external JSNumber f3d_world_create_hull(
    JSNumber world,
    JSNumber points,
    JSNumber count,
  );
  @JS('f3d_world_create_mesh')
  external JSNumber f3d_world_create_mesh(
    JSNumber world,
    JSNumber vertices,
    JSNumber vertexCount,
    JSNumber indices,
    JSNumber triangleCount,
  );
  @JS('f3d_world_mesh_triangle_count')
  external JSNumber f3d_world_mesh_triangle_count(
    JSNumber world,
    JSNumber mesh,
  );
  @JS('f3d_world_mesh_internal_edges')
  external JSNumber f3d_world_mesh_internal_edges(
    JSNumber world,
    JSNumber mesh,
  );
  @JS('f3d_world_get_hull_offset')
  external JSNumber f3d_world_get_hull_offset(
    JSNumber world,
    JSNumber hull,
    JSNumber out,
  );
  @JS('f3d_world_hull_vertex_count')
  external JSNumber f3d_world_hull_vertex_count(JSNumber world, JSNumber hull);
  @JS('f3d_world_body_count')
  external JSNumber f3d_world_body_count(JSNumber world);
  @JS('f3d_world_step')
  external void f3d_world_step(JSNumber world, JSNumber dt);
  @JS('f3d_world_set_threads')
  external JSNumber f3d_world_set_threads(JSNumber world, JSNumber threads);
  @JS('f3d_world_threads')
  external JSNumber f3d_world_threads(JSNumber world);
  @JS('f3d_world_set_fast')
  external JSNumber f3d_world_set_fast(JSNumber world, JSNumber fast);
  @JS('f3d_world_fast')
  external JSNumber f3d_world_fast(JSNumber world);
  @JS('f3d_world_read_transforms')
  external JSNumber f3d_world_read_transforms(
    JSNumber world,
    JSNumber transforms,
    JSNumber handles,
    JSNumber capacity,
  );
  @JS('f3d_world_read_fires')
  external JSNumber f3d_world_read_fires(
    JSNumber world,
    JSNumber fires,
    JSNumber handles,
    JSNumber capacity,
  );
  @JS('f3d_world_read_events')
  external JSNumber f3d_world_read_events(
    JSNumber world,
    JSNumber bodies,
    JSNumber others,
    JSNumber kinds,
    JSNumber capacity,
  );
  @JS('f3d_world_set_substeps')
  external JSNumber f3d_world_set_substeps(JSNumber world, JSNumber substeps);
  @JS('f3d_world_set_speculative')
  external JSNumber f3d_world_set_speculative(JSNumber world, JSNumber enabled);
  @JS('f3d_world_set_contact_margin')
  external JSNumber f3d_world_set_contact_margin(
    JSNumber world,
    JSNumber margin,
  );
  @JS('f3d_world_query_box')
  external JSNumber f3d_world_query_box(
    JSNumber world,
    JSNumber lx,
    JSNumber ly,
    JSNumber lz,
    JSNumber hx,
    JSNumber hy,
    JSNumber hz,
    JSNumber out,
    JSNumber capacity,
  );
  @JS('f3d_world_contact_count')
  external JSNumber f3d_world_contact_count(JSNumber world);
  @JS('f3d_world_read_contacts')
  external JSNumber f3d_world_read_contacts(
    JSNumber world,
    JSNumber contacts,
    JSNumber pairs,
    JSNumber capacity,
  );
  @JS('f3d_world_events_dropped')
  external JSNumber f3d_world_events_dropped(JSNumber world);
  @JS('f3d_joint_create__w')
  external JSNumber f3d_joint_create(
    JSNumber world,
    JSNumber type,
    JSNumber aLow,
    JSNumber aHigh,
    JSNumber bLow,
    JSNumber bHigh,
    JSNumber ax,
    JSNumber ay,
    JSNumber az,
    JSNumber ux,
    JSNumber uy,
    JSNumber uz,
  );
  @JS('f3d_joint_create_distance__w')
  external JSNumber f3d_joint_create_distance(
    JSNumber world,
    JSNumber aLow,
    JSNumber aHigh,
    JSNumber bLow,
    JSNumber bHigh,
    JSNumber ax,
    JSNumber ay,
    JSNumber az,
    JSNumber bx,
    JSNumber by,
    JSNumber bz,
  );
  @JS('f3d_joint_destroy__w')
  external JSNumber f3d_joint_destroy(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
  );
  @JS('f3d_joint_is_valid__w')
  external JSNumber f3d_joint_is_valid(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
  );
  @JS('f3d_world_joint_count')
  external JSNumber f3d_world_joint_count(JSNumber world);
  @JS('f3d_joint_set_limits__w')
  external JSNumber f3d_joint_set_limits(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
    JSNumber enabled,
    JSNumber lower,
    JSNumber upper,
  );
  @JS('f3d_joint_set_cone__w')
  external JSNumber f3d_joint_set_cone(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
    JSNumber enabled,
    JSNumber angle,
  );
  @JS('f3d_joint_set_friction__w')
  external JSNumber f3d_joint_set_friction(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
    JSNumber enabled,
    JSNumber torque,
  );
  @JS('f3d_joint_set_motor__w')
  external JSNumber f3d_joint_set_motor(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
    JSNumber enabled,
    JSNumber speed,
    JSNumber maxForce,
  );
  @JS('f3d_joint_set_spring__w')
  external JSNumber f3d_joint_set_spring(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
    JSNumber enabled,
    JSNumber hertz,
    JSNumber damping,
  );
  @JS('f3d_joint_set_length__w')
  external JSNumber f3d_joint_set_length(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
    JSNumber length,
    JSNumber least,
    JSNumber most,
  );
  @JS('f3d_joint_set_collide__w')
  external JSNumber f3d_joint_set_collide(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
    JSNumber collide,
  );
  @JS('f3d_joint_get_value__w')
  external JSNumber f3d_joint_get_value(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
    JSNumber out,
  );
  @JS('f3d_joint_get_swing__w')
  external JSNumber f3d_joint_get_swing(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
    JSNumber out,
  );
  @JS('f3d_joint_get_force__w')
  external JSNumber f3d_joint_get_force(
    JSNumber world,
    JSNumber jointLow,
    JSNumber jointHigh,
    JSNumber out,
  );
  @JS('f3d_world_ray_cast__w')
  external JSNumber f3d_world_ray_cast(
    JSNumber world,
    JSNumber ox,
    JSNumber oy,
    JSNumber oz,
    JSNumber dx,
    JSNumber dy,
    JSNumber dz,
    JSNumber maxDistance,
    JSNumber mask,
    JSNumber ignoreLow,
    JSNumber ignoreHigh,
    JSNumber body,
    JSNumber hit,
  );
  @JS('f3d_world_ray_cast_all__w')
  external JSNumber f3d_world_ray_cast_all(
    JSNumber world,
    JSNumber ox,
    JSNumber oy,
    JSNumber oz,
    JSNumber dx,
    JSNumber dy,
    JSNumber dz,
    JSNumber maxDistance,
    JSNumber mask,
    JSNumber ignoreLow,
    JSNumber ignoreHigh,
    JSNumber bodies,
    JSNumber hits,
    JSNumber capacity,
  );
  @JS('f3d_world_overlap_shape__w')
  external JSNumber f3d_world_overlap_shape(
    JSNumber world,
    JSNumber kind,
    JSNumber a,
    JSNumber b,
    JSNumber c,
    JSNumber rounding,
    JSNumber px,
    JSNumber py,
    JSNumber pz,
    JSNumber qx,
    JSNumber qy,
    JSNumber qz,
    JSNumber qw,
    JSNumber mask,
    JSNumber ignoreLow,
    JSNumber ignoreHigh,
    JSNumber out,
    JSNumber capacity,
  );
  @JS('f3d_world_cast_shape__w')
  external JSNumber f3d_world_cast_shape(
    JSNumber world,
    JSNumber kind,
    JSNumber a,
    JSNumber b,
    JSNumber c,
    JSNumber rounding,
    JSNumber px,
    JSNumber py,
    JSNumber pz,
    JSNumber qx,
    JSNumber qy,
    JSNumber qz,
    JSNumber qw,
    JSNumber tx,
    JSNumber ty,
    JSNumber tz,
    JSNumber mask,
    JSNumber ignoreLow,
    JSNumber ignoreHigh,
    JSNumber body,
    JSNumber hit,
  );
  @JS('f3d_world_move_character__w')
  external JSNumber f3d_world_move_character(
    JSNumber world,
    JSNumber radius,
    JSNumber halfHeight,
    JSNumber position,
    JSNumber dx,
    JSNumber dy,
    JSNumber dz,
    JSNumber maxSlopeCos,
    JSNumber stepHeight,
    JSNumber mask,
    JSNumber ignoreLow,
    JSNumber ignoreHigh,
    JSNumber groundBody,
    JSNumber ground,
  );
  @JS('f3d_particles_create')
  external JSNumber f3d_particles_create(JSNumber capacity);
  @JS('f3d_particles_destroy')
  external void f3d_particles_destroy(JSNumber particles);
  @JS('f3d_particles_capacity')
  external JSNumber f3d_particles_capacity(JSNumber particles);
  @JS('f3d_particles_emit')
  external JSNumber f3d_particles_emit(
    JSNumber particles,
    JSNumber particlesData,
    JSNumber count,
  );
  @JS('f3d_particles_step')
  external void f3d_particles_step(
    JSNumber particles,
    JSNumber forces,
    JSNumber dt,
  );
  @JS('f3d_particles_read')
  external JSNumber f3d_particles_read(
    JSNumber particles,
    JSNumber out,
    JSNumber capacity,
  );
  @JS('f3d_debris_create')
  external JSNumber f3d_debris_create(JSNumber capacity);
  @JS('f3d_debris_destroy')
  external void f3d_debris_destroy(JSNumber debris);
  @JS('f3d_debris_capacity')
  external JSNumber f3d_debris_capacity(JSNumber debris);
  @JS('f3d_debris_add')
  external JSNumber f3d_debris_add(
    JSNumber debris,
    JSNumber data,
    JSNumber count,
  );
  @JS('f3d_debris_set_statics')
  external JSNumber f3d_debris_set_statics(
    JSNumber debris,
    JSNumber data,
    JSNumber count,
  );
  @JS('f3d_debris_step')
  external void f3d_debris_step(
    JSNumber debris,
    JSNumber settings,
    JSNumber dt,
  );
  @JS('f3d_debris_read')
  external JSNumber f3d_debris_read(
    JSNumber debris,
    JSNumber out,
    JSNumber capacity,
  );
  @JS('f3d_cloth_create')
  external JSNumber f3d_cloth_create(
    JSNumber points,
    JSNumber pointCount,
    JSNumber edges,
    JSNumber compliance,
    JSNumber edgeCount,
  );
  @JS('f3d_cloth_destroy')
  external void f3d_cloth_destroy(JSNumber cloth);
  @JS('f3d_cloth_point_count')
  external JSNumber f3d_cloth_point_count(JSNumber cloth);
  @JS('f3d_cloth_colour_count')
  external JSNumber f3d_cloth_colour_count(JSNumber cloth);
  @JS('f3d_cloth_edge_count')
  external JSNumber f3d_cloth_edge_count(JSNumber cloth);
  @JS('f3d_cloth_edges')
  external void f3d_cloth_edges(
    JSNumber cloth,
    JSNumber pairs,
    JSNumber rest,
    JSNumber compliance,
    JSNumber colourStart,
  );
  @JS('f3d_cloth_set_balls')
  external JSNumber f3d_cloth_set_balls(
    JSNumber cloth,
    JSNumber balls,
    JSNumber count,
  );
  @JS('f3d_cloth_move_point')
  external void f3d_cloth_move_point(
    JSNumber cloth,
    JSNumber index,
    JSNumber x,
    JSNumber y,
    JSNumber z,
  );
  @JS('f3d_cloth_step')
  external void f3d_cloth_step(JSNumber cloth, JSNumber settings, JSNumber dt);
  @JS('f3d_cloth_read')
  external JSNumber f3d_cloth_read(
    JSNumber cloth,
    JSNumber out,
    JSNumber capacity,
  );
  @JS('f3d_fluid_create')
  external JSNumber f3d_fluid_create(JSNumber capacity, JSNumber spacing);
  @JS('f3d_fluid_destroy')
  external void f3d_fluid_destroy(JSNumber fluid);
  @JS('f3d_fluid_capacity')
  external JSNumber f3d_fluid_capacity(JSNumber fluid);
  @JS('f3d_fluid_rest_density')
  external JSNumber f3d_fluid_rest_density(JSNumber fluid);
  @JS('f3d_fluid_add')
  external JSNumber f3d_fluid_add(
    JSNumber fluid,
    JSNumber data,
    JSNumber count,
  );
  @JS('f3d_fluid_step')
  external void f3d_fluid_step(JSNumber fluid, JSNumber settings, JSNumber dt);
  @JS('f3d_fluid_read')
  external JSNumber f3d_fluid_read(
    JSNumber fluid,
    JSNumber out,
    JSNumber capacity,
  );
  @JS('f3d_world_snapshot_size')
  external JSNumber f3d_world_snapshot_size(JSNumber world);
  @JS('f3d_world_snapshot_write')
  external JSNumber f3d_world_snapshot_write(
    JSNumber world,
    JSNumber buffer,
    JSNumber size,
  );
  @JS('f3d_world_restore')
  external JSNumber f3d_world_restore(
    JSNumber world,
    JSNumber buffer,
    JSNumber size,
  );
  @JS('f3d_body_create__w')
  external JSNumber f3d_body_create(
    JSNumber world,
    JSNumber type,
    JSNumber px,
    JSNumber py,
    JSNumber pz,
    JSNumber mass,
  );
  @JS('f3d_body_destroy__w')
  external JSNumber f3d_body_destroy(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
  );
  @JS('f3d_body_is_valid__w')
  external JSNumber f3d_body_is_valid(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
  );
  @JS('f3d_body_set_velocity__w')
  external JSNumber f3d_body_set_velocity(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber x,
    JSNumber y,
    JSNumber z,
  );
  @JS('f3d_body_get_velocity__w')
  external JSNumber f3d_body_get_velocity(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_set_position__w')
  external JSNumber f3d_body_set_position(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber x,
    JSNumber y,
    JSNumber z,
  );
  @JS('f3d_body_get_position__w')
  external JSNumber f3d_body_get_position(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_get_world_position__w')
  external JSNumber f3d_body_get_world_position(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_set_angular_velocity__w')
  external JSNumber f3d_body_set_angular_velocity(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber x,
    JSNumber y,
    JSNumber z,
  );
  @JS('f3d_body_get_angular_velocity__w')
  external JSNumber f3d_body_get_angular_velocity(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_set_orientation__w')
  external JSNumber f3d_body_set_orientation(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber x,
    JSNumber y,
    JSNumber z,
    JSNumber w,
  );
  @JS('f3d_body_get_orientation__w')
  external JSNumber f3d_body_get_orientation(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_set_shape__w')
  external JSNumber f3d_body_set_shape(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber kind,
    JSNumber a,
    JSNumber b,
    JSNumber c,
  );
  @JS('f3d_body_get_inertia__w')
  external JSNumber f3d_body_get_inertia(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_get_inertia_tensor__w')
  external JSNumber f3d_body_get_inertia_tensor(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_set_rounding__w')
  external JSNumber f3d_body_set_rounding(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber radius,
  );
  @JS('f3d_body_set_hull__w')
  external JSNumber f3d_body_set_hull(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber hull,
  );
  @JS('f3d_body_set_mesh__w')
  external JSNumber f3d_body_set_mesh(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber mesh,
  );
  @JS('f3d_body_get_mass__w')
  external JSNumber f3d_body_get_mass(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_lock_rotation__w')
  external JSNumber f3d_body_lock_rotation(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber locked,
  );
  @JS('f3d_body_set_damping__w')
  external JSNumber f3d_body_set_damping(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber linear,
    JSNumber angular,
  );
  @JS('f3d_body_set_drag__w')
  external JSNumber f3d_body_set_drag(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber coefficient,
  );
  @JS('f3d_body_apply_impulse__w')
  external JSNumber f3d_body_apply_impulse(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber x,
    JSNumber y,
    JSNumber z,
  );
  @JS('f3d_body_apply_impulse_at__w')
  external JSNumber f3d_body_apply_impulse_at(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber x,
    JSNumber y,
    JSNumber z,
    JSNumber px,
    JSNumber py,
    JSNumber pz,
  );
  @JS('f3d_body_add_force__w')
  external JSNumber f3d_body_add_force(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber x,
    JSNumber y,
    JSNumber z,
  );
  @JS('f3d_body_add_torque__w')
  external JSNumber f3d_body_add_torque(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber x,
    JSNumber y,
    JSNumber z,
  );
  @JS('f3d_body_set_bullet__w')
  external JSNumber f3d_body_set_bullet(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber bullet,
  );
  @JS('f3d_body_set_friction__w')
  external JSNumber f3d_body_set_friction(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber friction,
  );
  @JS('f3d_body_set_restitution__w')
  external JSNumber f3d_body_set_restitution(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber restitution,
  );
  @JS('f3d_body_set_collision_filter__w')
  external JSNumber f3d_body_set_collision_filter(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber layer,
    JSNumber mask,
  );
  @JS('f3d_body_is_asleep__w')
  external JSNumber f3d_body_is_asleep(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
  );
  @JS('f3d_body_wake__w')
  external JSNumber f3d_body_wake(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
  );
  @JS('f3d_material_preset')
  external JSNumber f3d_material_preset(JSNumber kind, JSNumber out);
  @JS('f3d_body_set_material__w')
  external JSNumber f3d_body_set_material(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber material,
  );
  @JS('f3d_body_set_temperature__w')
  external JSNumber f3d_body_set_temperature(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber kelvin,
  );
  @JS('f3d_body_get_temperature__w')
  external JSNumber f3d_body_get_temperature(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_add_heat__w')
  external JSNumber f3d_body_add_heat(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber joules,
  );
  @JS('f3d_body_add_water__w')
  external JSNumber f3d_body_add_water(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber kg,
  );
  @JS('f3d_body_get_water__w')
  external JSNumber f3d_body_get_water(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_get_fuel__w')
  external JSNumber f3d_body_get_fuel(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_is_burning__w')
  external JSNumber f3d_body_is_burning(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
  @JS('f3d_body_get_heat_release__w')
  external JSNumber f3d_body_get_heat_release(
    JSNumber world,
    JSNumber bodyLow,
    JSNumber bodyHigh,
    JSNumber out,
  );
}

_Exports get _x => coreExports as _Exports;
int f3d_abi_version() => _x.f3d_abi_version().toDartInt.toUnsigned(32);
int f3d_real_bytes() => _x.f3d_real_bytes().toDartInt.toUnsigned(32);
int f3d_buffer_alloc(int bytes) =>
    _x.f3d_buffer_alloc(bytes.toJS).toDartInt.toUnsigned(32);
void f3d_buffer_free(int buffer) => _x.f3d_buffer_free(buffer.toJS);
int f3d_world_create() => _x.f3d_world_create().toDartInt.toUnsigned(32);
void f3d_world_destroy(int world) => _x.f3d_world_destroy(world.toJS);
void f3d_world_set_gravity(int world, double x, double y, double z) =>
    _x.f3d_world_set_gravity(world.toJS, x.toJS, y.toJS, z.toJS);
void f3d_world_get_gravity(int world, int out) =>
    _x.f3d_world_get_gravity(world.toJS, out.toJS);
int f3d_world_set_air(int world, double temperature, double density) =>
    _x.f3d_world_set_air(world.toJS, temperature.toJS, density.toJS).toDartInt;
void f3d_world_get_air(int world, int out) =>
    _x.f3d_world_get_air(world.toJS, out.toJS);
void f3d_world_set_wind(int world, double x, double y, double z) =>
    _x.f3d_world_set_wind(world.toJS, x.toJS, y.toJS, z.toJS);
int f3d_world_set_wind_grid(
  int world,
  double ox,
  double oy,
  double oz,
  double cell,
  int nx,
  int ny,
  int nz,
  int velocities,
) => _x
    .f3d_world_set_wind_grid(
      world.toJS,
      ox.toJS,
      oy.toJS,
      oz.toJS,
      cell.toJS,
      nx.toJS,
      ny.toJS,
      nz.toJS,
      velocities.toJS,
    )
    .toDartInt;
void f3d_world_sample_wind(int world, double x, double y, double z, int out) =>
    _x.f3d_world_sample_wind(world.toJS, x.toJS, y.toJS, z.toJS, out.toJS);
int f3d_world_set_sleep(int world, double speed, double time) =>
    _x.f3d_world_set_sleep(world.toJS, speed.toJS, time.toJS).toDartInt;
void f3d_world_get_origin(int world, int out) =>
    _x.f3d_world_get_origin(world.toJS, out.toJS);
void f3d_world_shift_origin(int world, double dx, double dy, double dz) =>
    _x.f3d_world_shift_origin(world.toJS, dx.toJS, dy.toJS, dz.toJS);
int f3d_world_create_hull(int world, int points, int count) => _x
    .f3d_world_create_hull(world.toJS, points.toJS, count.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_world_create_mesh(
  int world,
  int vertices,
  int vertexCount,
  int indices,
  int triangleCount,
) => _x
    .f3d_world_create_mesh(
      world.toJS,
      vertices.toJS,
      vertexCount.toJS,
      indices.toJS,
      triangleCount.toJS,
    )
    .toDartInt
    .toUnsigned(32);
int f3d_world_mesh_triangle_count(int world, int mesh) => _x
    .f3d_world_mesh_triangle_count(world.toJS, mesh.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_world_mesh_internal_edges(int world, int mesh) => _x
    .f3d_world_mesh_internal_edges(world.toJS, mesh.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_world_get_hull_offset(int world, int hull, int out) =>
    _x.f3d_world_get_hull_offset(world.toJS, hull.toJS, out.toJS).toDartInt;
int f3d_world_hull_vertex_count(int world, int hull) => _x
    .f3d_world_hull_vertex_count(world.toJS, hull.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_world_body_count(int world) =>
    _x.f3d_world_body_count(world.toJS).toDartInt.toUnsigned(32);
void f3d_world_step(int world, double dt) =>
    _x.f3d_world_step(world.toJS, dt.toJS);
int f3d_world_set_threads(int world, int threads) =>
    _x.f3d_world_set_threads(world.toJS, threads.toJS).toDartInt;
int f3d_world_threads(int world) =>
    _x.f3d_world_threads(world.toJS).toDartInt.toUnsigned(32);
int f3d_world_set_fast(int world, int fast) =>
    _x.f3d_world_set_fast(world.toJS, fast.toJS).toDartInt;
int f3d_world_fast(int world) => _x.f3d_world_fast(world.toJS).toDartInt;
int f3d_world_read_transforms(
  int world,
  int transforms,
  int handles,
  int capacity,
) => _x
    .f3d_world_read_transforms(
      world.toJS,
      transforms.toJS,
      handles.toJS,
      capacity.toJS,
    )
    .toDartInt
    .toUnsigned(32);
int f3d_world_read_fires(int world, int fires, int handles, int capacity) => _x
    .f3d_world_read_fires(world.toJS, fires.toJS, handles.toJS, capacity.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_world_read_events(
  int world,
  int bodies,
  int others,
  int kinds,
  int capacity,
) => _x
    .f3d_world_read_events(
      world.toJS,
      bodies.toJS,
      others.toJS,
      kinds.toJS,
      capacity.toJS,
    )
    .toDartInt
    .toUnsigned(32);
int f3d_world_set_substeps(int world, int substeps) =>
    _x.f3d_world_set_substeps(world.toJS, substeps.toJS).toDartInt;
int f3d_world_set_speculative(int world, int enabled) =>
    _x.f3d_world_set_speculative(world.toJS, enabled.toJS).toDartInt;
int f3d_world_set_contact_margin(int world, double margin) =>
    _x.f3d_world_set_contact_margin(world.toJS, margin.toJS).toDartInt;
int f3d_world_query_box(
  int world,
  double lx,
  double ly,
  double lz,
  double hx,
  double hy,
  double hz,
  int out,
  int capacity,
) => _x
    .f3d_world_query_box(
      world.toJS,
      lx.toJS,
      ly.toJS,
      lz.toJS,
      hx.toJS,
      hy.toJS,
      hz.toJS,
      out.toJS,
      capacity.toJS,
    )
    .toDartInt
    .toUnsigned(32);
int f3d_world_contact_count(int world) =>
    _x.f3d_world_contact_count(world.toJS).toDartInt.toUnsigned(32);
int f3d_world_read_contacts(int world, int contacts, int pairs, int capacity) =>
    _x
        .f3d_world_read_contacts(
          world.toJS,
          contacts.toJS,
          pairs.toJS,
          capacity.toJS,
        )
        .toDartInt
        .toUnsigned(32);
int f3d_world_events_dropped(int world) =>
    _x.f3d_world_events_dropped(world.toJS).toDartInt.toUnsigned(32);
int f3d_joint_create(
  int world,
  int type,
  int a,
  int b,
  double ax,
  double ay,
  double az,
  double ux,
  double uy,
  double uz,
) => joinHalves(
  _x
      .f3d_joint_create(
        world.toJS,
        type.toJS,
        lowHalf(a).toJS,
        highHalf(a).toJS,
        lowHalf(b).toJS,
        highHalf(b).toJS,
        ax.toJS,
        ay.toJS,
        az.toJS,
        ux.toJS,
        uy.toJS,
        uz.toJS,
      )
      .toDartInt,
  highResult(),
);
int f3d_joint_create_distance(
  int world,
  int a,
  int b,
  double ax,
  double ay,
  double az,
  double bx,
  double by,
  double bz,
) => joinHalves(
  _x
      .f3d_joint_create_distance(
        world.toJS,
        lowHalf(a).toJS,
        highHalf(a).toJS,
        lowHalf(b).toJS,
        highHalf(b).toJS,
        ax.toJS,
        ay.toJS,
        az.toJS,
        bx.toJS,
        by.toJS,
        bz.toJS,
      )
      .toDartInt,
  highResult(),
);
int f3d_joint_destroy(int world, int joint) => _x
    .f3d_joint_destroy(world.toJS, lowHalf(joint).toJS, highHalf(joint).toJS)
    .toDartInt;
int f3d_joint_is_valid(int world, int joint) => _x
    .f3d_joint_is_valid(world.toJS, lowHalf(joint).toJS, highHalf(joint).toJS)
    .toDartInt;
int f3d_world_joint_count(int world) =>
    _x.f3d_world_joint_count(world.toJS).toDartInt.toUnsigned(32);
int f3d_joint_set_limits(
  int world,
  int joint,
  int enabled,
  double lower,
  double upper,
) => _x
    .f3d_joint_set_limits(
      world.toJS,
      lowHalf(joint).toJS,
      highHalf(joint).toJS,
      enabled.toJS,
      lower.toJS,
      upper.toJS,
    )
    .toDartInt;
int f3d_joint_set_cone(int world, int joint, int enabled, double angle) => _x
    .f3d_joint_set_cone(
      world.toJS,
      lowHalf(joint).toJS,
      highHalf(joint).toJS,
      enabled.toJS,
      angle.toJS,
    )
    .toDartInt;
int f3d_joint_set_friction(int world, int joint, int enabled, double torque) =>
    _x
        .f3d_joint_set_friction(
          world.toJS,
          lowHalf(joint).toJS,
          highHalf(joint).toJS,
          enabled.toJS,
          torque.toJS,
        )
        .toDartInt;
int f3d_joint_set_motor(
  int world,
  int joint,
  int enabled,
  double speed,
  double maxForce,
) => _x
    .f3d_joint_set_motor(
      world.toJS,
      lowHalf(joint).toJS,
      highHalf(joint).toJS,
      enabled.toJS,
      speed.toJS,
      maxForce.toJS,
    )
    .toDartInt;
int f3d_joint_set_spring(
  int world,
  int joint,
  int enabled,
  double hertz,
  double damping,
) => _x
    .f3d_joint_set_spring(
      world.toJS,
      lowHalf(joint).toJS,
      highHalf(joint).toJS,
      enabled.toJS,
      hertz.toJS,
      damping.toJS,
    )
    .toDartInt;
int f3d_joint_set_length(
  int world,
  int joint,
  double length,
  double least,
  double most,
) => _x
    .f3d_joint_set_length(
      world.toJS,
      lowHalf(joint).toJS,
      highHalf(joint).toJS,
      length.toJS,
      least.toJS,
      most.toJS,
    )
    .toDartInt;
int f3d_joint_set_collide(int world, int joint, int collide) => _x
    .f3d_joint_set_collide(
      world.toJS,
      lowHalf(joint).toJS,
      highHalf(joint).toJS,
      collide.toJS,
    )
    .toDartInt;
int f3d_joint_get_value(int world, int joint, int out) => _x
    .f3d_joint_get_value(
      world.toJS,
      lowHalf(joint).toJS,
      highHalf(joint).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_joint_get_swing(int world, int joint, int out) => _x
    .f3d_joint_get_swing(
      world.toJS,
      lowHalf(joint).toJS,
      highHalf(joint).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_joint_get_force(int world, int joint, int out) => _x
    .f3d_joint_get_force(
      world.toJS,
      lowHalf(joint).toJS,
      highHalf(joint).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_world_ray_cast(
  int world,
  double ox,
  double oy,
  double oz,
  double dx,
  double dy,
  double dz,
  double maxDistance,
  int mask,
  int ignore,
  int body,
  int hit,
) => _x
    .f3d_world_ray_cast(
      world.toJS,
      ox.toJS,
      oy.toJS,
      oz.toJS,
      dx.toJS,
      dy.toJS,
      dz.toJS,
      maxDistance.toJS,
      mask.toJS,
      lowHalf(ignore).toJS,
      highHalf(ignore).toJS,
      body.toJS,
      hit.toJS,
    )
    .toDartInt;
int f3d_world_ray_cast_all(
  int world,
  double ox,
  double oy,
  double oz,
  double dx,
  double dy,
  double dz,
  double maxDistance,
  int mask,
  int ignore,
  int bodies,
  int hits,
  int capacity,
) => _x
    .f3d_world_ray_cast_all(
      world.toJS,
      ox.toJS,
      oy.toJS,
      oz.toJS,
      dx.toJS,
      dy.toJS,
      dz.toJS,
      maxDistance.toJS,
      mask.toJS,
      lowHalf(ignore).toJS,
      highHalf(ignore).toJS,
      bodies.toJS,
      hits.toJS,
      capacity.toJS,
    )
    .toDartInt
    .toUnsigned(32);
int f3d_world_overlap_shape(
  int world,
  int kind,
  double a,
  double b,
  double c,
  double rounding,
  double px,
  double py,
  double pz,
  double qx,
  double qy,
  double qz,
  double qw,
  int mask,
  int ignore,
  int out,
  int capacity,
) => _x
    .f3d_world_overlap_shape(
      world.toJS,
      kind.toJS,
      a.toJS,
      b.toJS,
      c.toJS,
      rounding.toJS,
      px.toJS,
      py.toJS,
      pz.toJS,
      qx.toJS,
      qy.toJS,
      qz.toJS,
      qw.toJS,
      mask.toJS,
      lowHalf(ignore).toJS,
      highHalf(ignore).toJS,
      out.toJS,
      capacity.toJS,
    )
    .toDartInt
    .toUnsigned(32);
int f3d_world_cast_shape(
  int world,
  int kind,
  double a,
  double b,
  double c,
  double rounding,
  double px,
  double py,
  double pz,
  double qx,
  double qy,
  double qz,
  double qw,
  double tx,
  double ty,
  double tz,
  int mask,
  int ignore,
  int body,
  int hit,
) => _x
    .f3d_world_cast_shape(
      world.toJS,
      kind.toJS,
      a.toJS,
      b.toJS,
      c.toJS,
      rounding.toJS,
      px.toJS,
      py.toJS,
      pz.toJS,
      qx.toJS,
      qy.toJS,
      qz.toJS,
      qw.toJS,
      tx.toJS,
      ty.toJS,
      tz.toJS,
      mask.toJS,
      lowHalf(ignore).toJS,
      highHalf(ignore).toJS,
      body.toJS,
      hit.toJS,
    )
    .toDartInt;
int f3d_world_move_character(
  int world,
  double radius,
  double halfHeight,
  int position,
  double dx,
  double dy,
  double dz,
  double maxSlopeCos,
  double stepHeight,
  int mask,
  int ignore,
  int groundBody,
  int ground,
) => _x
    .f3d_world_move_character(
      world.toJS,
      radius.toJS,
      halfHeight.toJS,
      position.toJS,
      dx.toJS,
      dy.toJS,
      dz.toJS,
      maxSlopeCos.toJS,
      stepHeight.toJS,
      mask.toJS,
      lowHalf(ignore).toJS,
      highHalf(ignore).toJS,
      groundBody.toJS,
      ground.toJS,
    )
    .toDartInt
    .toUnsigned(32);
int f3d_particles_create(int capacity) =>
    _x.f3d_particles_create(capacity.toJS).toDartInt.toUnsigned(32);
void f3d_particles_destroy(int particles) =>
    _x.f3d_particles_destroy(particles.toJS);
int f3d_particles_capacity(int particles) =>
    _x.f3d_particles_capacity(particles.toJS).toDartInt.toUnsigned(32);
int f3d_particles_emit(int particles, int particlesData, int count) => _x
    .f3d_particles_emit(particles.toJS, particlesData.toJS, count.toJS)
    .toDartInt
    .toUnsigned(32);
void f3d_particles_step(int particles, int forces, double dt) =>
    _x.f3d_particles_step(particles.toJS, forces.toJS, dt.toJS);
int f3d_particles_read(int particles, int out, int capacity) => _x
    .f3d_particles_read(particles.toJS, out.toJS, capacity.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_debris_create(int capacity) =>
    _x.f3d_debris_create(capacity.toJS).toDartInt.toUnsigned(32);
void f3d_debris_destroy(int debris) => _x.f3d_debris_destroy(debris.toJS);
int f3d_debris_capacity(int debris) =>
    _x.f3d_debris_capacity(debris.toJS).toDartInt.toUnsigned(32);
int f3d_debris_add(int debris, int data, int count) => _x
    .f3d_debris_add(debris.toJS, data.toJS, count.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_debris_set_statics(int debris, int data, int count) =>
    _x.f3d_debris_set_statics(debris.toJS, data.toJS, count.toJS).toDartInt;
void f3d_debris_step(int debris, int settings, double dt) =>
    _x.f3d_debris_step(debris.toJS, settings.toJS, dt.toJS);
int f3d_debris_read(int debris, int out, int capacity) => _x
    .f3d_debris_read(debris.toJS, out.toJS, capacity.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_cloth_create(
  int points,
  int pointCount,
  int edges,
  int compliance,
  int edgeCount,
) => _x
    .f3d_cloth_create(
      points.toJS,
      pointCount.toJS,
      edges.toJS,
      compliance.toJS,
      edgeCount.toJS,
    )
    .toDartInt
    .toUnsigned(32);
void f3d_cloth_destroy(int cloth) => _x.f3d_cloth_destroy(cloth.toJS);
int f3d_cloth_point_count(int cloth) =>
    _x.f3d_cloth_point_count(cloth.toJS).toDartInt.toUnsigned(32);
int f3d_cloth_colour_count(int cloth) =>
    _x.f3d_cloth_colour_count(cloth.toJS).toDartInt.toUnsigned(32);
int f3d_cloth_edge_count(int cloth) =>
    _x.f3d_cloth_edge_count(cloth.toJS).toDartInt.toUnsigned(32);
void f3d_cloth_edges(
  int cloth,
  int pairs,
  int rest,
  int compliance,
  int colourStart,
) => _x.f3d_cloth_edges(
  cloth.toJS,
  pairs.toJS,
  rest.toJS,
  compliance.toJS,
  colourStart.toJS,
);
int f3d_cloth_set_balls(int cloth, int balls, int count) =>
    _x.f3d_cloth_set_balls(cloth.toJS, balls.toJS, count.toJS).toDartInt;
void f3d_cloth_move_point(int cloth, int index, double x, double y, double z) =>
    _x.f3d_cloth_move_point(cloth.toJS, index.toJS, x.toJS, y.toJS, z.toJS);
void f3d_cloth_step(int cloth, int settings, double dt) =>
    _x.f3d_cloth_step(cloth.toJS, settings.toJS, dt.toJS);
int f3d_cloth_read(int cloth, int out, int capacity) => _x
    .f3d_cloth_read(cloth.toJS, out.toJS, capacity.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_fluid_create(int capacity, double spacing) =>
    _x.f3d_fluid_create(capacity.toJS, spacing.toJS).toDartInt.toUnsigned(32);
void f3d_fluid_destroy(int fluid) => _x.f3d_fluid_destroy(fluid.toJS);
int f3d_fluid_capacity(int fluid) =>
    _x.f3d_fluid_capacity(fluid.toJS).toDartInt.toUnsigned(32);
double f3d_fluid_rest_density(int fluid) =>
    _x.f3d_fluid_rest_density(fluid.toJS).toDartDouble;
int f3d_fluid_add(int fluid, int data, int count) => _x
    .f3d_fluid_add(fluid.toJS, data.toJS, count.toJS)
    .toDartInt
    .toUnsigned(32);
void f3d_fluid_step(int fluid, int settings, double dt) =>
    _x.f3d_fluid_step(fluid.toJS, settings.toJS, dt.toJS);
int f3d_fluid_read(int fluid, int out, int capacity) => _x
    .f3d_fluid_read(fluid.toJS, out.toJS, capacity.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_world_snapshot_size(int world) =>
    _x.f3d_world_snapshot_size(world.toJS).toDartInt.toUnsigned(32);
int f3d_world_snapshot_write(int world, int buffer, int size) => _x
    .f3d_world_snapshot_write(world.toJS, buffer.toJS, size.toJS)
    .toDartInt
    .toUnsigned(32);
int f3d_world_restore(int world, int buffer, int size) =>
    _x.f3d_world_restore(world.toJS, buffer.toJS, size.toJS).toDartInt;
int f3d_body_create(
  int world,
  int type,
  double px,
  double py,
  double pz,
  double mass,
) => joinHalves(
  _x
      .f3d_body_create(
        world.toJS,
        type.toJS,
        px.toJS,
        py.toJS,
        pz.toJS,
        mass.toJS,
      )
      .toDartInt,
  highResult(),
);
int f3d_body_destroy(int world, int body) => _x
    .f3d_body_destroy(world.toJS, lowHalf(body).toJS, highHalf(body).toJS)
    .toDartInt;
int f3d_body_is_valid(int world, int body) => _x
    .f3d_body_is_valid(world.toJS, lowHalf(body).toJS, highHalf(body).toJS)
    .toDartInt;
int f3d_body_set_velocity(int world, int body, double x, double y, double z) =>
    _x
        .f3d_body_set_velocity(
          world.toJS,
          lowHalf(body).toJS,
          highHalf(body).toJS,
          x.toJS,
          y.toJS,
          z.toJS,
        )
        .toDartInt;
int f3d_body_get_velocity(int world, int body, int out) => _x
    .f3d_body_get_velocity(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_set_position(int world, int body, double x, double y, double z) =>
    _x
        .f3d_body_set_position(
          world.toJS,
          lowHalf(body).toJS,
          highHalf(body).toJS,
          x.toJS,
          y.toJS,
          z.toJS,
        )
        .toDartInt;
int f3d_body_get_position(int world, int body, int out) => _x
    .f3d_body_get_position(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_get_world_position(int world, int body, int out) => _x
    .f3d_body_get_world_position(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_set_angular_velocity(
  int world,
  int body,
  double x,
  double y,
  double z,
) => _x
    .f3d_body_set_angular_velocity(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      x.toJS,
      y.toJS,
      z.toJS,
    )
    .toDartInt;
int f3d_body_get_angular_velocity(int world, int body, int out) => _x
    .f3d_body_get_angular_velocity(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_set_orientation(
  int world,
  int body,
  double x,
  double y,
  double z,
  double w,
) => _x
    .f3d_body_set_orientation(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      x.toJS,
      y.toJS,
      z.toJS,
      w.toJS,
    )
    .toDartInt;
int f3d_body_get_orientation(int world, int body, int out) => _x
    .f3d_body_get_orientation(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_set_shape(
  int world,
  int body,
  int kind,
  double a,
  double b,
  double c,
) => _x
    .f3d_body_set_shape(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      kind.toJS,
      a.toJS,
      b.toJS,
      c.toJS,
    )
    .toDartInt;
int f3d_body_get_inertia(int world, int body, int out) => _x
    .f3d_body_get_inertia(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_get_inertia_tensor(int world, int body, int out) => _x
    .f3d_body_get_inertia_tensor(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_set_rounding(int world, int body, double radius) => _x
    .f3d_body_set_rounding(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      radius.toJS,
    )
    .toDartInt;
int f3d_body_set_hull(int world, int body, int hull) => _x
    .f3d_body_set_hull(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      hull.toJS,
    )
    .toDartInt;
int f3d_body_set_mesh(int world, int body, int mesh) => _x
    .f3d_body_set_mesh(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      mesh.toJS,
    )
    .toDartInt;
int f3d_body_get_mass(int world, int body, int out) => _x
    .f3d_body_get_mass(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_lock_rotation(int world, int body, int locked) => _x
    .f3d_body_lock_rotation(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      locked.toJS,
    )
    .toDartInt;
int f3d_body_set_damping(int world, int body, double linear, double angular) =>
    _x
        .f3d_body_set_damping(
          world.toJS,
          lowHalf(body).toJS,
          highHalf(body).toJS,
          linear.toJS,
          angular.toJS,
        )
        .toDartInt;
int f3d_body_set_drag(int world, int body, double coefficient) => _x
    .f3d_body_set_drag(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      coefficient.toJS,
    )
    .toDartInt;
int f3d_body_apply_impulse(int world, int body, double x, double y, double z) =>
    _x
        .f3d_body_apply_impulse(
          world.toJS,
          lowHalf(body).toJS,
          highHalf(body).toJS,
          x.toJS,
          y.toJS,
          z.toJS,
        )
        .toDartInt;
int f3d_body_apply_impulse_at(
  int world,
  int body,
  double x,
  double y,
  double z,
  double px,
  double py,
  double pz,
) => _x
    .f3d_body_apply_impulse_at(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      x.toJS,
      y.toJS,
      z.toJS,
      px.toJS,
      py.toJS,
      pz.toJS,
    )
    .toDartInt;
int f3d_body_add_force(int world, int body, double x, double y, double z) => _x
    .f3d_body_add_force(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      x.toJS,
      y.toJS,
      z.toJS,
    )
    .toDartInt;
int f3d_body_add_torque(int world, int body, double x, double y, double z) => _x
    .f3d_body_add_torque(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      x.toJS,
      y.toJS,
      z.toJS,
    )
    .toDartInt;
int f3d_body_set_bullet(int world, int body, int bullet) => _x
    .f3d_body_set_bullet(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      bullet.toJS,
    )
    .toDartInt;
int f3d_body_set_friction(int world, int body, double friction) => _x
    .f3d_body_set_friction(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      friction.toJS,
    )
    .toDartInt;
int f3d_body_set_restitution(int world, int body, double restitution) => _x
    .f3d_body_set_restitution(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      restitution.toJS,
    )
    .toDartInt;
int f3d_body_set_collision_filter(int world, int body, int layer, int mask) =>
    _x
        .f3d_body_set_collision_filter(
          world.toJS,
          lowHalf(body).toJS,
          highHalf(body).toJS,
          layer.toJS,
          mask.toJS,
        )
        .toDartInt;
int f3d_body_is_asleep(int world, int body) => _x
    .f3d_body_is_asleep(world.toJS, lowHalf(body).toJS, highHalf(body).toJS)
    .toDartInt;
int f3d_body_wake(int world, int body) => _x
    .f3d_body_wake(world.toJS, lowHalf(body).toJS, highHalf(body).toJS)
    .toDartInt;
int f3d_material_preset(int kind, int out) =>
    _x.f3d_material_preset(kind.toJS, out.toJS).toDartInt;
int f3d_body_set_material(int world, int body, int material) => _x
    .f3d_body_set_material(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      material.toJS,
    )
    .toDartInt;
int f3d_body_set_temperature(int world, int body, double kelvin) => _x
    .f3d_body_set_temperature(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      kelvin.toJS,
    )
    .toDartInt;
int f3d_body_get_temperature(int world, int body, int out) => _x
    .f3d_body_get_temperature(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_add_heat(int world, int body, double joules) => _x
    .f3d_body_add_heat(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      joules.toJS,
    )
    .toDartInt;
int f3d_body_add_water(int world, int body, double kg) => _x
    .f3d_body_add_water(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      kg.toJS,
    )
    .toDartInt;
int f3d_body_get_water(int world, int body, int out) => _x
    .f3d_body_get_water(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_get_fuel(int world, int body, int out) => _x
    .f3d_body_get_fuel(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_is_burning(int world, int body, int out) => _x
    .f3d_body_is_burning(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
int f3d_body_get_heat_release(int world, int body, int out) => _x
    .f3d_body_get_heat_release(
      world.toJS,
      lowHalf(body).toJS,
      highHalf(body).toJS,
      out.toJS,
    )
    .toDartInt;
