// Generated by tool/gen_core.dart from csrc/include/f3d_physics.h: do not edit.
//
// The structs the Dart side fills, as byte offsets into a block of the
// core's memory, laid out as C lays them out for the float build.
library;

/// `F3dMaterial`.
abstract final class F3dMaterialLayout {
  static const int specificHeat = 0;
  static const int emissivity = 4;
  static const int ignitionTemperature = 8;
  static const int heatOfCombustion = 12;
  static const int burnRate = 16;
  static const int fuelFraction = 20;
  static const int flameFeedback = 24;
  static const int conductivity = 28;
  static const int size = 32;
}

/// `F3dParticleForces`.
abstract final class F3dParticleForcesLayout {
  static const int gravity = 0;
  static const int wind = 12;
  static const int drag = 24;
  static const int floorY = 28;
  static const int restitution = 32;
  static const int friction = 36;
  static const int size = 40;
}

/// `F3dDebrisSettings`.
abstract final class F3dDebrisSettingsLayout {
  static const int gravity = 0;
  static const int friction = 12;
  static const int restitution = 16;
  static const int linearDamping = 20;
  static const int angularDamping = 24;
  static const int maxSpeed = 28;
  static const int substeps = 32;
  static const int iterations = 36;
  static const int size = 40;
}

/// `F3dClothSettings`.
abstract final class F3dClothSettingsLayout {
  static const int gravity = 0;
  static const int wind = 12;
  static const int drag = 24;
  static const int damping = 28;
  static const int floorY = 32;
  static const int thickness = 36;
  static const int friction = 40;
  static const int substeps = 44;
  static const int size = 48;
}

/// `F3dFluidSettings`.
abstract final class F3dFluidSettingsLayout {
  static const int gravity = 0;
  static const int tankMin = 12;
  static const int tankMax = 24;
  static const int viscosity = 36;
  static const int relaxation = 40;
  static const int substeps = 44;
  static const int iterations = 48;
  static const int size = 52;
}
