/// The public surface of a package as text: what `api/<package>.api` holds.
///
/// **What is listed.** Every library a caller can import — each `.dart` file
/// under `lib/` outside `lib/src/` — and in it every name it exports, after
/// `show` and `hide`, through any chain of exports:
///
///  * a declaration of the package itself, in full: its header with its
///    class modifiers, and each public member's signature — types, parameter
///    names, defaults, `const` initialisers (a constant's value is part of
///    what a caller compiled against);
///  * the annotations that change what a caller may do: `@Deprecated` with
///    its message, `@visibleForTesting`, `@protected`, `@internal`,
///    `@experimental` and the rest of [_annotationsThatMatter];
///  * `abstract ` before a member with no body, in a type outside code may
///    extend or mix in — the one place a body decides whether a new member
///    breaks somebody;
///  * a re-export of another package of this repository as its own block,
///    naming the library it comes through and every name it admits, with
///    `from <package>` on a name declared one package further. A
///    whole-library re-export is visible as one: `(whole library)`;
///  * a re-export from outside the repository as one line with its
///    combinators, since its names are somebody else's to list.
///
/// Bodies, doc comments, comments and private members are not listed, and
/// whitespace is normalised, so reformatting or rewording moves nothing.
/// Declarations and members are sorted, so reordering moves nothing either.
/// Parsed, not resolved: the text is what the source says.
library;

import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/token.dart';

/// The repository root: the directory whose pubspec names
/// `flutter3d_workspace`, found by walking up from [from].
Directory repositoryRootFrom(Directory from) {
  var dir = from.absolute;
  while (true) {
    final pubspec = File('${dir.path}/pubspec.yaml');
    if (pubspec.existsSync() &&
        pubspec.readAsStringSync().contains('name: flutter3d_workspace')) {
      return dir;
    }
    final up = dir.parent;
    if (up.path == dir.path) {
      throw StateError('no flutter3d_workspace pubspec above ${from.path}');
    }
    dir = up;
  }
}

/// Every package of the repository by name: `packages/*`, published or not,
/// because a published package may re-export one that is not.
Map<String, Directory> repositoryPackages(Directory root) {
  final found = <String, Directory>{};
  for (final parent in <String>['packages']) {
    final dir = Directory('${root.path}/$parent');
    if (!dir.existsSync()) continue;
    for (final child in dir.listSync().whereType<Directory>()) {
      final pubspec = File('${child.path}/pubspec.yaml');
      if (!pubspec.existsSync()) continue;
      final name = RegExp(
        r'^name:\s*(\S+)',
        multiLine: true,
      ).firstMatch(pubspec.readAsStringSync())?.group(1);
      if (name != null) found[name] = child;
    }
  }
  return found;
}

/// Whether [package] goes to pub.dev: its pubspec does not say
/// `publish_to: none`.
bool isPublished(Directory package) => !RegExp(
  r'''^publish_to:\s*['"]?none''',
  multiLine: true,
).hasMatch(File('${package.path}/pubspec.yaml').readAsStringSync());

/// Where a package's snapshot lives, relative to the package.
String snapshotPathOf(String package) => 'api/$package.api';

/// Writes snapshots for the packages of one repository, sharing what it has
/// parsed between them: `flutter3d` re-exports `flutter3d_core`, and the core
/// is read once for both.
final class ApiSnapshotter {
  ApiSnapshotter(this.packages);

  /// Every package of the repository, by name — to resolve `package:` URIs.
  final Map<String, Directory> packages;

  final Map<String, _Namespace> _namespaces = <String, _Namespace>{};

  /// The snapshot of [package], as `api/<package>.api` holds it.
  String snapshot(String package) {
    final root = packages[package]!;
    final out = StringBuffer()
      ..writeln('# The public API of $package.')
      ..writeln(
        '# Generated by `dart run api_snapshot --update $package` in tool/api. '
        'Do not edit.',
      )
      ..writeln(
        '# A change here is a semver decision: see "The API is a snapshot" '
        'in CONTRIBUTING.md.',
      );
    for (final library in publicLibraries(root)) {
      final path = relativePath(library, Directory('${root.path}/lib'));
      out
        ..writeln()
        ..writeln('library package:$package/$path');
      final namespace = _namespace(library, package);
      final own = <String, String>{
        for (final e in namespace.entries.values)
          if (e.package == package && e.via == null) e.name: e.block,
      };
      for (final name in own.keys.toList()..sort()) {
        out
          ..writeln()
          ..write(own[name]);
      }
      for (final block in _reExportBlocks(namespace, package)) {
        out
          ..writeln()
          ..write(block);
      }
    }
    return out.toString();
  }

  /// The libraries a caller of [root] can import: every `.dart` under `lib/`
  /// but outside `lib/src/`, and not a `part of` another, sorted.
  static List<File> publicLibraries(Directory root) {
    final lib = Directory('${root.path}/lib');
    if (!lib.existsSync()) return const <File>[];
    final files =
        lib
            .listSync(recursive: true)
            .whereType<File>()
            .where((File f) => f.path.endsWith('.dart'))
            .where((File f) {
              final path = relativePath(f, lib);
              return !path.startsWith('src/');
            })
            .where(
              (File f) => !RegExp(
                r'^part of\b',
                multiLine: true,
              ).hasMatch(f.readAsStringSync()),
            )
            .toList()
          ..sort(
            (File a, File b) =>
                relativePath(a, lib).compareTo(relativePath(b, lib)),
          );
    return files;
  }

  List<String> _reExportBlocks(_Namespace namespace, String package) {
    final byVia = <String, List<_Entry>>{};
    for (final e in namespace.entries.values) {
      if (e.via == null) continue;
      (byVia[e.via!.uri] ??= <_Entry>[]).add(e);
    }
    final externalsByVia = <String, List<_External>>{};
    final direct = <_External>[];
    for (final x in namespace.externals) {
      if (x.via == null) {
        direct.add(x);
      } else {
        (externalsByVia[x.via!.uri] ??= <_External>[]).add(x);
      }
    }
    final vias = <String, _Via>{
      for (final e in namespace.entries.values)
        if (e.via != null) e.via!.uri: e.via!,
      for (final x in namespace.externals)
        if (x.via != null) x.via!.uri: x.via!,
    };
    final blocks = <String, String>{};
    for (final uri in vias.keys) {
      final via = vias[uri]!;
      final origin = Uri.parse(uri).pathSegments.first;
      final lines = <String>[
        for (final e in byVia[uri] ?? const <_Entry>[])
          e.package == origin ? e.name : '${e.name} from ${e.package}',
        for (final x in externalsByVia[uri] ?? const <_External>[])
          x.describe(),
      ]..sort();
      final shape = via.combinators.isEmpty
          ? ' (whole library)'
          : ' ${via.combinators}';
      blocks[uri] = <String>[
        'export $uri$shape',
        for (final l in lines.toSet()) '  $l',
        '',
      ].join('\n');
    }
    for (final x in direct) {
      blocks[x.uri + x.combinators] = '${x.describe()}\n';
    }
    return <String>[
      for (final key in blocks.keys.toList()..sort()) blocks[key]!,
    ];
  }

  /// What [file] exports, as seen from outside it.
  _Namespace _namespace(File file, String package) {
    final key = file.absolute.path;
    final known = _namespaces[key];
    if (known != null) return known;
    final namespace = _namespaces[key] = _Namespace();
    if (!file.existsSync()) return namespace;

    final unit = _parse(file);
    for (final entry in _declarationsOf(file, unit).entries) {
      namespace.entries[entry.key] = _Entry(
        entry.key.endsWith('=')
            ? entry.key.substring(0, entry.key.length - 1)
            : entry.key,
        package,
        entry.value,
        null,
      );
    }
    for (final directive in unit.directives.whereType<ExportDirective>()) {
      final uri = directive.uri.stringValue;
      if (uri == null) continue;
      final admits = _combinators(directive.combinators);
      final combinators = directive.combinators
          .map((Combinator c) => _text(c.beginToken, c.end))
          .join(' ');
      final target = _resolve(file, package, uri);
      if (target == null) {
        namespace.externals.add(_External(uri, combinators, null));
        continue;
      }
      final inner = _namespace(target.file, target.package);
      final crossing = target.package != package;
      final via = crossing
          ? _Via('package:${target.package}/${target.path}', combinators)
          : null;
      for (final e in inner.entries.entries) {
        if (!admits(e.value.name)) continue;
        namespace.entries[e.key] = crossing
            ? _Entry(e.value.name, e.value.package, e.value.block, via)
            : e.value;
      }
      for (final x in inner.externals) {
        namespace.externals.add(
          _External(
            x.uri,
            <String>[
              x.combinators,
              combinators,
            ].where((String s) => s.isNotEmpty).join(' '),
            crossing ? via : x.via,
          ),
        );
      }
    }
    return namespace;
  }

  /// [uri] exported from [from], as a file of this repository, or null when
  /// it is outside it.
  ({File file, String package, String path})? _resolve(
    File from,
    String package,
    String uri,
  ) {
    if (uri.startsWith('dart:')) return null;
    if (uri.startsWith('package:')) {
      final segments = uri.substring('package:'.length).split('/');
      final root = packages[segments.first];
      if (root == null) return null;
      final path = segments.skip(1).join('/');
      return (
        file: File('${root.path}/lib/$path'),
        package: segments.first,
        path: path,
      );
    }
    final file = File(from.parent.uri.resolve(uri).toFilePath());
    final lib = Directory('${packages[package]!.path}/lib');
    return (file: file, package: package, path: relativePath(file, lib));
  }
}

final class _Namespace {
  final Map<String, _Entry> entries = <String, _Entry>{};
  final List<_External> externals = <_External>[];
}

/// The library of another package a name came in through, with the
/// combinators on that export.
final class _Via {
  const _Via(this.uri, this.combinators);
  final String uri;
  final String combinators;
}

final class _Entry {
  const _Entry(this.name, this.package, this.block, this.via);
  final String name;

  /// The package that declares it.
  final String package;
  final String block;
  final _Via? via;
}

final class _External {
  const _External(this.uri, this.combinators, this.via);
  final String uri;
  final String combinators;
  final _Via? via;

  String describe() =>
      'export $uri${combinators.isEmpty ? '' : ' $combinators'} '
      '(outside this repository)';
}

bool Function(String) _combinators(List<Combinator> combinators) {
  // Applied in order, as the language does: `show A, B hide B` admits A.
  return (String name) {
    for (final c in combinators) {
      switch (c) {
        case ShowCombinator(:final shownNames)
            when !shownNames.any((SimpleIdentifier n) => n.name == name):
          return false;
        case HideCombinator(:final hiddenNames)
            when hiddenNames.any((SimpleIdentifier n) => n.name == name):
          return false;
        default:
          break;
      }
    }
    return true;
  };
}

final _features = parseString(content: '').unit.featureSet;

CompilationUnit _parse(File file) => parseString(
  content: file.readAsStringSync(),
  path: file.absolute.path,
  featureSet: _features,
).unit;

/// [file]'s path relative to [dir], with forward slashes.
String relativePath(File file, Directory dir) => file.absolute.path
    .substring(dir.absolute.path.length + 1)
    .replaceAll(Platform.pathSeparator, '/');

/// Every public top-level declaration of [file] and its parts, by name
/// (a setter as `name=`), rendered.
Map<String, String> _declarationsOf(File file, CompilationUnit unit) {
  final found = <String, String>{};
  void collect(CompilationUnit u) {
    for (final d in u.declarations) {
      _render(d, found);
    }
  }

  collect(unit);
  for (final part in unit.directives.whereType<PartDirective>()) {
    final uri = part.uri.stringValue;
    if (uri == null) continue;
    final partFile = File(file.parent.uri.resolve(uri).toFilePath());
    if (partFile.existsSync()) collect(_parse(partFile));
  }
  return found;
}

void _render(CompilationUnitMember d, Map<String, String> found) {
  String header(AnnotatedNode node, int end) =>
      _annotated(node, _text(node.firstTokenAfterCommentAndMetadata, end));
  switch (d) {
    case ClassDeclaration(:final namePart, :final body):
      final name = namePart.typeName.lexeme;
      if (_private(name)) return;
      final abstractMembers =
          d.abstractKeyword != null && d.interfaceKeyword == null ||
          d.mixinKeyword != null && d.abstractKeyword != null;
      found[name] = _block(
        header(d, body.offset),
        _members(body.members, markAbstract: abstractMembers),
      );
    case MixinDeclaration(:final name, :final body):
      if (_private(name.lexeme)) return;
      found[name.lexeme] = _block(
        header(d, body.offset),
        _members(body.members, markAbstract: true),
      );
    case EnumDeclaration(:final namePart, :final body):
      final name = namePart.typeName.lexeme;
      if (_private(name)) return;
      found[name] = _block(header(d, body.offset), <String>[
        'values: ${body.constants.map((c) => c.name.lexeme).join(', ')}',
        ..._members(body.members),
      ]);
    case ExtensionTypeDeclaration(:final namePart, :final body):
      final name = namePart.typeName.lexeme;
      if (_private(name)) return;
      found[name] = _block(header(d, body.offset), _members(body.members));
    case ExtensionDeclaration(:final name, :final body):
      // An unnamed extension applies only inside its own library, so it is
      // nobody else's API.
      final label = name?.lexeme ?? '';
      if (label.isEmpty || _private(label)) return;
      found[label] = _block(header(d, body.offset), _members(body.members));
    case ClassTypeAlias(:final name):
      if (_private(name.lexeme)) return;
      found[name.lexeme] = '${header(d, d.end)}\n';
    case GenericTypeAlias(:final name) || FunctionTypeAlias(:final name):
      if (_private(name.lexeme)) return;
      found[name.lexeme] = '${header(d, d.end)}\n';
    case FunctionDeclaration(:final name, :final functionExpression):
      if (_private(name.lexeme)) return;
      final key = d.isSetter ? '${name.lexeme}=' : name.lexeme;
      found[key] =
          '${header(d, functionExpression.parameters?.end ?? name.end)}\n';
    case TopLevelVariableDeclaration(:final variables):
      for (final v in variables.variables) {
        if (_private(v.name.lexeme)) continue;
        found[v.name.lexeme] = '${_annotated(d, _variable(variables, v))}\n';
      }
    default:
      break;
  }
}

List<String> _members(List<ClassMember> members, {bool markAbstract = false}) {
  String text(AnnotatedNode m, int end) =>
      _annotated(m, _text(m.firstTokenAfterCommentAndMetadata, end));
  String abstract(bool isAbstract, String line) {
    if (!markAbstract || !isAbstract) return line;
    final split = _leadingAnnotations(line);
    return '${split.annotations}abstract ${split.rest}';
  }

  return <String>[
    for (final m in members)
      ...switch (m) {
        ConstructorDeclaration() when !_private(m.name?.lexeme ?? '') =>
          <String>[text(m, m.parameters.end)],
        MethodDeclaration() when !_private(m.name.lexeme) => <String>[
          abstract(
            m.body is EmptyFunctionBody && m.externalKeyword == null,
            text(m, m.parameters?.end ?? m.name.end),
          ),
        ],
        FieldDeclaration(:final fields) => <String>[
          for (final v in fields.variables)
            if (!_private(v.name.lexeme))
              abstract(
                m.abstractKeyword != null,
                _annotated(m, _variable(fields, v, isStatic: m.isStatic)),
              ),
        ],
        _ => const <String>[],
      },
  ]..sort();
}

({String annotations, String rest}) _leadingAnnotations(String line) {
  var rest = line;
  final annotations = StringBuffer();
  while (rest.startsWith('@')) {
    var depth = 0;
    var end = 0;
    for (; end < rest.length; end++) {
      final c = rest[end];
      if (c == '(') depth++;
      if (c == ')') depth--;
      if (c == ' ' && depth == 0) break;
    }
    annotations.write('${rest.substring(0, end)} ');
    rest = rest.substring(end).trimLeft();
  }
  return (annotations: annotations.toString(), rest: rest);
}

String _variable(
  VariableDeclarationList list,
  VariableDeclaration v, {
  bool isStatic = false,
}) {
  final keyword = list.keyword?.lexeme;
  final type = list.type == null
      ? ''
      : '${_text(list.type!.beginToken, list.type!.end)} ';
  // A constant's value is part of what a caller compiled against — a
  // feature's name is its identity in a report — so it is listed. Up to a
  // point: a generated table or a usage text is data, and listing it would
  // turn every shader edit into a version decision. Past
  // [_longestListedValue] characters the value is `…`, which still says
  // there is one.
  final value = list.isConst && v.initializer != null
      ? _text(v.initializer!.beginToken, v.initializer!.end)
      : null;
  final initializer = value == null
      ? ''
      : ' = ${value.length > _longestListedValue ? '…' : value}';
  return '${isStatic ? 'static ' : ''}${list.lateKeyword == null ? '' : 'late '}'
      '${keyword == null ? '' : '$keyword '}$type${v.name.lexeme}$initializer';
}

/// How long a constant's value may be and still be listed. The longest
/// value that is a name or a number in the repository today is well under
/// it; the shortest generated table is well over.
const int _longestListedValue = 160;

String _block(String header, List<String> members) =>
    <String>[header, for (final m in members) '  $m', ''].join('\n');

bool _private(String name) => name.startsWith('_');

/// The annotations that change what a caller or a subclass may do. The rest
/// (`@override`, `@pragma`, …) say nothing to somebody outside the package.
const Set<String> _annotationsThatMatter = <String>{
  'Deprecated',
  'deprecated',
  'visibleForTesting',
  'visibleForOverriding',
  'protected',
  'internal',
  'experimental',
  'nonVirtual',
  'mustCallSuper',
  'mustBeOverridden',
  'sealed',
  'immutable',
};

/// [text] with the annotations of [node] that matter written before it.
String _annotated(AnnotatedNode node, String text) {
  final kept = <String>[
    for (final a in node.metadata)
      if (_annotationsThatMatter.contains(a.name.name.split('.').last))
        _text(a.beginToken, a.end),
  ];
  return kept.isEmpty ? text : '${kept.join(' ')} $text';
}

/// The source from [begin] up to offset [end], as tokens: comments dropped,
/// whitespace collapsed to one space where there was any, so a reformat or a
/// reworded comment inside a signature changes nothing.
String _text(Token begin, int end) {
  final out = StringBuffer();
  Token? previous;
  for (Token? t = begin; t != null && !t.isEof && t.end <= end; t = t.next) {
    if (previous != null && t.offset > previous.end) out.write(' ');
    out.write(t.lexeme);
    previous = t;
  }
  return _normalize(out.toString());
}

String _normalize(String text) => text
    .replaceAll(RegExp(r'\s+'), ' ')
    .replaceAll('( ', '(')
    .replaceAll(' )', ')')
    .replaceAll('{ ', '{')
    .replaceAll(' }', '}')
    .replaceAll('[ ', '[')
    .replaceAll(' ]', ']')
    .replaceAllMapped(RegExp(r',\s*([)\]}])'), (Match m) => m[1]!)
    .trim();
