/// Writes `flutter3d_shaders/lib/stage_bindings.dart`: what every compiled
/// stage in the bundle keeps, by name.
///
///     dart run tool/stage_bindings.dart
///
/// Compiled with the real `impellerc` for Metal and read off its reflection,
/// keeping only the blocks and samplers the Metal function actually has a slot
/// for. That is the set a draw must bind and may bind: a resource the source
/// declares and the compiler dropped is neither. `FakeBackend` takes the table
/// so a missing or misdirected bind fails a test on the VM, and
/// `stage_bindings_test.dart` holds the committed table to a fresh compile.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter3d_impeller/src/shader_bundle_build.dart';

/// Stage name to the blocks and samplers its compiled Metal function keeps.
Map<String, ({Set<String> blocks, Set<String> samplers})> reflectStages({
  required String shadersRoot,
}) {
  final compiler = impellercPath();
  final shaderLib = File(compiler).parent.uri.resolve('shader_lib').path;
  final manifest =
      jsonDecode(
            File('$shadersRoot/flutter3d.shaderbundle.json').readAsStringSync(),
          )
          as Map<String, Object?>;
  final scratch = Directory.systemTemp.createTempSync('f3d_stages_');
  try {
    final stages = <String, ({Set<String> blocks, Set<String> samplers})>{};
    for (final MapEntry(key: name, value: entry) in manifest.entries) {
      final stage = entry! as Map<String, Object?>;
      final file = (stage['file']! as String).replaceFirst('shaders/', '');
      final reflection = '${scratch.path}/$name.json';
      final result = Process.runSync(compiler, <String>[
        '--metal-desktop',
        '--input=$shadersRoot/$file',
        '--sl=${scratch.path}/$name.metal',
        '--spirv=${scratch.path}/$name.spv',
        '--reflection-json=$reflection',
        '--include=$shaderLib',
        '--include=$shadersRoot',
        '--include=$shadersRoot/lib',
        '--input-type=${stage['type'] == 'vertex' ? 'vert' : 'frag'}',
      ]);
      if (result.exitCode != 0) {
        throw StateError('$name did not compile: ${result.stderr}');
      }
      final reflected =
          jsonDecode(File(reflection).readAsStringSync())
              as Map<String, Object?>;
      Set<String> kept(String kind) => <String>{
        for (final r in (reflected[kind] as List<Object?>? ?? const []))
          if ((r! as Map<String, Object?>)['ext_res_0'] != 0xFFFFFFFF)
            (r as Map<String, Object?>)['name']! as String,
      };
      stages[name] = (
        blocks: kept('buffers'),
        samplers: kept('sampled_images'),
      );
    }
    return stages;
  } finally {
    scratch.deleteSync(recursive: true);
  }
}

/// [stages] as the Dart source of `stage_bindings.dart`.
String stageBindingsSource(
  Map<String, ({Set<String> blocks, Set<String> samplers})> stages,
) {
  String set(Set<String> names) => names.isEmpty
      ? '<String>{}'
      : '<String>{${(names.toList()..sort()).map((n) => "'$n'").join(', ')}}';
  final out = StringBuffer()
    ..writeln('// GENERATED by flutter3d_impeller/tool/stage_bindings.dart.')
    ..writeln('// Do not edit; run the tool after any shader edit.')
    ..writeln()
    ..writeln(
      "/// What every stage in the engine's bundle keeps once compiled:",
    )
    ..writeln('/// the uniform blocks and samplers a draw through it must bind')
    ..writeln('/// and may bind. Read off impellerc\'s Metal reflection, so a')
    ..writeln('/// resource the source declares and the compiler dropped is')
    ..writeln('/// not here. `FakeBackend(stageBindings: stageBindings)` holds')
    ..writeln('/// a renderer to it on the VM.')
    ..writeln('library;')
    ..writeln()
    ..writeln(
      'const Map<String, ({Set<String> blocks, Set<String> samplers})> '
      'stageBindings = <String, ({Set<String> blocks, Set<String> samplers})>{',
    );
  for (final name in stages.keys.toList()..sort()) {
    final stage = stages[name]!;
    out.writeln(
      "  '$name': (blocks: ${set(stage.blocks)}, "
      'samplers: ${set(stage.samplers)}),',
    );
  }
  out.writeln('};');
  return out.toString();
}

void main() {
  final shaders = Directory('../flutter3d_shaders/shaders').absolute.path;
  final target = File('../flutter3d_shaders/lib/stage_bindings.dart');
  target.writeAsStringSync(
    stageBindingsSource(reflectStages(shadersRoot: shaders)),
  );
  Process.runSync('dart', <String>['format', target.path]);
  stdout.writeln('wrote ${target.path}');
}
