/// Who made what, and under which licence.
///
/// **A condition of the licence, not a courtesy.** A CC BY licence asks that
/// attribution appear wherever the work does, and the platformer shipped
/// nothing of the kind — not in the application, not on the web page — so every
/// run of it was a breach for as long as it ran, and no test could have said so
/// because there was nothing to test.
///
/// **Moved here when the second game wanted one.** Nothing in it was ever the
/// platformer's: what is owed for somebody else's work, and how to say it on a
/// screen, is the same question in every game. What differs is the list, and
/// each game keeps its own — see `Credits.models` in the platformer and the
/// dungeon, and `credits_test.dart` in both, which reads the asset directory
/// rather than the list beside it.
///
/// **What is *not* credited belongs here too.** An asset nobody can trace has
/// to appear as untraced, or the screen agrees with itself while the game goes
/// on shipping it.
library;

import 'package:flutter/material.dart';

/// One piece of work the game did not make, and what is owed for it.
final class Credit {
  const Credit({
    required this.file,
    required this.work,
    required this.author,
    required this.source,
    required this.licence,
    required this.licenceUrl,
    this.modified = false,
  });

  /// An asset that came from somewhere nobody can name.
  ///
  /// A separate constructor rather than a null licence passed by a caller, so
  /// the awkward case has to be written out on purpose.
  const Credit.untraced({required this.file, required this.work})
      : author = null,
        source = null,
        licence = null,
        licenceUrl = null,
        modified = true;

  /// The file as it ships, relative to `assets/`.
  final String file;

  final String work;
  final String? author;
  final String? source;

  /// The licence's short name, or null when nobody could trace one.
  final String? licence;
  final String? licenceUrl;

  /// Whether this repository changed the file, which CC BY also asks be said.
  final bool modified;

  /// Whether the licence is known at all.
  bool get traced => licence != null;

  /// Whether the licence obliges the game to name the author.
  ///
  /// CC0 does not, and the entry is kept anyway: a licence nobody can trace is
  /// a debt, and a file whose provenance is "somebody downloaded it" cannot be
  /// told apart from one that is.
  bool get owesAttribution => licence != null && licence!.startsWith('CC BY');

  /// One line, as a screen would read it out.
  String get line {
    if (!traced) return '$work — author unknown, licence untraced';
    final changed = modified ? ', modified' : '';
    return '$work by $author — $licence$changed';
  }
}

/// Who made the art, wherever the game is shown.
///
/// **Not decoration.** Two of the models are CC BY 4.0, and the licence asks
/// that attribution travel with the work — so this belongs on any screen a
/// player can reach without finishing the game, which is why it is a widget of
/// its own rather than a paragraph in one screen.
///
/// The list is handed in and so is the test's: prose typed in here would be a
/// second copy of a legal notice, and the second copy is the one that goes
/// stale.
class CreditsSection extends StatelessWidget {
  const CreditsSection({
    super.key,
    required this.credits,
    this.heading = 'Art',
    this.footnote = 'Sounds and surfaces are generated by this repository.',
  });

  /// What this game ships that somebody else made. The game's own list, because
  /// two games ship different things.
  final List<Credit> credits;

  final String heading;

  /// What the game made itself, said once so the list above is not padded with
  /// entries that owe nobody anything.
  final String footnote;

  @override
  Widget build(BuildContext context) {
    final faded = Colors.white.withValues(alpha: 0.75);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text(
          heading,
          style: TextStyle(color: faded, letterSpacing: 2, fontSize: 12),
        ),
        const SizedBox(height: 8),
        for (final credit in credits) ...<Widget>[
          Text(
            credit.line,
            style: const TextStyle(color: Colors.white, fontSize: 13),
          ),
          if (credit.licenceUrl != null)
            Text(
              credit.licenceUrl!,
              style: TextStyle(
                color: Colors.white.withValues(alpha: 0.55),
                fontSize: 11,
              ),
            ),
          const SizedBox(height: 6),
        ],
        Text(footnote, style: TextStyle(color: faded, fontSize: 12)),
      ],
    );
  }
}
