/// What this game ships that somebody else made.
///
/// The class and the screen are `flutter3d_ui`'s — see `Credit` there. What is
/// here is the list, which is this game's alone.
///
/// **This game was in breach and nobody had noticed.** `assets/models/LICENSES.md`
/// says it in as many words about the car: *"Attribution is a condition of the
/// licence, so it is written here, and it must appear wherever the game does —
/// a credits screen, a store page, a README."* There was no credits screen, no
/// mention in the application and nothing on the web page, so every run of this
/// game was a breach for as long as it ran — and no test could have said so,
/// because there was nothing to test.
library;

import 'package:flutter3d_app/flutter3d_app.dart'; // Credit, from flutter3d_ui

/// Everything the game ships that somebody else made.
///
/// The sounds are synthesised by `tool/make_sounds.py` and the track is
/// generated by `tool/make_track.py`, so both are this repository's own and are
/// not here. That was the point of generating them.
abstract final class Credits {
  static const List<Credit> models = <Credit>[
    Credit(
      file: 'models/car.glb',
      work: '2002 McLaren MP4-17',
      author: 'Dave Love',
      source:
          'https://sketchfab.com/3d-models/2002-mclaren-mp4-17-bf74904934284bbbb5e3c69f1650bdba',
      licence: 'CC BY 4.0',
      licenceUrl: 'http://creativecommons.org/licenses/by/4.0/',
      modified: true,
    ),
  ];

  /// The ones whose licence makes naming the author a condition.
  ///
  /// **Not empty here**, unlike the other two games, and that is the whole
  /// reason this file exists rather than being a formality copied across.
  static List<Credit> get owed =>
      models.where((Credit c) => c.owesAttribution).toList();

  /// The ones that cannot be credited because nobody knows who made them.
  ///
  /// While this has anything in it the game cannot be released, whatever the
  /// screen says. `credits_test.dart` reads the asset directory rather than
  /// this list, so an untraced file arriving is a red test rather than an entry
  /// somebody forgets to add.
  static List<Credit> get untraced =>
      models.where((Credit c) => !c.traced).toList();
}
