/// What this game ships that somebody else made.
///
/// The ledger, the class and the screen are `flutter3d_game_ui/screens.dart`' — see
/// `CreditLedger` there. What is here is the list, which is this game's alone.
///
/// **This game was once in breach and nobody had noticed.** Its first car was
/// CC BY, whose licence makes naming the author a condition wherever the game
/// appears, and there was no credits screen, no mention in the application and
/// nothing on the web page — and no test could have said so, because there was
/// nothing to test. The screens and this list came of that; the car is CC0
/// now, and they stay for whatever comes in next.
library;

import 'package:flutter3d_game_ui/screens.dart';

/// Everything the game ships that somebody else made.
///
/// The sounds are synthesised by `tool/make_sounds.py` and the track is
/// generated by `tool/make_track.py`, so both are this repository's own and are
/// not here. That was the point of generating them.
const CreditLedger credits = CreditLedger(<Credit>[
  Credit(
    file: 'models/car.glb',
    work: 'Car Kit — race car',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/car-kit',
    license: 'CC0 1.0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/',
    modified: true,
  ),
  // The roadside. CC0 owes nobody a line on a screen — `owesAttribution` is
  // false for these — but the accounting is per file rather than per debt,
  // so a model that ships is a model that appears here whatever its licence
  // says. That is what keeps "somebody downloaded it" from looking the same
  // as "this is public domain".
  Credit(
    file: 'models/building-a.glb',
    work: 'City Kit (Suburban) — building type A',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/city-kit-suburban',
    license: 'CC0 1.0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/',
  ),
  Credit(
    file: 'models/building-e.glb',
    work: 'City Kit (Suburban) — building type E',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/city-kit-suburban',
    license: 'CC0 1.0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/',
  ),
  Credit(
    file: 'models/building-k.glb',
    work: 'City Kit (Suburban) — building type K',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/city-kit-suburban',
    license: 'CC0 1.0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/',
  ),
  Credit(
    file: 'models/building-q.glb',
    work: 'City Kit (Suburban) — building type Q',
    author: 'Kenney',
    source: 'https://kenney.nl/assets/city-kit-suburban',
    license: 'CC0 1.0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/',
  ),
]);
