// Generated by flutter3d_build from the `flutter3d_plugins:`
// markers of this package's dependencies. Do not edit:
// `dart run flutter3d_build:plugins` and every build write it
// again. Pass a list of your own to the engine to override it.

import 'package:flutter3d_plugin_api/flutter3d_plugin_api.dart';

/// The plugins this package's dependencies declare, made
/// afresh on each read.
List<Flutter3dPlugin> get installedPlugins => <Flutter3dPlugin>[];
