/// Who made what, and under which licence.
///
/// **A condition of the licence, not a courtesy.** A CC BY licence asks that
/// attribution appear wherever the work does, and the platformer shipped
/// nothing of the kind — not in the application, not on the web page — so every
/// run of it was a breach for as long as it ran, and no test could have said so
/// because there was nothing to test.
///
/// **Moved here when the second game wanted one.** Nothing in it was ever the
/// platformer's: what is owed for somebody else's work, and how to say it on a
/// screen, is the same question in every game. What differs is the list, and
/// each game keeps its own — see `Credits.models` in the platformer and the
/// dungeon, and `credits_test.dart` in both, which reads the asset directory
/// rather than the list beside it.
///
/// **What is *not* credited belongs here too.** An asset nobody can trace has
/// to appear as untraced, or the screen agrees with itself while the game goes
/// on shipping it.
///
/// **One file since 1.0.0-rc.1.** [Credit] and [CreditsSection] were
/// `flutter3d_game`'s and [CreditLedger] and [LicenseRecord] this package's,
/// so the list, the questions asked of it and the screen it is shown on had
/// two homes. They are all widgets' business, and all here.
library;

import 'package:flutter/material.dart';

import '../l10n/game_localizations.dart';
import '../theme/game_ui_theme.dart';

/// One piece of work the game did not make, and what is owed for it.
final class Credit {
  const Credit({
    required this.file,
    required this.work,
    required this.author,
    required this.source,
    required this.license,
    required this.licenseUrl,
    this.modified = false,
  });

  /// An asset that came from somewhere nobody can name.
  ///
  /// A separate constructor rather than a null licence passed by a caller, so
  /// the awkward case has to be written out on purpose.
  const Credit.untraced({required this.file, required this.work})
    : author = null,
      source = null,
      license = null,
      licenseUrl = null,
      modified = true;

  /// The file as it ships, relative to `assets/`.
  final String file;

  final String work;
  final String? author;
  final String? source;

  /// The licence's short name, or null when nobody could trace one.
  final String? license;
  final String? licenseUrl;

  /// Whether this repository changed the file, which CC BY also asks be said.
  final bool modified;

  /// Whether the licence is known at all.
  bool get isTraced => license != null;

  /// Whether the licence obliges the game to name the author.
  ///
  /// CC0 does not, and the entry is kept anyway: a licence nobody can trace is
  /// a debt, and a file whose provenance is "somebody downloaded it" cannot be
  /// told apart from one that is.
  bool get owesAttribution => license != null && license!.startsWith('CC BY');

  /// One line, in English, for a log or a test; a screen shows
  /// [Flutter3dGameLocalizations.creditLine], in the player's language.
  String get line {
    if (!isTraced) return '$work — author unknown, licence untraced';
    final changed = modified ? ', modified' : '';
    return '$work by $author — $license$changed';
  }
}

/// Who made the art, wherever the game is shown.
///
/// **Not decoration.** Two of the models are CC BY 4.0, and the licence asks
/// that attribution travel with the work — so this belongs on any screen a
/// player can reach without finishing the game, which is why it is a widget of
/// its own rather than a paragraph in one screen.
///
/// The list is handed in and so is the test's: prose typed in here would be a
/// second copy of a legal notice, and the second copy is the one that goes
/// stale.
class CreditsSection extends StatelessWidget {
  const CreditsSection({
    super.key,
    required this.credits,
    this.heading,
    this.footnote,
  });

  /// What this game ships that somebody else made. The game's own list, because
  /// two games ship different things.
  final List<Credit> credits;

  /// The heading the list goes under; null for
  /// [Flutter3dGameLocalizations.art] in the player's language.
  final String? heading;

  /// What the game made itself, said once so the list above is not padded with
  /// entries that owe nobody anything — or null for no such line.
  ///
  /// **No default.** It used to say "Sounds and surfaces are generated by
  /// this repository", which was true of this repository's demos and of no
  /// game built on the engine: a footnote a game does not write is one it
  /// does not show.
  final String? footnote;

  @override
  Widget build(BuildContext context) {
    final words = Flutter3dGameLocalizations.of(context);
    final theme = GameUiTheme.of(context);
    final faded = theme.heading;
    final aside = footnote;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text(
          heading ?? words.art,
          style: TextStyle(color: faded, letterSpacing: 2, fontSize: 12),
        ),
        const SizedBox(height: 8),
        for (final credit in credits) ...<Widget>[
          Text(
            words.creditLine(credit),
            style: TextStyle(color: theme.text, fontSize: 13),
          ),
          if (credit.licenseUrl != null)
            Text(
              credit.licenseUrl!,
              style: TextStyle(
                color: Colors.white.withValues(alpha: 0.55),
                fontSize: 11,
              ),
            ),
          const SizedBox(height: 6),
        ],
        if (aside != null)
          Text(aside, style: TextStyle(color: faded, fontSize: 12)),
      ],
    );
  }
}

/// What a game ships that somebody else made, and the two questions every
/// game asks of it.
///
/// **Five games wrote these same three lines.** Each kept its list of
/// [Credit]s in an `abstract final class Credits` with an `owed` and an
/// `untraced` getter spelled the same way in all five. The list is the game's;
/// the questions are not, so a game declares its list as one of these and
/// asks it.
///
/// ```dart
/// const CreditLedger credits = CreditLedger(<Credit>[
///   Credit(file: 'models/car.glb', work: 'Car Kit, race car', ...),
/// ]);
///
/// CreditsSection(credits: credits.owed);
/// ```
final class CreditLedger {
  const CreditLedger(this.models);

  /// Everything the game ships that somebody else made, one entry a file.
  final List<Credit> models;

  /// The ones whose licence makes naming the author a condition. These go on
  /// a screen every player meets: a title card, an ending.
  List<Credit> get owed =>
      models.where((Credit c) => c.owesAttribution).toList();

  /// The ones nobody knows the maker of. While this has anything in it the
  /// game cannot be released, whatever its screens say.
  List<Credit> get untraced => models.where((Credit c) => !c.isTraced).toList();

  /// Where this list and the licence record on disk say different things,
  /// one sentence each; empty when they agree.
  ///
  /// **Two records of one fact, so they are held to each other.** The
  /// `LICENSES.md` beside the models is the long version a person reads, and
  /// this list is the half a player sees. A file the record does not mention
  /// is a finding; so is a licence or an author the two state differently,
  /// where the record states one at all.
  List<String> disagreementsWith(LicenseRecord record) => <String>[
    for (final credit in models) ...record._disagreementsWith(credit),
  ];
}

/// One section of a `LICENSES.md`: the files it covers and the rows its
/// table gives for them.
final class LicenseEntry {
  const LicenseEntry({
    required this.files,
    this.author,
    this.source,
    this.license,
    this.licenseUrl,
  });

  /// The file names the section is about, as its heading or its row names
  /// them: `car.glb`, not `models/car.glb`.
  final List<String> files;

  /// The `Author` row's name, without the link after it.
  final String? author;

  /// The `Source` row, whole.
  final String? source;

  /// The `Licence` row's short name, `CC0 1.0`, without emphasis or link.
  final String? license;

  /// The first link in the `Licence` row.
  final String? licenseUrl;
}

/// A `LICENSES.md` as a game's credits read it.
///
/// **The record a person writes, read by the game rather than copied into
/// it.** Every game here keeps one beside its models, in one of two shapes:
///
/// * a section a file, its heading naming the files in backticks and a
///   two-column table under it with `Author`, `Source` and `Licence` rows;
/// * one table a file, with a `File` column, when the whole directory has one
///   licence stated once above it.
///
/// Both are read; anything else in the file is prose and is kept as [text],
/// so a file named only in a paragraph still counts as mentioned.
final class LicenseRecord {
  LicenseRecord._(this.entries, this.text);

  /// Reads [markdown]. Never throws: a section with no table is an entry
  /// with its files and nothing else.
  factory LicenseRecord.parse(String markdown) {
    final entries = <LicenseEntry>[];
    List<String>? files;
    final rows = <String, String>{};
    var inFileTable = false;

    void close() {
      final named = files;
      if (named != null && named.isNotEmpty) {
        entries.add(_entry(named, rows));
      }
      files = null;
      rows.clear();
    }

    for (final line in markdown.split('\n')) {
      final trimmed = line.trim();
      if (trimmed.startsWith('## ')) {
        close();
        inFileTable = false;
        files = _fileNames(trimmed);
        continue;
      }
      if (!trimmed.startsWith('|')) {
        inFileTable = false;
        continue;
      }
      final cells = _cells(trimmed);
      if (cells.isEmpty) continue;
      if (cells.first.toLowerCase() == 'file') {
        inFileTable = true;
        continue;
      }
      if (inFileTable) {
        // Under a section that already names its files, a `File` table is a
        // note about them (which is which), not an entry of its own.
        final named = _fileNames(cells.first);
        if (files == null && named.isNotEmpty) {
          entries.add(LicenseEntry(files: named));
        }
        continue;
      }
      if (cells.length >= 2) rows[cells[0].toLowerCase()] = cells[1];
    }
    close();
    return LicenseRecord._(List<LicenseEntry>.unmodifiable(entries), markdown);
  }

  /// Every section and file row, in the order the file has them.
  final List<LicenseEntry> entries;

  /// The whole file.
  final String text;

  /// The entry that names [fileName], or null.
  LicenseEntry? entryFor(String fileName) {
    for (final entry in entries) {
      if (entry.files.contains(fileName)) return entry;
    }
    return null;
  }

  /// Whether the record names [fileName] anywhere, in a heading, a row or
  /// a sentence.
  bool mentions(String fileName) =>
      entryFor(fileName) != null || text.contains(fileName);

  List<String> _disagreementsWith(Credit credit) {
    final name = credit.file.split('/').last;
    if (!mentions(name)) {
      return <String>['the licence record does not mention $name'];
    }
    final entry = entryFor(name);
    return <String>[
      if (entry?.license case final recorded?
          when credit.license != null && recorded != credit.license)
        '$name is credited as ${credit.license}; the record says $recorded',
      if (entry?.author case final recorded?
          when credit.author != null && recorded != credit.author)
        '$name is credited to ${credit.author}; the record says $recorded',
    ];
  }
}

final RegExp _backticked = RegExp(r'`([^`/\s]+\.[A-Za-z0-9]+)`');
final RegExp _link = RegExp(r'<?(https?://[^\s>]+)>?');

List<String> _fileNames(String text) => <String>[
  for (final match in _backticked.allMatches(text)) match.group(1)!,
];

List<String> _cells(String row) {
  final inner = row.substring(1, row.endsWith('|') ? row.length - 1 : null);
  final cells = <String>[for (final cell in inner.split('|')) cell.trim()];
  // The rule under a header, `|---|---|`, is no row.
  if (cells.every((String c) => RegExp(r'^:?-*:?$').hasMatch(c))) {
    return const <String>[];
  }
  return cells;
}

LicenseEntry _entry(List<String> files, Map<String, String> rows) {
  final license = rows['licence'] ?? rows['license'];
  return LicenseEntry(
    files: List<String>.unmodifiable(files),
    author: switch (rows['author']) {
      final author? => _beforeLink(author),
      null => null,
    },
    source: rows['source'],
    license: switch (license) {
      final l? => _beforeLink(l),
      null => null,
    },
    licenseUrl: switch (license) {
      final l? => _link.firstMatch(l)?.group(1),
      null => null,
    },
  );
}

/// `**CC0 1.0** — http://…` → `CC0 1.0`; `Kenney, https://…` → `Kenney`.
String? _beforeLink(String cell) {
  final plain = cell.replaceAll('**', '');
  final at = plain.indexOf(_link);
  final head = (at < 0 ? plain : plain.substring(0, at)).trim();
  final name = head.replaceFirst(RegExp(r'[\s—,:-]+$'), '').trim();
  return name.isEmpty ? null : name;
}
