/// Translates the engine's GLSL into a Dart file of GLSL ES 3.00 sources.
///
///     dart run tool/generate_shaders.dart
///
/// Generated at build time rather than translated at run time, for the same
/// reason the Impeller backend ships a compiled bundle: a translation that
/// fails should fail while somebody is looking, not on a user's first frame.
/// It also means the web build carries no GLSL sources and no translator.
///
/// The sources come from `flutter3d_shaders`, resolved by package name through
/// `.dart_tool/package_config.json` — the one mapping pub guarantees for path,
/// git and hosted dependencies alike. A relative path would work here and break
/// the day this package is consumed from the cache.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter3d_webgl/src/glsl_translate.dart';

void main(List<String> args) {
  final root = _sourcePackageRoot();
  final shaders = Directory('$root/shaders');
  if (!shaders.existsSync()) {
    _fail('no shaders/ in $root');
  }

  final sources = <String, String>{};
  for (final file in shaders.listSync(recursive: true).whereType<File>()) {
    final path = file.path;
    if (!path.endsWith('.glsl') &&
        !path.endsWith('.frag') &&
        !path.endsWith('.vert')) {
      continue;
    }
    sources[path.substring(shaders.path.length + 1)] = file.readAsStringSync();
  }

  // The same manifest impellerc reads. One list of entry points for both
  // backends, so a shader added for one cannot be quietly missing from the
  // other — the engine asks for a name and both must answer to it.
  final manifestFile = File('${shaders.path}/flutter3d.shaderbundle.json');
  if (!manifestFile.existsSync()) _fail('no manifest at ${manifestFile.path}');
  final manifest =
      jsonDecode(manifestFile.readAsStringSync()) as Map<String, dynamic>;

  final vertex = <String, String>{};
  final fragment = <String, String>{};
  manifest.forEach((name, spec) {
    final entry = spec as Map<String, dynamic>;
    final file = (entry['file'] as String).replaceFirst('shaders/', '');
    final source = sources[file] ??
        _fail('$name names $file, which is not in shaders/');
    final isFragment = entry['type'] == 'fragment';
    final translated =
        translateGlsl(source, sources, from: file, fragment: isFragment);
    (isFragment ? fragment : vertex)[name] = translated;
  });

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_shaders.dart. Do not edit.')
    ..writeln('//')
    ..writeln('// Source: package:flutter3d_shaders, translated to GLSL ES')
    ..writeln('// 3.00. Re-run the generator when those shaders change; there')
    ..writeln('// is no check that this file is current, which is the same')
    ..writeln('// bargain the compiled Impeller bundle makes.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'src/webgl_shaders.dart';")
    ..writeln()
    ..writeln('/// Every shader the engine asks for, in GLSL ES 3.00.')
    ..writeln('final ShaderSources engineShaders = ShaderSources(')
    ..writeln('  <String, String>{');
  vertex.forEach((name, src) => out.writeln("    '$name': r'''$src''',"));
  out
    ..writeln('  },')
    ..writeln('  <String, String>{');
  fragment.forEach((name, src) => out.writeln("    '$name': r'''$src''',"));
  out
    ..writeln('  },')
    ..writeln(');');

  final target = File('lib/engine_shaders.dart');
  target.writeAsStringSync(out.toString());
  stdout.writeln(
      'wrote ${target.path}: ${vertex.length} vertex, ${fragment.length} '
      'fragment');
}

/// Where `flutter3d_shaders` unpacked to, from the package config.
String _sourcePackageRoot() {
  var dir = Directory.current;
  while (true) {
    final config = File('${dir.path}/.dart_tool/package_config.json');
    if (config.existsSync()) {
      final json =
          jsonDecode(config.readAsStringSync()) as Map<String, dynamic>;
      for (final entry in (json['packages'] as List<dynamic>)) {
        final package = entry as Map<String, dynamic>;
        if (package['name'] != 'flutter3d_shaders') continue;
        // rootUri is a URI and relative for a workspace member, resolved
        // against .dart_tool/ — which is why this is Uri.resolve and not a
        // string join.
        final base = Uri.directory('${dir.path}/.dart_tool/');
        return base
            .resolve(package['rootUri'] as String)
            .toFilePath()
            .replaceAll(RegExp(r'/$'), '');
      }
      _fail('flutter3d_shaders is not in ${config.path}. '
          'Is it a dependency, and has `flutter pub get` run?');
    }
    final parent = dir.parent;
    if (parent.path == dir.path) {
      _fail('no .dart_tool/package_config.json above ${Directory.current.path}');
    }
    dir = parent;
  }
}

Never _fail(String message) {
  stderr.writeln('generate_shaders: $message');
  exit(2);
}
