/// A 3D engine, written against a graphics vocabulary rather than a graphics
/// API.
///
/// Everything a consumer needs is exported here. The layout behind it is not
/// arbitrary and is worth knowing before reaching past this file:
///
/// - **This package names no graphics API.** It depends on `flutter3d_hardware` and
///   nothing below it, so an application chooses a backend package
///   today — and hands it to `Renderer.create`. That is checked, not intended:
///   `tool/structure.dart`'s "the engine names no backend" rule, which scans
///   this package's `lib/`. The rule named here until now — "the hardware
///   layer names no graphics API" — scans `flutter3d_hardware` and says
///   nothing whatever about this file's claim.
/// - `geometry`, `scene`, `assets` and `render/key_sort` need no device at all,
///   which is what lets bounds, culling, framing, picking, decoding and sorting
///   be unit tested without one.
///
/// The shader bundle is still an asset of *this* package, and that is a known
/// wrinkle rather than a decision: a compiled bundle is one backend's output,
/// so it belongs with
/// the backend that can read it. The GLSL it is built from is shared. Moving it
/// is a question about where shader sources live, which is worth answering on
/// its own rather than as a side effect of the package split.
/// `packages/flutter3d_impeller/tool/build_shaders.sh` builds it — beside the
/// backend that needs it, not beside this package — and it has to be rebuilt
/// after every Flutter SDK change.
library;

// The rendering core: animation, assets, the render graph and the scene
// graph, with the geometry and the model formats under them — everything that
// resolves without the Flutter SDK, which mcp-03n moved to its own package
// once the four files that did not were down to four small seams. See
// `flutter3d_core`'s own doc comment for the full account of what moved and
// why.
//
// **Named, not whole.** Everything below the core is a promise from 1.0.0, so
// the list says which of its names are this package's API too: the ones
// applications, examples and tests reach through this import, the types those
// names are written in, and what the guides name. A name added to the core
// becomes API here only by being added to this list. What is left out — the
// format internals (`F3dSection`, the KTX2 field tables), the material
// language's syntax tree, the block encoders, the splat and shadow
// bookkeeping — is still public in `flutter3d_core`, one import away.
export 'package:flutter3d_core/flutter3d_core.dart'
    show
        AdaptiveQuality,
        AdaptiveQualitySettings,
        AdaptiveScale,
        AdaptiveScaleSettings,
        AmbientOcclusionMethod,
        AmbientOcclusionSettings,
        AnimationBlend,
        AnimationBlendSpace,
        AnimationClip,
        AnimationComparison,
        AnimationCondition,
        AnimationGoal,
        AnimationGraph,
        AnimationGraphFormatException,
        AnimationGraphJson,
        AnimationGraphLayer,
        AnimationInterpolation,
        AnimationLayer,
        AnimationMarker,
        AnimationMask,
        AnimationParameter,
        AnimationParameterSchema,
        AnimationParameterType,
        AnimationParameters,
        AnimationPath,
        AnimationPlayer,
        AnimationPointer,
        AnimationPointerProperty,
        AnimationPointerSink,
        AnimationPointerTarget,
        AnimationPose,
        AnimationState,
        AnimationStateMachine,
        AnimationTarget,
        AnimationTrack,
        AnimationTransition,
        AnimationWrap,
        AntiAliasSettings,
        AssetRequest,
        AssetSource,
        AssetSourceFactory,
        AssetSources,
        AssetUriResolver,
        Atmosphere,
        AtmosphereCycle,
        AutoExposureSettings,
        BakedPoses,
        BlendPoint,
        BloomSettings,
        BoolCondition,
        BundledMaterials,
        CameraNode,
        CapsuleShape,
        CaptureThumbnail,
        CapturedImage,
        CapturedPass,
        CellGrid,
        ChangedBounds,
        CheckedModelWriter,
        CheckerboardTexture,
        ColorHint,
        ColorVision,
        ColorVisionDeficiency,
        CompareCondition,
        CompiledFrameGraph,
        ConeShape,
        ContactShadowSettings,
        ContributorFrame,
        ContributorLights,
        CpuMesh,
        CropProjection,
        CubeLut,
        CubeLutFormatException,
        CuboidShape,
        CylinderShape,
        DebugColors,
        DebugDraw,
        DebugDrawGizmos,
        DebugDrawSettings,
        DebugView,
        DebugViewKind,
        DebugViewSettings,
        DebugWipeSide,
        DecalNode,
        DecalSettings,
        DecodedImage,
        DepthOfFieldSettings,
        DerivedShape,
        DeviceClass,
        DeviceClassMemory,
        DeviceClassPicker,
        DeviceClassSelector,
        DeviceMesh,
        DeviceTraits,
        DiffuseModel,
        DiscShape,
        DisplayTransform,
        DocumentAsset,
        DocumentDifference,
        DracoAttribute,
        DracoAttributeType,
        DracoException,
        DracoMesh,
        DrawJournal,
        DrawRecord,
        DrawableGeometry,
        EdgeSmoothing,
        EffectiveAntiAliasing,
        EncodedImage,
        EnumHint,
        EnumHintValue,
        EnvironmentMap,
        ExportReport,
        ExposureAdapter,
        ExposureMeter,
        F3dDecoder,
        F3dDocument,
        F3dExtraSection,
        F3dFormatException,
        F3dModelWriter,
        F3dSectionFlags,
        F3dWriter,
        FabrikIk,
        FbxDecoder,
        FbxFormatException,
        FieldPass,
        FileAssetSource,
        FmatFormatException,
        FogSettings,
        FootLeg,
        FootPlantGoal,
        FrameCapture,
        FrameCaptureFormatException,
        FrameContext,
        FrameFraction,
        FrameGraph,
        FrameGraphError,
        FrameGraphNode,
        FrameHeld,
        FrameHistory,
        FramePacing,
        FramePass,
        FramePipelineStall,
        FrameResourceIds,
        FrameResources,
        FrameResult,
        FrameTextureSource,
        FrameWorkBudget,
        FreeLook,
        FullscreenDraw,
        FullscreenEffect,
        GlbContainer,
        GlbModelWriter,
        GltfAsset,
        GltfComponentType,
        GltfFormatException,
        GltfLoader,
        GltfWriter,
        HdrFormatException,
        HdrImage,
        HiZOcclusion,
        HighContrastSettings,
        HitResult,
        ImageDecoder,
        ImageFormatException,
        ImpostorNode,
        InstanceHandle,
        InstancedMeshNode,
        IrradianceField,
        JitteredProjection,
        Ktx2FormatException,
        Ktx2Texture,
        LatheShape,
        LensFlareSettings,
        LightChannels,
        LightGroup,
        LightNode,
        LightShaftSettings,
        LightType,
        LightingModel,
        LineStripNode,
        LocalExposureSettings,
        LocalRay,
        LodGroup,
        LodLevel,
        LookGoal,
        LookSettings,
        MaterialAlphaMode,
        MaterialBindings,
        MaterialBundleException,
        MaterialDocument,
        MaterialExtensions,
        MaterialHint,
        MaterialHintKind,
        MaterialMap,
        MaterialParameter,
        MaterialProgram,
        MaterialSortIds,
        MaterialStatement,
        MaterialSurfaceValues,
        MaterialSyntaxException,
        MaterialTextureSlot,
        MaterialType,
        MaterialVariant,
        MemoryCategory,
        MemoryEntry,
        MemoryReport,
        MeshBuilder,
        MeshClusters,
        MeshData,
        MeshGeometry,
        MeshNode,
        MeshOverlay,
        MeshTangents,
        MeshoptFormatException,
        MeterRect,
        ModelCamera,
        ModelCameraProjection,
        ModelDecoder,
        ModelDecoders,
        ModelDocument,
        ModelFormat,
        ModelImpostor,
        ModelLight,
        ModelLightType,
        ModelLoadRequest,
        ModelLod,
        ModelNode,
        ModelPart,
        ModelPerspectiveCamera,
        ModelSkin,
        ModelSplat,
        ModelSurface,
        ModelWrite,
        ModelWriteFormat,
        ModelWriteRequest,
        ModelWriter,
        MorphBlend,
        MorphSink,
        MorphState,
        MorphTarget,
        MorphTexture,
        MotionBlurSettings,
        MtlMaterial,
        NodeHistory,
        ObjDocument,
        ObjLoader,
        ObjModelWriter,
        ObjNormals,
        ObjWriter,
        ObjectIdFrame,
        OcclusionBuffer,
        OcclusionMode,
        OcclusionTest,
        OffAxisProjection,
        OpenPath,
        OrbitController,
        OrthographicProjection,
        OutputTransform,
        OverlayBatch,
        PackedIndices,
        PagedSplatOctree,
        PanoramaFormatException,
        ParameterWrite,
        PassContribution,
        PassContributor,
        PassSkip,
        PerspectiveProjection,
        PhotoCaptureReport,
        PhotoFilter,
        PhotoFinish,
        Photometric,
        PhysicalCamera,
        PhysicalSky,
        PipelineGeometry,
        PipelineStall,
        PlainModelDocument,
        PlanarReflectionSettings,
        PlanarReflectorNode,
        PlaneShape,
        PointerTargets,
        PosedMesh,
        PostFrameResult,
        ProceduralTexture,
        Projection,
        QualityRow,
        QualitySetting,
        QualityTable,
        RangeHint,
        Raycaster,
        ReachGoal,
        ReactiveFrame,
        ReactiveShape,
        ReflectionProbeNode,
        ReflectionSettings,
        RenderFrame,
        RenderListener,
        RenderMaterial,
        RenderNode,
        RenderServices,
        RenderSettings,
        RenderStep,
        RenderView,
        RenderViewSettings,
        Renderer,
        RendererSteps,
        ResourceCache,
        ResourceDesc,
        ResourceHandle,
        ResourceId,
        ResourceOrigin,
        ResourceSize,
        ResourceVersion,
        Rgba8Image,
        Scene,
        SceneBvh,
        SceneNode,
        ScreenBounds,
        ShadowCasterFaces,
        ShadowCastingMode,
        ShadowFilter,
        ShadowKernel,
        ShadowPrefilter,
        ShadowSettings,
        ShadowTechnique,
        Shape,
        Skeleton,
        SkinBlend,
        SkippedPass,
        SkyColor,
        SkyDome,
        SkyGradient,
        SkyLook,
        SkySettings,
        SoftwareOcclusion,
        SolidColorTexture,
        SortMode,
        SpatialUpscaleSettings,
        SphereShape,
        SplatAxes,
        SplatCloud,
        SplatColorSpace,
        SplatComposite,
        SplatContributor,
        SplatGpuSort,
        SplatLens,
        SplatLod,
        SplatOctree,
        SplatOctreeException,
        SplatOctreeNode,
        SplatPlyException,
        SplatQuads,
        SplatRangeReader,
        SplatSorter,
        SplatSpzException,
        StlLoader,
        StlModelWriter,
        StlNormals,
        StlWriter,
        SurfaceAlphaMode,
        SurfaceMaterial,
        TangentMethod,
        TemporalClip,
        TemporalSettings,
        TextureBinding,
        TextureHint,
        TextureSampling,
        TextureTransform,
        TextureWrap,
        TiledProjection,
        TonemapCurve,
        TorusShape,
        TransparencyMode,
        TriangleBvh,
        TriggerCondition,
        TwoBoneIk,
        UniversalTarget,
        UsdzModelWriter,
        UsdzWriter,
        VertexAttribute,
        VertexLayout,
        ViewModelNode,
        ViewportRect,
        ViewportShading,
        ViewportShadingSettings,
        VkFormat,
        VolumetricFogSettings,
        WorldRay,
        WrittenFile,
        XraySettings,
        advanceTime,
        averageCacheMissRatio,
        bloomLevelsFor,
        buildIdentityLut,
        buildMipChain,
        buildPolyline,
        buildSplatOctree,
        buildsMipChain,
        builtInMaterialHints,
        builtInModelDecoder,
        builtInModelExtensions,
        builtInModelWriters,
        canDecodeFileName,
        capturePhoto,
        compareModelDocuments,
        contributionBetween,
        coreFormats,
        decodeDataUri,
        decodeDraco,
        decodeJpeg,
        decodeModel,
        decodeModelBytes,
        decodeModelInIsolate,
        decodePng,
        defaultVertexCacheSize,
        describeEmptyFrame,
        describeMaterial,
        deviceClassPath,
        emitMaterialFragment,
        encodeAstc4x4,
        encodeBc1,
        encodeBc3,
        encodeCompressedPng,
        encodeEtc2Rgb8,
        encodeModel,
        encodeModelInIsolate,
        evaluateMaterial,
        exportChecked,
        exportToGlb,
        exportToObj,
        exportToStl,
        f3dVendorKindStart,
        fileUriResolver,
        followCamera,
        gather,
        impostorCard,
        impostorGrid,
        impostorRight,
        impostorViewDirection,
        inflate,
        isF3dFile,
        isFmat,
        isMissingFile,
        measureFrameMicros,
        modelWriterNamed,
        optimizeTriangleOrder,
        optimizeVertexFetch,
        paintSky,
        parseMaterial,
        parseSplatPly,
        parseSplatSpz,
        payloadBits,
        photoSettings,
        projectPoint,
        rayAabb,
        raySphere,
        rayTriangle,
        readFmat,
        readHdr,
        recognizedModelFormat,
        ribbon,
        rootMotionExtra,
        safeRelativeAssetPath,
        samplerOptionsFor,
        screenBoundsOfBox,
        screenMotion,
        skyNode,
        sniffModelFormat,
        sortPackedKeys,
        specializeMaterial,
        splatBytesReader,
        splatGpuSortLimit,
        splatShC0,
        splatVerticesPerSplat,
        textureBytes,
        toDepthRange,
        toFramebufferOrigin,
        toReversedDepth,
        uploadEncodedImage,
        uploadRgba8,
        validateGltfExport,
        viewAxisOf,
        withDepthPlanes,
        withTextureTransform,
        writeFmat,
        writeKtx2,
        writeKtx2WithMips;
// The foundation's value types this package's API, and the core's under
// it, are written in: the colour and the position every material, light and
// node takes, their crossings into `vector_math`, and the exception roots a
// caller catches. Named, like the core's and the hardware's.
export 'package:flutter3d_foundation/flutter3d_foundation.dart'
    show
        CapabilityException,
        Flutter3dException,
        Flutter3dFormatException,
        LinearColor,
        LinearColorVector,
        PluginException,
        ResourceException,
        Vector3Foundation,
        Vector4Foundation,
        WorldPosition,
        WorldPositionVector;
// The graphics vocabulary, re-exported from `flutter3d_hardware`.
//
// Re-exported rather than left for a consumer to depend on separately, because
// these names are all over this package's own API — a `RenderMaterial` holds
// `SamplerDescriptor`, a `RenderNode` is handed a `GraphicsDevice` — and a
// consumer should not have to add a dependency to spell the type of something
// this package handed them.
//
// The backend is deliberately **not** re-exported. An application picks one and
// depends on one by name; there are three today — `flutter3d_impeller`,
// `flutter3d_webgl` and `flutter3d_cpu` — and room for more.
// That choice is the one thing that must stay visible in an application's
// pubspec.
//
// Named, like the core above: the HAL types this package's API and its users'
// code are written in. The registries a backend fills in, the format tables
// and the shader-library plumbing stay `flutter3d_hardware`'s.
export 'package:flutter3d_hardware/flutter3d_hardware.dart'
    show
        BackendOpener,
        BlendFactor,
        BlendOperation,
        BlendState,
        BufferDescriptor,
        BufferLayout,
        BufferTextureLayout,
        BufferUsage,
        ColorTarget,
        ColorWriteMask,
        CommandEncoder,
        CompareFunction,
        ComputeEncoder,
        ComputePipelineHandle,
        CullMode,
        DepthBias,
        DepthRange,
        DepthTarget,
        DeviceFeature,
        DeviceFeatures,
        DeviceLimits,
        DeviceRegistry,
        DeviceResourceException,
        DeviceUnavailableException,
        FeatureStability,
        FramebufferOrigin,
        GeometryBuffer,
        GeometryUsage,
        GpuFrameTimings,
        GpuPassTiming,
        GraphicsDevice,
        IndexType,
        IndexedDraw,
        InputAttribute,
        LoadAction,
        LoadedShaderLibrary,
        MapMode,
        MappedBuffer,
        MinMagFilter,
        MipChain,
        MipFilter,
        PassEncoder,
        PassState,
        PassTimestampWrites,
        PipelineHandle,
        PolygonMode,
        PrimitiveType,
        QuerySet,
        QueryType,
        RenderBundle,
        RenderBundleDescriptor,
        RenderBundleEncoder,
        RenderPassDescriptor,
        RenderTargetPool,
        RenderTargetDescriptor,
        SamplerAddressMode,
        SamplerBorderColor,
        SamplerDescriptor,
        ScreenRect,
        ShaderBundle,
        ShaderBundleException,
        ShaderBundleStage,
        ShaderHandle,
        ShaderLibrary,
        StageBindings,
        StencilOperation,
        StencilState,
        StorageBuffer,
        StorageMode,
        StorageTextureAccess,
        StoreAction,
        SynchronousBufferReadback,
        TextureAllocator,
        TextureCopyLocation,
        TextureDescriptor,
        TextureDimension,
        TextureFormat,
        TextureFormatStencil,
        TextureFormatSupport,
        TextureHandle,
        TextureRegion,
        TextureType,
        TextureUsage,
        TransferEncoder,
        UniformBlock,
        UniformMemberLayout,
        UnsupportedCapability,
        VertexFormat,
        VertexLayoutDescriptor,
        VertexStepMode,
        WindingOrder,
        decodeMaterialSection,
        encodeMaterialSection,
        indexWindow,
        readbackFormats,
        readbackRegionOf;
// The simulation, the physics and the audio are not re-exported: a game
// that steps a level names `flutter3d_sim`, or takes `flutter3d_game`, the
// one facade, which re-exports what a first game uses of them.
// `Colors` is Flutter's name; the vectors come without vector_math's own.
export 'package:vector_math/vector_math.dart'
    show Matrix3, Quaternion, Vector2, Vector3, Vector4;

// What could not go with the hardware list above, each because it needs
// something this package may name and that one may not: the two Flutter-named
// asset sources and glTF resolvers, `defaultImageDecoder`, everything from
// `ModelAsset` down that defaults to it, and the crossing from a Flutter
// `Color` to the engine's linear colour.
export 'src/engine/assets/bundle_asset_source.dart';
export 'src/engine/assets/decoders.dart';
export 'src/engine/assets/default_image_decoder.dart';
export 'src/engine/assets/gltf_resolvers.dart';
export 'src/engine/assets/load_model_asset.dart';
export 'src/engine/assets/material_loader.dart';
export 'src/engine/assets/model_asset.dart';
export 'src/engine/assets/model_wardrobe.dart';
export 'src/engine/assets/revalidated_asset.dart';
export 'src/engine/linear_color_flutter.dart';

// Particles are `package:flutter3d_particles` and are named nowhere here.
// The engine defines what a contributor is; what draws through one is not its
// business, which is the whole test of the extension model.
