/// Turns `lib/src/db/migrations/*.sql` into one Dart file the binary carries.
///
/// **A compiled `dart compile exe` has no files beside it.** The service is one
/// executable rsynced to a server, so a migration read from disk at start would
/// be a migration that has to be deployed separately — and the failure mode is
/// a schema one version behind with nothing in the log to say why.
///
///     dart run tool/embed_migrations.dart          # write
///     dart run tool/embed_migrations.dart --check   # fail if stale
///
/// The `--check` form is what CI runs: the generated file is in the repository,
/// so a `.sql` edited without regenerating is a diff rather than a surprise in
/// production.
library;

import 'dart:io';

void main(List<String> arguments) {
  final check = arguments.contains('--check');
  final root = Directory.current;
  final source = Directory('${root.path}/lib/src/db/migrations');
  final target = File('${root.path}/lib/src/db/migrations.g.dart');

  if (!source.existsSync()) {
    stderr.writeln('No ${source.path}. Run this from cloud/server.');
    exit(2);
  }

  final files =
      source
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.sql'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

  final generated = _render([
    for (final file in files)
      (name: _basename(file.path), sql: file.readAsStringSync()),
  ]);

  if (check) {
    final current = target.existsSync() ? target.readAsStringSync() : '';
    if (current == generated) {
      stdout.writeln('migrations.g.dart is current (${files.length} files)');
      return;
    }
    stderr.writeln(
      'migrations.g.dart is stale. Run: dart run tool/embed_migrations.dart',
    );
    exit(1);
  }

  target.writeAsStringSync(generated);
  stdout.writeln('wrote ${target.path} (${files.length} migrations)');
}

String _basename(String path) => path.split(Platform.pathSeparator).last;

String _render(List<({String name, String sql})> files) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/embed_migrations.dart. Do not edit.')
    ..writeln('// Source: lib/src/db/migrations/*.sql')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'database.dart';")
    ..writeln()
    ..writeln('/// Every migration, in the order their numbers put them.')
    ..writeln('const migrations = <Migration>[');

  for (final file in files) {
    final version = int.parse(file.name.split('_').first);
    buffer
      ..writeln('  Migration(')
      ..writeln('    $version,')
      ..writeln("    '${file.name}',")
      ..writeln("    r'''")
      ..write(file.sql)
      ..writeln("''',")
      ..writeln('  ),');
  }

  buffer.writeln('];');
  return buffer.toString();
}
