// GENERATED by flutter3d_build from the material sources. Do not edit;
// change the .f3dmat and build again.

/// Typed accessors for the uniforms of the materials written in
/// the material language — one per material, over the
/// `RenderMaterial.parameters` map the renderer binds.
library;

import 'dart:typed_data';

import 'package:vector_math/vector_math.dart';

/// The uniforms of the material `Liquid`, from `assets_src/liquid.f3dmat`, typed.
///
/// Over [parameters], which it reads and writes in place: the
/// map a `RenderMaterial` is drawn with, or a `FullscreenEffect`'s
/// `MaterialParams`. A member the map lacks is added at nought.
extension type LiquidParameters(Map<String, Float32List> parameters) {
  /// The material's name in its bundle.
  static const String materialName = 'Liquid';

  /// Every uniform at its declared default, a fresh map each
  /// call — what `BundledMaterials.parameters` starts from.
  static Map<String, Float32List> defaults() => <String, Float32List>{
    'time': Float32List.fromList(<double>[0.0]),
    'chop': Float32List.fromList(<double>[1.0]),
    'eye': Float32List.fromList(<double>[0.0, 10.0, 0.0]),
    'pixel': Float32List.fromList(<double>[0.001]),
    'toSun': Float32List.fromList(<double>[-0.35, 0.7, 0.6]),
    'sunColor': Float32List.fromList(<double>[2.0, 1.95, 1.85]),
    'zenith': Float32List.fromList(<double>[0.22, 0.42, 0.78]),
    'horizon': Float32List.fromList(<double>[0.68, 0.79, 0.92]),
    'absorb': Float32List.fromList(<double>[0.264, 0.0565, 0.0106]),
    'scatter': Float32List.fromList(<double>[0.0023, 0.0166, 0.151]),
    'glow': Float32List.fromList(<double>[0.0, 0.0, 0.0]),
  };

  /// `uniform float time`, 0.0 by default.
  double get time => _at('time', 1)[0];

  set time(double value) => _at('time', 1)[0] = value;

  /// `uniform float chop`, 1.0 by default.
  double get chop => _at('chop', 1)[0];

  set chop(double value) => _at('chop', 1)[0] = value;

  /// `uniform vec3 eye`, 0.0, 10.0, 0.0 by default.
  Vector3 get eye => Vector3.array(_at('eye', 3));

  set eye(Vector3 value) => _at('eye', 3).setAll(0, value.storage);

  /// `uniform float pixel`, 0.001 by default.
  double get pixel => _at('pixel', 1)[0];

  set pixel(double value) => _at('pixel', 1)[0] = value;

  /// `uniform vec3 toSun`, -0.35, 0.7, 0.6 by default.
  Vector3 get toSun => Vector3.array(_at('toSun', 3));

  set toSun(Vector3 value) => _at('toSun', 3).setAll(0, value.storage);

  /// `uniform vec3 sunColor`, 2.0, 1.95, 1.85 by default.
  Vector3 get sunColor => Vector3.array(_at('sunColor', 3));

  set sunColor(Vector3 value) => _at('sunColor', 3).setAll(0, value.storage);

  /// `uniform vec3 zenith`, 0.22, 0.42, 0.78 by default.
  Vector3 get zenith => Vector3.array(_at('zenith', 3));

  set zenith(Vector3 value) => _at('zenith', 3).setAll(0, value.storage);

  /// `uniform vec3 horizon`, 0.68, 0.79, 0.92 by default.
  Vector3 get horizon => Vector3.array(_at('horizon', 3));

  set horizon(Vector3 value) => _at('horizon', 3).setAll(0, value.storage);

  /// `uniform vec3 absorb`, 0.264, 0.0565, 0.0106 by default.
  Vector3 get absorb => Vector3.array(_at('absorb', 3));

  set absorb(Vector3 value) => _at('absorb', 3).setAll(0, value.storage);

  /// `uniform vec3 scatter`, 0.0023, 0.0166, 0.151 by default.
  Vector3 get scatter => Vector3.array(_at('scatter', 3));

  set scatter(Vector3 value) => _at('scatter', 3).setAll(0, value.storage);

  /// `uniform vec3 glow`, 0.0, 0.0, 0.0 by default.
  Vector3 get glow => Vector3.array(_at('glow', 3));

  set glow(Vector3 value) => _at('glow', 3).setAll(0, value.storage);

  Float32List _at(String name, int length) =>
      parameters[name] ??= Float32List(length);
}

/// The uniforms of the material `Seabed`, from `assets_src/seabed.f3dmat`, typed.
///
/// Over [parameters], which it reads and writes in place: the
/// map a `RenderMaterial` is drawn with, or a `FullscreenEffect`'s
/// `MaterialParams`. A member the map lacks is added at nought.
extension type SeabedParameters(Map<String, Float32List> parameters) {
  /// The material's name in its bundle.
  static const String materialName = 'Seabed';

  /// Every uniform at its declared default, a fresh map each
  /// call — what `BundledMaterials.parameters` starts from.
  static Map<String, Float32List> defaults() => <String, Float32List>{
    'time': Float32List.fromList(<double>[0.0]),
    'chop': Float32List.fromList(<double>[1.0]),
    'eye': Float32List.fromList(<double>[0.0, 10.0, 0.0]),
    'level': Float32List.fromList(<double>[0.0]),
    'toSun': Float32List.fromList(<double>[-0.35, 0.7, 0.6]),
    'sunColor': Float32List.fromList(<double>[2.0, 1.95, 1.85]),
    'absorb': Float32List.fromList(<double>[0.264, 0.0565, 0.0106]),
    'scatter': Float32List.fromList(<double>[0.0023, 0.0166, 0.151]),
  };

  /// `uniform float time`, 0.0 by default.
  double get time => _at('time', 1)[0];

  set time(double value) => _at('time', 1)[0] = value;

  /// `uniform float chop`, 1.0 by default.
  double get chop => _at('chop', 1)[0];

  set chop(double value) => _at('chop', 1)[0] = value;

  /// `uniform vec3 eye`, 0.0, 10.0, 0.0 by default.
  Vector3 get eye => Vector3.array(_at('eye', 3));

  set eye(Vector3 value) => _at('eye', 3).setAll(0, value.storage);

  /// `uniform float level`, 0.0 by default.
  double get level => _at('level', 1)[0];

  set level(double value) => _at('level', 1)[0] = value;

  /// `uniform vec3 toSun`, -0.35, 0.7, 0.6 by default.
  Vector3 get toSun => Vector3.array(_at('toSun', 3));

  set toSun(Vector3 value) => _at('toSun', 3).setAll(0, value.storage);

  /// `uniform vec3 sunColor`, 2.0, 1.95, 1.85 by default.
  Vector3 get sunColor => Vector3.array(_at('sunColor', 3));

  set sunColor(Vector3 value) => _at('sunColor', 3).setAll(0, value.storage);

  /// `uniform vec3 absorb`, 0.264, 0.0565, 0.0106 by default.
  Vector3 get absorb => Vector3.array(_at('absorb', 3));

  set absorb(Vector3 value) => _at('absorb', 3).setAll(0, value.storage);

  /// `uniform vec3 scatter`, 0.0023, 0.0166, 0.151 by default.
  Vector3 get scatter => Vector3.array(_at('scatter', 3));

  set scatter(Vector3 value) => _at('scatter', 3).setAll(0, value.storage);

  Float32List _at(String name, int length) =>
      parameters[name] ??= Float32List(length);
}
