import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter3d_physics/flutter3d_physics.dart';
import 'package:vector_math/vector_math.dart';

import 'level.dart';
import 'level_collision.dart';

/// Which parts of a level can be seen from where, decided before the game
/// runs.
///
/// **A brush level is the one kind of level this is cheap for.** Every wall is
/// an axis-aligned box, so "can a ray get from here to there" is a question
/// the collision world already answers exactly, and the empty space between
/// the walls divides into a grid whose cells are the units of the answer. Each
/// cell carries a bit per other cell — visible or not — computed once by a
/// tool and stored beside the level, and a frame asks one question: which
/// cell is the camera in, and which batches of geometry touch a cell that one
/// can see. Everything else is not drawn.
///
/// ## What "visible" means, and which way the errors fall
///
/// Two cells see each other when **any** ray between a handful of sample
/// points in one and a handful in the other crosses no solid brush. That is
/// a sample, not a proof, and a sample can miss a slit narrower than the
/// spacing between points — which would hide a room somebody can see into,
/// the one failure this must not have. Three things push the errors the safe
/// way:
///
/// * cells that touch, even at a corner, always see each other;
/// * a cell no sample point of which is in empty space is *closed*, and a
///   camera standing in a closed cell — or outside the grid — sees
///   everything;
/// * a batch is drawn if **any** cell its bounds overlap is visible, so a
///   long wall reaching into a visible room is drawn whole.
///
/// What is left is a room seen only through a gap thinner than the sampling.
/// The test in the dungeon fires thousands of random rays through the crypt
/// and checks the table against them; the number it settles on is the one
/// this class is trusted to.
///
/// ## Why it lives beside the level rather than in it
///
/// The dungeon's levels are generated by scripts and CI regenerates them, so
/// a table written into the document would be gone on the next run. It is a
/// sidecar, `<level>.visibility.json`, carrying a hash of the brushes it was
/// baked from; a table whose hash no longer matches the level is ignored with
/// a word, and the level draws everything, as it did before there was one.
final class LevelVisibility {
  LevelVisibility._({
    required this.cellSize,
    required this.origin,
    required this.countX,
    required this.countY,
    required this.countZ,
    required Int32List cells,
    required List<Uint32List> pvs,
    required this.brushHash,
  }) : // Private fields cannot be named initialising formals.
       // ignore: prefer_initializing_formals
       _cells = cells,
       // ignore: prefer_initializing_formals
       _pvs = pvs;

  /// Bumped when an existing field changes meaning.
  static const int formatVersion = 1;

  /// The edge of one cell, in metres.
  final double cellSize;

  /// The corner of the grid, in world space.
  final Vector3 origin;

  final int countX;
  final int countY;
  final int countZ;

  /// What the table was baked from: a hash of the level's brushes.
  final int brushHash;

  /// Per grid slot, the id of the open cell there, or -1 for closed.
  final Int32List _cells;

  /// Per open cell, a bit per open cell: set where the two see each other.
  final List<Uint32List> _pvs;

  /// How many open cells the level has.
  int get cellCount => _pvs.length;

  /// The grid slot holding a point, or -1 outside the grid.
  int slotOf(double x, double y, double z) {
    final ix = ((x - origin.x) / cellSize).floor();
    final iy = ((y - origin.y) / cellSize).floor();
    final iz = ((z - origin.z) / cellSize).floor();
    if (ix < 0 || iy < 0 || iz < 0) return -1;
    if (ix >= countX || iy >= countY || iz >= countZ) return -1;
    return ix + countX * (iy + countY * iz);
  }

  /// The open cell a point is in, or -1 for outside the grid or inside a wall.
  int cellAt(Vector3 point) {
    final slot = slotOf(point.x, point.y, point.z);
    return slot < 0 ? -1 : _cells[slot];
  }

  /// Whether cell [from] sees cell [to]. Symmetric.
  bool canSee(int from, int to) {
    if (from < 0 || to < 0) return true;
    return (_pvs[from][to >> 5] & (1 << (to & 31))) != 0;
  }

  /// Whether anything inside [bounds] can be seen from cell [from].
  ///
  /// True when any open cell the box overlaps is visible from [from], when
  /// [from] is unknown, and when the box overlaps no open cell at all — a
  /// batch entirely inside the walls is a batch this table has no opinion on,
  /// and no opinion draws.
  bool isVisible(int from, Aabb3 bounds) {
    if (from < 0) return true;
    final minX = _clampIndex((bounds.min.x - origin.x) / cellSize, countX);
    final minY = _clampIndex((bounds.min.y - origin.y) / cellSize, countY);
    final minZ = _clampIndex((bounds.min.z - origin.z) / cellSize, countZ);
    final maxX = _clampIndex((bounds.max.x - origin.x) / cellSize, countX);
    final maxY = _clampIndex((bounds.max.y - origin.y) / cellSize, countY);
    final maxZ = _clampIndex((bounds.max.z - origin.z) / cellSize, countZ);
    var overlapsOpen = false;
    for (var z = minZ; z <= maxZ; z++) {
      for (var y = minY; y <= maxY; y++) {
        for (var x = minX; x <= maxX; x++) {
          final cell = _cells[x + countX * (y + countY * z)];
          if (cell < 0) continue;
          overlapsOpen = true;
          if (canSee(from, cell)) return true;
        }
      }
    }
    return !overlapsOpen;
  }

  /// How far past a cell's edge a query looks, in metres.
  ///
  /// **A metre, and the number was measured.** The table is a sample, and
  /// its misses cluster where an eye or a wall stands near a cell boundary:
  /// the sample points of the cell it is in do not reach the extreme line
  /// that squeezes past a doorway's edge, while the next cell's would. So a
  /// query asks on behalf of every cell within this distance of the eye, and
  /// grows the box it asks about by the same, and the misses go. Against
  /// fifty-five hundred random unblocked rays through the dungeon's three
  /// levels: none hidden at a metre, one at half a metre, twenty-two at
  /// nought. The price is culling — the crypt's standing point sees 54% of
  /// cells instead of 41% — and it is paid for a room that never pops.
  static const double queryMargin = 1.0;

  /// Whether anything inside [bounds] can be seen by an eye at [eye].
  ///
  /// The question a frame asks. [isVisible] on the eye's own cell, widened
  /// by [queryMargin] on both sides, for the reason given there.
  bool canSeeFrom(Vector3 eye, Aabb3 bounds) {
    final grown = Aabb3.minMax(
      Vector3(
        bounds.min.x - queryMargin,
        bounds.min.y - queryMargin,
        bounds.min.z - queryMargin,
      ),
      Vector3(
        bounds.max.x + queryMargin,
        bounds.max.y + queryMargin,
        bounds.max.z + queryMargin,
      ),
    );
    for (var dz = -1; dz <= 1; dz++) {
      for (var dy = -1; dy <= 1; dy++) {
        for (var dx = -1; dx <= 1; dx++) {
          final slot = slotOf(
            eye.x + dx * queryMargin,
            eye.y + dy * queryMargin,
            eye.z + dz * queryMargin,
          );
          // Off the grid on any side: no opinion, which draws.
          if (slot < 0) return true;
          final cell = _cells[slot];
          if (cell < 0) continue;
          if (isVisible(cell, grown)) return true;
        }
      }
    }
    // Every probe landed inside a wall: the eye is somewhere the table did
    // not sample, and no opinion draws.
    return cellAt(eye) < 0;
  }

  static int _clampIndex(double value, int count) {
    final index = value.floor();
    return index < 0 ? 0 : (index >= count ? count - 1 : index);
  }

  /// Whether this table was baked from a level with different brushes.
  bool isStaleFor(Level level) => brushHash != hashBrushes(level);

  /// A hash of everything about the brushes that decides visibility.
  ///
  /// FNV-1a over the numbers written to four decimals, so it is the same on
  /// every platform this runs on: a hash of doubles' bits would be too, but a
  /// hash of their text is one a person can reproduce by hand when a table is
  /// refused and they want to know why.
  static int hashBrushes(Level level) {
    var hash = 0x811C9DC5;
    void mix(String text) {
      for (final unit in text.codeUnits) {
        hash ^= unit;
        hash = (hash * 0x01000193) & 0xFFFFFFFF;
      }
      hash ^= 0x7C;
      hash = (hash * 0x01000193) & 0xFFFFFFFF;
    }

    for (final brush in level.brushes) {
      if (!brush.solid) continue;
      mix(brush.centre.x.toStringAsFixed(4));
      mix(brush.centre.y.toStringAsFixed(4));
      mix(brush.centre.z.toStringAsFixed(4));
      mix(brush.size.x.toStringAsFixed(4));
      mix(brush.size.y.toStringAsFixed(4));
      mix(brush.size.z.toStringAsFixed(4));
      final ramp = brush.ramp;
      mix(ramp == null ? '-' : '${ramp.x},${ramp.z}');
    }
    return hash;
  }

  Map<String, Object?> toJson() {
    final words = _pvs.isEmpty ? 0 : _pvs.first.length;
    final all = Uint32List(_pvs.length * words);
    for (var i = 0; i < _pvs.length; i++) {
      all.setRange(i * words, (i + 1) * words, _pvs[i]);
    }
    return <String, Object?>{
      'version': formatVersion,
      'cellSize': cellSize,
      'origin': <double>[origin.x, origin.y, origin.z],
      'counts': <int>[countX, countY, countZ],
      'brushHash': brushHash,
      'cells': base64Encode(_cells.buffer.asUint8List()),
      'pvs': base64Encode(all.buffer.asUint8List()),
    };
  }

  /// Reads a table, or throws a [VisibilityFormatException] that says why not.
  factory LevelVisibility.fromJson(Map<String, Object?> json) {
    final version = json['version'];
    if (version is! num) {
      throw const VisibilityFormatException('the table has no version in it');
    }
    if (version > formatVersion) {
      throw VisibilityFormatException(
        'the table was written by a newer build (format $version, this build '
        'reads $formatVersion)',
      );
    }
    final cellSize = json['cellSize'];
    final origin = json['origin'];
    final counts = json['counts'];
    final hash = json['brushHash'];
    final cells = json['cells'];
    final pvs = json['pvs'];
    if (cellSize is! num ||
        origin is! List<Object?> ||
        origin.length != 3 ||
        counts is! List<Object?> ||
        counts.length != 3 ||
        hash is! num ||
        cells is! String ||
        pvs is! String) {
      throw const VisibilityFormatException(
        'the table is missing a field, so it was not written all the way',
      );
    }
    final countX = (counts[0]! as num).toInt();
    final countY = (counts[1]! as num).toInt();
    final countZ = (counts[2]! as num).toInt();
    final cellBytes = base64Decode(cells);
    final slots = Int32List.view(
      Uint8List.fromList(cellBytes).buffer,
      0,
      countX * countY * countZ,
    );
    var open = 0;
    for (final cell in slots) {
      if (cell >= 0) open++;
    }
    final words = (open + 31) >> 5;
    final pvsWords = Uint32List.view(
      Uint8List.fromList(base64Decode(pvs)).buffer,
      0,
      open * words,
    );
    return LevelVisibility._(
      cellSize: cellSize.toDouble(),
      origin: Vector3(
        (origin[0]! as num).toDouble(),
        (origin[1]! as num).toDouble(),
        (origin[2]! as num).toDouble(),
      ),
      countX: countX,
      countY: countY,
      countZ: countZ,
      cells: slots,
      pvs: <Uint32List>[
        for (var i = 0; i < open; i++)
          pvsWords.sublist(i * words, (i + 1) * words),
      ],
      brushHash: hash.toInt(),
    );
  }

  /// Bakes a table for [level].
  ///
  /// Deterministic: no randomness and no clock, so two bakes of one level are
  /// the same bytes, and a table's hash says which brushes it was baked from.
  /// [samplesPerAxis] points along each axis of a cell are the rays' ends —
  /// with the centre added when the count is even, so the middle of a cell is
  /// always sampled. **Three, not two, and the number was measured**: two
  /// is nine points and eighty-one rays a pair, and against four thousand
  /// random rays through the crypt it hid cells three of them could reach;
  /// three is twenty-seven points and 729 rays, hid none, and costs the crypt
  /// thirty-six seconds instead of three. A bake is a tool run, not a load.
  static LevelVisibility bake(
    Level level, {
    double cellSize = 3.0,
    int samplesPerAxis = 3,
  }) {
    assert(cellSize > 0.0);
    assert(samplesPerAxis >= 1);
    final solids = level.brushes.where((b) => b.solid).toList();
    if (solids.isEmpty) {
      return LevelVisibility._(
        cellSize: cellSize,
        origin: Vector3.zero(),
        countX: 0,
        countY: 0,
        countZ: 0,
        cells: Int32List(0),
        pvs: const <Uint32List>[],
        brushHash: hashBrushes(level),
      );
    }

    // The grid: the brushes' extent, snapped outward to whole cells.
    var minX = double.infinity, minY = double.infinity, minZ = double.infinity;
    var maxX = -double.infinity,
        maxY = -double.infinity,
        maxZ = -double.infinity;
    for (final brush in solids) {
      final lo = brush.min;
      final hi = brush.max;
      if (lo.x < minX) minX = lo.x;
      if (lo.y < minY) minY = lo.y;
      if (lo.z < minZ) minZ = lo.z;
      if (hi.x > maxX) maxX = hi.x;
      if (hi.y > maxY) maxY = hi.y;
      if (hi.z > maxZ) maxZ = hi.z;
    }
    final origin = Vector3(
      (minX / cellSize).floor() * cellSize,
      (minY / cellSize).floor() * cellSize,
      (minZ / cellSize).floor() * cellSize,
    );
    final countX = ((maxX - origin.x) / cellSize).ceil().clamp(1, 1 << 20);
    final countY = ((maxY - origin.y) / cellSize).ceil().clamp(1, 1 << 20);
    final countZ = ((maxZ - origin.z) / cellSize).ceil().clamp(1, 1 << 20);

    // Sample points per cell, those in empty space only. A cell with none is
    // closed: solid rock, or a wall the grid happens to land on.
    final fractions = <double>[
      for (var i = 0; i < samplesPerAxis; i++) (i + 0.5) / samplesPerAxis,
    ];
    final slotCount = countX * countY * countZ;
    final cells = Int32List(slotCount)..fillRange(0, slotCount, -1);
    final samples = <List<Vector3>>[];
    final coords = <(int, int, int)>[];
    for (var z = 0; z < countZ; z++) {
      for (var y = 0; y < countY; y++) {
        for (var x = 0; x < countX; x++) {
          final points = <Vector3>[];
          void consider(double fx, double fy, double fz) {
            final p = Vector3(
              origin.x + (x + fx) * cellSize,
              origin.y + (y + fy) * cellSize,
              origin.z + (z + fz) * cellSize,
            );
            if (!_insideSolid(solids, p)) points.add(p);
          }

          for (final fx in fractions) {
            for (final fy in fractions) {
              for (final fz in fractions) {
                consider(fx, fy, fz);
              }
            }
          }
          if (samplesPerAxis.isEven) consider(0.5, 0.5, 0.5);
          if (points.isEmpty) continue;
          cells[x + countX * (y + countY * z)] = samples.length;
          samples.add(points);
          coords.add((x, y, z));
        }
      }
    }

    // The rays, through the level's own collision world: exact against boxes
    // and wedges, with the broad phase the game already pays for.
    final world = CollisionWorld();
    level.addTo(world);
    world.update();
    final words = (samples.length + 31) >> 5;
    final pvs = <Uint32List>[
      for (var i = 0; i < samples.length; i++) Uint32List(words),
    ];
    void see(int a, int b) {
      pvs[a][b >> 5] |= 1 << (b & 31);
      pvs[b][a >> 5] |= 1 << (a & 31);
    }

    final hit = RayHit();
    final direction = Vector3.zero();
    for (var a = 0; a < samples.length; a++) {
      see(a, a);
      final (ax, ay, az) = coords[a];
      for (var b = a + 1; b < samples.length; b++) {
        final (bx, by, bz) = coords[b];
        if ((ax - bx).abs() <= 1 &&
            (ay - by).abs() <= 1 &&
            (az - bz).abs() <= 1) {
          see(a, b);
          continue;
        }
        var visible = false;
        for (final from in samples[a]) {
          for (final to in samples[b]) {
            direction
              ..setFrom(to)
              ..sub(from);
            final distance = direction.length;
            if (distance <= 0.0) {
              visible = true;
              break;
            }
            direction.scale(1.0 / distance);
            if (!world.raycast(from, direction, distance, hit)) {
              visible = true;
              break;
            }
          }
          if (visible) break;
        }
        if (visible) see(a, b);
      }
    }

    return LevelVisibility._(
      cellSize: cellSize,
      origin: origin,
      countX: countX,
      countY: countY,
      countZ: countZ,
      cells: cells,
      pvs: pvs,
      brushHash: hashBrushes(level),
    );
  }

  /// Whether a point is inside, or within a centimetre of, any solid brush.
  ///
  /// **The centimetre is load-bearing.** A grid of whole metres puts sample
  /// points on whole coordinates, and a brush face is on one too, so a sample
  /// can land exactly on a wall — outside it by the strict test, and the
  /// origin of rays that a box does not block because they begin on its
  /// surface. The first bake of a three-room test level saw straight through
  /// its floor that way. A point that close to a wall is no place a camera
  /// can be, so it is no loss as a sample.
  ///
  /// A wedge counts as its whole box, which closes a sample in the wedge's
  /// empty half — the safe way round, since a closed cell sees everything.
  static bool _insideSolid(List<Brush> solids, Vector3 p) {
    const margin = 0.01;
    for (final brush in solids) {
      final lo = brush.min;
      final hi = brush.max;
      if (p.x > lo.x - margin &&
          p.x < hi.x + margin &&
          p.y > lo.y - margin &&
          p.y < hi.y + margin &&
          p.z > lo.z - margin &&
          p.z < hi.z + margin) {
        return true;
      }
    }
    return false;
  }
}

/// Thrown when a visibility table cannot be read at all.
final class VisibilityFormatException implements Exception {
  const VisibilityFormatException(this.message);

  final String message;

  @override
  String toString() => 'VisibilityFormatException: $message';
}
