/// Who made what, and under which licence.
///
/// **A condition of the licence, not a courtesy.** Two of the models are CC BY
/// 4.0, whose text asks that attribution appear wherever the work does, and
/// `assets/models/LICENSES.md` says so in as many words. The game shipped
/// nothing of the kind — not in the application, not on the web page — so every
/// run of it was a breach for as long as it ran, and no test could have said so
/// because there was nothing to test.
///
/// One list, and it is the list the screen reads. The alternative is prose in a
/// widget, which is a copy, and a copy of a legal notice is the one that goes
/// stale.
///
/// **What is *not* credited is here too.** `key.glb` has no traceable author at
/// all, and leaving it out would make this file agree with itself while the game
/// went on shipping it. `LICENSES.md` records the same thing at length; this is
/// the half of it a player can see.
library;

import 'package:flutter/material.dart';

/// One piece of work the game did not make, and what is owed for it.
final class Credit {
  const Credit({
    required this.file,
    required this.work,
    required this.author,
    required this.source,
    required this.licence,
    required this.licenceUrl,
    this.modified = false,
  });

  /// An asset that came from somewhere nobody can name.
  ///
  /// A separate constructor rather than a null licence passed by a caller, so
  /// the awkward case has to be written out on purpose.
  const Credit.untraced({required this.file, required this.work})
      : author = null,
        source = null,
        licence = null,
        licenceUrl = null,
        modified = true;

  /// The file as it ships, relative to `assets/`.
  final String file;

  final String work;
  final String? author;
  final String? source;

  /// The licence's short name, or null when nobody could trace one.
  final String? licence;
  final String? licenceUrl;

  /// Whether this repository changed the file, which CC BY also asks be said.
  final bool modified;

  /// Whether the licence is known at all.
  bool get traced => licence != null;

  /// Whether the licence obliges the game to name the author.
  ///
  /// CC0 does not, and the entry is kept anyway: a licence nobody can trace is
  /// a debt, and a file whose provenance is "somebody downloaded it" cannot be
  /// told apart from one that is.
  bool get owesAttribution => licence != null && licence!.startsWith('CC BY');

  /// One line, as a screen would read it out.
  String get line {
    if (!traced) return '$work — author unknown, licence untraced';
    final changed = modified ? ', modified' : '';
    return '$work by $author — $licence$changed';
  }
}

/// Everything the game ships that somebody else made.
///
/// The textures and every sound are generated by `tool/make_textures.py` and
/// `tool/make_sounds.py`, so they are the repository's own and are not here.
/// That was the point of generating them.
abstract final class Credits {
  static const List<Credit> models = <Credit>[
    Credit(
      file: 'models/penguin.glb',
      work: 'Weathered penguin-bot',
      author: 'epilogueronin',
      source:
          'https://sketchfab.com/3d-models/weathered-penguin-bot-33afc2b450dd4c188b307c82f3b2cbc3',
      licence: 'CC BY 4.0',
      licenceUrl: 'http://creativecommons.org/licenses/by/4.0/',
      modified: true,
    ),
    Credit(
      file: 'models/coin.glb',
      work: 'Stylized Coin',
      author: 'BarracudaByte',
      source:
          'https://sketchfab.com/3d-models/stylized-coin-8cd6f95c44994ed5944a42892d0ffc10',
      licence: 'CC BY 4.0',
      licenceUrl: 'http://creativecommons.org/licenses/by/4.0/',
      modified: true,
    ),
    Credit(
      file: 'models/hero.glb',
      work: 'Animated Platformer Character',
      author: 'Quaternius',
      source: 'https://poly.pizza/m/kKtL4zvS3n',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modified: true,
    ),
    Credit(
      file: 'models/key.glb',
      work: 'A key',
      // **The one asset here that nobody had to be asked for.** The key that
      // used to sit in this slot came from an archive with no licence file, no
      // author and no trail back to one, and it was the only thing standing
      // between this game and a release. It is generated now — the provenance
      // is a script in this repository, and `tool/make_key.py` says why at
      // length.
      author: 'this repository',
      source: 'apps/platformer/tool/make_key.py',
      licence: 'CC0 1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    ),
  ];

  /// The ones whose licence makes naming the author a condition.
  static List<Credit> get owed =>
      models.where((Credit c) => c.owesAttribution).toList();

  /// The ones that cannot be credited because nobody knows who made them.
  ///
  /// **Empty now, and it took generating a key to get there.** While this list
  /// has anything in it the game cannot be released, whatever the credits screen
  /// says — so the way it emptied was not finding the author of the old key,
  /// which nobody could, but replacing it with one this repository made.
  ///
  /// It stays, because the next asset dropped into `assets/models` is one
  /// somebody found somewhere, and `credits_test.dart` reads the directory.
  static List<Credit> get untraced =>
      models.where((Credit c) => !c.traced).toList();
}

/// Who made the art, wherever the game is shown.
///
/// **Not decoration.** Two of the models are CC BY 4.0, and the licence asks
/// that attribution travel with the work — so this belongs on any screen a
/// player can reach without finishing the game, which is why it is a widget of
/// its own rather than a paragraph in one screen.
///
/// The list comes from [Credits], and so does the test: prose typed in here
/// would be a second copy of a legal notice, and the second copy is the one that
/// goes stale.
class CreditsSection extends StatelessWidget {
  const CreditsSection({super.key, this.heading = 'Art'});

  final String heading;

  @override
  Widget build(BuildContext context) {
    final faded = Colors.white.withValues(alpha: 0.75);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text(
          heading,
          style: TextStyle(color: faded, letterSpacing: 2, fontSize: 12),
        ),
        const SizedBox(height: 8),
        for (final credit in Credits.models) ...<Widget>[
          Text(
            credit.line,
            style: const TextStyle(color: Colors.white, fontSize: 13),
          ),
          if (credit.licenceUrl != null)
            Text(
              credit.licenceUrl!,
              style: TextStyle(
                color: Colors.white.withValues(alpha: 0.55),
                fontSize: 11,
              ),
            ),
          const SizedBox(height: 6),
        ],
        Text(
          'Sounds and surfaces are generated by this repository.',
          style: TextStyle(color: faded, fontSize: 12),
        ),
      ],
    );
  }
}
