import 'package:flutter/material.dart';
import 'package:flutter3d_audio/flutter3d_audio.dart';
import 'package:flutter3d_game/flutter3d_game.dart';

import 'credits.dart';

/// Volume sliders and the keys, over the top of the paused game.
///
/// Flutter widgets, which is the one thing this stack gets for nothing: a
/// settings screen in a C++ engine is a small project of its own, and here it
/// is a `Slider` and a `Column`.
class SettingsPanel extends StatelessWidget {
  const SettingsPanel({
    super.key,
    required this.mixer,
    required this.bindings,
    required this.onVolume,
    required this.onClose,
  });

  final Mixer mixer;
  final Bindings bindings;
  final void Function(AudioBus bus, double volume) onVolume;
  final VoidCallback onClose;

  static const List<AudioBus> _buses = <AudioBus>[
    AudioBus.master,
    AudioBus.sfx,
  ];

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: Colors.black.withValues(alpha: 0.72),
      child: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 460),
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(28),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                const Text(
                  'Settings',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 26,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                const SizedBox(height: 18),
                for (final bus in _buses) ...<Widget>[
                  Text(
                    bus.name,
                    style: TextStyle(
                      color: Colors.white.withValues(alpha: 0.75),
                      letterSpacing: 2,
                      fontSize: 12,
                    ),
                  ),
                  Slider(
                    value: mixer.volumeOf(bus),
                    onChanged: (double value) => onVolume(bus, value),
                  ),
                ],
                const SizedBox(height: 12),
                Text(
                  'Controls',
                  style: TextStyle(
                    color: Colors.white.withValues(alpha: 0.75),
                    letterSpacing: 2,
                    fontSize: 12,
                  ),
                ),
                const SizedBox(height: 8),
                // Read from the same table the keyboard reads, so a rebinding
                // that never reached the game cannot look as though it did.
                for (final action in GameAction.common)
                  _Binding(
                    action: action.name,
                    sources: bindings.sourcesFor(action).length,
                  ),
                const SizedBox(height: 18),
                const CreditsSection(),
                const SizedBox(height: 20),
                Align(
                  alignment: Alignment.centerRight,
                  child: TextButton(
                    onPressed: onClose,
                    child: const Text('Back to the game'),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

/// Who made the art, wherever the game is shown.
///
/// **Not decoration.** Two of the models are CC BY 4.0, and the licence asks
/// that attribution travel with the work — so this belongs on any screen a
/// player can reach without finishing the game, which is why it is a widget of
/// its own rather than a paragraph in one screen.
///
/// The list comes from [Credits], and so does the test: prose typed in here
/// would be a second copy of a legal notice, and the second copy is the one that
/// goes stale.
class CreditsSection extends StatelessWidget {
  const CreditsSection({super.key, this.heading = 'Art'});

  final String heading;

  @override
  Widget build(BuildContext context) {
    final faded = Colors.white.withValues(alpha: 0.75);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text(
          heading,
          style: TextStyle(color: faded, letterSpacing: 2, fontSize: 12),
        ),
        const SizedBox(height: 8),
        for (final credit in Credits.models) ...<Widget>[
          Text(
            credit.line,
            style: const TextStyle(color: Colors.white, fontSize: 13),
          ),
          if (credit.licenceUrl != null)
            Text(
              credit.licenceUrl!,
              style: TextStyle(
                color: Colors.white.withValues(alpha: 0.55),
                fontSize: 11,
              ),
            ),
          const SizedBox(height: 6),
        ],
        Text(
          'Sounds and surfaces are generated by this repository.',
          style: TextStyle(color: faded, fontSize: 12),
        ),
      ],
    );
  }
}

class _Binding extends StatelessWidget {
  const _Binding({required this.action, required this.sources});

  final String action;
  final int sources;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 3),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          Text(action, style: const TextStyle(color: Colors.white)),
          Text(
            sources == 1 ? '1 key' : '$sources keys',
            style: TextStyle(color: Colors.white.withValues(alpha: 0.6)),
          ),
        ],
      ),
    );
  }
}
