import 'package:flutter3d_audio/flutter3d_audio.dart';

/// What this game makes noise with.
///
/// Every file is generated by `tool/make_sounds.py` — a few sine and noise
/// envelopes — rather than sourced. `apps/dungeon` carries a recorded debt
/// because its key model and its maps have no licence traced, and a second game
/// repeating that would be repeating a known mistake.
abstract final class Sounds {
  static const SoundDef coin = SoundDef(
    name: 'coin',
    asset: 'assets/sounds/coin.wav',
    gain: 0.7,
    // Seven coins collected in one dash is not seven times as loud.
    maxInstances: 3,
    priority: 2,
    // A few per cent either way. There are two hundred and fifty coins in this
    // level, and identical repeats read as a machine long before they read as
    // a sound — the same finding `maxInstances` came from, at a slower rate.
    rateVariance: 0.12,
  );

  static const SoundDef jump = SoundDef(
    name: 'jump',
    asset: 'assets/sounds/jump.wav',
    gain: 0.5,
    maxInstances: 2,
    rateVariance: 0.08,
  );

  static const SoundDef airJump = SoundDef(
    name: 'airJump',
    asset: 'assets/sounds/airjump.wav',
    gain: 0.5,
    maxInstances: 2,
  );

  static const SoundDef land = SoundDef(
    name: 'land',
    asset: 'assets/sounds/land.wav',
    gain: 0.45,
    maxInstances: 2,
    rateVariance: 0.1,
  );

  static const SoundDef dash = SoundDef(
    name: 'dash',
    asset: 'assets/sounds/dash.wav',
    gain: 0.55,
    maxInstances: 2,
    rateVariance: 0.06,
  );

  static const SoundDef death = SoundDef(
    name: 'death',
    asset: 'assets/sounds/death.wav',
    gain: 0.8,
    priority: 5,
    maxInstances: 1,
  );

  static const SoundDef checkpoint = SoundDef(
    name: 'checkpoint',
    asset: 'assets/sounds/checkpoint.wav',
    gain: 0.7,
    priority: 4,
    maxInstances: 1,
  );

  static const List<SoundDef> all = <SoundDef>[
    coin,
    jump,
    airJump,
    land,
    dash,
    death,
    checkpoint,
  ];
}
