import 'package:flutter3d_audio/flutter3d_audio.dart';

/// What this game makes noise with.
///
/// Every file is generated by `tool/make_sounds.py` — a few sine and noise
/// envelopes — rather than sourced. `apps/dungeon` carries a recorded debt
/// because its key model and its maps have no licence traced, and a second game
/// repeating that would be repeating a known mistake.
abstract final class Sounds {
  static const SoundDef coin = SoundDef(
    name: 'coin',
    asset: 'assets/sounds/coin.wav',
    gain: 0.7,
    // Seven coins collected in one dash is not seven times as loud.
    maxInstances: 3,
    priority: 2,
    // A few per cent either way. There are two hundred and fifty coins in this
    // level, and identical repeats read as a machine long before they read as
    // a sound — the same finding `maxInstances` came from, at a slower rate.
    rateVariance: 0.12,
  );

  static const SoundDef jump = SoundDef(
    name: 'jump',
    asset: 'assets/sounds/jump.wav',
    gain: 0.5,
    maxInstances: 2,
    rateVariance: 0.08,
  );

  static const SoundDef airJump = SoundDef(
    name: 'airJump',
    asset: 'assets/sounds/airjump.wav',
    gain: 0.5,
    maxInstances: 2,
  );

  static const SoundDef land = SoundDef(
    name: 'land',
    asset: 'assets/sounds/land.wav',
    gain: 0.45,
    maxInstances: 2,
    rateVariance: 0.1,
  );

  static const SoundDef dash = SoundDef(
    name: 'dash',
    asset: 'assets/sounds/dash.wav',
    gain: 0.55,
    maxInstances: 2,
    rateVariance: 0.06,
  );

  static const SoundDef death = SoundDef(
    name: 'death',
    asset: 'assets/sounds/death.wav',
    gain: 0.8,
    priority: 5,
    maxInstances: 1,
  );

  static const SoundDef checkpoint = SoundDef(
    name: 'checkpoint',
    asset: 'assets/sounds/checkpoint.wav',
    gain: 0.7,
    priority: 4,
    maxInstances: 1,
  );

  /// The one long thing in the game, and the only one on the music bus.
  ///
  /// **The bus existed with a slider and nothing behind it**, which is a
  /// setting that does nothing — worse than an absent one, because a player who
  /// moves it learns the settings screen lies. Eight bars of A minor at ninety,
  /// written by `tool/make_music.py` for the same reason the sound effects are:
  /// a licence nobody can trace is a debt, and a music track is the easiest
  /// asset in the world to acquire carelessly.
  ///
  /// [NoAttenuation] and one instance: it is not in the level, it *is* the
  /// level. A looping sound played twice is the same sound out of phase with
  /// itself, which is a flanger and not a mistake anybody enjoys.
  static const SoundDef music = SoundDef(
    name: 'music',
    asset: 'assets/sounds/music.wav',
    gain: 1.0,
    loop: true,
    bus: AudioBus.music,
    attenuation: NoAttenuation(),
    maxInstances: 1,
    priority: 10,
  );

  /// Everything to load before the game starts.
  ///
  /// **Six of these were missing, and the game was quietly half silent.** Every
  /// footstep, every spring, every crumbling shelf and the fanfare at the exit
  /// were declared, had their `.wav` on disk, were shipped in the bundle, were
  /// asked for by `Soundtrack` — and were never preloaded, so `SoLoudBackend`
  /// had no source to start and returned no voice at all.
  ///
  /// It also leaked. An emitter with no voice is neither stopped nor finished,
  /// and `AudioScene.update` retires only those two — so every footstep left one
  /// behind for the length of the run, roughly one per two metres walked.
  ///
  /// A list beside a list, with nothing comparing them. `sounds_test.dart` is
  /// that comparison now: it reads the definitions out of this file and refuses
  /// any that this list has forgotten.
  static const List<SoundDef> all = <SoundDef>[
    coin,
    jump,
    airJump,
    land,
    dash,
    death,
    checkpoint,
    music,
    stepMoss,
    stepStone,
    stepIce,
    spring,
    crumble,
    exit,
  ];

  /// A footstep, by what is underfoot.
  ///
  /// **Running is most of what a player does, and it was silent.** Three of
  /// them because the level's floors already differ underfoot — ice slides and
  /// mud drags — and a step that sounds the same on both tells the player the
  /// surface change was decoration.
  ///
  /// Quiet and short: a sound heard twice a second either sits under everything
  /// else or becomes the whole mix. `maxInstances` of two, because two feet is
  /// the most that can ever be in the air at once.
  static const SoundDef stepMoss = SoundDef(
    name: 'step_moss',
    asset: 'assets/sounds/step_moss.wav',
    gain: 0.22,
    maxInstances: 2,
    priority: 0,
    rateVariance: 0.14,
  );

  static const SoundDef stepStone = SoundDef(
    name: 'step_stone',
    asset: 'assets/sounds/step_stone.wav',
    gain: 0.24,
    maxInstances: 2,
    priority: 0,
    rateVariance: 0.14,
  );

  static const SoundDef stepIce = SoundDef(
    name: 'step_ice',
    asset: 'assets/sounds/step_ice.wav',
    gain: 0.2,
    maxInstances: 2,
    priority: 0,
    rateVariance: 0.14,
  );

  /// The throw off a pad, which had particles and no sound at all.
  static const SoundDef spring = SoundDef(
    name: 'spring',
    asset: 'assets/sounds/spring.wav',
    gain: 0.6,
    maxInstances: 2,
    rateVariance: 0.06,
  );

  /// Something giving way underfoot. Also used for a block broken by a pound:
  /// they are the same event to the ear, and a second file to tell them apart
  /// would be a distinction nobody hears.
  static const SoundDef crumble = SoundDef(
    name: 'crumble',
    asset: 'assets/sounds/crumble.wav',
    gain: 0.55,
    maxInstances: 3,
    rateVariance: 0.1,
  );

  /// The way out. The one sound in this game allowed to be long.
  static const SoundDef exit = SoundDef(
    name: 'exit',
    asset: 'assets/sounds/exit.wav',
    gain: 0.8,
    maxInstances: 1,
  );

  /// Which footstep a surface name gets.
  ///
  /// The names come off the level's brushes, so this is where the document's
  /// vocabulary meets the sound bank — and an unknown surface is stone rather
  /// than silence, because a floor nobody named is still a floor.
  static SoundDef stepOn(String? surface) => switch (surface) {
        'ice' => stepIce,
        'moss' => stepMoss,
        _ => stepStone,
      };
}
